#!/usr/bin/env python3
# SPDX-License-Identifier: MS-PL
"""Embeds the vendored D3D9 Effect Framework binaries into a generated C++ header.

FNA3D exposes no shader entry point other than FNA3D_CreateEffect(), which takes a compiled
Direct3D 9 Effect binary. This script turns the .fxb files sitting next to it (see README.md for
their provenance) into one `Fna3dStockEffectBlobs.hpp` of `constexpr` byte arrays, so the renderer
needs no runtime asset path and a test binary is self-contained.

Same shape as the shaders/compile_shaders.py generators the Vulkan/SDL_GPU/sokol renderer families
already use, except that the inputs here are pre-compiled artefacts rather than sources this repo
can rebuild -- no D3D9 effect compiler (fxc) exists on any platform CNA builds on.

Usage: embed_effects.py <output-header> <name>=<path> [<name>=<path> ...]
"""
import os
import sys


def emit_array(out, name, data):
    out.write(f"    /** @brief Compiled D3D9 Effect Framework binary for the stock {name} effect. */\n")
    out.write(f"    inline constexpr unsigned char k{name}Fxb[] = {{\n")
    for start in range(0, len(data), 16):
        chunk = data[start:start + 16]
        out.write("        " + "".join(f"0x{byte:02x}, " for byte in chunk).rstrip() + "\n")
    out.write("    };\n\n")


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        return 2

    output = argv[1]
    entries = []
    for spec in argv[2:]:
        name, _, path = spec.partition("=")
        if not name or not path:
            sys.stderr.write(f"malformed <name>=<path> argument: {spec}\n")
            return 2
        with open(path, "rb") as handle:
            entries.append((name, handle.read()))

    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="\n") as out:
        out.write("// SPDX-License-Identifier: MS-PL\n")
        out.write("// GENERATED by modules/renderers/fna3d/effects/embed_effects.py -- do not edit.\n")
        out.write("// Source blobs and their provenance: modules/renderers/fna3d/effects/README.md\n")
        out.write("#pragma once\n\n")
        out.write("namespace CNA::Internal::Renderers::Fna3d::StockEffectBlobs\n{\n")
        for name, data in entries:
            emit_array(out, name, data)
        out.write("} // namespace CNA::Internal::Renderers::Fna3d::StockEffectBlobs\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
