//
// Created by robertvokac on 5/24/26.
//

#ifndef WINDOWSPHONESPEEDYBLUPI_CNAHELPER_HPP
#define WINDOWSPHONESPEEDYBLUPI_CNAHELPER_HPP

#define NOXNA

#endif //WINDOWSPHONESPEEDYBLUPI_CNAHELPER_HPP
