// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Tests::GpuInstanceCullerGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "gpu_instance_culler_test";
inline constexpr std::string_view kManifestSha256 = "6f6a910a14740d5948c88c50a82b2bace59619920a3b8cc58901d5619030fccd";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kDrawEsVertexSource =
    R"CNA_SHADER(#version 310 es
precision highp float;

layout(std430, binding = 6) readonly buffer CnaVisibleInstances
{
    mat4 cnaVisibleInstances[];
};

layout(location = 0) in vec3 aPos;

void main()
{
    vec4 world = cnaVisibleInstances[gl_InstanceID] * vec4(aPos, 1.0);
    gl_Position = vec4(world.x / 4.0, world.y / 5.0, 0.5, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kDrawEsFragmentSource =
    R"CNA_SHADER(#version 310 es
precision highp float;

out vec4 FragColor;

void main()
{
    FragColor = vec4(1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kDrawDesktopVertexSource =
    R"CNA_SHADER(#version 430 core

layout(std430, binding = 6) readonly buffer CnaVisibleInstances
{
    mat4 cnaVisibleInstances[];
};

layout(location = 0) in vec3 aPos;

void main()
{
    vec4 world = cnaVisibleInstances[gl_InstanceID] * vec4(aPos, 1.0);
    gl_Position = vec4(world.x / 4.0, world.y / 5.0, 0.5, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kDrawDesktopFragmentSource =
    R"CNA_SHADER(#version 430 core

out vec4 FragColor;

void main()
{
    FragColor = vec4(1.0);
}
)CNA_SHADER";

inline constexpr std::uint32_t kDrawVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000039u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0008000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00000012u, 0x00000019u, 0x00000026u,
    0x00040047u, 0x0000000bu, 0x00000006u, 0x00000040u, 0x00030047u, 0x0000000cu, 0x00000003u, 0x00040048u,
    0x0000000cu, 0x00000000u, 0x00000005u, 0x00050048u, 0x0000000cu, 0x00000000u, 0x00000007u, 0x00000010u,
    0x00040048u, 0x0000000cu, 0x00000000u, 0x00000018u, 0x00050048u, 0x0000000cu, 0x00000000u, 0x00000023u,
    0x00000000u, 0x00030047u, 0x0000000eu, 0x00000018u, 0x00040047u, 0x0000000eu, 0x00000021u, 0x00000006u,
    0x00040047u, 0x0000000eu, 0x00000022u, 0x00000002u, 0x00040047u, 0x00000012u, 0x0000000bu, 0x0000002bu,
    0x00040047u, 0x00000019u, 0x0000001eu, 0x00000000u, 0x00030047u, 0x00000024u, 0x00000002u, 0x00050048u,
    0x00000024u, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u, 0x00000024u, 0x00000001u, 0x0000000bu,
    0x00000001u, 0x00050048u, 0x00000024u, 0x00000002u, 0x0000000bu, 0x00000003u, 0x00050048u, 0x00000024u,
    0x00000003u, 0x0000000bu, 0x00000004u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u,
    0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u, 0x00040018u,
    0x0000000au, 0x00000007u, 0x00000004u, 0x0003001du, 0x0000000bu, 0x0000000au, 0x0003001eu, 0x0000000cu,
    0x0000000bu, 0x00040020u, 0x0000000du, 0x00000002u, 0x0000000cu, 0x0004003bu, 0x0000000du, 0x0000000eu,
    0x00000002u, 0x00040015u, 0x0000000fu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000fu, 0x00000010u,
    0x00000000u, 0x00040020u, 0x00000011u, 0x00000001u, 0x0000000fu, 0x0004003bu, 0x00000011u, 0x00000012u,
    0x00000001u, 0x00040020u, 0x00000014u, 0x00000002u, 0x0000000au, 0x00040017u, 0x00000017u, 0x00000006u,
    0x00000003u, 0x00040020u, 0x00000018u, 0x00000001u, 0x00000017u, 0x0004003bu, 0x00000018u, 0x00000019u,
    0x00000001u, 0x0004002bu, 0x00000006u, 0x0000001bu, 0x3f800000u, 0x00040015u, 0x00000021u, 0x00000020u,
    0x00000000u, 0x0004002bu, 0x00000021u, 0x00000022u, 0x00000001u, 0x0004001cu, 0x00000023u, 0x00000006u,
    0x00000022u, 0x0006001eu, 0x00000024u, 0x00000007u, 0x00000006u, 0x00000023u, 0x00000023u, 0x00040020u,
    0x00000025u, 0x00000003u, 0x00000024u, 0x0004003bu, 0x00000025u, 0x00000026u, 0x00000003u, 0x0004002bu,
    0x00000006u, 0x00000031u, 0x3f000000u, 0x00040020u, 0x00000033u, 0x00000003u, 0x00000007u, 0x0004002bu,
    0x00000006u, 0x00000037u, 0x3e800000u, 0x0004002bu, 0x00000006u, 0x00000038u, 0x3e4ccccdu, 0x00050036u,
    0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du, 0x0000000fu,
    0x00000013u, 0x00000012u, 0x00060041u, 0x00000014u, 0x00000015u, 0x0000000eu, 0x00000010u, 0x00000013u,
    0x0004003du, 0x0000000au, 0x00000016u, 0x00000015u, 0x0004003du, 0x00000017u, 0x0000001au, 0x00000019u,
    0x00050051u, 0x00000006u, 0x0000001cu, 0x0000001au, 0x00000000u, 0x00050051u, 0x00000006u, 0x0000001du,
    0x0000001au, 0x00000001u, 0x00050051u, 0x00000006u, 0x0000001eu, 0x0000001au, 0x00000002u, 0x00070050u,
    0x00000007u, 0x0000001fu, 0x0000001cu, 0x0000001du, 0x0000001eu, 0x0000001bu, 0x00050091u, 0x00000007u,
    0x00000020u, 0x00000016u, 0x0000001fu, 0x00050051u, 0x00000006u, 0x0000002au, 0x00000020u, 0x00000000u,
    0x00050085u, 0x00000006u, 0x0000002cu, 0x0000002au, 0x00000037u, 0x00050051u, 0x00000006u, 0x0000002eu,
    0x00000020u, 0x00000001u, 0x00050085u, 0x00000006u, 0x00000030u, 0x0000002eu, 0x00000038u, 0x00070050u,
    0x00000007u, 0x00000032u, 0x0000002cu, 0x00000030u, 0x00000031u, 0x0000001bu, 0x00050041u, 0x00000033u,
    0x00000034u, 0x00000026u, 0x00000010u, 0x0003003eu, 0x00000034u, 0x00000032u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kDrawVulkanVertexSpirVByteSize = sizeof(kDrawVulkanVertexSpirV);

inline constexpr std::string_view kDrawVulkanVertexWgsl =
    R"CNA_SHADER(// draw.vulkan.vert.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct CnaVisibleInstances {
    cnaVisibleInstances: array<mat4x4<f32>>,
}

struct gl_PerVertex {
    @builtin(position) gl_Position: vec4<f32>,
    gl_PointSize: f32,
    gl_ClipDistance: array<f32, 1>,
    gl_CullDistance: array<f32, 1>,
}

@group(2) @binding(6) 
var<storage> unnamed: CnaVisibleInstances;
var<private> gl_InstanceIndex_1: i32;
var<private> aPos_1: vec3<f32>;
var<private> unnamed_1: gl_PerVertex = gl_PerVertex(vec4<f32>(0f, 0f, 0f, 1f), 1f, array<f32, 1>(), array<f32, 1>());

fn main_1() {
    var world: vec4<f32>;

    let _e12 = gl_InstanceIndex_1;
    let _e15 = unnamed.cnaVisibleInstances[_e12];
    let _e16 = aPos_1;
    world = (_e15 * vec4<f32>(_e16.x, _e16.y, _e16.z, 1f));
    let _e23 = world[0u];
    let _e26 = world[1u];
    unnamed_1.gl_Position = vec4<f32>((_e23 / 4f), (_e26 / 5f), 0.5f, 1f);
    return;
}

@vertex 
fn main(@builtin(instance_index) gl_InstanceIndex: u32, @location(0) aPos: vec3<f32>) -> @builtin(position) vec4<f32> {
    gl_InstanceIndex_1 = i32(gl_InstanceIndex);
    aPos_1 = aPos;
    main_1();
    let _e8 = unnamed_1.gl_Position.y;
    unnamed_1.gl_Position.y = -(_e8);
    let _e10 = unnamed_1.gl_Position;
    return _e10;
}
)CNA_SHADER";

inline constexpr std::uint32_t kDrawVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x0000000cu, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00000009u, 0x00030010u, 0x00000004u,
    0x00000007u, 0x00040047u, 0x00000009u, 0x0000001eu, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u,
    0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u,
    0x00000004u, 0x00040020u, 0x00000008u, 0x00000003u, 0x00000007u, 0x0004003bu, 0x00000008u, 0x00000009u,
    0x00000003u, 0x0004002bu, 0x00000006u, 0x0000000au, 0x3f800000u, 0x0007002cu, 0x00000007u, 0x0000000bu,
    0x0000000au, 0x0000000au, 0x0000000au, 0x0000000au, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u,
    0x00000003u, 0x000200f8u, 0x00000005u, 0x0003003eu, 0x00000009u, 0x0000000bu, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kDrawVulkanFragmentSpirVByteSize = sizeof(kDrawVulkanFragmentSpirV);

inline constexpr std::string_view kDrawVulkanFragmentWgsl =
    R"CNA_SHADER(// draw.vulkan.frag.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
var<private> FragColor: vec4<f32>;

fn main_1() {
    FragColor = vec4<f32>(1f, 1f, 1f, 1f);
    return;
}

@fragment 
fn main() -> @location(0) vec4<f32> {
    main_1();
    let _e1 = FragColor;
    return _e1;
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 8> kPayloads = {{
    {"kDrawEsVertexSource", "draw.es.vert.glsl", "e1201951c28b7c8ed9691f097e303faa1d709dde98f0122f440fa4f04256609f", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kDrawEsFragmentSource", "draw.es.frag.glsl", "091a1b423928f1d7d6f716844f047ca278abacec0b949c92599f0c5307884f22", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kDrawDesktopVertexSource", "draw.desktop.vert.glsl", "c30c66efd2a932dea323fd017949622f85c640f3c8ca0d0cc7a94cc9f6122501", "glsl", "glsl", "vertex", "text", "main"},
    {"kDrawDesktopFragmentSource", "draw.desktop.frag.glsl", "2748e23c67948787ed3f27aa199502dc56cf3690909505f18f0f8e20d7c00e1b", "glsl", "glsl", "fragment", "text", "main"},
    {"kDrawVulkanVertexSpirV", "draw.vulkan.vert.glsl", "225c895a3db2bfd881233aab6b637df65a1ecf30760315661499f2506422f01f", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kDrawVulkanVertexWgsl", "draw.vulkan.vert.glsl", "225c895a3db2bfd881233aab6b637df65a1ecf30760315661499f2506422f01f", "wgsl", "vulkan-glsl", "vertex", "wgsl", "main"},
    {"kDrawVulkanFragmentSpirV", "draw.vulkan.frag.glsl", "50fc1538740e6fb0e46b8aa425e37b1cdf52494a2cfb03151c2b3540abfb488f", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
    {"kDrawVulkanFragmentWgsl", "draw.vulkan.frag.glsl", "50fc1538740e6fb0e46b8aa425e37b1cdf52494a2cfb03151c2b3540abfb488f", "wgsl", "vulkan-glsl", "fragment", "wgsl", "main"},
}};

} // namespace CNA::Tests::GpuInstanceCullerGenerated

#endif // CNA_CNAEXT
