// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Tests::ModernConformance {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "modern_conformance";
inline constexpr std::string_view kManifestSha256 = "3b936c30b652d2a99b1ab089bb701df49b144dde39d301e701a9b7fcc9b2b268";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "zero";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kGridEsSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

// Every invocation of a 3D dispatch writes its own global id, packed, at its own linear index.
layout(local_size_x = 4, local_size_y = 2, local_size_z = 2) in;
layout(std430, binding = 0) writeonly buffer Output
{
    uint values[];
};

uniform int uWidth;
uniform int uHeight;

void main()
{
    uvec3 g = gl_GlobalInvocationID;
    uint index = g.x + g.y * uint(uWidth) + g.z * uint(uWidth) * uint(uHeight);
    values[index] = (g.x << 20u) | (g.y << 10u) | g.z;
}
)CNA_SHADER";

inline constexpr std::uint32_t kGridSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000042u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000004u, 0x00000002u, 0x00000002u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x000a0004u,
    0x475f4c47u, 0x4c474f4fu, 0x70635f45u, 0x74735f70u, 0x5f656c79u, 0x656e696cu, 0x7269645fu, 0x69746365u,
    0x00006576u, 0x00080004u, 0x475f4c47u, 0x4c474f4fu, 0x6e695f45u, 0x64756c63u, 0x69645f65u, 0x74636572u,
    0x00657669u, 0x00040005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00030005u, 0x00000009u, 0x00000067u,
    0x00080005u, 0x0000000bu, 0x475f6c67u, 0x61626f6cu, 0x766e496cu, 0x7461636fu, 0x496e6f69u, 0x00000044u,
    0x00040005u, 0x0000000eu, 0x65646e69u, 0x00000078u, 0x00040005u, 0x00000016u, 0x61726150u, 0x0000736du,
    0x00050006u, 0x00000016u, 0x00000000u, 0x64695775u, 0x00006874u, 0x00050006u, 0x00000016u, 0x00000001u,
    0x69654875u, 0x00746867u, 0x00040005u, 0x00000018u, 0x61726170u, 0x0000736du, 0x00040005u, 0x0000002eu,
    0x7074754fu, 0x00007475u, 0x00050006u, 0x0000002eu, 0x00000000u, 0x756c6176u, 0x00007365u, 0x00030005u,
    0x00000030u, 0x00000000u, 0x00040047u, 0x0000000bu, 0x0000000bu, 0x0000001cu, 0x00030047u, 0x00000016u,
    0x00000002u, 0x00050048u, 0x00000016u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00050048u, 0x00000016u,
    0x00000001u, 0x00000023u, 0x00000004u, 0x00040047u, 0x0000002du, 0x00000006u, 0x00000004u, 0x00030047u,
    0x0000002eu, 0x00000003u, 0x00040048u, 0x0000002eu, 0x00000000u, 0x00000019u, 0x00050048u, 0x0000002eu,
    0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u, 0x00000030u, 0x00000019u, 0x00040047u, 0x00000030u,
    0x00000021u, 0x00000000u, 0x00040047u, 0x00000030u, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000041u,
    0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u,
    0x00000006u, 0x00000020u, 0x00000000u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000003u, 0x00040020u,
    0x00000008u, 0x00000007u, 0x00000007u, 0x00040020u, 0x0000000au, 0x00000001u, 0x00000007u, 0x0004003bu,
    0x0000000au, 0x0000000bu, 0x00000001u, 0x00040020u, 0x0000000du, 0x00000007u, 0x00000006u, 0x0004002bu,
    0x00000006u, 0x0000000fu, 0x00000000u, 0x0004002bu, 0x00000006u, 0x00000012u, 0x00000001u, 0x00040015u,
    0x00000015u, 0x00000020u, 0x00000001u, 0x0004001eu, 0x00000016u, 0x00000015u, 0x00000015u, 0x00040020u,
    0x00000017u, 0x00000009u, 0x00000016u, 0x0004003bu, 0x00000017u, 0x00000018u, 0x00000009u, 0x0004002bu,
    0x00000015u, 0x00000019u, 0x00000000u, 0x00040020u, 0x0000001au, 0x00000009u, 0x00000015u, 0x0004002bu,
    0x00000006u, 0x00000020u, 0x00000002u, 0x0004002bu, 0x00000015u, 0x00000027u, 0x00000001u, 0x0003001du,
    0x0000002du, 0x00000006u, 0x0003001eu, 0x0000002eu, 0x0000002du, 0x00040020u, 0x0000002fu, 0x00000002u,
    0x0000002eu, 0x0004003bu, 0x0000002fu, 0x00000030u, 0x00000002u, 0x0004002bu, 0x00000006u, 0x00000034u,
    0x00000014u, 0x0004002bu, 0x00000006u, 0x00000038u, 0x0000000au, 0x00040020u, 0x0000003eu, 0x00000002u,
    0x00000006u, 0x0004002bu, 0x00000006u, 0x00000040u, 0x00000004u, 0x0006002cu, 0x00000007u, 0x00000041u,
    0x00000040u, 0x00000020u, 0x00000020u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u,
    0x000200f8u, 0x00000005u, 0x0004003bu, 0x00000008u, 0x00000009u, 0x00000007u, 0x0004003bu, 0x0000000du,
    0x0000000eu, 0x00000007u, 0x0004003du, 0x00000007u, 0x0000000cu, 0x0000000bu, 0x0003003eu, 0x00000009u,
    0x0000000cu, 0x00050041u, 0x0000000du, 0x00000010u, 0x00000009u, 0x0000000fu, 0x0004003du, 0x00000006u,
    0x00000011u, 0x00000010u, 0x00050041u, 0x0000000du, 0x00000013u, 0x00000009u, 0x00000012u, 0x0004003du,
    0x00000006u, 0x00000014u, 0x00000013u, 0x00050041u, 0x0000001au, 0x0000001bu, 0x00000018u, 0x00000019u,
    0x0004003du, 0x00000015u, 0x0000001cu, 0x0000001bu, 0x0004007cu, 0x00000006u, 0x0000001du, 0x0000001cu,
    0x00050084u, 0x00000006u, 0x0000001eu, 0x00000014u, 0x0000001du, 0x00050080u, 0x00000006u, 0x0000001fu,
    0x00000011u, 0x0000001eu, 0x00050041u, 0x0000000du, 0x00000021u, 0x00000009u, 0x00000020u, 0x0004003du,
    0x00000006u, 0x00000022u, 0x00000021u, 0x00050041u, 0x0000001au, 0x00000023u, 0x00000018u, 0x00000019u,
    0x0004003du, 0x00000015u, 0x00000024u, 0x00000023u, 0x0004007cu, 0x00000006u, 0x00000025u, 0x00000024u,
    0x00050084u, 0x00000006u, 0x00000026u, 0x00000022u, 0x00000025u, 0x00050041u, 0x0000001au, 0x00000028u,
    0x00000018u, 0x00000027u, 0x0004003du, 0x00000015u, 0x00000029u, 0x00000028u, 0x0004007cu, 0x00000006u,
    0x0000002au, 0x00000029u, 0x00050084u, 0x00000006u, 0x0000002bu, 0x00000026u, 0x0000002au, 0x00050080u,
    0x00000006u, 0x0000002cu, 0x0000001fu, 0x0000002bu, 0x0003003eu, 0x0000000eu, 0x0000002cu, 0x0004003du,
    0x00000006u, 0x00000031u, 0x0000000eu, 0x00050041u, 0x0000000du, 0x00000032u, 0x00000009u, 0x0000000fu,
    0x0004003du, 0x00000006u, 0x00000033u, 0x00000032u, 0x000500c4u, 0x00000006u, 0x00000035u, 0x00000033u,
    0x00000034u, 0x00050041u, 0x0000000du, 0x00000036u, 0x00000009u, 0x00000012u, 0x0004003du, 0x00000006u,
    0x00000037u, 0x00000036u, 0x000500c4u, 0x00000006u, 0x00000039u, 0x00000037u, 0x00000038u, 0x000500c5u,
    0x00000006u, 0x0000003au, 0x00000035u, 0x00000039u, 0x00050041u, 0x0000000du, 0x0000003bu, 0x00000009u,
    0x00000020u, 0x0004003du, 0x00000006u, 0x0000003cu, 0x0000003bu, 0x000500c5u, 0x00000006u, 0x0000003du,
    0x0000003au, 0x0000003cu, 0x00060041u, 0x0000003eu, 0x0000003fu, 0x00000030u, 0x00000019u, 0x00000031u,
    0x0003003eu, 0x0000003fu, 0x0000003du, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kGridSpirVByteSize = sizeof(kGridSpirV);

inline constexpr std::string_view kGridWgsl =
    R"CNA_SHADER(// grid.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct Params {
    uWidth: i32,
    uHeight: i32,
}

struct Output {
    values: array<u32>,
}

var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(3) @binding(0) 
var<uniform> params: Params;
@group(0) @binding(0) 
var<storage, read_write> unnamed: Output;

fn main_1() {
    var g: vec3<u32>;
    var index: u32;

    let _e14 = gl_GlobalInvocationID_1;
    g = _e14;
    let _e16 = g[0u];
    let _e18 = g[1u];
    let _e20 = params.uWidth;
    let _e25 = g[2u];
    let _e27 = params.uWidth;
    let _e31 = params.uHeight;
    index = ((_e16 + (_e18 * bitcast<u32>(_e20))) + ((_e25 * bitcast<u32>(_e27)) * bitcast<u32>(_e31)));
    let _e35 = index;
    let _e37 = g[0u];
    let _e41 = g[1u];
    let _e46 = g[2u];
    unnamed.values[_e35] = (((_e37 << bitcast<u32>(20u)) | (_e41 << bitcast<u32>(10u))) | _e46);
    return;
}

@compute @workgroup_size(4, 2, 2) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::string_view kAccumulateEsSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

// Read-modify-write: acc[i] += input[i] * uScale, for i < uCount.
layout(local_size_x = 64) in;
layout(std430, binding = 0) readonly buffer Input
{
    float inputs[];
};
layout(std430, binding = 1) buffer Accumulator
{
    float acc[];
};

uniform int uCount;
uniform float uScale;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i < uint(uCount))
        acc[i] = acc[i] + inputs[i] * uScale;
}
)CNA_SHADER";

inline constexpr std::uint32_t kAccumulateSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000039u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000040u, 0x00000001u, 0x00000001u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x000a0004u,
    0x475f4c47u, 0x4c474f4fu, 0x70635f45u, 0x74735f70u, 0x5f656c79u, 0x656e696cu, 0x7269645fu, 0x69746365u,
    0x00006576u, 0x00080004u, 0x475f4c47u, 0x4c474f4fu, 0x6e695f45u, 0x64756c63u, 0x69645f65u, 0x74636572u,
    0x00657669u, 0x00040005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00030005u, 0x00000008u, 0x00000069u,
    0x00080005u, 0x0000000bu, 0x475f6c67u, 0x61626f6cu, 0x766e496cu, 0x7461636fu, 0x496e6f69u, 0x00000044u,
    0x00040005u, 0x00000013u, 0x61726150u, 0x0000736du, 0x00050006u, 0x00000013u, 0x00000000u, 0x756f4375u,
    0x0000746eu, 0x00050006u, 0x00000013u, 0x00000001u, 0x61635375u, 0x0000656cu, 0x00040005u, 0x00000015u,
    0x61726170u, 0x0000736du, 0x00050005u, 0x00000020u, 0x75636341u, 0x616c756du, 0x00726f74u, 0x00040006u,
    0x00000020u, 0x00000000u, 0x00636361u, 0x00030005u, 0x00000022u, 0x00000000u, 0x00040005u, 0x00000029u,
    0x75706e49u, 0x00000074u, 0x00050006u, 0x00000029u, 0x00000000u, 0x75706e69u, 0x00007374u, 0x00030005u,
    0x0000002bu, 0x00000000u, 0x00040047u, 0x0000000bu, 0x0000000bu, 0x0000001cu, 0x00030047u, 0x00000013u,
    0x00000002u, 0x00050048u, 0x00000013u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00050048u, 0x00000013u,
    0x00000001u, 0x00000023u, 0x00000004u, 0x00040047u, 0x0000001fu, 0x00000006u, 0x00000004u, 0x00030047u,
    0x00000020u, 0x00000003u, 0x00050048u, 0x00000020u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u,
    0x00000022u, 0x00000021u, 0x00000001u, 0x00040047u, 0x00000022u, 0x00000022u, 0x00000000u, 0x00040047u,
    0x00000028u, 0x00000006u, 0x00000004u, 0x00030047u, 0x00000029u, 0x00000003u, 0x00040048u, 0x00000029u,
    0x00000000u, 0x00000018u, 0x00050048u, 0x00000029u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u,
    0x0000002bu, 0x00000018u, 0x00040047u, 0x0000002bu, 0x00000021u, 0x00000000u, 0x00040047u, 0x0000002bu,
    0x00000022u, 0x00000000u, 0x00040047u, 0x00000038u, 0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u,
    0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u, 0x00000006u, 0x00000020u, 0x00000000u, 0x00040020u,
    0x00000007u, 0x00000007u, 0x00000006u, 0x00040017u, 0x00000009u, 0x00000006u, 0x00000003u, 0x00040020u,
    0x0000000au, 0x00000001u, 0x00000009u, 0x0004003bu, 0x0000000au, 0x0000000bu, 0x00000001u, 0x0004002bu,
    0x00000006u, 0x0000000cu, 0x00000000u, 0x00040020u, 0x0000000du, 0x00000001u, 0x00000006u, 0x00040015u,
    0x00000011u, 0x00000020u, 0x00000001u, 0x00030016u, 0x00000012u, 0x00000020u, 0x0004001eu, 0x00000013u,
    0x00000011u, 0x00000012u, 0x00040020u, 0x00000014u, 0x00000009u, 0x00000013u, 0x0004003bu, 0x00000014u,
    0x00000015u, 0x00000009u, 0x0004002bu, 0x00000011u, 0x00000016u, 0x00000000u, 0x00040020u, 0x00000017u,
    0x00000009u, 0x00000011u, 0x00020014u, 0x0000001bu, 0x0003001du, 0x0000001fu, 0x00000012u, 0x0003001eu,
    0x00000020u, 0x0000001fu, 0x00040020u, 0x00000021u, 0x00000002u, 0x00000020u, 0x0004003bu, 0x00000021u,
    0x00000022u, 0x00000002u, 0x00040020u, 0x00000025u, 0x00000002u, 0x00000012u, 0x0003001du, 0x00000028u,
    0x00000012u, 0x0003001eu, 0x00000029u, 0x00000028u, 0x00040020u, 0x0000002au, 0x00000002u, 0x00000029u,
    0x0004003bu, 0x0000002au, 0x0000002bu, 0x00000002u, 0x0004002bu, 0x00000011u, 0x0000002fu, 0x00000001u,
    0x00040020u, 0x00000030u, 0x00000009u, 0x00000012u, 0x0004002bu, 0x00000006u, 0x00000036u, 0x00000040u,
    0x0004002bu, 0x00000006u, 0x00000037u, 0x00000001u, 0x0006002cu, 0x00000009u, 0x00000038u, 0x00000036u,
    0x00000037u, 0x00000037u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u,
    0x00000005u, 0x0004003bu, 0x00000007u, 0x00000008u, 0x00000007u, 0x00050041u, 0x0000000du, 0x0000000eu,
    0x0000000bu, 0x0000000cu, 0x0004003du, 0x00000006u, 0x0000000fu, 0x0000000eu, 0x0003003eu, 0x00000008u,
    0x0000000fu, 0x0004003du, 0x00000006u, 0x00000010u, 0x00000008u, 0x00050041u, 0x00000017u, 0x00000018u,
    0x00000015u, 0x00000016u, 0x0004003du, 0x00000011u, 0x00000019u, 0x00000018u, 0x0004007cu, 0x00000006u,
    0x0000001au, 0x00000019u, 0x000500b0u, 0x0000001bu, 0x0000001cu, 0x00000010u, 0x0000001au, 0x000300f7u,
    0x0000001eu, 0x00000000u, 0x000400fau, 0x0000001cu, 0x0000001du, 0x0000001eu, 0x000200f8u, 0x0000001du,
    0x0004003du, 0x00000006u, 0x00000023u, 0x00000008u, 0x0004003du, 0x00000006u, 0x00000024u, 0x00000008u,
    0x00060041u, 0x00000025u, 0x00000026u, 0x00000022u, 0x00000016u, 0x00000024u, 0x0004003du, 0x00000012u,
    0x00000027u, 0x00000026u, 0x0004003du, 0x00000006u, 0x0000002cu, 0x00000008u, 0x00060041u, 0x00000025u,
    0x0000002du, 0x0000002bu, 0x00000016u, 0x0000002cu, 0x0004003du, 0x00000012u, 0x0000002eu, 0x0000002du,
    0x00050041u, 0x00000030u, 0x00000031u, 0x00000015u, 0x0000002fu, 0x0004003du, 0x00000012u, 0x00000032u,
    0x00000031u, 0x00050085u, 0x00000012u, 0x00000033u, 0x0000002eu, 0x00000032u, 0x00050081u, 0x00000012u,
    0x00000034u, 0x00000027u, 0x00000033u, 0x00060041u, 0x00000025u, 0x00000035u, 0x00000022u, 0x00000016u,
    0x00000023u, 0x0003003eu, 0x00000035u, 0x00000034u, 0x000200f9u, 0x0000001eu, 0x000200f8u, 0x0000001eu,
    0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kAccumulateSpirVByteSize = sizeof(kAccumulateSpirV);

inline constexpr std::string_view kAccumulateWgsl =
    R"CNA_SHADER(// accumulate.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct Params {
    uCount: i32,
    uScale: f32,
}

struct Accumulator {
    acc: array<f32>,
}

struct Input {
    inputs: array<f32>,
}

var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(3) @binding(0) 
var<uniform> params: Params;
@group(0) @binding(1) 
var<storage, read_write> unnamed: Accumulator;
@group(0) @binding(0) 
var<storage> unnamed_1: Input;

fn main_1() {
    var i: u32;

    let _e12 = gl_GlobalInvocationID_1[0u];
    i = _e12;
    let _e13 = i;
    let _e15 = params.uCount;
    if (_e13 < bitcast<u32>(_e15)) {
        let _e18 = i;
        let _e19 = i;
        let _e22 = unnamed.acc[_e19];
        let _e23 = i;
        let _e26 = unnamed_1.inputs[_e23];
        let _e28 = params.uScale;
        unnamed.acc[_e18] = (_e22 + (_e26 * _e28));
    }
    return;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::string_view kChainEsSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

// One link of a chain: dst[i] = src[i] * 2 + 1. Chained dispatches read what the previous one wrote.
layout(local_size_x = 64) in;
layout(std430, binding = 0) readonly buffer Source
{
    uint src[];
};
layout(std430, binding = 1) writeonly buffer Destination
{
    uint dst[];
};

uniform int uCount;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i < uint(uCount))
        dst[i] = src[i] * 2u + 1u;
}
)CNA_SHADER";

inline constexpr std::uint32_t kChainSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000032u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000040u, 0x00000001u, 0x00000001u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x000a0004u,
    0x475f4c47u, 0x4c474f4fu, 0x70635f45u, 0x74735f70u, 0x5f656c79u, 0x656e696cu, 0x7269645fu, 0x69746365u,
    0x00006576u, 0x00080004u, 0x475f4c47u, 0x4c474f4fu, 0x6e695f45u, 0x64756c63u, 0x69645f65u, 0x74636572u,
    0x00657669u, 0x00040005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00030005u, 0x00000008u, 0x00000069u,
    0x00080005u, 0x0000000bu, 0x475f6c67u, 0x61626f6cu, 0x766e496cu, 0x7461636fu, 0x496e6f69u, 0x00000044u,
    0x00040005u, 0x00000012u, 0x61726150u, 0x0000736du, 0x00050006u, 0x00000012u, 0x00000000u, 0x756f4375u,
    0x0000746eu, 0x00040005u, 0x00000014u, 0x61726170u, 0x0000736du, 0x00050005u, 0x0000001fu, 0x74736544u,
    0x74616e69u, 0x006e6f69u, 0x00040006u, 0x0000001fu, 0x00000000u, 0x00747364u, 0x00030005u, 0x00000021u,
    0x00000000u, 0x00040005u, 0x00000024u, 0x72756f53u, 0x00006563u, 0x00040006u, 0x00000024u, 0x00000000u,
    0x00637273u, 0x00030005u, 0x00000026u, 0x00000000u, 0x00040047u, 0x0000000bu, 0x0000000bu, 0x0000001cu,
    0x00030047u, 0x00000012u, 0x00000002u, 0x00050048u, 0x00000012u, 0x00000000u, 0x00000023u, 0x00000000u,
    0x00040047u, 0x0000001eu, 0x00000006u, 0x00000004u, 0x00030047u, 0x0000001fu, 0x00000003u, 0x00040048u,
    0x0000001fu, 0x00000000u, 0x00000019u, 0x00050048u, 0x0000001fu, 0x00000000u, 0x00000023u, 0x00000000u,
    0x00030047u, 0x00000021u, 0x00000019u, 0x00040047u, 0x00000021u, 0x00000021u, 0x00000001u, 0x00040047u,
    0x00000021u, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000023u, 0x00000006u, 0x00000004u, 0x00030047u,
    0x00000024u, 0x00000003u, 0x00040048u, 0x00000024u, 0x00000000u, 0x00000018u, 0x00050048u, 0x00000024u,
    0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u, 0x00000026u, 0x00000018u, 0x00040047u, 0x00000026u,
    0x00000021u, 0x00000000u, 0x00040047u, 0x00000026u, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000031u,
    0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u,
    0x00000006u, 0x00000020u, 0x00000000u, 0x00040020u, 0x00000007u, 0x00000007u, 0x00000006u, 0x00040017u,
    0x00000009u, 0x00000006u, 0x00000003u, 0x00040020u, 0x0000000au, 0x00000001u, 0x00000009u, 0x0004003bu,
    0x0000000au, 0x0000000bu, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000000cu, 0x00000000u, 0x00040020u,
    0x0000000du, 0x00000001u, 0x00000006u, 0x00040015u, 0x00000011u, 0x00000020u, 0x00000001u, 0x0003001eu,
    0x00000012u, 0x00000011u, 0x00040020u, 0x00000013u, 0x00000009u, 0x00000012u, 0x0004003bu, 0x00000013u,
    0x00000014u, 0x00000009u, 0x0004002bu, 0x00000011u, 0x00000015u, 0x00000000u, 0x00040020u, 0x00000016u,
    0x00000009u, 0x00000011u, 0x00020014u, 0x0000001au, 0x0003001du, 0x0000001eu, 0x00000006u, 0x0003001eu,
    0x0000001fu, 0x0000001eu, 0x00040020u, 0x00000020u, 0x00000002u, 0x0000001fu, 0x0004003bu, 0x00000020u,
    0x00000021u, 0x00000002u, 0x0003001du, 0x00000023u, 0x00000006u, 0x0003001eu, 0x00000024u, 0x00000023u,
    0x00040020u, 0x00000025u, 0x00000002u, 0x00000024u, 0x0004003bu, 0x00000025u, 0x00000026u, 0x00000002u,
    0x00040020u, 0x00000028u, 0x00000002u, 0x00000006u, 0x0004002bu, 0x00000006u, 0x0000002bu, 0x00000002u,
    0x0004002bu, 0x00000006u, 0x0000002du, 0x00000001u, 0x0004002bu, 0x00000006u, 0x00000030u, 0x00000040u,
    0x0006002cu, 0x00000009u, 0x00000031u, 0x00000030u, 0x0000002du, 0x0000002du, 0x00050036u, 0x00000002u,
    0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003bu, 0x00000007u, 0x00000008u,
    0x00000007u, 0x00050041u, 0x0000000du, 0x0000000eu, 0x0000000bu, 0x0000000cu, 0x0004003du, 0x00000006u,
    0x0000000fu, 0x0000000eu, 0x0003003eu, 0x00000008u, 0x0000000fu, 0x0004003du, 0x00000006u, 0x00000010u,
    0x00000008u, 0x00050041u, 0x00000016u, 0x00000017u, 0x00000014u, 0x00000015u, 0x0004003du, 0x00000011u,
    0x00000018u, 0x00000017u, 0x0004007cu, 0x00000006u, 0x00000019u, 0x00000018u, 0x000500b0u, 0x0000001au,
    0x0000001bu, 0x00000010u, 0x00000019u, 0x000300f7u, 0x0000001du, 0x00000000u, 0x000400fau, 0x0000001bu,
    0x0000001cu, 0x0000001du, 0x000200f8u, 0x0000001cu, 0x0004003du, 0x00000006u, 0x00000022u, 0x00000008u,
    0x0004003du, 0x00000006u, 0x00000027u, 0x00000008u, 0x00060041u, 0x00000028u, 0x00000029u, 0x00000026u,
    0x00000015u, 0x00000027u, 0x0004003du, 0x00000006u, 0x0000002au, 0x00000029u, 0x00050084u, 0x00000006u,
    0x0000002cu, 0x0000002au, 0x0000002bu, 0x00050080u, 0x00000006u, 0x0000002eu, 0x0000002cu, 0x0000002du,
    0x00060041u, 0x00000028u, 0x0000002fu, 0x00000021u, 0x00000015u, 0x00000022u, 0x0003003eu, 0x0000002fu,
    0x0000002eu, 0x000200f9u, 0x0000001du, 0x000200f8u, 0x0000001du, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kChainSpirVByteSize = sizeof(kChainSpirV);

inline constexpr std::string_view kChainWgsl =
    R"CNA_SHADER(// chain.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct Params {
    uCount: i32,
}

struct Destination {
    dst: array<u32>,
}

struct Source {
    src: array<u32>,
}

var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(3) @binding(0) 
var<uniform> params: Params;
@group(0) @binding(1) 
var<storage, read_write> unnamed: Destination;
@group(0) @binding(0) 
var<storage> unnamed_1: Source;

fn main_1() {
    var i: u32;

    let _e12 = gl_GlobalInvocationID_1[0u];
    i = _e12;
    let _e13 = i;
    let _e15 = params.uCount;
    if (_e13 < bitcast<u32>(_e15)) {
        let _e18 = i;
        let _e19 = i;
        let _e22 = unnamed_1.src[_e19];
        unnamed.dst[_e18] = ((_e22 * 2u) + 1u);
    }
    return;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::string_view kImageEsSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

// Writes a coordinate pattern into an rgba8 storage image: (x, y, x ^ y, 255) as bytes.
layout(local_size_x = 8, local_size_y = 8) in;
layout(rgba8, binding = 0) writeonly uniform highp image2D uImage;

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    imageStore(uImage, p, vec4(float(p.x), float(p.y), float(p.x ^ p.y), 255.0) / 255.0);
}
)CNA_SHADER";

inline constexpr std::uint32_t kImageSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x0000002eu, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000du, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000008u, 0x00000008u, 0x00000001u, 0x00030003u, 0x00000002u, 0x000001c2u, 0x000a0004u,
    0x475f4c47u, 0x4c474f4fu, 0x70635f45u, 0x74735f70u, 0x5f656c79u, 0x656e696cu, 0x7269645fu, 0x69746365u,
    0x00006576u, 0x00080004u, 0x475f4c47u, 0x4c474f4fu, 0x6e695f45u, 0x64756c63u, 0x69645f65u, 0x74636572u,
    0x00657669u, 0x00040005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00030005u, 0x00000009u, 0x00000070u,
    0x00080005u, 0x0000000du, 0x475f6c67u, 0x61626f6cu, 0x766e496cu, 0x7461636fu, 0x496e6f69u, 0x00000044u,
    0x00040005u, 0x00000015u, 0x616d4975u, 0x00006567u, 0x00040047u, 0x0000000du, 0x0000000bu, 0x0000001cu,
    0x00030047u, 0x00000015u, 0x00000019u, 0x00040047u, 0x00000015u, 0x00000021u, 0x00000000u, 0x00040047u,
    0x00000015u, 0x00000022u, 0x00000000u, 0x00040047u, 0x0000002du, 0x0000000bu, 0x00000019u, 0x00020013u,
    0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u, 0x00000006u, 0x00000020u, 0x00000001u,
    0x00040017u, 0x00000007u, 0x00000006u, 0x00000002u, 0x00040020u, 0x00000008u, 0x00000007u, 0x00000007u,
    0x00040015u, 0x0000000au, 0x00000020u, 0x00000000u, 0x00040017u, 0x0000000bu, 0x0000000au, 0x00000003u,
    0x00040020u, 0x0000000cu, 0x00000001u, 0x0000000bu, 0x0004003bu, 0x0000000cu, 0x0000000du, 0x00000001u,
    0x00040017u, 0x0000000eu, 0x0000000au, 0x00000002u, 0x00030016u, 0x00000012u, 0x00000020u, 0x00090019u,
    0x00000013u, 0x00000012u, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000002u, 0x00000004u,
    0x00040020u, 0x00000014u, 0x00000000u, 0x00000013u, 0x0004003bu, 0x00000014u, 0x00000015u, 0x00000000u,
    0x0004002bu, 0x0000000au, 0x00000018u, 0x00000000u, 0x00040020u, 0x00000019u, 0x00000007u, 0x00000006u,
    0x0004002bu, 0x0000000au, 0x0000001du, 0x00000001u, 0x0004002bu, 0x00000012u, 0x00000027u, 0x437f0000u,
    0x00040017u, 0x00000028u, 0x00000012u, 0x00000004u, 0x0004002bu, 0x0000000au, 0x0000002cu, 0x00000008u,
    0x0006002cu, 0x0000000bu, 0x0000002du, 0x0000002cu, 0x0000002cu, 0x0000001du, 0x00050036u, 0x00000002u,
    0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003bu, 0x00000008u, 0x00000009u,
    0x00000007u, 0x0004003du, 0x0000000bu, 0x0000000fu, 0x0000000du, 0x0007004fu, 0x0000000eu, 0x00000010u,
    0x0000000fu, 0x0000000fu, 0x00000000u, 0x00000001u, 0x0004007cu, 0x00000007u, 0x00000011u, 0x00000010u,
    0x0003003eu, 0x00000009u, 0x00000011u, 0x0004003du, 0x00000013u, 0x00000016u, 0x00000015u, 0x0004003du,
    0x00000007u, 0x00000017u, 0x00000009u, 0x00050041u, 0x00000019u, 0x0000001au, 0x00000009u, 0x00000018u,
    0x0004003du, 0x00000006u, 0x0000001bu, 0x0000001au, 0x0004006fu, 0x00000012u, 0x0000001cu, 0x0000001bu,
    0x00050041u, 0x00000019u, 0x0000001eu, 0x00000009u, 0x0000001du, 0x0004003du, 0x00000006u, 0x0000001fu,
    0x0000001eu, 0x0004006fu, 0x00000012u, 0x00000020u, 0x0000001fu, 0x00050041u, 0x00000019u, 0x00000021u,
    0x00000009u, 0x00000018u, 0x0004003du, 0x00000006u, 0x00000022u, 0x00000021u, 0x00050041u, 0x00000019u,
    0x00000023u, 0x00000009u, 0x0000001du, 0x0004003du, 0x00000006u, 0x00000024u, 0x00000023u, 0x000500c6u,
    0x00000006u, 0x00000025u, 0x00000022u, 0x00000024u, 0x0004006fu, 0x00000012u, 0x00000026u, 0x00000025u,
    0x00070050u, 0x00000028u, 0x00000029u, 0x0000001cu, 0x00000020u, 0x00000026u, 0x00000027u, 0x00070050u,
    0x00000028u, 0x0000002au, 0x00000027u, 0x00000027u, 0x00000027u, 0x00000027u, 0x00050088u, 0x00000028u,
    0x0000002bu, 0x00000029u, 0x0000002au, 0x00040063u, 0x00000016u, 0x00000017u, 0x0000002bu, 0x000100fdu,
    0x00010038u,
};
inline constexpr std::size_t kImageSpirVByteSize = sizeof(kImageSpirV);

inline constexpr std::string_view kImageWgsl =
    R"CNA_SHADER(// image.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(0) @binding(0) 
var uImage: texture_storage_2d<rgba8unorm,write>;

fn main_1() {
    var p: vec2<i32>;

    let _e8 = gl_GlobalInvocationID_1;
    p = bitcast<vec2<i32>>(_e8.xy);
    let _e11 = p;
    let _e13 = p[0u];
    let _e16 = p[1u];
    let _e19 = p[0u];
    let _e21 = p[1u];
    textureStore(uImage, _e11, (vec4<f32>(f32(_e13), f32(_e16), f32((_e19 ^ _e21)), 255f) / vec4(255f)));
    return;
}

@compute @workgroup_size(8, 8, 1) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::string_view kGridDesktopSource =
    R"CNA_SHADER(#version 430 core

// Every invocation of a 3D dispatch writes its own global id, packed, at its own linear index.
layout(local_size_x = 4, local_size_y = 2, local_size_z = 2) in;
layout(std430, binding = 0) writeonly buffer Output
{
    uint values[];
};

uniform int uWidth;
uniform int uHeight;

void main()
{
    uvec3 g = gl_GlobalInvocationID;
    uint index = g.x + g.y * uint(uWidth) + g.z * uint(uWidth) * uint(uHeight);
    values[index] = (g.x << 20u) | (g.y << 10u) | g.z;
}
)CNA_SHADER";

inline constexpr std::string_view kAccumulateDesktopSource =
    R"CNA_SHADER(#version 430 core

// Read-modify-write: acc[i] += input[i] * uScale, for i < uCount.
layout(local_size_x = 64) in;
layout(std430, binding = 0) readonly buffer Input
{
    float inputs[];
};
layout(std430, binding = 1) buffer Accumulator
{
    float acc[];
};

uniform int uCount;
uniform float uScale;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i < uint(uCount))
        acc[i] = acc[i] + inputs[i] * uScale;
}
)CNA_SHADER";

inline constexpr std::string_view kChainDesktopSource =
    R"CNA_SHADER(#version 430 core

// One link of a chain: dst[i] = src[i] * 2 + 1. Chained dispatches read what the previous one wrote.
layout(local_size_x = 64) in;
layout(std430, binding = 0) readonly buffer Source
{
    uint src[];
};
layout(std430, binding = 1) writeonly buffer Destination
{
    uint dst[];
};

uniform int uCount;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i < uint(uCount))
        dst[i] = src[i] * 2u + 1u;
}
)CNA_SHADER";

inline constexpr std::string_view kImageDesktopSource =
    R"CNA_SHADER(#version 430 core

// Writes a coordinate pattern into an rgba8 storage image: (x, y, x ^ y, 255) as bytes.
layout(local_size_x = 8, local_size_y = 8) in;
layout(rgba8, binding = 0) writeonly uniform image2D uImage;

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    imageStore(uImage, p, vec4(float(p.x), float(p.y), float(p.x ^ p.y), 255.0) / 255.0);
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 16> kPayloads = {{
    {"kGridEsSource", "grid.es.comp.glsl", "28c6e2e6ecab4d70b968b33766240ce83c16c2274fa0953307190a5d5c6d55bf", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kGridSpirV", "grid.vulkan.comp.glsl", "ca44c1f5a0fef7c460b8e585720f22480124c339ff6dc27f05aed13fa838c71e", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kGridWgsl", "grid.vulkan.comp.glsl", "ca44c1f5a0fef7c460b8e585720f22480124c339ff6dc27f05aed13fa838c71e", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
    {"kAccumulateEsSource", "accumulate.es.comp.glsl", "e1ddb16eb1a502992619b92a7ef1bfeffc739782476e30d0ce9c090ae54e4527", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kAccumulateSpirV", "accumulate.vulkan.comp.glsl", "89c7048ccdcbeaf8b125ec69a31bf9c37dfdcc1ba02f4b8b983c5e06e1fa924c", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kAccumulateWgsl", "accumulate.vulkan.comp.glsl", "89c7048ccdcbeaf8b125ec69a31bf9c37dfdcc1ba02f4b8b983c5e06e1fa924c", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
    {"kChainEsSource", "chain.es.comp.glsl", "6eb3c8a87a05d44c8d7968871618f5ddd1b6e9836e1d0380272ebae422fdad36", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kChainSpirV", "chain.vulkan.comp.glsl", "123efb44366e5596cdf1f2f3702ce20d72ecaf95273389194681fa52d60edb17", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kChainWgsl", "chain.vulkan.comp.glsl", "123efb44366e5596cdf1f2f3702ce20d72ecaf95273389194681fa52d60edb17", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
    {"kImageEsSource", "image.es.comp.glsl", "640b207c30916fae4a3eb5dfdea7a6ec29c8115d035a2ac5d22e5b5498a42526", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kImageSpirV", "image.vulkan.comp.glsl", "978e15a776f882edc4c61f87fe7623d79efe37180d272d157c550e367c032729", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kImageWgsl", "image.vulkan.comp.glsl", "978e15a776f882edc4c61f87fe7623d79efe37180d272d157c550e367c032729", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
    {"kGridDesktopSource", "grid.desktop.comp.glsl", "310a18f9eb94b19bb8ee35c3b00bc69baa23470bb2f9f7343d95f2f851e452ed", "glsl", "glsl", "compute", "text", "main"},
    {"kAccumulateDesktopSource", "accumulate.desktop.comp.glsl", "270ecb2aaea983484e875e3f3ea80eefbf6b1a0d8042bffbb2504a5518ea5733", "glsl", "glsl", "compute", "text", "main"},
    {"kChainDesktopSource", "chain.desktop.comp.glsl", "4e5771bfa0794232fec85f23fd1f7a8be520b9c62c50d6cc02b5a6ea3221b3d9", "glsl", "glsl", "compute", "text", "main"},
    {"kImageDesktopSource", "image.desktop.comp.glsl", "84c0159e3f2a2d8577347eae110c2a9f3cd3bd98785d6fca63d89da8de5d3f1a", "glsl", "glsl", "compute", "text", "main"},
}};

} // namespace CNA::Tests::ModernConformance
