// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Tests::TransparencyGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "transparency_test";
inline constexpr std::string_view kManifestSha256 = "1a895889f075d497e61d9f2e87842d02cef30ecefcaf986635698f6eb782d245";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kBasicEsVertexSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

layout(location = 0) in vec3 aPos;

void main()
{
    gl_Position = vec4(aPos, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kDirectEsVertexSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

layout(location = 0) in vec3 aPos;
out float PositionX;

void main()
{
    gl_Position = vec4(aPos, 1.0);
    PositionX = aPos.x * 0.5 + 0.5;
}
)CNA_SHADER";

inline constexpr std::string_view kEmitterEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

layout(location = 0) out vec4 cnaOitAccumulation;
layout(location = 1) out vec4 cnaOitRevealage;
uniform vec4 uEffectParams;
uniform float uScalar;

void main()
{
    float alpha = uEffectParams.a;
    float z = clamp(uScalar, 0.0, 1.0);
    float weight = alpha * clamp(0.03 / (1e-5 + pow(z, 4.0)), 1e-2, 3e3);
    cnaOitAccumulation = vec4(uEffectParams.rgb * alpha * weight, alpha * weight);
    cnaOitRevealage = vec4(log(max(1.0 - alpha, 1e-4)), 0.0, 0.0, 0.0);
}
)CNA_SHADER";

inline constexpr std::string_view kFlatEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

out vec4 FragColor;
uniform vec4 uEffectParams;

void main()
{
    FragColor = uEffectParams;
}
)CNA_SHADER";

inline constexpr std::string_view kWeightProbeEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

in float PositionX;
out vec4 FragColor;
uniform vec4 uEffectParams;

void main()
{
    float depth = mix(uEffectParams.y, uEffectParams.z, PositionX);
    float z = clamp(depth / max(uEffectParams.w, 1e-4), 0.0, 1.0);
    float weight = uEffectParams.x * clamp(0.03 / (1e-5 + pow(z, 4.0)), 1e-2, 3e3);
    float encoded = (log(weight) / 2.302585 + 2.0) / 5.5;
    FragColor = vec4(clamp(encoded, 0.0, 1.0), 0.0, 0.0, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kBasicDesktopVertexSource =
    R"CNA_SHADER(#version 330 core

layout(location = 0) in vec3 aPos;

void main()
{
    gl_Position = vec4(aPos, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kDirectDesktopVertexSource =
    R"CNA_SHADER(#version 330 core

layout(location = 0) in vec3 aPos;
out float PositionX;

void main()
{
    gl_Position = vec4(aPos, 1.0);
    PositionX = aPos.x * 0.5 + 0.5;
}
)CNA_SHADER";

inline constexpr std::string_view kEmitterDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core

layout(location = 0) out vec4 cnaOitAccumulation;
layout(location = 1) out vec4 cnaOitRevealage;
uniform vec4 uEffectParams;
uniform float uScalar;

void main()
{
    float alpha = uEffectParams.a;
    float z = clamp(uScalar, 0.0, 1.0);
    float weight = alpha * clamp(0.03 / (1e-5 + pow(z, 4.0)), 1e-2, 3e3);
    cnaOitAccumulation = vec4(uEffectParams.rgb * alpha * weight, alpha * weight);
    cnaOitRevealage = vec4(log(max(1.0 - alpha, 1e-4)), 0.0, 0.0, 0.0);
}
)CNA_SHADER";

inline constexpr std::string_view kFlatDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core

out vec4 FragColor;
uniform vec4 uEffectParams;

void main()
{
    FragColor = uEffectParams;
}
)CNA_SHADER";

inline constexpr std::string_view kWeightProbeDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core

in float PositionX;
out vec4 FragColor;
uniform vec4 uEffectParams;

void main()
{
    float depth = mix(uEffectParams.y, uEffectParams.z, PositionX);
    float z = clamp(depth / max(uEffectParams.w, 1e-4), 0.0, 1.0);
    float weight = uEffectParams.x * clamp(0.03 / (1e-5 + pow(z, 4.0)), 1e-2, 3e3);
    float encoded = (log(weight) / 2.302585 + 2.0) / 5.5;
    FragColor = vec4(clamp(encoded, 0.0, 1.0), 0.0, 0.0, 1.0);
}
)CNA_SHADER";

inline constexpr std::uint32_t kBasicVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000023u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0007000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000du, 0x00000012u, 0x00030047u,
    0x0000000bu, 0x00000002u, 0x00050048u, 0x0000000bu, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u,
    0x0000000bu, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x0000000bu, 0x00000002u, 0x0000000bu,
    0x00000003u, 0x00050048u, 0x0000000bu, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00040047u, 0x00000012u,
    0x0000001eu, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u,
    0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u, 0x00040015u, 0x00000008u,
    0x00000020u, 0x00000000u, 0x0004002bu, 0x00000008u, 0x00000009u, 0x00000001u, 0x0004001cu, 0x0000000au,
    0x00000006u, 0x00000009u, 0x0006001eu, 0x0000000bu, 0x00000007u, 0x00000006u, 0x0000000au, 0x0000000au,
    0x00040020u, 0x0000000cu, 0x00000003u, 0x0000000bu, 0x0004003bu, 0x0000000cu, 0x0000000du, 0x00000003u,
    0x00040015u, 0x0000000eu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000eu, 0x0000000fu, 0x00000000u,
    0x00040017u, 0x00000010u, 0x00000006u, 0x00000003u, 0x00040020u, 0x00000011u, 0x00000001u, 0x00000010u,
    0x0004003bu, 0x00000011u, 0x00000012u, 0x00000001u, 0x0004002bu, 0x00000008u, 0x00000016u, 0x00000002u,
    0x00040020u, 0x00000017u, 0x00000001u, 0x00000006u, 0x0004002bu, 0x00000006u, 0x0000001au, 0x3f000000u,
    0x0004002bu, 0x00000006u, 0x0000001du, 0x3f800000u, 0x00040020u, 0x00000021u, 0x00000003u, 0x00000007u,
    0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du,
    0x00000010u, 0x00000014u, 0x00000012u, 0x00050041u, 0x00000017u, 0x00000018u, 0x00000012u, 0x00000016u,
    0x0004003du, 0x00000006u, 0x00000019u, 0x00000018u, 0x00050085u, 0x00000006u, 0x0000001bu, 0x00000019u,
    0x0000001au, 0x00050081u, 0x00000006u, 0x0000001cu, 0x0000001bu, 0x0000001au, 0x00050051u, 0x00000006u,
    0x0000001eu, 0x00000014u, 0x00000000u, 0x00050051u, 0x00000006u, 0x0000001fu, 0x00000014u, 0x00000001u,
    0x00070050u, 0x00000007u, 0x00000020u, 0x0000001eu, 0x0000001fu, 0x0000001cu, 0x0000001du, 0x00050041u,
    0x00000021u, 0x00000022u, 0x0000000du, 0x0000000fu, 0x0003003eu, 0x00000022u, 0x00000020u, 0x000100fdu,
    0x00010038u,
};
inline constexpr std::size_t kBasicVulkanVertexSpirVByteSize = sizeof(kBasicVulkanVertexSpirV);

inline constexpr std::string_view kBasicVulkanVertexWgsl =
    R"CNA_SHADER(// basic.vulkan.vert.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct gl_PerVertex {
    @builtin(position) gl_Position: vec4<f32>,
    gl_PointSize: f32,
    gl_ClipDistance: array<f32, 1>,
    gl_CullDistance: array<f32, 1>,
}

var<private> unnamed: gl_PerVertex = gl_PerVertex(vec4<f32>(0f, 0f, 0f, 1f), 1f, array<f32, 1>(), array<f32, 1>());
var<private> aPos_1: vec3<f32>;

fn main_1() {
    let _e7 = aPos_1;
    let _e8 = _e7.xy;
    let _e10 = aPos_1[2u];
    unnamed.gl_Position = vec4<f32>(_e8.x, _e8.y, ((_e10 * 0.5f) + 0.5f), 1f);
    return;
}

@vertex 
fn main(@location(0) aPos: vec3<f32>) -> @builtin(position) vec4<f32> {
    aPos_1 = aPos;
    main_1();
    let _e5 = unnamed.gl_Position.y;
    unnamed.gl_Position.y = -(_e5);
    let _e7 = unnamed.gl_Position;
    return _e7;
}
)CNA_SHADER";

inline constexpr std::uint32_t kDirectVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x0000002au, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0008000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000du, 0x00000012u, 0x00000024u,
    0x00030047u, 0x0000000bu, 0x00000002u, 0x00050048u, 0x0000000bu, 0x00000000u, 0x0000000bu, 0x00000000u,
    0x00050048u, 0x0000000bu, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x0000000bu, 0x00000002u,
    0x0000000bu, 0x00000003u, 0x00050048u, 0x0000000bu, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00040047u,
    0x00000012u, 0x0000001eu, 0x00000000u, 0x00040047u, 0x00000024u, 0x0000001eu, 0x00000000u, 0x00020013u,
    0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u,
    0x00000007u, 0x00000006u, 0x00000004u, 0x00040015u, 0x00000008u, 0x00000020u, 0x00000000u, 0x0004002bu,
    0x00000008u, 0x00000009u, 0x00000001u, 0x0004001cu, 0x0000000au, 0x00000006u, 0x00000009u, 0x0006001eu,
    0x0000000bu, 0x00000007u, 0x00000006u, 0x0000000au, 0x0000000au, 0x00040020u, 0x0000000cu, 0x00000003u,
    0x0000000bu, 0x0004003bu, 0x0000000cu, 0x0000000du, 0x00000003u, 0x00040015u, 0x0000000eu, 0x00000020u,
    0x00000001u, 0x0004002bu, 0x0000000eu, 0x0000000fu, 0x00000000u, 0x00040017u, 0x00000010u, 0x00000006u,
    0x00000003u, 0x00040020u, 0x00000011u, 0x00000001u, 0x00000010u, 0x0004003bu, 0x00000011u, 0x00000012u,
    0x00000001u, 0x0004002bu, 0x00000008u, 0x00000016u, 0x00000002u, 0x00040020u, 0x00000017u, 0x00000001u,
    0x00000006u, 0x0004002bu, 0x00000006u, 0x0000001au, 0x3f000000u, 0x0004002bu, 0x00000006u, 0x0000001du,
    0x3f800000u, 0x00040020u, 0x00000021u, 0x00000003u, 0x00000007u, 0x00040020u, 0x00000023u, 0x00000003u,
    0x00000006u, 0x0004003bu, 0x00000023u, 0x00000024u, 0x00000003u, 0x0004002bu, 0x00000008u, 0x00000025u,
    0x00000000u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u,
    0x0004003du, 0x00000010u, 0x00000014u, 0x00000012u, 0x00050041u, 0x00000017u, 0x00000018u, 0x00000012u,
    0x00000016u, 0x0004003du, 0x00000006u, 0x00000019u, 0x00000018u, 0x00050085u, 0x00000006u, 0x0000001bu,
    0x00000019u, 0x0000001au, 0x00050081u, 0x00000006u, 0x0000001cu, 0x0000001bu, 0x0000001au, 0x00050051u,
    0x00000006u, 0x0000001eu, 0x00000014u, 0x00000000u, 0x00050051u, 0x00000006u, 0x0000001fu, 0x00000014u,
    0x00000001u, 0x00070050u, 0x00000007u, 0x00000020u, 0x0000001eu, 0x0000001fu, 0x0000001cu, 0x0000001du,
    0x00050041u, 0x00000021u, 0x00000022u, 0x0000000du, 0x0000000fu, 0x0003003eu, 0x00000022u, 0x00000020u,
    0x00050041u, 0x00000017u, 0x00000026u, 0x00000012u, 0x00000025u, 0x0004003du, 0x00000006u, 0x00000027u,
    0x00000026u, 0x00050085u, 0x00000006u, 0x00000028u, 0x00000027u, 0x0000001au, 0x00050081u, 0x00000006u,
    0x00000029u, 0x00000028u, 0x0000001au, 0x0003003eu, 0x00000024u, 0x00000029u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kDirectVulkanVertexSpirVByteSize = sizeof(kDirectVulkanVertexSpirV);

inline constexpr std::string_view kDirectVulkanVertexWgsl =
    R"CNA_SHADER(// direct.vulkan.vert.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct gl_PerVertex {
    @builtin(position) gl_Position: vec4<f32>,
    gl_PointSize: f32,
    gl_ClipDistance: array<f32, 1>,
    gl_CullDistance: array<f32, 1>,
}

struct VertexOutput {
    @builtin(position) gl_Position: vec4<f32>,
    @location(0) member: f32,
}

var<private> unnamed: gl_PerVertex = gl_PerVertex(vec4<f32>(0f, 0f, 0f, 1f), 1f, array<f32, 1>(), array<f32, 1>());
var<private> aPos_1: vec3<f32>;
var<private> PositionX: f32;

fn main_1() {
    let _e9 = aPos_1;
    let _e10 = _e9.xy;
    let _e12 = aPos_1[2u];
    unnamed.gl_Position = vec4<f32>(_e10.x, _e10.y, ((_e12 * 0.5f) + 0.5f), 1f);
    let _e20 = aPos_1[0u];
    PositionX = ((_e20 * 0.5f) + 0.5f);
    return;
}

@vertex 
fn main(@location(0) aPos: vec3<f32>) -> VertexOutput {
    aPos_1 = aPos;
    main_1();
    let _e6 = unnamed.gl_Position.y;
    unnamed.gl_Position.y = -(_e6);
    let _e8 = unnamed.gl_Position;
    let _e9 = PositionX;
    return VertexOutput(_e8, _e9);
}
)CNA_SHADER";

inline constexpr std::uint32_t kEmitterVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000043u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0007000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000002bu, 0x0000003cu, 0x00030010u,
    0x00000004u, 0x00000007u, 0x00030047u, 0x0000000cu, 0x00000002u, 0x00050048u, 0x0000000cu, 0x00000000u,
    0x00000023u, 0x00000000u, 0x00040048u, 0x0000000cu, 0x00000001u, 0x00000005u, 0x00050048u, 0x0000000cu,
    0x00000001u, 0x00000007u, 0x00000010u, 0x00050048u, 0x0000000cu, 0x00000001u, 0x00000023u, 0x00000010u,
    0x00050048u, 0x0000000cu, 0x00000002u, 0x00000023u, 0x00000050u, 0x00050048u, 0x0000000cu, 0x00000003u,
    0x00000023u, 0x00000060u, 0x00040047u, 0x0000002bu, 0x0000001eu, 0x00000000u, 0x00040047u, 0x0000003cu,
    0x0000001eu, 0x00000001u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u,
    0x00000006u, 0x00000020u, 0x00040017u, 0x00000009u, 0x00000006u, 0x00000002u, 0x00040017u, 0x0000000au,
    0x00000006u, 0x00000004u, 0x00040018u, 0x0000000bu, 0x0000000au, 0x00000004u, 0x0006001eu, 0x0000000cu,
    0x00000009u, 0x0000000bu, 0x0000000au, 0x00000006u, 0x00040020u, 0x0000000du, 0x00000009u, 0x0000000cu,
    0x0004003bu, 0x0000000du, 0x0000000eu, 0x00000009u, 0x00040015u, 0x0000000fu, 0x00000020u, 0x00000001u,
    0x0004002bu, 0x0000000fu, 0x00000010u, 0x00000002u, 0x00040015u, 0x00000011u, 0x00000020u, 0x00000000u,
    0x0004002bu, 0x00000011u, 0x00000012u, 0x00000003u, 0x00040020u, 0x00000013u, 0x00000009u, 0x00000006u,
    0x0004002bu, 0x0000000fu, 0x00000017u, 0x00000003u, 0x0004002bu, 0x00000006u, 0x0000001au, 0x00000000u,
    0x0004002bu, 0x00000006u, 0x0000001bu, 0x3f800000u, 0x0004002bu, 0x00000006u, 0x0000001fu, 0x3cf5c28fu,
    0x0004002bu, 0x00000006u, 0x00000020u, 0x3727c5acu, 0x0004002bu, 0x00000006u, 0x00000022u, 0x40800000u,
    0x0004002bu, 0x00000006u, 0x00000026u, 0x3c23d70au, 0x0004002bu, 0x00000006u, 0x00000027u, 0x453b8000u,
    0x00040020u, 0x0000002au, 0x00000003u, 0x0000000au, 0x0004003bu, 0x0000002au, 0x0000002bu, 0x00000003u,
    0x00040017u, 0x0000002cu, 0x00000006u, 0x00000003u, 0x00040020u, 0x0000002du, 0x00000009u, 0x0000000au,
    0x0004003bu, 0x0000002au, 0x0000003cu, 0x00000003u, 0x0004002bu, 0x00000006u, 0x0000003fu, 0x38d1b717u,
    0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x00060041u,
    0x00000013u, 0x00000014u, 0x0000000eu, 0x00000010u, 0x00000012u, 0x0004003du, 0x00000006u, 0x00000015u,
    0x00000014u, 0x00050041u, 0x00000013u, 0x00000018u, 0x0000000eu, 0x00000017u, 0x0004003du, 0x00000006u,
    0x00000019u, 0x00000018u, 0x0008000cu, 0x00000006u, 0x0000001cu, 0x00000001u, 0x0000002bu, 0x00000019u,
    0x0000001au, 0x0000001bu, 0x0007000cu, 0x00000006u, 0x00000023u, 0x00000001u, 0x0000001au, 0x0000001cu,
    0x00000022u, 0x00050081u, 0x00000006u, 0x00000024u, 0x00000020u, 0x00000023u, 0x00050088u, 0x00000006u,
    0x00000025u, 0x0000001fu, 0x00000024u, 0x0008000cu, 0x00000006u, 0x00000028u, 0x00000001u, 0x0000002bu,
    0x00000025u, 0x00000026u, 0x00000027u, 0x00050085u, 0x00000006u, 0x00000029u, 0x00000015u, 0x00000028u,
    0x00050041u, 0x0000002du, 0x0000002eu, 0x0000000eu, 0x00000010u, 0x0004003du, 0x0000000au, 0x0000002fu,
    0x0000002eu, 0x0008004fu, 0x0000002cu, 0x00000030u, 0x0000002fu, 0x0000002fu, 0x00000000u, 0x00000001u,
    0x00000002u, 0x0005008eu, 0x0000002cu, 0x00000032u, 0x00000030u, 0x00000015u, 0x0005008eu, 0x0000002cu,
    0x00000034u, 0x00000032u, 0x00000029u, 0x00050085u, 0x00000006u, 0x00000037u, 0x00000015u, 0x00000029u,
    0x00050051u, 0x00000006u, 0x00000038u, 0x00000034u, 0x00000000u, 0x00050051u, 0x00000006u, 0x00000039u,
    0x00000034u, 0x00000001u, 0x00050051u, 0x00000006u, 0x0000003au, 0x00000034u, 0x00000002u, 0x00070050u,
    0x0000000au, 0x0000003bu, 0x00000038u, 0x00000039u, 0x0000003au, 0x00000037u, 0x0003003eu, 0x0000002bu,
    0x0000003bu, 0x00050083u, 0x00000006u, 0x0000003eu, 0x0000001bu, 0x00000015u, 0x0007000cu, 0x00000006u,
    0x00000040u, 0x00000001u, 0x00000028u, 0x0000003eu, 0x0000003fu, 0x0006000cu, 0x00000006u, 0x00000041u,
    0x00000001u, 0x0000001cu, 0x00000040u, 0x00070050u, 0x0000000au, 0x00000042u, 0x00000041u, 0x0000001au,
    0x0000001au, 0x0000001au, 0x0003003eu, 0x0000003cu, 0x00000042u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kEmitterVulkanFragmentSpirVByteSize = sizeof(kEmitterVulkanFragmentSpirV);

inline constexpr std::string_view kEmitterVulkanFragmentWgsl =
    R"CNA_SHADER(// emitter.vulkan.frag.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct PushConstants {
    viewportSize: vec2<f32>,
    uMatrix: mat4x4<f32>,
    uEffectParams: vec4<f32>,
    uScalar: f32,
}

struct FragmentOutput {
    @location(0) member: vec4<f32>,
    @location(1) member_1: vec4<f32>,
}

@group(3) @binding(0) 
var<uniform> pc: PushConstants;
var<private> cnaOitAccumulation: vec4<f32>;
var<private> cnaOitRevealage: vec4<f32>;

fn main_1() {
    var alpha: f32;
    var z: f32;
    var weight: f32;

    let _e19 = pc.uEffectParams[3u];
    alpha = _e19;
    let _e21 = pc.uScalar;
    z = clamp(_e21, 0f, 1f);
    let _e23 = alpha;
    let _e24 = z;
    weight = (_e23 * clamp((0.03f / (0.00001f + pow(_e24, 4f))), 0.01f, 3000f));
    let _e31 = pc.uEffectParams;
    let _e33 = alpha;
    let _e35 = weight;
    let _e36 = ((_e31.xyz * _e33) * _e35);
    let _e37 = alpha;
    let _e38 = weight;
    cnaOitAccumulation = vec4<f32>(_e36.x, _e36.y, _e36.z, (_e37 * _e38));
    let _e44 = alpha;
    cnaOitRevealage = vec4<f32>(log(max((1f - _e44), 0.0001f)), 0f, 0f, 0f);
    return;
}

@fragment 
fn main() -> FragmentOutput {
    main_1();
    let _e2 = cnaOitAccumulation;
    let _e3 = cnaOitRevealage;
    return FragmentOutput(_e2, _e3);
}
)CNA_SHADER";

inline constexpr std::uint32_t kFlatVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000014u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00000009u, 0x00030010u, 0x00000004u,
    0x00000007u, 0x00040047u, 0x00000009u, 0x0000001eu, 0x00000000u, 0x00030047u, 0x0000000cu, 0x00000002u,
    0x00050048u, 0x0000000cu, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040048u, 0x0000000cu, 0x00000001u,
    0x00000005u, 0x00050048u, 0x0000000cu, 0x00000001u, 0x00000007u, 0x00000010u, 0x00050048u, 0x0000000cu,
    0x00000001u, 0x00000023u, 0x00000010u, 0x00050048u, 0x0000000cu, 0x00000002u, 0x00000023u, 0x00000050u,
    0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u,
    0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u, 0x00040020u, 0x00000008u, 0x00000003u, 0x00000007u,
    0x0004003bu, 0x00000008u, 0x00000009u, 0x00000003u, 0x00040017u, 0x0000000au, 0x00000006u, 0x00000002u,
    0x00040018u, 0x0000000bu, 0x00000007u, 0x00000004u, 0x0005001eu, 0x0000000cu, 0x0000000au, 0x0000000bu,
    0x00000007u, 0x00040020u, 0x0000000du, 0x00000009u, 0x0000000cu, 0x0004003bu, 0x0000000du, 0x0000000eu,
    0x00000009u, 0x00040015u, 0x0000000fu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000fu, 0x00000010u,
    0x00000002u, 0x00040020u, 0x00000011u, 0x00000009u, 0x00000007u, 0x00050036u, 0x00000002u, 0x00000004u,
    0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x00050041u, 0x00000011u, 0x00000012u, 0x0000000eu,
    0x00000010u, 0x0004003du, 0x00000007u, 0x00000013u, 0x00000012u, 0x0003003eu, 0x00000009u, 0x00000013u,
    0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kFlatVulkanFragmentSpirVByteSize = sizeof(kFlatVulkanFragmentSpirV);

inline constexpr std::string_view kFlatVulkanFragmentWgsl =
    R"CNA_SHADER(// flat.vulkan.frag.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct PushConstants {
    viewportSize: vec2<f32>,
    uMatrix: mat4x4<f32>,
    uEffectParams: vec4<f32>,
}

var<private> FragColor: vec4<f32>;
@group(3) @binding(0) 
var<uniform> pc: PushConstants;

fn main_1() {
    let _e4 = pc.uEffectParams;
    FragColor = _e4;
    return;
}

@fragment 
fn main() -> @location(0) vec4<f32> {
    main_1();
    let _e1 = FragColor;
    return _e1;
}
)CNA_SHADER";

inline constexpr std::uint32_t kWeightProbeVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000047u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0007000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000001au, 0x00000041u, 0x00030010u,
    0x00000004u, 0x00000007u, 0x00030047u, 0x0000000cu, 0x00000002u, 0x00050048u, 0x0000000cu, 0x00000000u,
    0x00000023u, 0x00000000u, 0x00040048u, 0x0000000cu, 0x00000001u, 0x00000005u, 0x00050048u, 0x0000000cu,
    0x00000001u, 0x00000007u, 0x00000010u, 0x00050048u, 0x0000000cu, 0x00000001u, 0x00000023u, 0x00000010u,
    0x00050048u, 0x0000000cu, 0x00000002u, 0x00000023u, 0x00000050u, 0x00040047u, 0x0000001au, 0x0000001eu,
    0x00000000u, 0x00040047u, 0x00000041u, 0x0000001eu, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u,
    0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000009u, 0x00000006u,
    0x00000002u, 0x00040017u, 0x0000000au, 0x00000006u, 0x00000004u, 0x00040018u, 0x0000000bu, 0x0000000au,
    0x00000004u, 0x0005001eu, 0x0000000cu, 0x00000009u, 0x0000000bu, 0x0000000au, 0x00040020u, 0x0000000du,
    0x00000009u, 0x0000000cu, 0x0004003bu, 0x0000000du, 0x0000000eu, 0x00000009u, 0x00040015u, 0x0000000fu,
    0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000fu, 0x00000010u, 0x00000002u, 0x00040015u, 0x00000011u,
    0x00000020u, 0x00000000u, 0x0004002bu, 0x00000011u, 0x00000012u, 0x00000001u, 0x00040020u, 0x00000013u,
    0x00000009u, 0x00000006u, 0x0004002bu, 0x00000011u, 0x00000016u, 0x00000002u, 0x00040020u, 0x00000019u,
    0x00000001u, 0x00000006u, 0x0004003bu, 0x00000019u, 0x0000001au, 0x00000001u, 0x0004002bu, 0x00000011u,
    0x0000001fu, 0x00000003u, 0x0004002bu, 0x00000006u, 0x00000022u, 0x38d1b717u, 0x0004002bu, 0x00000006u,
    0x00000025u, 0x00000000u, 0x0004002bu, 0x00000006u, 0x00000026u, 0x3f800000u, 0x0004002bu, 0x00000011u,
    0x00000029u, 0x00000000u, 0x0004002bu, 0x00000006u, 0x0000002cu, 0x3cf5c28fu, 0x0004002bu, 0x00000006u,
    0x0000002du, 0x3727c5acu, 0x0004002bu, 0x00000006u, 0x0000002fu, 0x40800000u, 0x0004002bu, 0x00000006u,
    0x00000033u, 0x3c23d70au, 0x0004002bu, 0x00000006u, 0x00000034u, 0x453b8000u, 0x0004002bu, 0x00000006u,
    0x0000003cu, 0x40000000u, 0x00040020u, 0x00000040u, 0x00000003u, 0x0000000au, 0x0004003bu, 0x00000040u,
    0x00000041u, 0x00000003u, 0x0004002bu, 0x00000006u, 0x00000045u, 0x3ede5bdau, 0x0004002bu, 0x00000006u,
    0x00000046u, 0x3e3a2e8cu, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u,
    0x00000005u, 0x00060041u, 0x00000013u, 0x00000014u, 0x0000000eu, 0x00000010u, 0x00000012u, 0x0004003du,
    0x00000006u, 0x00000015u, 0x00000014u, 0x00060041u, 0x00000013u, 0x00000017u, 0x0000000eu, 0x00000010u,
    0x00000016u, 0x0004003du, 0x00000006u, 0x00000018u, 0x00000017u, 0x0004003du, 0x00000006u, 0x0000001bu,
    0x0000001au, 0x0008000cu, 0x00000006u, 0x0000001cu, 0x00000001u, 0x0000002eu, 0x00000015u, 0x00000018u,
    0x0000001bu, 0x00060041u, 0x00000013u, 0x00000020u, 0x0000000eu, 0x00000010u, 0x0000001fu, 0x0004003du,
    0x00000006u, 0x00000021u, 0x00000020u, 0x0007000cu, 0x00000006u, 0x00000023u, 0x00000001u, 0x00000028u,
    0x00000021u, 0x00000022u, 0x00050088u, 0x00000006u, 0x00000024u, 0x0000001cu, 0x00000023u, 0x0008000cu,
    0x00000006u, 0x00000027u, 0x00000001u, 0x0000002bu, 0x00000024u, 0x00000025u, 0x00000026u, 0x00060041u,
    0x00000013u, 0x0000002au, 0x0000000eu, 0x00000010u, 0x00000029u, 0x0004003du, 0x00000006u, 0x0000002bu,
    0x0000002au, 0x0007000cu, 0x00000006u, 0x00000030u, 0x00000001u, 0x0000001au, 0x00000027u, 0x0000002fu,
    0x00050081u, 0x00000006u, 0x00000031u, 0x0000002du, 0x00000030u, 0x00050088u, 0x00000006u, 0x00000032u,
    0x0000002cu, 0x00000031u, 0x0008000cu, 0x00000006u, 0x00000035u, 0x00000001u, 0x0000002bu, 0x00000032u,
    0x00000033u, 0x00000034u, 0x00050085u, 0x00000006u, 0x00000036u, 0x0000002bu, 0x00000035u, 0x0006000cu,
    0x00000006u, 0x00000039u, 0x00000001u, 0x0000001cu, 0x00000036u, 0x00050085u, 0x00000006u, 0x0000003bu,
    0x00000039u, 0x00000045u, 0x00050081u, 0x00000006u, 0x0000003du, 0x0000003bu, 0x0000003cu, 0x00050085u,
    0x00000006u, 0x0000003fu, 0x0000003du, 0x00000046u, 0x0008000cu, 0x00000006u, 0x00000043u, 0x00000001u,
    0x0000002bu, 0x0000003fu, 0x00000025u, 0x00000026u, 0x00070050u, 0x0000000au, 0x00000044u, 0x00000043u,
    0x00000025u, 0x00000025u, 0x00000026u, 0x0003003eu, 0x00000041u, 0x00000044u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kWeightProbeVulkanFragmentSpirVByteSize = sizeof(kWeightProbeVulkanFragmentSpirV);

inline constexpr std::string_view kWeightProbeVulkanFragmentWgsl =
    R"CNA_SHADER(// weight_probe.vulkan.frag.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct PushConstants {
    viewportSize: vec2<f32>,
    uMatrix: mat4x4<f32>,
    uEffectParams: vec4<f32>,
}

@group(3) @binding(0) 
var<uniform> pc: PushConstants;
var<private> PositionX_1: f32;
var<private> FragColor: vec4<f32>;

fn main_1() {
    var depth: f32;
    var z: f32;
    var weight: f32;
    var encoded: f32;

    let _e25 = pc.uEffectParams[1u];
    let _e28 = pc.uEffectParams[2u];
    let _e29 = PositionX_1;
    depth = mix(_e25, _e28, _e29);
    let _e31 = depth;
    let _e34 = pc.uEffectParams[3u];
    z = clamp((_e31 / max(_e34, 0.0001f)), 0f, 1f);
    let _e40 = pc.uEffectParams[0u];
    let _e41 = z;
    weight = (_e40 * clamp((0.03f / (0.00001f + pow(_e41, 4f))), 0.01f, 3000f));
    let _e47 = weight;
    encoded = (((log(_e47) / 2.302585f) + 2f) / 5.5f);
    let _e52 = encoded;
    FragColor = vec4<f32>(clamp(_e52, 0f, 1f), 0f, 0f, 1f);
    return;
}

@fragment 
fn main(@location(0) PositionX: f32) -> @location(0) vec4<f32> {
    PositionX_1 = PositionX;
    main_1();
    let _e3 = FragColor;
    return _e3;
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 20> kPayloads = {{
    {"kBasicEsVertexSource", "basic.es.vert.glsl", "274ad658c2f3bc56f3586c802ae30779f9df41363afe823405f05586e2fc5d01", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kDirectEsVertexSource", "direct.es.vert.glsl", "122acc5d62965af6018af7ae1178348da89c8602815ec516e02f0293d0a0d23f", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kEmitterEsFragmentSource", "emitter.es.frag.glsl", "7d70cebf103026f9e4930dd87f8b44e0f86662a4e38cde1250f72d4ffc407b90", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kFlatEsFragmentSource", "flat.es.frag.glsl", "99f51e2c2de33d44fa8fd85d1f13d91f95a2f32cc0a8de1a0e1646435e4f4932", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kWeightProbeEsFragmentSource", "weight_probe.es.frag.glsl", "06b3724c4b7abf548243bd626b7d884dedfaf36cd744b5dd31a38f22196d891a", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kBasicDesktopVertexSource", "basic.desktop.vert.glsl", "0008eb043c9fca12d1548c104aec22fead0f0d73f90054885d9dcb54ddcbceb4", "glsl", "glsl", "vertex", "text", "main"},
    {"kDirectDesktopVertexSource", "direct.desktop.vert.glsl", "9b98684e378f48ee67aa6b53b998acae3931db9904916b535a313eee88f979a4", "glsl", "glsl", "vertex", "text", "main"},
    {"kEmitterDesktopFragmentSource", "emitter.desktop.frag.glsl", "844617ac9f802f28c8137cf8cdf495efd84e1f8c6053640930578982c10b4a6c", "glsl", "glsl", "fragment", "text", "main"},
    {"kFlatDesktopFragmentSource", "flat.desktop.frag.glsl", "f0e3c81eda3d000bcf5d63230a1e4de5530eca958d59360d9e5f0136608d7efa", "glsl", "glsl", "fragment", "text", "main"},
    {"kWeightProbeDesktopFragmentSource", "weight_probe.desktop.frag.glsl", "26f21c36cc8d7b80138c3ed802d670f3c460a10e03bdfd7cbf855b5d3f2725ca", "glsl", "glsl", "fragment", "text", "main"},
    {"kBasicVulkanVertexSpirV", "basic.vulkan.vert.glsl", "776d5215c78990640065ef09013a993b20e4805f3071a57e68dcf67d0120d679", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kBasicVulkanVertexWgsl", "basic.vulkan.vert.glsl", "776d5215c78990640065ef09013a993b20e4805f3071a57e68dcf67d0120d679", "wgsl", "vulkan-glsl", "vertex", "wgsl", "main"},
    {"kDirectVulkanVertexSpirV", "direct.vulkan.vert.glsl", "f35a78121f7801b43e35571b17fba11d7cfe8f82eb3fb3c139c92cc12a45001a", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kDirectVulkanVertexWgsl", "direct.vulkan.vert.glsl", "f35a78121f7801b43e35571b17fba11d7cfe8f82eb3fb3c139c92cc12a45001a", "wgsl", "vulkan-glsl", "vertex", "wgsl", "main"},
    {"kEmitterVulkanFragmentSpirV", "emitter.vulkan.frag.glsl", "4f3a2984288cee6af3da9185499d9fd934830d6f0fdb81e2c24430ee818ab003", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
    {"kEmitterVulkanFragmentWgsl", "emitter.vulkan.frag.glsl", "4f3a2984288cee6af3da9185499d9fd934830d6f0fdb81e2c24430ee818ab003", "wgsl", "vulkan-glsl", "fragment", "wgsl", "main"},
    {"kFlatVulkanFragmentSpirV", "flat.vulkan.frag.glsl", "331c06008eeb349df23c17e43bad242bf7142a88d2c01f7c515afd4884b387e4", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
    {"kFlatVulkanFragmentWgsl", "flat.vulkan.frag.glsl", "331c06008eeb349df23c17e43bad242bf7142a88d2c01f7c515afd4884b387e4", "wgsl", "vulkan-glsl", "fragment", "wgsl", "main"},
    {"kWeightProbeVulkanFragmentSpirV", "weight_probe.vulkan.frag.glsl", "5e20a04820826693398482a6c714f7a7d4c2d223c35eac0fbe51d932aa5355b8", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
    {"kWeightProbeVulkanFragmentWgsl", "weight_probe.vulkan.frag.glsl", "5e20a04820826693398482a6c714f7a7d4c2d223c35eac0fbe51d932aa5355b8", "wgsl", "vulkan-glsl", "fragment", "wgsl", "main"},
}};

} // namespace CNA::Tests::TransparencyGenerated

#endif // CNA_CNAEXT
