// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Graphics::detail::PostProcessGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "post_process";
inline constexpr std::string_view kManifestSha256 = "fc686a5ef4c4b8501179db8eec26ccf91d187c793c01d30cf8821d62da4ad5c6";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";

inline constexpr std::string_view kFullscreenEsVertexSource =
    R"CNA_SHADER(#version 300 es
precision highp float;
layout(location = 0) in vec2 aPos;
layout(location = 1) in vec2 aTexCoord;
layout(location = 2) in vec4 aColor;
out vec2 TexCoord;
out vec4 SpriteColor;
uniform mat4 projection;
void main()
{
    gl_Position = projection * vec4(aPos, 0.0, 1.0);
    TexCoord = aTexCoord;
    SpriteColor = aColor;
}
)CNA_SHADER";

inline constexpr std::string_view kChromaticEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;
in vec2 TexCoord;
in vec4 SpriteColor;
out vec4 FragColor;
uniform sampler2D texture1;
uniform float uStrength;

void main()
{
    vec2 fromCentre = TexCoord - vec2(0.5);
    vec2 redUv = vec2(0.5) + fromCentre * (1.0 + uStrength);
    vec2 blueUv = vec2(0.5) + fromCentre * (1.0 - uStrength);
    FragColor = vec4(texture(texture1, redUv).r,
                     texture(texture1, TexCoord).g,
                     texture(texture1, blueUv).b,
                     texture(texture1, TexCoord).a) * SpriteColor;
}
)CNA_SHADER";

inline constexpr std::string_view kFullscreenDesktopVertexSource =
    R"CNA_SHADER(#version 330 core
layout(location = 0) in vec2 aPos;
layout(location = 1) in vec2 aTexCoord;
layout(location = 2) in vec4 aColor;
out vec2 TexCoord;
out vec4 SpriteColor;
uniform mat4 projection;
void main()
{
    gl_Position = projection * vec4(aPos, 0.0, 1.0);
    TexCoord = aTexCoord;
    SpriteColor = aColor;
}
)CNA_SHADER";

inline constexpr std::string_view kChromaticDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core
in vec2 TexCoord;
in vec4 SpriteColor;
out vec4 FragColor;
uniform sampler2D texture1;
uniform float uStrength;

void main()
{
    vec2 fromCentre = TexCoord - vec2(0.5);
    vec2 redUv = vec2(0.5) + fromCentre * (1.0 + uStrength);
    vec2 blueUv = vec2(0.5) + fromCentre * (1.0 - uStrength);
    FragColor = vec4(texture(texture1, redUv).r,
                     texture(texture1, TexCoord).g,
                     texture(texture1, blueUv).b,
                     texture(texture1, TexCoord).a) * SpriteColor;
}
)CNA_SHADER";

inline constexpr std::uint32_t kFullscreenVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000036u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x000b000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00000022u, 0x0000002fu,
    0x00000030u, 0x00000032u, 0x00000034u, 0x00040047u, 0x0000000bu, 0x0000001eu, 0x00000000u, 0x00030047u,
    0x0000000fu, 0x00000002u, 0x00050048u, 0x0000000fu, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040048u,
    0x0000000fu, 0x00000001u, 0x00000005u, 0x00050048u, 0x0000000fu, 0x00000001u, 0x00000007u, 0x00000010u,
    0x00050048u, 0x0000000fu, 0x00000001u, 0x00000023u, 0x00000010u, 0x00050048u, 0x0000000fu, 0x00000002u,
    0x00000023u, 0x00000050u, 0x00050048u, 0x0000000fu, 0x00000003u, 0x00000023u, 0x00000060u, 0x00030047u,
    0x00000020u, 0x00000002u, 0x00050048u, 0x00000020u, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u,
    0x00000020u, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x00000020u, 0x00000002u, 0x0000000bu,
    0x00000003u, 0x00050048u, 0x00000020u, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00040047u, 0x0000002fu,
    0x0000001eu, 0x00000000u, 0x00040047u, 0x00000030u, 0x0000001eu, 0x00000001u, 0x00040047u, 0x00000032u,
    0x0000001eu, 0x00000001u, 0x00040047u, 0x00000034u, 0x0000001eu, 0x00000002u, 0x00020013u, 0x00000002u,
    0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u,
    0x00000006u, 0x00000002u, 0x00040020u, 0x0000000au, 0x00000001u, 0x00000007u, 0x0004003bu, 0x0000000au,
    0x0000000bu, 0x00000001u, 0x00040017u, 0x0000000du, 0x00000006u, 0x00000004u, 0x00040018u, 0x0000000eu,
    0x0000000du, 0x00000004u, 0x0006001eu, 0x0000000fu, 0x00000007u, 0x0000000eu, 0x0000000du, 0x00000006u,
    0x00040020u, 0x00000010u, 0x00000009u, 0x0000000fu, 0x0004003bu, 0x00000010u, 0x00000011u, 0x00000009u,
    0x00040015u, 0x00000012u, 0x00000020u, 0x00000001u, 0x0004002bu, 0x00000012u, 0x00000013u, 0x00000000u,
    0x00040020u, 0x00000014u, 0x00000009u, 0x00000007u, 0x0004002bu, 0x00000006u, 0x00000018u, 0x40000000u,
    0x0004002bu, 0x00000006u, 0x0000001au, 0x3f800000u, 0x0005002cu, 0x00000007u, 0x0000001bu, 0x0000001au,
    0x0000001au, 0x00040015u, 0x0000001du, 0x00000020u, 0x00000000u, 0x0004002bu, 0x0000001du, 0x0000001eu,
    0x00000001u, 0x0004001cu, 0x0000001fu, 0x00000006u, 0x0000001eu, 0x0006001eu, 0x00000020u, 0x0000000du,
    0x00000006u, 0x0000001fu, 0x0000001fu, 0x00040020u, 0x00000021u, 0x00000003u, 0x00000020u, 0x0004003bu,
    0x00000021u, 0x00000022u, 0x00000003u, 0x0004002bu, 0x00000006u, 0x0000002au, 0x00000000u, 0x00040020u,
    0x0000002cu, 0x00000003u, 0x0000000du, 0x00040020u, 0x0000002eu, 0x00000003u, 0x00000007u, 0x0004003bu,
    0x0000002eu, 0x0000002fu, 0x00000003u, 0x0004003bu, 0x0000000au, 0x00000030u, 0x00000001u, 0x0004003bu,
    0x0000002cu, 0x00000032u, 0x00000003u, 0x00040020u, 0x00000033u, 0x00000001u, 0x0000000du, 0x0004003bu,
    0x00000033u, 0x00000034u, 0x00000001u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u,
    0x000200f8u, 0x00000005u, 0x0004003du, 0x00000007u, 0x0000000cu, 0x0000000bu, 0x00050041u, 0x00000014u,
    0x00000015u, 0x00000011u, 0x00000013u, 0x0004003du, 0x00000007u, 0x00000016u, 0x00000015u, 0x00050088u,
    0x00000007u, 0x00000017u, 0x0000000cu, 0x00000016u, 0x0005008eu, 0x00000007u, 0x00000019u, 0x00000017u,
    0x00000018u, 0x00050083u, 0x00000007u, 0x0000001cu, 0x00000019u, 0x0000001bu, 0x00050051u, 0x00000006u,
    0x00000026u, 0x0000001cu, 0x00000000u, 0x00050051u, 0x00000006u, 0x00000028u, 0x0000001cu, 0x00000001u,
    0x0004007fu, 0x00000006u, 0x00000029u, 0x00000028u, 0x00070050u, 0x0000000du, 0x0000002bu, 0x00000026u,
    0x00000029u, 0x0000002au, 0x0000001au, 0x00050041u, 0x0000002cu, 0x0000002du, 0x00000022u, 0x00000013u,
    0x0003003eu, 0x0000002du, 0x0000002bu, 0x0004003du, 0x00000007u, 0x00000031u, 0x00000030u, 0x0003003eu,
    0x0000002fu, 0x00000031u, 0x0004003du, 0x0000000du, 0x00000035u, 0x00000034u, 0x0003003eu, 0x00000032u,
    0x00000035u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kFullscreenVulkanVertexSpirVByteSize = sizeof(kFullscreenVulkanVertexSpirV);

inline constexpr std::uint32_t kChromaticVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000047u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0008000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00000028u, 0x00000044u,
    0x00030010u, 0x00000004u, 0x00000007u, 0x00040047u, 0x0000000bu, 0x0000001eu, 0x00000000u, 0x00030047u,
    0x00000015u, 0x00000002u, 0x00050048u, 0x00000015u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040048u,
    0x00000015u, 0x00000001u, 0x00000005u, 0x00050048u, 0x00000015u, 0x00000001u, 0x00000007u, 0x00000010u,
    0x00050048u, 0x00000015u, 0x00000001u, 0x00000023u, 0x00000010u, 0x00050048u, 0x00000015u, 0x00000002u,
    0x00000023u, 0x00000050u, 0x00050048u, 0x00000015u, 0x00000003u, 0x00000023u, 0x00000060u, 0x00040047u,
    0x00000028u, 0x0000001eu, 0x00000000u, 0x00040047u, 0x0000002cu, 0x00000021u, 0x00000000u, 0x00040047u,
    0x0000002cu, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000044u, 0x0000001eu, 0x00000001u, 0x00020013u,
    0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u,
    0x00000007u, 0x00000006u, 0x00000002u, 0x00040020u, 0x0000000au, 0x00000001u, 0x00000007u, 0x0004003bu,
    0x0000000au, 0x0000000bu, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000000du, 0x3f000000u, 0x0005002cu,
    0x00000007u, 0x0000000eu, 0x0000000du, 0x0000000du, 0x0004002bu, 0x00000006u, 0x00000012u, 0x3f800000u,
    0x00040017u, 0x00000013u, 0x00000006u, 0x00000004u, 0x00040018u, 0x00000014u, 0x00000013u, 0x00000004u,
    0x0006001eu, 0x00000015u, 0x00000007u, 0x00000014u, 0x00000013u, 0x00000006u, 0x00040020u, 0x00000016u,
    0x00000009u, 0x00000015u, 0x0004003bu, 0x00000016u, 0x00000017u, 0x00000009u, 0x00040015u, 0x00000018u,
    0x00000020u, 0x00000001u, 0x0004002bu, 0x00000018u, 0x00000019u, 0x00000003u, 0x00040020u, 0x0000001au,
    0x00000009u, 0x00000006u, 0x00040020u, 0x00000027u, 0x00000003u, 0x00000013u, 0x0004003bu, 0x00000027u,
    0x00000028u, 0x00000003u, 0x00090019u, 0x00000029u, 0x00000006u, 0x00000001u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000001u, 0x00000000u, 0x0003001bu, 0x0000002au, 0x00000029u, 0x00040020u, 0x0000002bu,
    0x00000000u, 0x0000002au, 0x0004003bu, 0x0000002bu, 0x0000002cu, 0x00000000u, 0x00040020u, 0x00000043u,
    0x00000001u, 0x00000013u, 0x0004003bu, 0x00000043u, 0x00000044u, 0x00000001u, 0x00050036u, 0x00000002u,
    0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du, 0x00000007u, 0x0000000cu,
    0x0000000bu, 0x00050083u, 0x00000007u, 0x0000000fu, 0x0000000cu, 0x0000000eu, 0x00050041u, 0x0000001au,
    0x0000001bu, 0x00000017u, 0x00000019u, 0x0004003du, 0x00000006u, 0x0000001cu, 0x0000001bu, 0x00050081u,
    0x00000006u, 0x0000001du, 0x00000012u, 0x0000001cu, 0x0005008eu, 0x00000007u, 0x0000001eu, 0x0000000fu,
    0x0000001du, 0x00050081u, 0x00000007u, 0x0000001fu, 0x0000000eu, 0x0000001eu, 0x00050083u, 0x00000006u,
    0x00000024u, 0x00000012u, 0x0000001cu, 0x0005008eu, 0x00000007u, 0x00000025u, 0x0000000fu, 0x00000024u,
    0x00050081u, 0x00000007u, 0x00000026u, 0x0000000eu, 0x00000025u, 0x0004003du, 0x0000002au, 0x0000002du,
    0x0000002cu, 0x00050057u, 0x00000013u, 0x0000002fu, 0x0000002du, 0x0000001fu, 0x00050051u, 0x00000006u,
    0x00000032u, 0x0000002fu, 0x00000000u, 0x00050057u, 0x00000013u, 0x00000035u, 0x0000002du, 0x0000000cu,
    0x00050051u, 0x00000006u, 0x00000037u, 0x00000035u, 0x00000001u, 0x00050057u, 0x00000013u, 0x0000003au,
    0x0000002du, 0x00000026u, 0x00050051u, 0x00000006u, 0x0000003cu, 0x0000003au, 0x00000002u, 0x00050051u,
    0x00000006u, 0x00000041u, 0x00000035u, 0x00000003u, 0x00070050u, 0x00000013u, 0x00000042u, 0x00000032u,
    0x00000037u, 0x0000003cu, 0x00000041u, 0x0004003du, 0x00000013u, 0x00000045u, 0x00000044u, 0x00050085u,
    0x00000013u, 0x00000046u, 0x00000042u, 0x00000045u, 0x0003003eu, 0x00000028u, 0x00000046u, 0x000100fdu,
    0x00010038u,
};
inline constexpr std::size_t kChromaticVulkanFragmentSpirVByteSize = sizeof(kChromaticVulkanFragmentSpirV);

inline constexpr std::array<PayloadProvenance, 6> kPayloads = {{
    {"kFullscreenEsVertexSource", "fullscreen.es.vert.glsl", "ec4dbe0b5e367feed5a59d1091c93da8004f83e95c0fa1697aa5c3ae13539ef7", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kChromaticEsFragmentSource", "chromatic.es.frag.glsl", "74123544eb9f93443685d52e2fa34832021fc752c238511594517a40a0c10c67", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kFullscreenDesktopVertexSource", "fullscreen.desktop.vert.glsl", "fb01bc5f383d2375067f9320830f51753bf5a6d84c9d63f078f4b4cce6d994bf", "glsl", "glsl", "vertex", "text", "main"},
    {"kChromaticDesktopFragmentSource", "chromatic.desktop.frag.glsl", "5d1b4561e0d0078712c9223a8fa6166412b6e6da808edccfadf644acdc14e3a4", "glsl", "glsl", "fragment", "text", "main"},
    {"kFullscreenVulkanVertexSpirV", "fullscreen.vulkan.vert.glsl", "3108d0f66ccd4674b03dcf1b63d63569984d4f4e586ea774244b1a6d5f5f909a", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kChromaticVulkanFragmentSpirV", "chromatic.vulkan.frag.glsl", "ba84740abf65410ffe208652abb9f7e2cf9c915f2c28c2e1a8bd7d18b2537f32", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
}};

} // namespace CNA::Graphics::detail::PostProcessGenerated

#endif // CNA_CNAEXT
