// SPDX-License-Identifier: MS-PL

// plans/plan_modern.md MOD-2201: one repeatable runtime inventory for the EasyGL, Vulkan and
// OpenGL4 modern-GPU baseline. The detailed report is generated by the public immutable profile;
// the legacy table is emitted separately because those append-only ordinals remain public too.

#include "Microsoft/Xna/Framework/Graphics/GraphicsAdapter.hpp"
#include "Microsoft/Xna/Framework/Graphics/GraphicsDevice.hpp"
#include "Microsoft/Xna/Framework/Graphics/GraphicsProfile.hpp"
#include "Microsoft/Xna/Framework/Graphics/PresentationParameters.hpp"

#include "CNA/GraphicsCapability.hpp"

#include <array>
#include <cstdio>
#include <exception>
#include <memory>

using Microsoft::Xna::Framework::Graphics::GraphicsAdapter;
using Microsoft::Xna::Framework::Graphics::GraphicsDevice;
using Microsoft::Xna::Framework::Graphics::GraphicsProfile;
using Microsoft::Xna::Framework::Graphics::PresentationParameters;

namespace
{
    struct LegacyCapability
    {
        CNA::GraphicsCapability value;
        const char* name;
    };

    constexpr std::array<LegacyCapability, 19> kLegacyCapabilities{{
        {CNA::GraphicsCapability::ThreeD, "ThreeD"},
        {CNA::GraphicsCapability::DepthStencilBuffer, "DepthStencilBuffer"},
        {CNA::GraphicsCapability::MultiSampleAntiAliasing, "MultiSampleAntiAliasing"},
        {CNA::GraphicsCapability::MultipleRenderTargets, "MultipleRenderTargets"},
        {CNA::GraphicsCapability::AnisotropicFiltering, "AnisotropicFiltering"},
        {CNA::GraphicsCapability::WireFrame, "WireFrame"},
        {CNA::GraphicsCapability::OcclusionQuery, "OcclusionQuery"},
        {CNA::GraphicsCapability::CustomEffects, "CustomEffects"},
        {CNA::GraphicsCapability::Texture3D, "Texture3D"},
        {CNA::GraphicsCapability::MultiStreamVertexInput, "MultiStreamVertexInput"},
        {CNA::GraphicsCapability::Instancing, "Instancing"},
        {CNA::GraphicsCapability::StencilBuffer, "StencilBuffer"},
        {CNA::GraphicsCapability::AdditiveBlending, "AdditiveBlending"},
        {CNA::GraphicsCapability::CompiledEffects, "CompiledEffects"},
        {CNA::GraphicsCapability::FloatRenderTargets, "FloatRenderTargets"},
        {CNA::GraphicsCapability::HalfFloatRenderTargets, "HalfFloatRenderTargets"},
        {CNA::GraphicsCapability::HalfFloatTextureLinearFiltering,
         "HalfFloatTextureLinearFiltering"},
        {CNA::GraphicsCapability::ComputeShaders, "ComputeShaders"},
        {CNA::GraphicsCapability::IndirectDraw, "IndirectDraw"},
    }};

    static_assert(static_cast<int>(CNA::GraphicsCapability::ThreeD) == 0);
    static_assert(static_cast<int>(CNA::GraphicsCapability::IndirectDraw) == 18);
}

int main()
{
    try
    {
        PresentationParameters parameters;
        parameters.setBackBufferWidthProperty(64);
        parameters.setBackBufferHeightProperty(64);
        GraphicsDevice device(
            GraphicsAdapter::getDefaultAdapterProperty(), GraphicsProfile::HiDef, parameters);

        std::printf("renderer\t%.*s\n",
                    static_cast<int>(device.GetGraphicsRendererName().size()),
                    device.GetGraphicsRendererName().data());
        for (std::size_t ordinal = 0; ordinal < kLegacyCapabilities.size(); ++ordinal)
        {
            const auto& capability = kLegacyCapabilities[ordinal];
            if (static_cast<std::size_t>(capability.value) != ordinal)
            {
                std::fprintf(stderr, "non-contiguous GraphicsCapability ordinal at %zu\n", ordinal);
                return 1;
            }
            std::printf("legacy.%02zu.%s\t%s\n", ordinal, capability.name,
                        device.SupportsCapability(capability.value) ? "supported" : "unsupported");
        }

        const auto report = device.GetRendererCapabilityReportEXT();
        std::printf("--- detailed-profile ---\n%.*s\n--- end-profile ---\n",
                    static_cast<int>(report.size()), report.data());
        device.Dispose();
        return 0;
    }
    catch (const std::exception& error)
    {
        std::fprintf(stderr, "capability probe failed: %s\n", error.what());
        return 1;
    }
}
