#!/usr/bin/env python3
# SPDX-License-Identifier: MS-PL
"""Generates CNA's original avatar catalog v3 deterministically.

    python3 tools/avatar_builder/generate_avatar_catalog.py            # write the catalog
    python3 tools/avatar_builder/generate_avatar_catalog.py --check    # verify it byte for byte

Everything is procedural and original; nothing is downloaded or derived from third-party or
Xbox avatar content. Output: modules/gamer-services/assets/avatars/v3/. Catalogs v1 and v2 (the
directories next to it) are released and frozen and are never regenerated: v1 was written by this
tool's predecessor (Git history, commit 6ca06d069), v2 by this tool at commit d1730d4f3.
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from cna_avatar import catalog, face, facecontrols, rig, animations  # noqa: E402

DEFAULT_OUT = HERE.parent.parent / "modules" / "gamer-services" / "assets" / "avatars" / "v3"
CATALOG_VERSION = 3


def build():
    files = {}
    items, features = [], []
    for body_type in rig.BODY_TYPES:
        files["body.%s.glb" % body_type] = catalog.body_glb(body_type)
    for item_id, slot, name, female, male in catalog.ITEMS + catalog.FEATURE_ITEMS:
        entry = {"id": item_id, "slot": slot, "name": name, "random": {"female": female, "male": male},
                 "assets": {b: "%s.%s.glb" % (name, b) for b in rig.BODY_TYPES}}
        for body_type in rig.BODY_TYPES:
            files["%s.%s.glb" % (name, body_type)] = catalog.item_glb(body_type, item_id, slot, name)
            if slot == "hair":
                files["%s.hat.%s.glb" % (name, body_type)] = catalog.item_glb(body_type, item_id, slot, name, under_hat=True)
        if slot == "hair":
            entry["hatAssets"] = {b: "%s.hat.%s.glb" % (name, b) for b in rig.BODY_TYPES}
        if name in catalog.COVERING_HATS:
            entry["coversHair"] = True
        (features if slot == "facialHair" else items).append(entry)
    atlas, layout = face.atlas()
    files["face_features.png"] = atlas
    files["animations.glb"] = catalog.animations_glb()
    assets = [{"name": name, "sha256": hashlib.sha256(data).hexdigest(), "size": len(data)}
              for name, data in sorted(files.items())]
    manifest = {
        "format": 1, "catalogVersion": CATALOG_VERSION, "rig": "cna-avatar-71",
        "note": "Original CNA avatar assets generated by tools/avatar_builder/generate_avatar_catalog.py.",
        "bodies": {b: {"asset": "body.%s.glb" % b,
                       "authoredHeightMillimeters": int(round(rig.PROPORTIONS[b]["height"] * 1000))}
                   for b in rig.BODY_TYPES},
        "items": items,
        "featureItems": features,
        "faceControls": {b: facecontrols.controls(b) for b in rig.BODY_TYPES},
        "face": {"asset": "face_features.png", "layout": layout},
        "animations": {"asset": "animations.glb", "presets": animations.PRESETS},
        "assets": assets,
    }
    files["catalog.json"] = (json.dumps(manifest, indent=1, sort_keys=True) + "\n").encode("ascii")
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = build()
    if args.check:
        stale = [name for name, data in files.items()
                 if not (args.out / name).is_file() or (args.out / name).read_bytes() != data]
        extra = sorted(p.name for p in args.out.iterdir() if p.name not in files) if args.out.is_dir() else []
        if stale or extra:
            print("avatar catalog is stale: %s%s" % (", ".join(sorted(stale)), (" extra: " + ", ".join(extra)) if extra else ""))
            return 1
        print("avatar catalog v%d up to date (%d files, %d bytes)" % (CATALOG_VERSION, len(files),
                                                                      sum(len(d) for d in files.values())))
        return 0
    args.out.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (args.out / name).write_bytes(data)
    print("wrote %d files (%d bytes) to %s" % (len(files), sum(len(d) for d in files.values()), args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
