#!/usr/bin/env python3
# SPDX-License-Identifier: MS-PL
"""Generate the test that holds every `CNA_Bool` input to the contract.

`docs/c-api/ABI_VERSIONING.md` says only `CNA_FALSE` and `CNA_TRUE` are valid. `CBIND-066` measured
how evenly that was enforced: of the 94 routes taking a `CNA_Bool` by value, 24 refused a byte
outside {0, 1}, four forwarded to a helper that did, and **66 accepted it** -- then disagreed about
what it meant, reading the flag as `!= CNA_FALSE` in some places and `== CNA_TRUE` in others, so a
`9` was true in one route and false in another.

`CBIND-067` made all 94 refuse. Hand-writing 94 assertions would leave the guarantee exactly as
fragile as it was, because the next route to arrive would simply not have one. This generates them
from the headers instead, so a new `CNA_Bool` parameter is covered the moment it is declared and an
unguarded one fails the build.

Every other argument is passed as zero or an empty value: the point is the flag, and the guard runs
before the handle lookup, so an invalid handle beside it changes nothing. A route on a surface this
build compiled out answers `CNA_RESULT_NOT_SUPPORTED` for any input, which the generated test
accepts -- refusing an argument to a route that does not exist here would be the wrong answer.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HEADER_DIR = REPO_ROOT / "modules" / "c-api" / "include" / "CNA" / "C"
OUTPUT_PATH = REPO_ROOT / "modules" / "c-api" / "tests" / "pure_c" / "BoolContractSmoke.c"

# Every by-value aggregate a route may take beside its flag, and the zeroed local standing in for
# it. A type missing from here is a hard error rather than a skipped route: silently dropping one
# would shrink the covered set without saying so.
VALUE_TYPES = {
    "CNA_StringView": "empty_view", "CNA_Color": "zero_color", "CNA_Vector2": "zero_v2",
    "CNA_Vector3": "zero_v3", "CNA_Vector4": "zero_v4", "CNA_Quaternion": "zero_quat",
    "CNA_Matrix": "zero_matrix", "CNA_Plane": "zero_plane", "CNA_Rectangle": "zero_rect",
    "CNA_Point": "zero_point", "CNA_BoundingBox": "zero_bbox",
    "CNA_BoundingSphere": "zero_bsphere", "CNA_Ray": "zero_ray",
    "CNA_BoundingFrustum": "zero_bfrustum", "CNA_CurveKey": "zero_curvekey",
    "CNA_Viewport": "zero_viewport", "CNA_ColorMatrix4x4": "zero_colormatrix",
    "CNA_VertexElement": "zero_velem", "CNA_DateTimeOffset": "zero_dto",
    "CNA_OptionalInt32": "zero_optional_int32",
}
SCALAR = re.compile(r"^(u?int(8|16|32|64)_t|float|double|size_t|CNA_Handle|CNA_Result)$")
BOOL_PARAM = re.compile(r"^\s*CNA_Bool\s+[A-Za-z_][A-Za-z0-9_]*\s*$")


def argument_for(param: str) -> str:
    param = param.strip()
    if "*" in param:
        return "0"
    type_name = re.sub(r"\b(const)\b", "", param).strip()
    type_name = re.sub(r"\s+[A-Za-z_][A-Za-z0-9_]*$", "", type_name).strip()
    if type_name == "CNA_Bool":
        return "UINT8_C(9)"
    if type_name in VALUE_TYPES:
        return VALUE_TYPES[type_name]
    if SCALAR.match(type_name) or type_name.startswith("CNA_"):
        return "0"
    raise SystemExit(
        f"generate_bool_contract_test.py: no stand-in value for the by-value parameter "
        f"'{param}'. Add it to VALUE_TYPES rather than letting its route drop out of the test.")


def routes() -> list[tuple[str, list[str]]]:
    found = []
    for path in sorted(HEADER_DIR.glob("*.h")):
        text = re.sub(r"/\*.*?\*/", "", path.read_text(encoding="utf-8"), flags=re.S)
        for match in re.finditer(
                r"CNA_C_API\s+CNA_Result\s+(cna_[A-Za-z0-9_]+)\s*\(([^;]*?)\)\s*;", text, re.S):
            name, params = match.group(1), " ".join(match.group(2).split())
            if params.strip() in ("void", ""):
                continue
            parts = re.split(r",(?![^()]*\))", params)
            if not any(BOOL_PARAM.match(part) for part in parts):
                continue
            found.append((name, [argument_for(part) for part in parts]))
    if not found:
        raise SystemExit("No route takes a CNA_Bool by value; the generator is watching nothing.")
    return sorted(found)


def render(found: list[tuple[str, list[str]]]) -> str:
    locals_ = sorted(set(VALUE_TYPES.values()))
    types = {v: k for k, v in VALUE_TYPES.items()}
    lines = [
        "// SPDX-License-Identifier: MS-PL",
        "//",
        "// GENERATED by tools/c-api/generate_bool_contract_test.py -- do not edit by hand.",
        "// Regenerate with --write; CApiBoolContractCurrent fails when this file is stale.",
        "//",
        "// plans/plan_binding.md CBIND-067: every route taking a CNA_Bool refuses a byte outside",
        "// {CNA_FALSE, CNA_TRUE}, which docs/c-api/ABI_VERSIONING.md has always declared the only",
        "// valid values and which 66 of 94 routes used to accept -- then read as true in some",
        "// places and false in others. Generated rather than hand-written so a new flag parameter",
        "// is covered the moment it is declared.",
        "",
        "#include <CNA/C/cna.h>",
        "",
        "#include <stdint.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        "",
        "int main(void)",
        "{",
    ]
    for local in locals_:
        lines.append(f"    {types[local]} {local};")
    lines += [
        "    CNA_Result result = CNA_RESULT_SUCCESS;",
        "    int accepted = 0;",
        "",
    ]
    for local in locals_:
        lines.append(f"    memset(&{local}, 0, sizeof({local}));")
    lines += [
        "",
        "    /* A surface this build compiled out answers NOT_SUPPORTED for any input, and refusing",
        "       an argument to a route that does not exist here would be the wrong answer. */",
    ]
    for name, args in found:
        call = f"{name}({', '.join(args)})"
        lines.append(f"    result = {call};")
        lines.append("    if (result != CNA_RESULT_INVALID_ARGUMENT &&")
        lines.append("        result != CNA_RESULT_NOT_SUPPORTED) {")
        lines.append(f'        printf("accepted a non-canonical CNA_Bool (%u): {name}\\n",')
        lines.append("               (unsigned)result);")
        lines.append("        ++accepted;")
        lines.append("    }")
    lines += [
        "",
        f'    printf("%d of {len(found)} routes accepted a CNA_Bool of 9\\n", accepted);',
        "    return accepted == 0 ? 0 : 1;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the test")
    mode.add_argument("--check", action="store_true", help="fail if the checked-in test is stale")
    args = parser.parse_args()

    rendered = render(routes())
    if args.write:
        OUTPUT_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
        return 0
    if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
        print(
            f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale: run "
            "tools/c-api/generate_bool_contract_test.py --write")
        return 1
    print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
