// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Graphics::detail::ParticleSystemGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "particle_system";
inline constexpr std::string_view kManifestSha256 = "c913f5d208d87e454befa22e51d9ed10f10f4596a45dcd7e47c185903eba356d";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kSimulateEsComputeSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

layout(local_size_x = 64) in;

layout(std430, binding = 0) buffer CnaParticles
{
    vec4 cnaParticles[];
};

layout(std140, binding = 1) uniform ParticleSimulationParameters
{
    vec4 uSimulation0; // active count, elapsed, cone angle, speed
    vec4 uSimulation1; // speed variance, lifetime, lifetime variance, drag
    vec4 uOrigin;
    vec4 uDirection;
    vec4 uGravity;
};

uint cnaParticleHash(uint x)
{
    x ^= x >> 16u; x *= 0x7feb352du;
    x ^= x >> 15u; x *= 0x846ca68bu;
    x ^= x >> 16u; return x;
}

float cnaParticleRandom(uint seed)
{
    return float(cnaParticleHash(seed) & 0x00ffffffu) / 16777216.0;
}

vec3 cnaNormaliseOr(vec3 value, vec3 fallbackValue)
{
    float valueLength = length(value);
    return valueLength > 1e-6 ? value / valueLength : fallbackValue;
}

void cnaSpawn(uint index, uint generation, out vec3 position, out vec3 velocity,
              out float lifetime)
{
    uint seed = cnaParticleHash(index * 747796405u + generation * 2891336453u);
    float u = cnaParticleRandom(seed);
    float v = cnaParticleRandom(seed + 1u);
    float w = cnaParticleRandom(seed + 2u);
    float x = cnaParticleRandom(seed + 3u);

    float cosTheta = 1.0 + (cos(uSimulation0.z) - 1.0) * u;
    float sinTheta = sqrt(max(1.0 - cosTheta * cosTheta, 0.0));
    float phi = 6.28318530718 * v;

    vec3 axis = cnaNormaliseOr(uDirection.xyz, vec3(0.0, 1.0, 0.0));
    vec3 helper = abs(axis.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
    vec3 right = cnaNormaliseOr(cross(helper, axis), vec3(1.0, 0.0, 0.0));
    vec3 up = cross(axis, right);
    vec3 direction = axis * cosTheta
                   + (right * cos(phi) + up * sin(phi)) * sinTheta;

    float speed = uSimulation0.w
                * (1.0 + uSimulation1.x * (w * 2.0 - 1.0));
    position = uOrigin.xyz;
    velocity = direction * speed;
    lifetime = max(uSimulation1.y
                       * (1.0 + uSimulation1.z * (x * 2.0 - 1.0)),
                   1e-3);
}

void main()
{
    uint index = gl_GlobalInvocationID.x;
    uint activeCount = uint(max(uSimulation0.x, 0.0) + 0.5);
    if (index >= activeCount)
        return;

    uint base = index * 3u;
    vec3 position = cnaParticles[base].xyz;
    vec3 velocity = cnaParticles[base + 1u].xyz;
    vec4 state = cnaParticles[base + 2u];
    float age = state.x;
    float lifetime = state.y;
    float generation = state.w;

    age += uSimulation0.y;
    if (age >= lifetime)
    {
        generation += 1.0;
        age -= lifetime;
        cnaSpawn(index, uint(generation), position, velocity, lifetime);
    }

    velocity += uGravity.xyz * uSimulation0.y;
    velocity -= velocity * min(uSimulation1.w * uSimulation0.y, 1.0);
    position += velocity * uSimulation0.y;

    cnaParticles[base] = vec4(position, 0.0);
    cnaParticles[base + 1u] = vec4(velocity, 0.0);
    cnaParticles[base + 2u] = vec4(age, lifetime, state.z, generation);
}
)CNA_SHADER";

inline constexpr std::string_view kSimulateDesktopComputeSource =
    R"CNA_SHADER(#version 430 core

layout(local_size_x = 64) in;

layout(std430, binding = 0) buffer CnaParticles
{
    vec4 cnaParticles[];
};

layout(std140, binding = 1) uniform ParticleSimulationParameters
{
    vec4 uSimulation0;
    vec4 uSimulation1;
    vec4 uOrigin;
    vec4 uDirection;
    vec4 uGravity;
};

uint cnaParticleHash(uint x)
{
    x ^= x >> 16u; x *= 0x7feb352du;
    x ^= x >> 15u; x *= 0x846ca68bu;
    x ^= x >> 16u; return x;
}

float cnaParticleRandom(uint seed)
{
    return float(cnaParticleHash(seed) & 0x00ffffffu) / 16777216.0;
}

vec3 cnaNormaliseOr(vec3 value, vec3 fallbackValue)
{
    float valueLength = length(value);
    return valueLength > 1e-6 ? value / valueLength : fallbackValue;
}

void cnaSpawn(uint index, uint generation, out vec3 position, out vec3 velocity,
              out float lifetime)
{
    uint seed = cnaParticleHash(index * 747796405u + generation * 2891336453u);
    float u = cnaParticleRandom(seed);
    float v = cnaParticleRandom(seed + 1u);
    float w = cnaParticleRandom(seed + 2u);
    float x = cnaParticleRandom(seed + 3u);

    float cosTheta = 1.0 + (cos(uSimulation0.z) - 1.0) * u;
    float sinTheta = sqrt(max(1.0 - cosTheta * cosTheta, 0.0));
    float phi = 6.28318530718 * v;

    vec3 axis = cnaNormaliseOr(uDirection.xyz, vec3(0.0, 1.0, 0.0));
    vec3 helper = abs(axis.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
    vec3 right = cnaNormaliseOr(cross(helper, axis), vec3(1.0, 0.0, 0.0));
    vec3 up = cross(axis, right);
    vec3 direction = axis * cosTheta
                   + (right * cos(phi) + up * sin(phi)) * sinTheta;

    float speed = uSimulation0.w
                * (1.0 + uSimulation1.x * (w * 2.0 - 1.0));
    position = uOrigin.xyz;
    velocity = direction * speed;
    lifetime = max(uSimulation1.y
                       * (1.0 + uSimulation1.z * (x * 2.0 - 1.0)),
                   1e-3);
}

void main()
{
    uint index = gl_GlobalInvocationID.x;
    uint activeCount = uint(max(uSimulation0.x, 0.0) + 0.5);
    if (index >= activeCount)
        return;

    uint base = index * 3u;
    vec3 position = cnaParticles[base].xyz;
    vec3 velocity = cnaParticles[base + 1u].xyz;
    vec4 state = cnaParticles[base + 2u];
    float age = state.x;
    float lifetime = state.y;
    float generation = state.w;

    age += uSimulation0.y;
    if (age >= lifetime)
    {
        generation += 1.0;
        age -= lifetime;
        cnaSpawn(index, uint(generation), position, velocity, lifetime);
    }

    velocity += uGravity.xyz * uSimulation0.y;
    velocity -= velocity * min(uSimulation1.w * uSimulation0.y, 1.0);
    position += velocity * uSimulation0.y;

    cnaParticles[base] = vec4(position, 0.0);
    cnaParticles[base + 1u] = vec4(velocity, 0.0);
    cnaParticles[base + 2u] = vec4(age, lifetime, state.z, generation);
}
)CNA_SHADER";

inline constexpr std::uint32_t kSimulateVulkanComputeSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000290u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x000000e4u, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000040u, 0x00000001u, 0x00000001u, 0x00030047u, 0x00000078u, 0x00000002u, 0x00050048u,
    0x00000078u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00050048u, 0x00000078u, 0x00000001u, 0x00000023u,
    0x00000010u, 0x00050048u, 0x00000078u, 0x00000002u, 0x00000023u, 0x00000020u, 0x00050048u, 0x00000078u,
    0x00000003u, 0x00000023u, 0x00000030u, 0x00050048u, 0x00000078u, 0x00000004u, 0x00000023u, 0x00000040u,
    0x00040047u, 0x0000007au, 0x00000021u, 0x00000001u, 0x00040047u, 0x0000007au, 0x00000022u, 0x00000000u,
    0x00040047u, 0x000000e4u, 0x0000000bu, 0x0000001cu, 0x00040047u, 0x000000f9u, 0x00000006u, 0x00000010u,
    0x00030047u, 0x000000fau, 0x00000003u, 0x00050048u, 0x000000fau, 0x00000000u, 0x00000023u, 0x00000000u,
    0x00040047u, 0x000000fcu, 0x00000021u, 0x00000000u, 0x00040047u, 0x000000fcu, 0x00000022u, 0x00000000u,
    0x00040047u, 0x00000162u, 0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u,
    0x00000002u, 0x00040015u, 0x00000006u, 0x00000020u, 0x00000000u, 0x00030016u, 0x0000000cu, 0x00000020u,
    0x00040017u, 0x00000011u, 0x0000000cu, 0x00000003u, 0x0004002bu, 0x00000006u, 0x00000022u, 0x00000010u,
    0x0004002bu, 0x00000006u, 0x00000026u, 0x7feb352du, 0x0004002bu, 0x00000006u, 0x0000002au, 0x0000000fu,
    0x0004002bu, 0x00000006u, 0x0000002eu, 0x846ca68bu, 0x0004002bu, 0x00000006u, 0x0000003bu, 0x00ffffffu,
    0x0004002bu, 0x0000000cu, 0x00000046u, 0x358637bdu, 0x00020014u, 0x00000047u, 0x0004002bu, 0x00000006u,
    0x00000057u, 0x2c9277b5u, 0x0004002bu, 0x00000006u, 0x0000005au, 0xac564b05u, 0x0004002bu, 0x00000006u,
    0x00000065u, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000006bu, 0x00000002u, 0x0004002bu, 0x00000006u,
    0x00000071u, 0x00000003u, 0x0004002bu, 0x0000000cu, 0x00000076u, 0x3f800000u, 0x00040017u, 0x00000077u,
    0x0000000cu, 0x00000004u, 0x0007001eu, 0x00000078u, 0x00000077u, 0x00000077u, 0x00000077u, 0x00000077u,
    0x00000077u, 0x00040020u, 0x00000079u, 0x00000002u, 0x00000078u, 0x0004003bu, 0x00000079u, 0x0000007au,
    0x00000002u, 0x00040015u, 0x0000007bu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000007bu, 0x0000007cu,
    0x00000000u, 0x00040020u, 0x0000007du, 0x00000002u, 0x0000000cu, 0x0004002bu, 0x0000000cu, 0x0000008au,
    0x00000000u, 0x0004002bu, 0x0000007bu, 0x00000092u, 0x00000003u, 0x0006002cu, 0x00000011u, 0x00000093u,
    0x0000008au, 0x00000076u, 0x0000008au, 0x00040020u, 0x00000095u, 0x00000002u, 0x00000077u, 0x0004002bu,
    0x0000000cu, 0x0000009fu, 0x3f7d70a4u, 0x0006002cu, 0x00000011u, 0x000000a1u, 0x00000076u, 0x0000008au,
    0x0000008au, 0x00040017u, 0x000000a2u, 0x00000047u, 0x00000003u, 0x0004002bu, 0x0000007bu, 0x000000c3u,
    0x00000001u, 0x0004002bu, 0x00000006u, 0x000000c4u, 0x00000000u, 0x0004002bu, 0x0000007bu, 0x000000ceu,
    0x00000002u, 0x0004002bu, 0x0000000cu, 0x000000dfu, 0x3a83126fu, 0x00040017u, 0x000000e2u, 0x00000006u,
    0x00000003u, 0x00040020u, 0x000000e3u, 0x00000001u, 0x000000e2u, 0x0004003bu, 0x000000e3u, 0x000000e4u,
    0x00000001u, 0x00040020u, 0x000000e5u, 0x00000001u, 0x00000006u, 0x0004002bu, 0x0000000cu, 0x000000ecu,
    0x3f000000u, 0x0003001du, 0x000000f9u, 0x00000077u, 0x0003001eu, 0x000000fau, 0x000000f9u, 0x00040020u,
    0x000000fbu, 0x00000002u, 0x000000fau, 0x0004003bu, 0x000000fbu, 0x000000fcu, 0x00000002u, 0x0004002bu,
    0x0000007bu, 0x00000130u, 0x00000004u, 0x0004002bu, 0x00000006u, 0x00000161u, 0x00000040u, 0x0006002cu,
    0x000000e2u, 0x00000162u, 0x00000161u, 0x00000065u, 0x00000065u, 0x0004002bu, 0x0000000cu, 0x0000028du,
    0x33800000u, 0x0004002bu, 0x0000000cu, 0x0000028eu, 0x34c90fdbu, 0x0004002bu, 0x0000000cu, 0x0000028fu,
    0x34000000u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u,
    0x000300f7u, 0x00000163u, 0x00000000u, 0x000300fbu, 0x000000c4u, 0x00000164u, 0x000200f8u, 0x00000164u,
    0x00050041u, 0x000000e5u, 0x000000e6u, 0x000000e4u, 0x000000c4u, 0x0004003du, 0x00000006u, 0x000000e7u,
    0x000000e6u, 0x00060041u, 0x0000007du, 0x000000e9u, 0x0000007au, 0x0000007cu, 0x000000c4u, 0x0004003du,
    0x0000000cu, 0x000000eau, 0x000000e9u, 0x0007000cu, 0x0000000cu, 0x000000ebu, 0x00000001u, 0x00000028u,
    0x000000eau, 0x0000008au, 0x00050081u, 0x0000000cu, 0x000000edu, 0x000000ebu, 0x000000ecu, 0x0004006du,
    0x00000006u, 0x000000eeu, 0x000000edu, 0x000500aeu, 0x00000047u, 0x000000f1u, 0x000000e7u, 0x000000eeu,
    0x000300f7u, 0x000000f3u, 0x00000000u, 0x000400fau, 0x000000f1u, 0x000000f2u, 0x000000f3u, 0x000200f8u,
    0x000000f2u, 0x000200f9u, 0x00000163u, 0x000200f8u, 0x000000f3u, 0x00050084u, 0x00000006u, 0x000000f7u,
    0x000000e7u, 0x00000071u, 0x00060041u, 0x00000095u, 0x000000feu, 0x000000fcu, 0x0000007cu, 0x000000f7u,
    0x0004003du, 0x00000077u, 0x000000ffu, 0x000000feu, 0x0008004fu, 0x00000011u, 0x00000100u, 0x000000ffu,
    0x000000ffu, 0x00000000u, 0x00000001u, 0x00000002u, 0x00050080u, 0x00000006u, 0x00000103u, 0x000000f7u,
    0x00000065u, 0x00060041u, 0x00000095u, 0x00000104u, 0x000000fcu, 0x0000007cu, 0x00000103u, 0x0004003du,
    0x00000077u, 0x00000105u, 0x00000104u, 0x0008004fu, 0x00000011u, 0x00000106u, 0x00000105u, 0x00000105u,
    0x00000000u, 0x00000001u, 0x00000002u, 0x00050080u, 0x00000006u, 0x0000010au, 0x000000f7u, 0x0000006bu,
    0x00060041u, 0x00000095u, 0x0000010bu, 0x000000fcu, 0x0000007cu, 0x0000010au, 0x0004003du, 0x00000077u,
    0x0000010cu, 0x0000010bu, 0x00050051u, 0x0000000cu, 0x0000010fu, 0x0000010cu, 0x00000000u, 0x00050051u,
    0x0000000cu, 0x00000112u, 0x0000010cu, 0x00000001u, 0x00050051u, 0x0000000cu, 0x00000115u, 0x0000010cu,
    0x00000003u, 0x00060041u, 0x0000007du, 0x00000116u, 0x0000007au, 0x0000007cu, 0x00000065u, 0x0004003du,
    0x0000000cu, 0x00000117u, 0x00000116u, 0x00050081u, 0x0000000cu, 0x00000119u, 0x0000010fu, 0x00000117u,
    0x000500beu, 0x00000047u, 0x0000011cu, 0x00000119u, 0x00000112u, 0x000300f7u, 0x0000011eu, 0x00000000u,
    0x000400fau, 0x0000011cu, 0x0000011du, 0x0000011eu, 0x000200f8u, 0x0000011du, 0x00050081u, 0x0000000cu,
    0x00000120u, 0x00000115u, 0x00000076u, 0x00050083u, 0x0000000cu, 0x00000123u, 0x00000119u, 0x00000112u,
    0x0004006du, 0x00000006u, 0x00000125u, 0x00000120u, 0x00050084u, 0x00000006u, 0x00000182u, 0x000000e7u,
    0x00000057u, 0x00050084u, 0x00000006u, 0x00000184u, 0x00000125u, 0x0000005au, 0x00050080u, 0x00000006u,
    0x00000185u, 0x00000182u, 0x00000184u, 0x000500c2u, 0x00000006u, 0x000001dfu, 0x00000185u, 0x00000022u,
    0x000500c6u, 0x00000006u, 0x000001e1u, 0x00000185u, 0x000001dfu, 0x00050084u, 0x00000006u, 0x000001e3u,
    0x000001e1u, 0x00000026u, 0x000500c2u, 0x00000006u, 0x000001e5u, 0x000001e3u, 0x0000002au, 0x000500c6u,
    0x00000006u, 0x000001e7u, 0x000001e3u, 0x000001e5u, 0x00050084u, 0x00000006u, 0x000001e9u, 0x000001e7u,
    0x0000002eu, 0x000500c2u, 0x00000006u, 0x000001ebu, 0x000001e9u, 0x00000022u, 0x000500c6u, 0x00000006u,
    0x000001edu, 0x000001e9u, 0x000001ebu, 0x000500c2u, 0x00000006u, 0x000001fau, 0x000001edu, 0x00000022u,
    0x000500c6u, 0x00000006u, 0x000001fcu, 0x000001edu, 0x000001fau, 0x00050084u, 0x00000006u, 0x000001feu,
    0x000001fcu, 0x00000026u, 0x000500c2u, 0x00000006u, 0x00000200u, 0x000001feu, 0x0000002au, 0x000500c6u,
    0x00000006u, 0x00000202u, 0x000001feu, 0x00000200u, 0x00050084u, 0x00000006u, 0x00000204u, 0x00000202u,
    0x0000002eu, 0x000500c2u, 0x00000006u, 0x00000206u, 0x00000204u, 0x00000022u, 0x000500c6u, 0x00000006u,
    0x00000208u, 0x00000204u, 0x00000206u, 0x000500c7u, 0x00000006u, 0x000001f4u, 0x00000208u, 0x0000003bu,
    0x00040070u, 0x0000000cu, 0x000001f5u, 0x000001f4u, 0x00050085u, 0x0000000cu, 0x000001f6u, 0x000001f5u,
    0x0000028du, 0x00050080u, 0x00000006u, 0x0000018au, 0x000001edu, 0x00000065u, 0x000500c2u, 0x00000006u,
    0x00000215u, 0x0000018au, 0x00000022u, 0x000500c6u, 0x00000006u, 0x00000217u, 0x0000018au, 0x00000215u,
    0x00050084u, 0x00000006u, 0x00000219u, 0x00000217u, 0x00000026u, 0x000500c2u, 0x00000006u, 0x0000021bu,
    0x00000219u, 0x0000002au, 0x000500c6u, 0x00000006u, 0x0000021du, 0x00000219u, 0x0000021bu, 0x00050084u,
    0x00000006u, 0x0000021fu, 0x0000021du, 0x0000002eu, 0x000500c2u, 0x00000006u, 0x00000221u, 0x0000021fu,
    0x00000022u, 0x000500c6u, 0x00000006u, 0x00000223u, 0x0000021fu, 0x00000221u, 0x000500c7u, 0x00000006u,
    0x0000020fu, 0x00000223u, 0x0000003bu, 0x00040070u, 0x0000000cu, 0x00000210u, 0x0000020fu, 0x00050080u,
    0x00000006u, 0x0000018du, 0x000001edu, 0x0000006bu, 0x000500c2u, 0x00000006u, 0x00000230u, 0x0000018du,
    0x00000022u, 0x000500c6u, 0x00000006u, 0x00000232u, 0x0000018du, 0x00000230u, 0x00050084u, 0x00000006u,
    0x00000234u, 0x00000232u, 0x00000026u, 0x000500c2u, 0x00000006u, 0x00000236u, 0x00000234u, 0x0000002au,
    0x000500c6u, 0x00000006u, 0x00000238u, 0x00000234u, 0x00000236u, 0x00050084u, 0x00000006u, 0x0000023au,
    0x00000238u, 0x0000002eu, 0x000500c2u, 0x00000006u, 0x0000023cu, 0x0000023au, 0x00000022u, 0x000500c6u,
    0x00000006u, 0x0000023eu, 0x0000023au, 0x0000023cu, 0x000500c7u, 0x00000006u, 0x0000022au, 0x0000023eu,
    0x0000003bu, 0x00040070u, 0x0000000cu, 0x0000022bu, 0x0000022au, 0x00050080u, 0x00000006u, 0x00000190u,
    0x000001edu, 0x00000071u, 0x000500c2u, 0x00000006u, 0x0000024bu, 0x00000190u, 0x00000022u, 0x000500c6u,
    0x00000006u, 0x0000024du, 0x00000190u, 0x0000024bu, 0x00050084u, 0x00000006u, 0x0000024fu, 0x0000024du,
    0x00000026u, 0x000500c2u, 0x00000006u, 0x00000251u, 0x0000024fu, 0x0000002au, 0x000500c6u, 0x00000006u,
    0x00000253u, 0x0000024fu, 0x00000251u, 0x00050084u, 0x00000006u, 0x00000255u, 0x00000253u, 0x0000002eu,
    0x000500c2u, 0x00000006u, 0x00000257u, 0x00000255u, 0x00000022u, 0x000500c6u, 0x00000006u, 0x00000259u,
    0x00000255u, 0x00000257u, 0x000500c7u, 0x00000006u, 0x00000245u, 0x00000259u, 0x0000003bu, 0x00040070u,
    0x0000000cu, 0x00000246u, 0x00000245u, 0x00060041u, 0x0000007du, 0x00000192u, 0x0000007au, 0x0000007cu,
    0x0000006bu, 0x0004003du, 0x0000000cu, 0x00000193u, 0x00000192u, 0x0006000cu, 0x0000000cu, 0x00000194u,
    0x00000001u, 0x0000000eu, 0x00000193u, 0x00050083u, 0x0000000cu, 0x00000195u, 0x00000194u, 0x00000076u,
    0x00050085u, 0x0000000cu, 0x00000197u, 0x00000195u, 0x000001f6u, 0x00050081u, 0x0000000cu, 0x00000198u,
    0x00000076u, 0x00000197u, 0x00050085u, 0x0000000cu, 0x0000019bu, 0x00000198u, 0x00000198u, 0x00050083u,
    0x0000000cu, 0x0000019cu, 0x00000076u, 0x0000019bu, 0x0007000cu, 0x0000000cu, 0x0000019du, 0x00000001u,
    0x00000028u, 0x0000019cu, 0x0000008au, 0x0006000cu, 0x0000000cu, 0x0000019eu, 0x00000001u, 0x0000001fu,
    0x0000019du, 0x00050085u, 0x0000000cu, 0x000001a0u, 0x00000210u, 0x0000028eu, 0x00050041u, 0x00000095u,
    0x000001a1u, 0x0000007au, 0x00000092u, 0x0004003du, 0x00000077u, 0x000001a2u, 0x000001a1u, 0x0008004fu,
    0x00000011u, 0x000001a3u, 0x000001a2u, 0x000001a2u, 0x00000000u, 0x00000001u, 0x00000002u, 0x0006000cu,
    0x0000000cu, 0x00000260u, 0x00000001u, 0x00000042u, 0x000001a3u, 0x000500bau, 0x00000047u, 0x00000262u,
    0x00000260u, 0x00000046u, 0x000300f7u, 0x0000026au, 0x00000000u, 0x000400fau, 0x00000262u, 0x00000263u,
    0x00000268u, 0x000200f8u, 0x00000263u, 0x00060050u, 0x00000011u, 0x00000266u, 0x00000260u, 0x00000260u,
    0x00000260u, 0x00050088u, 0x00000011u, 0x00000267u, 0x000001a3u, 0x00000266u, 0x000200f9u, 0x0000026au,
    0x000200f8u, 0x00000268u, 0x000200f9u, 0x0000026au, 0x000200f8u, 0x0000026au, 0x000700f5u, 0x00000011u,
    0x00000282u, 0x00000267u, 0x00000263u, 0x00000093u, 0x00000268u, 0x00050051u, 0x0000000cu, 0x000001a6u,
    0x00000282u, 0x00000001u, 0x0006000cu, 0x0000000cu, 0x000001a7u, 0x00000001u, 0x00000004u, 0x000001a6u,
    0x000500b8u, 0x00000047u, 0x000001a8u, 0x000001a7u, 0x0000009fu, 0x00060050u, 0x000000a2u, 0x000001a9u,
    0x000001a8u, 0x000001a8u, 0x000001a8u, 0x000600a9u, 0x00000011u, 0x000001aau, 0x000001a9u, 0x00000093u,
    0x000000a1u, 0x0007000cu, 0x00000011u, 0x000001adu, 0x00000001u, 0x00000044u, 0x000001aau, 0x00000282u,
    0x0006000cu, 0x0000000cu, 0x00000271u, 0x00000001u, 0x00000042u, 0x000001adu, 0x000500bau, 0x00000047u,
    0x00000273u, 0x00000271u, 0x00000046u, 0x000300f7u, 0x0000027bu, 0x00000000u, 0x000400fau, 0x00000273u,
    0x00000274u, 0x00000279u, 0x000200f8u, 0x00000274u, 0x00060050u, 0x00000011u, 0x00000277u, 0x00000271u,
    0x00000271u, 0x00000271u, 0x00050088u, 0x00000011u, 0x00000278u, 0x000001adu, 0x00000277u, 0x000200f9u,
    0x0000027bu, 0x000200f8u, 0x00000279u, 0x000200f9u, 0x0000027bu, 0x000200f8u, 0x0000027bu, 0x000700f5u,
    0x00000011u, 0x00000283u, 0x00000278u, 0x00000274u, 0x000000a1u, 0x00000279u, 0x0007000cu, 0x00000011u,
    0x000001b1u, 0x00000001u, 0x00000044u, 0x00000282u, 0x00000283u, 0x0005008eu, 0x00000011u, 0x000001b4u,
    0x00000282u, 0x00000198u, 0x0006000cu, 0x0000000cu, 0x000001b7u, 0x00000001u, 0x0000000eu, 0x000001a0u,
    0x0005008eu, 0x00000011u, 0x000001b8u, 0x00000283u, 0x000001b7u, 0x0006000cu, 0x0000000cu, 0x000001bbu,
    0x00000001u, 0x0000000du, 0x000001a0u, 0x0005008eu, 0x00000011u, 0x000001bcu, 0x000001b1u, 0x000001bbu,
    0x00050081u, 0x00000011u, 0x000001bdu, 0x000001b8u, 0x000001bcu, 0x0005008eu, 0x00000011u, 0x000001bfu,
    0x000001bdu, 0x0000019eu, 0x00050081u, 0x00000011u, 0x000001c0u, 0x000001b4u, 0x000001bfu, 0x00060041u,
    0x0000007du, 0x000001c1u, 0x0000007au, 0x0000007cu, 0x00000071u, 0x0004003du, 0x0000000cu, 0x000001c2u,
    0x000001c1u, 0x00060041u, 0x0000007du, 0x000001c3u, 0x0000007au, 0x000000c3u, 0x000000c4u, 0x0004003du,
    0x0000000cu, 0x000001c4u, 0x000001c3u, 0x00050085u, 0x0000000cu, 0x000001c6u, 0x0000022bu, 0x0000028fu,
    0x00050083u, 0x0000000cu, 0x000001c7u, 0x000001c6u, 0x00000076u, 0x00050085u, 0x0000000cu, 0x000001c8u,
    0x000001c4u, 0x000001c7u, 0x00050081u, 0x0000000cu, 0x000001c9u, 0x00000076u, 0x000001c8u, 0x00050085u,
    0x0000000cu, 0x000001cau, 0x000001c2u, 0x000001c9u, 0x00050041u, 0x00000095u, 0x000001cbu, 0x0000007au,
    0x000000ceu, 0x0004003du, 0x00000077u, 0x000001ccu, 0x000001cbu, 0x0008004fu, 0x00000011u, 0x000001cdu,
    0x000001ccu, 0x000001ccu, 0x00000000u, 0x00000001u, 0x00000002u, 0x0005008eu, 0x00000011u, 0x000001d0u,
    0x000001c0u, 0x000001cau, 0x00060041u, 0x0000007du, 0x000001d1u, 0x0000007au, 0x000000c3u, 0x00000065u,
    0x0004003du, 0x0000000cu, 0x000001d2u, 0x000001d1u, 0x00060041u, 0x0000007du, 0x000001d3u, 0x0000007au,
    0x000000c3u, 0x0000006bu, 0x0004003du, 0x0000000cu, 0x000001d4u, 0x000001d3u, 0x00050085u, 0x0000000cu,
    0x000001d6u, 0x00000246u, 0x0000028fu, 0x00050083u, 0x0000000cu, 0x000001d7u, 0x000001d6u, 0x00000076u,
    0x00050085u, 0x0000000cu, 0x000001d8u, 0x000001d4u, 0x000001d7u, 0x00050081u, 0x0000000cu, 0x000001d9u,
    0x00000076u, 0x000001d8u, 0x00050085u, 0x0000000cu, 0x000001dau, 0x000001d2u, 0x000001d9u, 0x0007000cu,
    0x0000000cu, 0x000001dbu, 0x00000001u, 0x00000028u, 0x000001dau, 0x000000dfu, 0x000200f9u, 0x0000011eu,
    0x000200f8u, 0x0000011eu, 0x000700f5u, 0x0000000cu, 0x0000028au, 0x00000115u, 0x000000f3u, 0x00000120u,
    0x0000027bu, 0x000700f5u, 0x0000000cu, 0x00000289u, 0x00000112u, 0x000000f3u, 0x000001dbu, 0x0000027bu,
    0x000700f5u, 0x0000000cu, 0x00000286u, 0x00000119u, 0x000000f3u, 0x00000123u, 0x0000027bu, 0x000700f5u,
    0x00000011u, 0x00000285u, 0x00000100u, 0x000000f3u, 0x000001cdu, 0x0000027bu, 0x000700f5u, 0x00000011u,
    0x00000284u, 0x00000106u, 0x000000f3u, 0x000001d0u, 0x0000027bu, 0x00050041u, 0x00000095u, 0x00000131u,
    0x0000007au, 0x00000130u, 0x0004003du, 0x00000077u, 0x00000132u, 0x00000131u, 0x0008004fu, 0x00000011u,
    0x00000133u, 0x00000132u, 0x00000132u, 0x00000000u, 0x00000001u, 0x00000002u, 0x0005008eu, 0x00000011u,
    0x00000136u, 0x00000133u, 0x00000117u, 0x00050081u, 0x00000011u, 0x00000138u, 0x00000284u, 0x00000136u,
    0x00060041u, 0x0000007du, 0x0000013au, 0x0000007au, 0x000000c3u, 0x00000071u, 0x0004003du, 0x0000000cu,
    0x0000013bu, 0x0000013au, 0x00050085u, 0x0000000cu, 0x0000013eu, 0x0000013bu, 0x00000117u, 0x0007000cu,
    0x0000000cu, 0x0000013fu, 0x00000001u, 0x00000025u, 0x0000013eu, 0x00000076u, 0x0005008eu, 0x00000011u,
    0x00000140u, 0x00000138u, 0x0000013fu, 0x00050083u, 0x00000011u, 0x00000142u, 0x00000138u, 0x00000140u,
    0x0005008eu, 0x00000011u, 0x00000146u, 0x00000142u, 0x00000117u, 0x00050081u, 0x00000011u, 0x00000148u,
    0x00000285u, 0x00000146u, 0x00050051u, 0x0000000cu, 0x0000014bu, 0x00000148u, 0x00000000u, 0x00050051u,
    0x0000000cu, 0x0000014cu, 0x00000148u, 0x00000001u, 0x00050051u, 0x0000000cu, 0x0000014du, 0x00000148u,
    0x00000002u, 0x00070050u, 0x00000077u, 0x0000014eu, 0x0000014bu, 0x0000014cu, 0x0000014du, 0x0000008au,
    0x0003003eu, 0x000000feu, 0x0000014eu, 0x00050051u, 0x0000000cu, 0x00000153u, 0x00000142u, 0x00000000u,
    0x00050051u, 0x0000000cu, 0x00000154u, 0x00000142u, 0x00000001u, 0x00050051u, 0x0000000cu, 0x00000155u,
    0x00000142u, 0x00000002u, 0x00070050u, 0x00000077u, 0x00000156u, 0x00000153u, 0x00000154u, 0x00000155u,
    0x0000008au, 0x0003003eu, 0x00000104u, 0x00000156u, 0x00050051u, 0x0000000cu, 0x0000015du, 0x0000010cu,
    0x00000002u, 0x00070050u, 0x00000077u, 0x0000015fu, 0x00000286u, 0x00000289u, 0x0000015du, 0x0000028au,
    0x0003003eu, 0x0000010bu, 0x0000015fu, 0x000200f9u, 0x00000163u, 0x000200f8u, 0x00000163u, 0x000100fdu,
    0x00010038u,
};
inline constexpr std::size_t kSimulateVulkanComputeSpirVByteSize = sizeof(kSimulateVulkanComputeSpirV);

inline constexpr std::string_view kSimulateVulkanComputeWgsl =
    R"CNA_SHADER(// simulate.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct ParticleSimulationParameters {
    uSimulation0_: vec4<f32>,
    uSimulation1_: vec4<f32>,
    uOrigin: vec4<f32>,
    uDirection: vec4<f32>,
    uGravity: vec4<f32>,
}

struct CnaParticles {
    cnaParticles: array<vec4<f32>>,
}

@group(0) @binding(1) 
var<uniform> unnamed: ParticleSimulationParameters;
var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(0) @binding(0) 
var<storage, read_write> unnamed_1: CnaParticles;

fn cnaNormaliseOr_u0028_vf3_u003b_vf3_u003b(value: ptr<function, vec3<f32>>, fallbackValue: ptr<function, vec3<f32>>) -> vec3<f32> {
    var valueLength: f32;
    var local: vec3<f32>;

    let _e36 = (*value);
    valueLength = length(_e36);
    let _e38 = valueLength;
    if (_e38 > 0.000001f) {
        let _e40 = (*value);
        let _e41 = valueLength;
        local = (_e40 / vec3(_e41));
    } else {
        let _e44 = (*fallbackValue);
        local = _e44;
    }
    let _e45 = local;
    return _e45;
}

fn cnaParticleHash_u0028_u1_u003b(x: ptr<function, u32>) -> u32 {
    let _e33 = (*x);
    let _e36 = (*x);
    (*x) = (_e36 ^ (_e33 >> bitcast<u32>(16u)));
    let _e38 = (*x);
    (*x) = (_e38 * 2146121005u);
    let _e40 = (*x);
    let _e43 = (*x);
    (*x) = (_e43 ^ (_e40 >> bitcast<u32>(15u)));
    let _e45 = (*x);
    (*x) = (_e45 * 2221713035u);
    let _e47 = (*x);
    let _e50 = (*x);
    (*x) = (_e50 ^ (_e47 >> bitcast<u32>(16u)));
    let _e52 = (*x);
    return _e52;
}

fn cnaParticleRandom_u0028_u1_u003b(seed: ptr<function, u32>) -> f32 {
    var param: u32;

    let _e34 = (*seed);
    param = _e34;
    let _e35 = cnaParticleHash_u0028_u1_u003b((&param));
    return (f32((_e35 & 16777215u)) / 16777216f);
}

fn cnaSpawn_u0028_u1_u003b_u1_u003b_vf3_u003b_vf3_u003b_f1_u003b(index: ptr<function, u32>, generation: ptr<function, u32>, position: ptr<function, vec3<f32>>, velocity: ptr<function, vec3<f32>>, lifetime: ptr<function, f32>) {
    var seed_1: u32;
    var param_1: u32;
    var u: f32;
    var param_2: u32;
    var v: f32;
    var param_3: u32;
    var w: f32;
    var param_4: u32;
    var x_1: f32;
    var param_5: u32;
    var cosTheta: f32;
    var sinTheta: f32;
    var phi: f32;
    var axis: vec3<f32>;
    var param_6: vec3<f32>;
    var param_7: vec3<f32>;
    var helper: vec3<f32>;
    var right: vec3<f32>;
    var param_8: vec3<f32>;
    var param_9: vec3<f32>;
    var up: vec3<f32>;
    var direction: vec3<f32>;
    var speed: f32;

    let _e60 = (*index);
    let _e62 = (*generation);
    param_1 = ((_e60 * 747796405u) + (_e62 * 2891336453u));
    let _e65 = cnaParticleHash_u0028_u1_u003b((&param_1));
    seed_1 = _e65;
    let _e66 = seed_1;
    param_2 = _e66;
    let _e67 = cnaParticleRandom_u0028_u1_u003b((&param_2));
    u = _e67;
    let _e68 = seed_1;
    param_3 = (_e68 + 1u);
    let _e70 = cnaParticleRandom_u0028_u1_u003b((&param_3));
    v = _e70;
    let _e71 = seed_1;
    param_4 = (_e71 + 2u);
    let _e73 = cnaParticleRandom_u0028_u1_u003b((&param_4));
    w = _e73;
    let _e74 = seed_1;
    param_5 = (_e74 + 3u);
    let _e76 = cnaParticleRandom_u0028_u1_u003b((&param_5));
    x_1 = _e76;
    let _e79 = unnamed.uSimulation0_[2u];
    let _e82 = u;
    cosTheta = (1f + ((cos(_e79) - 1f) * _e82));
    let _e85 = cosTheta;
    let _e86 = cosTheta;
    sinTheta = sqrt(max((1f - (_e85 * _e86)), 0f));
    let _e91 = v;
    phi = (6.2831855f * _e91);
    let _e94 = unnamed.uDirection;
    param_6 = _e94.xyz;
    param_7 = vec3<f32>(0f, 1f, 0f);
    let _e96 = cnaNormaliseOr_u0028_vf3_u003b_vf3_u003b((&param_6), (&param_7));
    axis = _e96;
    let _e98 = axis[1u];
    helper = select(vec3<f32>(1f, 0f, 0f), vec3<f32>(0f, 1f, 0f), vec3((abs(_e98) < 0.99f)));
    let _e103 = helper;
    let _e104 = axis;
    param_8 = cross(_e103, _e104);
    param_9 = vec3<f32>(1f, 0f, 0f);
    let _e106 = cnaNormaliseOr_u0028_vf3_u003b_vf3_u003b((&param_8), (&param_9));
    right = _e106;
    let _e107 = axis;
    let _e108 = right;
    up = cross(_e107, _e108);
    let _e110 = axis;
    let _e111 = cosTheta;
    let _e113 = right;
    let _e114 = phi;
    let _e117 = up;
    let _e118 = phi;
    let _e122 = sinTheta;
    direction = ((_e110 * _e111) + (((_e113 * cos(_e114)) + (_e117 * sin(_e118))) * _e122));
    let _e127 = unnamed.uSimulation0_[3u];
    let _e130 = unnamed.uSimulation1_[0u];
    let _e131 = w;
    speed = (_e127 * (1f + (_e130 * ((_e131 * 2f) - 1f))));
    let _e138 = unnamed.uOrigin;
    (*position) = _e138.xyz;
    let _e140 = direction;
    let _e141 = speed;
    (*velocity) = (_e140 * _e141);
    let _e145 = unnamed.uSimulation1_[1u];
    let _e148 = unnamed.uSimulation1_[2u];
    let _e149 = x_1;
    (*lifetime) = max((_e145 * (1f + (_e148 * ((_e149 * 2f) - 1f)))), 0.001f);
    return;
}

fn main_1() {
    var index_1: u32;
    var activeCount: u32;
    var base: u32;
    var position_1: vec3<f32>;
    var velocity_1: vec3<f32>;
    var state: vec4<f32>;
    var age: f32;
    var lifetime_1: f32;
    var generation_1: f32;
    var param_10: u32;
    var param_11: u32;
    var param_12: vec3<f32>;
    var param_13: vec3<f32>;
    var param_14: f32;

    let _e47 = gl_GlobalInvocationID_1[0u];
    index_1 = _e47;
    let _e50 = unnamed.uSimulation0_[0u];
    activeCount = u32((max(_e50, 0f) + 0.5f));
    let _e54 = index_1;
    let _e55 = activeCount;
    if (_e54 >= _e55) {
        return;
    }
    let _e57 = index_1;
    base = (_e57 * 3u);
    let _e59 = base;
    let _e62 = unnamed_1.cnaParticles[_e59];
    position_1 = _e62.xyz;
    let _e64 = base;
    let _e68 = unnamed_1.cnaParticles[(_e64 + 1u)];
    velocity_1 = _e68.xyz;
    let _e70 = base;
    let _e74 = unnamed_1.cnaParticles[(_e70 + 2u)];
    state = _e74;
    let _e76 = state[0u];
    age = _e76;
    let _e78 = state[1u];
    lifetime_1 = _e78;
    let _e80 = state[3u];
    generation_1 = _e80;
    let _e83 = unnamed.uSimulation0_[1u];
    let _e84 = age;
    age = (_e84 + _e83);
    let _e86 = age;
    let _e87 = lifetime_1;
    if (_e86 >= _e87) {
        let _e89 = generation_1;
        generation_1 = (_e89 + 1f);
        let _e91 = lifetime_1;
        let _e92 = age;
        age = (_e92 - _e91);
        let _e94 = generation_1;
        let _e96 = index_1;
        param_10 = _e96;
        param_11 = u32(_e94);
        cnaSpawn_u0028_u1_u003b_u1_u003b_vf3_u003b_vf3_u003b_f1_u003b((&param_10), (&param_11), (&param_12), (&param_13), (&param_14));
        let _e97 = param_12;
        position_1 = _e97;
        let _e98 = param_13;
        velocity_1 = _e98;
        let _e99 = param_14;
        lifetime_1 = _e99;
    }
    let _e101 = unnamed.uGravity;
    let _e105 = unnamed.uSimulation0_[1u];
    let _e107 = velocity_1;
    velocity_1 = (_e107 + (_e101.xyz * _e105));
    let _e109 = velocity_1;
    let _e112 = unnamed.uSimulation1_[3u];
    let _e115 = unnamed.uSimulation0_[1u];
    let _e119 = velocity_1;
    velocity_1 = (_e119 - (_e109 * min((_e112 * _e115), 1f)));
    let _e121 = velocity_1;
    let _e124 = unnamed.uSimulation0_[1u];
    let _e126 = position_1;
    position_1 = (_e126 + (_e121 * _e124));
    let _e128 = base;
    let _e129 = position_1;
    unnamed_1.cnaParticles[_e128] = vec4<f32>(_e129.x, _e129.y, _e129.z, 0f);
    let _e136 = base;
    let _e138 = velocity_1;
    unnamed_1.cnaParticles[(_e136 + 1u)] = vec4<f32>(_e138.x, _e138.y, _e138.z, 0f);
    let _e145 = base;
    let _e147 = age;
    let _e148 = lifetime_1;
    let _e150 = state[2u];
    let _e151 = generation_1;
    unnamed_1.cnaParticles[(_e145 + 2u)] = vec4<f32>(_e147, _e148, _e150, _e151);
    return;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::string_view kDrawEsVertexSource =
    R"CNA_SHADER(#version 310 es
precision highp float;

layout(std430, binding = 7) readonly buffer CnaParticleBuffer
{
    vec4 cnaParticles[];
};

layout(location = 0) in vec3 aPos;
out vec2 vTexCoord;
out vec4 vColor;
out float vViewDepth;

uniform mat4 uParticleMatrices[2];
uniform vec3 uParticleColours[2];
uniform float uParticleScalars[11];

void main()
{
    int base = gl_InstanceID * 3;
    vec3 position = cnaParticles[base].xyz;
    vec4 state = cnaParticles[base + 2];
    float t = clamp(state.x / max(state.y, 1e-4), 0.0, 1.0);
    float size = mix(uParticleScalars[2], uParticleScalars[3], t);
    if (float(gl_InstanceID) >= uParticleScalars[4])
        size = 0.0;

    vec3 viewPosition = (uParticleMatrices[0] * vec4(position, 1.0)).xyz;
    viewPosition.xy += aPos.xy * size;
    gl_Position = uParticleMatrices[1] * vec4(viewPosition, 1.0);
    vTexCoord = aPos.xy + 0.5;
    vColor = vec4(mix(uParticleColours[0], uParticleColours[1], t),
                  mix(uParticleScalars[0], uParticleScalars[1], t));
    vViewDepth = -viewPosition.z;
}
)CNA_SHADER";

inline constexpr std::string_view kDrawEsFragmentSource =
    R"CNA_SHADER(#version 310 es
precision highp float;

in vec2 vTexCoord;
in vec4 vColor;
in float vViewDepth;
out vec4 FragColor;

uniform sampler2D texture1;
uniform sampler2D uSceneDepth;
uniform float uParticleScalars[11];

float cnaUnpackDepth(vec4 channels)
{
    const vec4 shift = vec4(1.0 / 16581375.0, 1.0 / 65025.0, 1.0 / 255.0, 1.0);
    return dot(channels, shift);
}

void main()
{
    vec4 colour = texture(texture1, vTexCoord) * vColor;
    if (uParticleScalars[5] > 0.5 && uParticleScalars[6] > 0.0)
    {
        vec2 viewportSize = max(vec2(uParticleScalars[8], uParticleScalars[9]), vec2(1.0));
        vec2 uv = gl_FragCoord.xy / viewportSize;
        vec4 depthTexel = texture(uSceneDepth, uv);
        float linearDepth = mix(depthTexel.r, cnaUnpackDepth(depthTexel),
                                clamp(uParticleScalars[10], 0.0, 1.0));
        float behind = linearDepth * uParticleScalars[7];
        colour.a *= clamp((behind - vViewDepth) / uParticleScalars[6], 0.0, 1.0);
    }
    FragColor = colour;
}
)CNA_SHADER";

inline constexpr std::string_view kDrawDesktopVertexSource =
    R"CNA_SHADER(#version 430 core

layout(std430, binding = 7) readonly buffer CnaParticleBuffer
{
    vec4 cnaParticles[];
};

layout(location = 0) in vec3 aPos;
out vec2 vTexCoord;
out vec4 vColor;
out float vViewDepth;

uniform mat4 uParticleMatrices[2];
uniform vec3 uParticleColours[2];
uniform float uParticleScalars[11];

void main()
{
    int base = gl_InstanceID * 3;
    vec3 position = cnaParticles[base].xyz;
    vec4 state = cnaParticles[base + 2];
    float t = clamp(state.x / max(state.y, 1e-4), 0.0, 1.0);
    float size = mix(uParticleScalars[2], uParticleScalars[3], t);
    if (float(gl_InstanceID) >= uParticleScalars[4])
        size = 0.0;

    vec3 viewPosition = (uParticleMatrices[0] * vec4(position, 1.0)).xyz;
    viewPosition.xy += aPos.xy * size;
    gl_Position = uParticleMatrices[1] * vec4(viewPosition, 1.0);
    vTexCoord = aPos.xy + 0.5;
    vColor = vec4(mix(uParticleColours[0], uParticleColours[1], t),
                  mix(uParticleScalars[0], uParticleScalars[1], t));
    vViewDepth = -viewPosition.z;
}
)CNA_SHADER";

inline constexpr std::string_view kDrawDesktopFragmentSource =
    R"CNA_SHADER(#version 430 core

in vec2 vTexCoord;
in vec4 vColor;
in float vViewDepth;
out vec4 FragColor;

uniform sampler2D texture1;
uniform sampler2D uSceneDepth;
uniform float uParticleScalars[11];

float cnaUnpackDepth(vec4 channels)
{
    const vec4 shift = vec4(1.0 / 16581375.0, 1.0 / 65025.0, 1.0 / 255.0, 1.0);
    return dot(channels, shift);
}

void main()
{
    vec4 colour = texture(texture1, vTexCoord) * vColor;
    if (uParticleScalars[5] > 0.5 && uParticleScalars[6] > 0.0)
    {
        vec2 viewportSize = max(vec2(uParticleScalars[8], uParticleScalars[9]), vec2(1.0));
        vec2 uv = gl_FragCoord.xy / viewportSize;
        vec4 depthTexel = texture(uSceneDepth, uv);
        float linearDepth = mix(depthTexel.r, cnaUnpackDepth(depthTexel),
                                clamp(uParticleScalars[10], 0.0, 1.0));
        float behind = linearDepth * uParticleScalars[7];
        colour.a *= clamp((behind - vViewDepth) / uParticleScalars[6], 0.0, 1.0);
    }
    FragColor = colour;
}
)CNA_SHADER";

inline constexpr std::uint32_t kDrawVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x000000a5u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x000b000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000au, 0x0000005au, 0x0000006au,
    0x00000077u, 0x0000007du, 0x00000095u, 0x00040047u, 0x0000000au, 0x0000000bu, 0x0000002bu, 0x00040047u,
    0x00000013u, 0x00000006u, 0x00000010u, 0x00030047u, 0x00000014u, 0x00000003u, 0x00040048u, 0x00000014u,
    0x00000000u, 0x00000018u, 0x00050048u, 0x00000014u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u,
    0x00000016u, 0x00000018u, 0x00040047u, 0x00000016u, 0x00000021u, 0x00000007u, 0x00040047u, 0x00000016u,
    0x00000022u, 0x00000002u, 0x00040047u, 0x00000035u, 0x00000006u, 0x00000010u, 0x00030047u, 0x00000036u,
    0x00000002u, 0x00050048u, 0x00000036u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x00000038u,
    0x00000021u, 0x0000000cu, 0x00040047u, 0x00000038u, 0x00000022u, 0x00000001u, 0x00040047u, 0x0000004bu,
    0x00000006u, 0x00000040u, 0x00030047u, 0x0000004cu, 0x00000002u, 0x00040048u, 0x0000004cu, 0x00000000u,
    0x00000005u, 0x00050048u, 0x0000004cu, 0x00000000u, 0x00000007u, 0x00000010u, 0x00050048u, 0x0000004cu,
    0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x0000004eu, 0x00000021u, 0x0000000fu, 0x00040047u,
    0x0000004eu, 0x00000022u, 0x00000001u, 0x00040047u, 0x0000005au, 0x0000001eu, 0x00000000u, 0x00030047u,
    0x00000068u, 0x00000002u, 0x00050048u, 0x00000068u, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u,
    0x00000068u, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x00000068u, 0x00000002u, 0x0000000bu,
    0x00000003u, 0x00050048u, 0x00000068u, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00040047u, 0x00000077u,
    0x0000001eu, 0x00000000u, 0x00040047u, 0x0000007du, 0x0000001eu, 0x00000001u, 0x00040047u, 0x0000007eu,
    0x00000006u, 0x00000010u, 0x00030047u, 0x0000007fu, 0x00000002u, 0x00050048u, 0x0000007fu, 0x00000000u,
    0x00000023u, 0x00000000u, 0x00040047u, 0x00000081u, 0x00000021u, 0x0000000eu, 0x00040047u, 0x00000081u,
    0x00000022u, 0x00000001u, 0x00040047u, 0x00000095u, 0x0000001eu, 0x00000002u, 0x00020013u, 0x00000002u,
    0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u, 0x00000006u, 0x00000020u, 0x00000001u, 0x00040020u,
    0x00000009u, 0x00000001u, 0x00000006u, 0x0004003bu, 0x00000009u, 0x0000000au, 0x00000001u, 0x0004002bu,
    0x00000006u, 0x0000000cu, 0x00000003u, 0x00030016u, 0x0000000eu, 0x00000020u, 0x00040017u, 0x0000000fu,
    0x0000000eu, 0x00000003u, 0x00040017u, 0x00000012u, 0x0000000eu, 0x00000004u, 0x0003001du, 0x00000013u,
    0x00000012u, 0x0003001eu, 0x00000014u, 0x00000013u, 0x00040020u, 0x00000015u, 0x00000002u, 0x00000014u,
    0x0004003bu, 0x00000015u, 0x00000016u, 0x00000002u, 0x0004002bu, 0x00000006u, 0x00000017u, 0x00000000u,
    0x00040020u, 0x00000019u, 0x00000002u, 0x00000012u, 0x0004002bu, 0x00000006u, 0x00000020u, 0x00000002u,
    0x00040015u, 0x00000026u, 0x00000020u, 0x00000000u, 0x0004002bu, 0x00000026u, 0x0000002au, 0x00000001u,
    0x0004002bu, 0x0000000eu, 0x0000002du, 0x38d1b717u, 0x0004002bu, 0x0000000eu, 0x00000030u, 0x00000000u,
    0x0004002bu, 0x0000000eu, 0x00000031u, 0x3f800000u, 0x0004002bu, 0x00000026u, 0x00000034u, 0x00000048u,
    0x0004001cu, 0x00000035u, 0x0000000eu, 0x00000034u, 0x0003001eu, 0x00000036u, 0x00000035u, 0x00040020u,
    0x00000037u, 0x00000002u, 0x00000036u, 0x0004003bu, 0x00000037u, 0x00000038u, 0x00000002u, 0x00040020u,
    0x00000039u, 0x00000002u, 0x0000000eu, 0x0004002bu, 0x00000006u, 0x00000042u, 0x00000004u, 0x00020014u,
    0x00000045u, 0x00040018u, 0x0000004au, 0x00000012u, 0x00000004u, 0x0004001cu, 0x0000004bu, 0x0000004au,
    0x00000034u, 0x0003001eu, 0x0000004cu, 0x0000004bu, 0x00040020u, 0x0000004du, 0x00000002u, 0x0000004cu,
    0x0004003bu, 0x0000004du, 0x0000004eu, 0x00000002u, 0x00040020u, 0x0000004fu, 0x00000002u, 0x0000004au,
    0x00040020u, 0x00000059u, 0x00000001u, 0x0000000fu, 0x0004003bu, 0x00000059u, 0x0000005au, 0x00000001u,
    0x00040017u, 0x0000005bu, 0x0000000eu, 0x00000002u, 0x0004001cu, 0x00000067u, 0x0000000eu, 0x0000002au,
    0x0006001eu, 0x00000068u, 0x00000012u, 0x0000000eu, 0x00000067u, 0x00000067u, 0x00040020u, 0x00000069u,
    0x00000003u, 0x00000068u, 0x0004003bu, 0x00000069u, 0x0000006au, 0x00000003u, 0x0004002bu, 0x00000006u,
    0x0000006bu, 0x00000001u, 0x00040020u, 0x00000074u, 0x00000003u, 0x00000012u, 0x00040020u, 0x00000076u,
    0x00000003u, 0x0000005bu, 0x0004003bu, 0x00000076u, 0x00000077u, 0x00000003u, 0x0004002bu, 0x0000000eu,
    0x0000007au, 0x3f000000u, 0x0004003bu, 0x00000074u, 0x0000007du, 0x00000003u, 0x0004001cu, 0x0000007eu,
    0x0000000fu, 0x00000034u, 0x0003001eu, 0x0000007fu, 0x0000007eu, 0x00040020u, 0x00000080u, 0x00000002u,
    0x0000007fu, 0x0004003bu, 0x00000080u, 0x00000081u, 0x00000002u, 0x00040020u, 0x00000082u, 0x00000002u,
    0x0000000fu, 0x00040020u, 0x00000094u, 0x00000003u, 0x0000000eu, 0x0004003bu, 0x00000094u, 0x00000095u,
    0x00000003u, 0x0005002cu, 0x0000005bu, 0x000000a2u, 0x0000007au, 0x0000007au, 0x0003002eu, 0x0000000fu,
    0x000000a3u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u,
    0x0004003du, 0x00000006u, 0x0000000bu, 0x0000000au, 0x00050084u, 0x00000006u, 0x0000000du, 0x0000000bu,
    0x0000000cu, 0x00060041u, 0x00000019u, 0x0000001au, 0x00000016u, 0x00000017u, 0x0000000du, 0x0004003du,
    0x00000012u, 0x0000001bu, 0x0000001au, 0x00050080u, 0x00000006u, 0x00000021u, 0x0000000du, 0x00000020u,
    0x00060041u, 0x00000019u, 0x00000022u, 0x00000016u, 0x00000017u, 0x00000021u, 0x0004003du, 0x00000012u,
    0x00000023u, 0x00000022u, 0x00050051u, 0x0000000eu, 0x00000029u, 0x00000023u, 0x00000000u, 0x00050051u,
    0x0000000eu, 0x0000002cu, 0x00000023u, 0x00000001u, 0x0007000cu, 0x0000000eu, 0x0000002eu, 0x00000001u,
    0x00000028u, 0x0000002cu, 0x0000002du, 0x00050088u, 0x0000000eu, 0x0000002fu, 0x00000029u, 0x0000002eu,
    0x0008000cu, 0x0000000eu, 0x00000032u, 0x00000001u, 0x0000002bu, 0x0000002fu, 0x00000030u, 0x00000031u,
    0x00060041u, 0x00000039u, 0x0000003au, 0x00000038u, 0x00000017u, 0x00000020u, 0x0004003du, 0x0000000eu,
    0x0000003bu, 0x0000003au, 0x00060041u, 0x00000039u, 0x0000003cu, 0x00000038u, 0x00000017u, 0x0000000cu,
    0x0004003du, 0x0000000eu, 0x0000003du, 0x0000003cu, 0x0008000cu, 0x0000000eu, 0x0000003fu, 0x00000001u,
    0x0000002eu, 0x0000003bu, 0x0000003du, 0x00000032u, 0x0004006fu, 0x0000000eu, 0x00000041u, 0x0000000bu,
    0x00060041u, 0x00000039u, 0x00000043u, 0x00000038u, 0x00000017u, 0x00000042u, 0x0004003du, 0x0000000eu,
    0x00000044u, 0x00000043u, 0x000500beu, 0x00000045u, 0x00000046u, 0x00000041u, 0x00000044u, 0x000600a9u,
    0x0000000eu, 0x000000a4u, 0x00000046u, 0x00000030u, 0x0000003fu, 0x00060041u, 0x0000004fu, 0x00000050u,
    0x0000004eu, 0x00000017u, 0x00000017u, 0x0004003du, 0x0000004au, 0x00000051u, 0x00000050u, 0x00050051u,
    0x0000000eu, 0x00000053u, 0x0000001bu, 0x00000000u, 0x00050051u, 0x0000000eu, 0x00000054u, 0x0000001bu,
    0x00000001u, 0x00050051u, 0x0000000eu, 0x00000055u, 0x0000001bu, 0x00000002u, 0x00070050u, 0x00000012u,
    0x00000056u, 0x00000053u, 0x00000054u, 0x00000055u, 0x00000031u, 0x00050091u, 0x00000012u, 0x00000057u,
    0x00000051u, 0x00000056u, 0x0004003du, 0x0000000fu, 0x0000005cu, 0x0000005au, 0x0007004fu, 0x0000005bu,
    0x0000005du, 0x0000005cu, 0x0000005cu, 0x00000000u, 0x00000001u, 0x0005008eu, 0x0000005bu, 0x0000005fu,
    0x0000005du, 0x000000a4u, 0x0007004fu, 0x0000005bu, 0x00000061u, 0x00000057u, 0x000000a3u, 0x00000000u,
    0x00000001u, 0x00050081u, 0x0000005bu, 0x00000062u, 0x00000061u, 0x0000005fu, 0x00050051u, 0x0000000eu,
    0x00000064u, 0x00000062u, 0x00000000u, 0x00050051u, 0x0000000eu, 0x00000066u, 0x00000062u, 0x00000001u,
    0x00060041u, 0x0000004fu, 0x0000006cu, 0x0000004eu, 0x00000017u, 0x0000006bu, 0x0004003du, 0x0000004au,
    0x0000006du, 0x0000006cu, 0x00050051u, 0x0000000eu, 0x00000071u, 0x00000057u, 0x00000002u, 0x00070050u,
    0x00000012u, 0x00000072u, 0x00000064u, 0x00000066u, 0x00000071u, 0x00000031u, 0x00050091u, 0x00000012u,
    0x00000073u, 0x0000006du, 0x00000072u, 0x00050041u, 0x00000074u, 0x00000075u, 0x0000006au, 0x00000017u,
    0x0003003eu, 0x00000075u, 0x00000073u, 0x00050081u, 0x0000005bu, 0x0000007cu, 0x0000005du, 0x000000a2u,
    0x0003003eu, 0x00000077u, 0x0000007cu, 0x00060041u, 0x00000082u, 0x00000083u, 0x00000081u, 0x00000017u,
    0x00000017u, 0x0004003du, 0x0000000fu, 0x00000084u, 0x00000083u, 0x00060041u, 0x00000082u, 0x00000085u,
    0x00000081u, 0x00000017u, 0x0000006bu, 0x0004003du, 0x0000000fu, 0x00000086u, 0x00000085u, 0x00060050u,
    0x0000000fu, 0x00000088u, 0x00000032u, 0x00000032u, 0x00000032u, 0x0008000cu, 0x0000000fu, 0x00000089u,
    0x00000001u, 0x0000002eu, 0x00000084u, 0x00000086u, 0x00000088u, 0x00060041u, 0x00000039u, 0x0000008au,
    0x00000038u, 0x00000017u, 0x00000017u, 0x0004003du, 0x0000000eu, 0x0000008bu, 0x0000008au, 0x00060041u,
    0x00000039u, 0x0000008cu, 0x00000038u, 0x00000017u, 0x0000006bu, 0x0004003du, 0x0000000eu, 0x0000008du,
    0x0000008cu, 0x0008000cu, 0x0000000eu, 0x0000008fu, 0x00000001u, 0x0000002eu, 0x0000008bu, 0x0000008du,
    0x00000032u, 0x00050051u, 0x0000000eu, 0x00000090u, 0x00000089u, 0x00000000u, 0x00050051u, 0x0000000eu,
    0x00000091u, 0x00000089u, 0x00000001u, 0x00050051u, 0x0000000eu, 0x00000092u, 0x00000089u, 0x00000002u,
    0x00070050u, 0x00000012u, 0x00000093u, 0x00000090u, 0x00000091u, 0x00000092u, 0x0000008fu, 0x0003003eu,
    0x0000007du, 0x00000093u, 0x0004007fu, 0x0000000eu, 0x00000099u, 0x00000071u, 0x0003003eu, 0x00000095u,
    0x00000099u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kDrawVulkanVertexSpirVByteSize = sizeof(kDrawVulkanVertexSpirV);

inline constexpr std::string_view kDrawVulkanVertexWgsl =
    R"CNA_SHADER(// draw.vulkan.vert.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct CnaParticleBuffer {
    cnaParticles: array<vec4<f32>>,
}

struct FloatArray {
    uParticleScalars: array<f32, 72>,
}

struct Mat4Array {
    uParticleMatrices: array<mat4x4<f32>, 72>,
}

struct gl_PerVertex {
    @builtin(position) gl_Position: vec4<f32>,
    gl_PointSize: f32,
    gl_ClipDistance: array<f32, 1>,
    gl_CullDistance: array<f32, 1>,
}

struct Vec3Array {
    uParticleColours: array<vec3<f32>, 72>,
}

struct VertexOutput {
    @builtin(position) gl_Position: vec4<f32>,
    @location(0) member: vec2<f32>,
    @location(1) member_1: vec4<f32>,
    @location(2) member_2: f32,
}

var<private> gl_InstanceIndex_1: i32;
@group(2) @binding(7) 
var<storage> unnamed: CnaParticleBuffer;
@group(1) @binding(12) 
var<storage> unnamed_1: FloatArray;
@group(1) @binding(15) 
var<uniform> unnamed_2: Mat4Array;
var<private> aPos_1: vec3<f32>;
var<private> unnamed_3: gl_PerVertex = gl_PerVertex(vec4<f32>(0f, 0f, 0f, 1f), 1f, array<f32, 1>(), array<f32, 1>());
var<private> vTexCoord: vec2<f32>;
var<private> vColor: vec4<f32>;
@group(1) @binding(14) 
var<uniform> unnamed_4: Vec3Array;
var<private> vViewDepth: f32;

fn main_1() {
    var base: i32;
    var position: vec3<f32>;
    var state: vec4<f32>;
    var t: f32;
    var size: f32;
    var viewPosition: vec3<f32>;

    let _e29 = gl_InstanceIndex_1;
    base = (_e29 * 3i);
    let _e31 = base;
    let _e34 = unnamed.cnaParticles[_e31];
    position = _e34.xyz;
    let _e36 = base;
    let _e40 = unnamed.cnaParticles[(_e36 + 2i)];
    state = _e40;
    let _e42 = state[0u];
    let _e44 = state[1u];
    t = clamp((_e42 / max(_e44, 0.0001f)), 0f, 1f);
    let _e50 = unnamed_1.uParticleScalars[2i];
    let _e53 = unnamed_1.uParticleScalars[3i];
    let _e54 = t;
    size = mix(_e50, _e53, _e54);
    let _e56 = gl_InstanceIndex_1;
    let _e60 = unnamed_1.uParticleScalars[4i];
    if (f32(_e56) >= _e60) {
        size = 0f;
    }
    let _e64 = unnamed_2.uParticleMatrices[0i];
    let _e65 = position;
    viewPosition = (_e64 * vec4<f32>(_e65.x, _e65.y, _e65.z, 1f)).xyz;
    let _e72 = aPos_1;
    let _e74 = size;
    let _e76 = viewPosition;
    let _e78 = (_e76.xy + (_e72.xy * _e74));
    viewPosition[0u] = _e78.x;
    viewPosition[1u] = _e78.y;
    let _e85 = unnamed_2.uParticleMatrices[1i];
    let _e86 = viewPosition;
    unnamed_3.gl_Position = (_e85 * vec4<f32>(_e86.x, _e86.y, _e86.z, 1f));
    let _e93 = aPos_1;
    vTexCoord = (_e93.xy + vec2(0.5f));
    let _e99 = unnamed_4.uParticleColours[0i];
    let _e102 = unnamed_4.uParticleColours[1i];
    let _e103 = t;
    let _e105 = mix(_e99, _e102, vec3(_e103));
    let _e108 = unnamed_1.uParticleScalars[0i];
    let _e111 = unnamed_1.uParticleScalars[1i];
    let _e112 = t;
    vColor = vec4<f32>(_e105.x, _e105.y, _e105.z, mix(_e108, _e111, _e112));
    let _e119 = viewPosition[2u];
    vViewDepth = -(_e119);
    return;
}

@vertex 
fn main(@builtin(instance_index) gl_InstanceIndex: u32, @location(0) aPos: vec3<f32>) -> VertexOutput {
    gl_InstanceIndex_1 = i32(gl_InstanceIndex);
    aPos_1 = aPos;
    main_1();
    let _e11 = unnamed_3.gl_Position.y;
    unnamed_3.gl_Position.y = -(_e11);
    let _e13 = unnamed_3.gl_Position;
    let _e14 = vTexCoord;
    let _e15 = vColor;
    let _e16 = vViewDepth;
    return VertexOutput(_e13, _e14, _e15, _e16);
}
)CNA_SHADER";

inline constexpr std::uint32_t kDrawVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000082u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x000a000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000001eu, 0x00000022u, 0x0000004au,
    0x00000069u, 0x00000076u, 0x00030010u, 0x00000004u, 0x00000007u, 0x00040047u, 0x0000001au, 0x00000021u,
    0x00000000u, 0x00040047u, 0x0000001au, 0x00000022u, 0x00000000u, 0x00040047u, 0x0000001eu, 0x0000001eu,
    0x00000000u, 0x00040047u, 0x00000022u, 0x0000001eu, 0x00000001u, 0x00040047u, 0x00000028u, 0x00000006u,
    0x00000010u, 0x00030047u, 0x00000029u, 0x00000002u, 0x00050048u, 0x00000029u, 0x00000000u, 0x00000023u,
    0x00000000u, 0x00040047u, 0x0000002bu, 0x00000021u, 0x0000000cu, 0x00040047u, 0x0000002bu, 0x00000022u,
    0x00000001u, 0x00040047u, 0x0000004au, 0x0000000bu, 0x0000000fu, 0x00040047u, 0x00000050u, 0x00000021u,
    0x00000001u, 0x00040047u, 0x00000050u, 0x00000022u, 0x00000001u, 0x00040047u, 0x00000069u, 0x0000001eu,
    0x00000002u, 0x00040047u, 0x00000076u, 0x0000001eu, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u,
    0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u,
    0x00000004u, 0x0004002bu, 0x00000006u, 0x0000000eu, 0x33818305u, 0x0004002bu, 0x00000006u, 0x0000000fu,
    0x37810182u, 0x0004002bu, 0x00000006u, 0x00000010u, 0x3b808081u, 0x0004002bu, 0x00000006u, 0x00000011u,
    0x3f800000u, 0x0007002cu, 0x00000007u, 0x00000012u, 0x0000000eu, 0x0000000fu, 0x00000010u, 0x00000011u,
    0x00090019u, 0x00000017u, 0x00000006u, 0x00000001u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000001u,
    0x00000000u, 0x0003001bu, 0x00000018u, 0x00000017u, 0x00040020u, 0x00000019u, 0x00000000u, 0x00000018u,
    0x0004003bu, 0x00000019u, 0x0000001au, 0x00000000u, 0x00040017u, 0x0000001cu, 0x00000006u, 0x00000002u,
    0x00040020u, 0x0000001du, 0x00000001u, 0x0000001cu, 0x0004003bu, 0x0000001du, 0x0000001eu, 0x00000001u,
    0x00040020u, 0x00000021u, 0x00000001u, 0x00000007u, 0x0004003bu, 0x00000021u, 0x00000022u, 0x00000001u,
    0x00020014u, 0x00000025u, 0x00040015u, 0x00000026u, 0x00000020u, 0x00000000u, 0x0004002bu, 0x00000026u,
    0x00000027u, 0x00000048u, 0x0004001cu, 0x00000028u, 0x00000006u, 0x00000027u, 0x0003001eu, 0x00000029u,
    0x00000028u, 0x00040020u, 0x0000002au, 0x00000002u, 0x00000029u, 0x0004003bu, 0x0000002au, 0x0000002bu,
    0x00000002u, 0x00040015u, 0x0000002cu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000002cu, 0x0000002du,
    0x00000000u, 0x0004002bu, 0x0000002cu, 0x0000002eu, 0x00000005u, 0x00040020u, 0x0000002fu, 0x00000002u,
    0x00000006u, 0x0004002bu, 0x00000006u, 0x00000032u, 0x3f000000u, 0x0004002bu, 0x0000002cu, 0x00000036u,
    0x00000006u, 0x0004002bu, 0x00000006u, 0x00000039u, 0x00000000u, 0x0004002bu, 0x0000002cu, 0x00000040u,
    0x00000008u, 0x0004002bu, 0x0000002cu, 0x00000043u, 0x00000009u, 0x0005002cu, 0x0000001cu, 0x00000047u,
    0x00000011u, 0x00000011u, 0x0004003bu, 0x00000021u, 0x0000004au, 0x00000001u, 0x0004003bu, 0x00000019u,
    0x00000050u, 0x00000000u, 0x0004002bu, 0x0000002cu, 0x0000005cu, 0x0000000au, 0x0004002bu, 0x0000002cu,
    0x00000063u, 0x00000007u, 0x00040020u, 0x00000068u, 0x00000001u, 0x00000006u, 0x0004003bu, 0x00000068u,
    0x00000069u, 0x00000001u, 0x00040020u, 0x00000075u, 0x00000003u, 0x00000007u, 0x0004003bu, 0x00000075u,
    0x00000076u, 0x00000003u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u,
    0x00000005u, 0x0004003du, 0x00000018u, 0x0000001bu, 0x0000001au, 0x0004003du, 0x0000001cu, 0x0000001fu,
    0x0000001eu, 0x00050057u, 0x00000007u, 0x00000020u, 0x0000001bu, 0x0000001fu, 0x0004003du, 0x00000007u,
    0x00000023u, 0x00000022u, 0x00050085u, 0x00000007u, 0x00000024u, 0x00000020u, 0x00000023u, 0x00060041u,
    0x0000002fu, 0x00000030u, 0x0000002bu, 0x0000002du, 0x0000002eu, 0x0004003du, 0x00000006u, 0x00000031u,
    0x00000030u, 0x000500bau, 0x00000025u, 0x00000033u, 0x00000031u, 0x00000032u, 0x000300f7u, 0x00000035u,
    0x00000000u, 0x000400fau, 0x00000033u, 0x00000034u, 0x00000035u, 0x000200f8u, 0x00000034u, 0x00060041u,
    0x0000002fu, 0x00000037u, 0x0000002bu, 0x0000002du, 0x00000036u, 0x0004003du, 0x00000006u, 0x00000038u,
    0x00000037u, 0x000500bau, 0x00000025u, 0x0000003au, 0x00000038u, 0x00000039u, 0x000200f9u, 0x00000035u,
    0x000200f8u, 0x00000035u, 0x000700f5u, 0x00000025u, 0x0000003bu, 0x00000033u, 0x00000005u, 0x0000003au,
    0x00000034u, 0x000300f7u, 0x0000003du, 0x00000000u, 0x000400fau, 0x0000003bu, 0x0000003cu, 0x0000003du,
    0x000200f8u, 0x0000003cu, 0x00060041u, 0x0000002fu, 0x00000041u, 0x0000002bu, 0x0000002du, 0x00000040u,
    0x0004003du, 0x00000006u, 0x00000042u, 0x00000041u, 0x00060041u, 0x0000002fu, 0x00000044u, 0x0000002bu,
    0x0000002du, 0x00000043u, 0x0004003du, 0x00000006u, 0x00000045u, 0x00000044u, 0x00050050u, 0x0000001cu,
    0x00000046u, 0x00000042u, 0x00000045u, 0x0007000cu, 0x0000001cu, 0x00000048u, 0x00000001u, 0x00000028u,
    0x00000046u, 0x00000047u, 0x0004003du, 0x00000007u, 0x0000004bu, 0x0000004au, 0x0007004fu, 0x0000001cu,
    0x0000004cu, 0x0000004bu, 0x0000004bu, 0x00000000u, 0x00000001u, 0x00050088u, 0x0000001cu, 0x0000004eu,
    0x0000004cu, 0x00000048u, 0x0004003du, 0x00000018u, 0x00000051u, 0x00000050u, 0x00050057u, 0x00000007u,
    0x00000053u, 0x00000051u, 0x0000004eu, 0x00050051u, 0x00000006u, 0x00000058u, 0x00000053u, 0x00000000u,
    0x00050094u, 0x00000006u, 0x0000007bu, 0x00000053u, 0x00000012u, 0x00060041u, 0x0000002fu, 0x0000005du,
    0x0000002bu, 0x0000002du, 0x0000005cu, 0x0004003du, 0x00000006u, 0x0000005eu, 0x0000005du, 0x0008000cu,
    0x00000006u, 0x0000005fu, 0x00000001u, 0x0000002bu, 0x0000005eu, 0x00000039u, 0x00000011u, 0x0008000cu,
    0x00000006u, 0x00000060u, 0x00000001u, 0x0000002eu, 0x00000058u, 0x0000007bu, 0x0000005fu, 0x00060041u,
    0x0000002fu, 0x00000064u, 0x0000002bu, 0x0000002du, 0x00000063u, 0x0004003du, 0x00000006u, 0x00000065u,
    0x00000064u, 0x00050085u, 0x00000006u, 0x00000066u, 0x00000060u, 0x00000065u, 0x0004003du, 0x00000006u,
    0x0000006au, 0x00000069u, 0x00050083u, 0x00000006u, 0x0000006bu, 0x00000066u, 0x0000006au, 0x00060041u,
    0x0000002fu, 0x0000006cu, 0x0000002bu, 0x0000002du, 0x00000036u, 0x0004003du, 0x00000006u, 0x0000006du,
    0x0000006cu, 0x00050088u, 0x00000006u, 0x0000006eu, 0x0000006bu, 0x0000006du, 0x0008000cu, 0x00000006u,
    0x0000006fu, 0x00000001u, 0x0000002bu, 0x0000006eu, 0x00000039u, 0x00000011u, 0x00050051u, 0x00000006u,
    0x00000072u, 0x00000024u, 0x00000003u, 0x00050085u, 0x00000006u, 0x00000073u, 0x00000072u, 0x0000006fu,
    0x00060052u, 0x00000007u, 0x0000007fu, 0x00000073u, 0x00000024u, 0x00000003u, 0x000200f9u, 0x0000003du,
    0x000200f8u, 0x0000003du, 0x000700f5u, 0x00000007u, 0x00000081u, 0x00000024u, 0x00000035u, 0x0000007fu,
    0x0000003cu, 0x0003003eu, 0x00000076u, 0x00000081u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kDrawVulkanFragmentSpirVByteSize = sizeof(kDrawVulkanFragmentSpirV);

inline constexpr std::string_view kDrawVulkanFragmentWgsl =
    R"CNA_SHADER(// draw.vulkan.frag.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct FloatArray {
    uParticleScalars: array<f32, 72>,
}

@group(0) @binding(0) 
var texture1_cnaTexture: texture_2d<f32>;
@group(0) @binding(32) 
var texture1_cnaSampler: sampler;
var<private> vTexCoord_1: vec2<f32>;
var<private> vColor_1: vec4<f32>;
@group(1) @binding(12) 
var<storage> unnamed: FloatArray;
var<private> gl_FragCoord_1: vec4<f32>;
@group(1) @binding(1) 
var uSceneDepth_cnaTexture: texture_2d<f32>;
@group(1) @binding(33) 
var uSceneDepth_cnaSampler: sampler;
var<private> vViewDepth_1: f32;
var<private> FragColor: vec4<f32>;

fn cnaUnpackDepth_u0028_vf4_u003b(channels: ptr<function, vec4<f32>>) -> f32 {
    let _e29 = (*channels);
    return dot(_e29, vec4<f32>(0.00000006030863f, 0.0000153787f, 0.003921569f, 1f));
}

fn main_1() {
    var colour: vec4<f32>;
    var viewportSize: vec2<f32>;
    var uv: vec2<f32>;
    var depthTexel: vec4<f32>;
    var linearDepth: f32;
    var param: vec4<f32>;
    var behind: f32;
    var phi_64_: bool;

    let _e35 = vTexCoord_1;
    let _e36 = textureSample(texture1_cnaTexture, texture1_cnaSampler, _e35);
    let _e37 = vColor_1;
    colour = (_e36 * _e37);
    let _e41 = unnamed.uParticleScalars[5i];
    let _e42 = (_e41 > 0.5f);
    phi_64_ = _e42;
    if _e42 {
        let _e45 = unnamed.uParticleScalars[6i];
        phi_64_ = (_e45 > 0f);
    }
    let _e48 = phi_64_;
    if _e48 {
        let _e51 = unnamed.uParticleScalars[8i];
        let _e54 = unnamed.uParticleScalars[9i];
        viewportSize = max(vec2<f32>(_e51, _e54), vec2<f32>(1f, 1f));
        let _e57 = gl_FragCoord_1;
        let _e59 = viewportSize;
        uv = (_e57.xy / _e59);
        let _e61 = uv;
        let _e62 = textureSample(uSceneDepth_cnaTexture, uSceneDepth_cnaSampler, _e61);
        depthTexel = _e62;
        let _e64 = depthTexel[0u];
        let _e65 = depthTexel;
        param = _e65;
        let _e66 = cnaUnpackDepth_u0028_vf4_u003b((&param));
        let _e69 = unnamed.uParticleScalars[10i];
        linearDepth = mix(_e64, _e66, clamp(_e69, 0f, 1f));
        let _e72 = linearDepth;
        let _e75 = unnamed.uParticleScalars[7i];
        behind = (_e72 * _e75);
        let _e77 = behind;
        let _e78 = vViewDepth_1;
        let _e82 = unnamed.uParticleScalars[6i];
        let _e86 = colour[3u];
        colour[3u] = (_e86 * clamp(((_e77 - _e78) / _e82), 0f, 1f));
    }
    let _e89 = colour;
    FragColor = _e89;
    return;
}

@fragment 
fn main(@location(0) vTexCoord: vec2<f32>, @location(1) vColor: vec4<f32>, @builtin(position) gl_FragCoord: vec4<f32>, @location(2) vViewDepth: f32) -> @location(0) vec4<f32> {
    vTexCoord_1 = vTexCoord;
    vColor_1 = vColor;
    gl_FragCoord_1 = gl_FragCoord;
    vViewDepth_1 = vViewDepth;
    main_1();
    let _e9 = FragColor;
    return _e9;
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 12> kPayloads = {{
    {"kSimulateEsComputeSource", "simulate.es.comp.glsl", "b81e0eb63ad074d3057c4a328ce8ccb6d2767b9462cdc1fbd588f46239b823c4", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kSimulateDesktopComputeSource", "simulate.desktop.comp.glsl", "df2d8f3cae8638072c048ddee3c52f7e6fd74ce314da4bb5b6118b58cb718cc7", "glsl", "glsl", "compute", "text", "main"},
    {"kSimulateVulkanComputeSpirV", "simulate.vulkan.comp.glsl", "48f6ef4a44dc289714ba9c868a0662f21bb1c7e733c3dc53bc596547da9fe632", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kSimulateVulkanComputeWgsl", "simulate.vulkan.comp.glsl", "48f6ef4a44dc289714ba9c868a0662f21bb1c7e733c3dc53bc596547da9fe632", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
    {"kDrawEsVertexSource", "draw.es.vert.glsl", "a42d83dcc9941e54bb3cbf9ab76019d0f3224e6515e64b49b25a2d365bd49b90", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kDrawEsFragmentSource", "draw.es.frag.glsl", "340b0ea5fcd42d2a80f9c94dea588d8006a7dc14522daaaffb3731cbc0cc9846", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kDrawDesktopVertexSource", "draw.desktop.vert.glsl", "28674a821d8f559219b02072b9c130345250a26f7d5dd3de272d829eec52044b", "glsl", "glsl", "vertex", "text", "main"},
    {"kDrawDesktopFragmentSource", "draw.desktop.frag.glsl", "5b8e745253340fd7fa3d120184458dd64e678a7765bdac7060606fb4f17f2199", "glsl", "glsl", "fragment", "text", "main"},
    {"kDrawVulkanVertexSpirV", "draw.vulkan.vert.glsl", "c1348ca26f08c855c2f2df0c31a1f14afcd0392d6919ddfe3bd08d4e0d841060", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kDrawVulkanVertexWgsl", "draw.vulkan.vert.glsl", "c1348ca26f08c855c2f2df0c31a1f14afcd0392d6919ddfe3bd08d4e0d841060", "wgsl", "vulkan-glsl", "vertex", "wgsl", "main"},
    {"kDrawVulkanFragmentSpirV", "draw.vulkan.frag.glsl", "042ce3489671bc162320beaaaa78927872f2fbf0f48794b3b0a86885cf9fb667", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
    {"kDrawVulkanFragmentWgsl", "draw.vulkan.frag.glsl", "042ce3489671bc162320beaaaa78927872f2fbf0f48794b3b0a86885cf9fb667", "wgsl", "vulkan-glsl", "fragment", "wgsl", "main"},
}};

} // namespace CNA::Graphics::detail::ParticleSystemGenerated

#endif // CNA_CNAEXT
