// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Graphics::detail::GpuInstanceCullerGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "gpu_instance_culler";
inline constexpr std::string_view kManifestSha256 = "12b8d939e20f06566928223d212ca7e3124d713bccbf492af37fc0c977056200";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";

inline constexpr std::string_view kCullEsComputeSource =
    R"CNA_SHADER(#version 310 es

layout(local_size_x = 64) in;

struct CnaInstance
{
    mat4 world;
    vec4 centre;
    vec4 extent;
};

layout(std430, binding = 0) readonly buffer CnaInstances
{
    CnaInstance cnaInstances[];
};
layout(std430, binding = 1) writeonly buffer CnaVisible
{
    mat4 cnaVisible[];
};
layout(std430, binding = 2) readonly buffer CnaPlanes
{
    vec4 cnaPlanes[];
};
layout(std430, binding = 3) buffer CnaCommand
{
    uint cnaCommand[];
};

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index >= cnaCommand[5])
        return;

    vec3 centre = cnaInstances[index].centre.xyz;
    vec3 extent = cnaInstances[index].extent.xyz;
    for (int i = 0; i < 6; ++i)
    {
        vec4 plane = cnaPlanes[i];
        // XNA frustum plane normals point outward, so even the box's nearest corner being in
        // front of a plane means the complete box is outside it.
        float radius = dot(extent, abs(plane.xyz));
        if (dot(plane.xyz, centre) + plane.w - radius > 0.0)
            return;
    }

    // InstanceCount is both the compaction atomic and the following indirect draw's live count.
    uint slot = atomicAdd(cnaCommand[1], 1u);
    cnaVisible[slot] = cnaInstances[index].world;
}
)CNA_SHADER";

inline constexpr std::string_view kCullDesktopComputeSource =
    R"CNA_SHADER(#version 430 core

layout(local_size_x = 64) in;

struct CnaInstance
{
    mat4 world;
    vec4 centre;
    vec4 extent;
};

layout(std430, binding = 0) readonly buffer CnaInstances
{
    CnaInstance cnaInstances[];
};
layout(std430, binding = 1) writeonly buffer CnaVisible
{
    mat4 cnaVisible[];
};
layout(std430, binding = 2) readonly buffer CnaPlanes
{
    vec4 cnaPlanes[];
};
layout(std430, binding = 3) buffer CnaCommand
{
    uint cnaCommand[];
};

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index >= cnaCommand[5])
        return;

    vec3 centre = cnaInstances[index].centre.xyz;
    vec3 extent = cnaInstances[index].extent.xyz;
    for (int i = 0; i < 6; ++i)
    {
        vec4 plane = cnaPlanes[i];
        // XNA frustum plane normals point outward, so even the box's nearest corner being in
        // front of a plane means the complete box is outside it.
        float radius = dot(extent, abs(plane.xyz));
        if (dot(plane.xyz, centre) + plane.w - radius > 0.0)
            return;
    }

    // InstanceCount is both the compaction atomic and the following indirect draw's live count.
    uint slot = atomicAdd(cnaCommand[1], 1u);
    cnaVisible[slot] = cnaInstances[index].world;
}
)CNA_SHADER";

inline constexpr std::uint32_t kCullVulkanComputeSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x0000007du, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000040u, 0x00000001u, 0x00000001u, 0x00040047u, 0x0000000bu, 0x0000000bu, 0x0000001cu,
    0x00040047u, 0x00000011u, 0x00000006u, 0x00000004u, 0x00030047u, 0x00000012u, 0x00000003u, 0x00050048u,
    0x00000012u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x00000014u, 0x00000021u, 0x00000003u,
    0x00040047u, 0x00000014u, 0x00000022u, 0x00000000u, 0x00040048u, 0x00000026u, 0x00000000u, 0x00000005u,
    0x00050048u, 0x00000026u, 0x00000000u, 0x00000007u, 0x00000010u, 0x00050048u, 0x00000026u, 0x00000000u,
    0x00000023u, 0x00000000u, 0x00050048u, 0x00000026u, 0x00000001u, 0x00000023u, 0x00000040u, 0x00050048u,
    0x00000026u, 0x00000002u, 0x00000023u, 0x00000050u, 0x00040047u, 0x00000027u, 0x00000006u, 0x00000060u,
    0x00030047u, 0x00000028u, 0x00000003u, 0x00040048u, 0x00000028u, 0x00000000u, 0x00000018u, 0x00050048u,
    0x00000028u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u, 0x0000002au, 0x00000018u, 0x00040047u,
    0x0000002au, 0x00000021u, 0x00000000u, 0x00040047u, 0x0000002au, 0x00000022u, 0x00000000u, 0x00040047u,
    0x00000043u, 0x00000006u, 0x00000010u, 0x00030047u, 0x00000044u, 0x00000003u, 0x00040048u, 0x00000044u,
    0x00000000u, 0x00000018u, 0x00050048u, 0x00000044u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u,
    0x00000046u, 0x00000018u, 0x00040047u, 0x00000046u, 0x00000021u, 0x00000002u, 0x00040047u, 0x00000046u,
    0x00000022u, 0x00000000u, 0x00040047u, 0x00000066u, 0x00000006u, 0x00000040u, 0x00030047u, 0x00000067u,
    0x00000003u, 0x00040048u, 0x00000067u, 0x00000000u, 0x00000005u, 0x00050048u, 0x00000067u, 0x00000000u,
    0x00000007u, 0x00000010u, 0x00040048u, 0x00000067u, 0x00000000u, 0x00000019u, 0x00050048u, 0x00000067u,
    0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u, 0x00000069u, 0x00000019u, 0x00040047u, 0x00000069u,
    0x00000021u, 0x00000001u, 0x00040047u, 0x00000069u, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000071u,
    0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u,
    0x00000006u, 0x00000020u, 0x00000000u, 0x00040017u, 0x00000009u, 0x00000006u, 0x00000003u, 0x00040020u,
    0x0000000au, 0x00000001u, 0x00000009u, 0x0004003bu, 0x0000000au, 0x0000000bu, 0x00000001u, 0x0004002bu,
    0x00000006u, 0x0000000cu, 0x00000000u, 0x00040020u, 0x0000000du, 0x00000001u, 0x00000006u, 0x0003001du,
    0x00000011u, 0x00000006u, 0x0003001eu, 0x00000012u, 0x00000011u, 0x00040020u, 0x00000013u, 0x00000002u,
    0x00000012u, 0x0004003bu, 0x00000013u, 0x00000014u, 0x00000002u, 0x00040015u, 0x00000015u, 0x00000020u,
    0x00000001u, 0x0004002bu, 0x00000015u, 0x00000016u, 0x00000000u, 0x0004002bu, 0x00000015u, 0x00000017u,
    0x00000005u, 0x00040020u, 0x00000018u, 0x00000002u, 0x00000006u, 0x00020014u, 0x0000001bu, 0x00030016u,
    0x00000020u, 0x00000020u, 0x00040017u, 0x00000021u, 0x00000020u, 0x00000003u, 0x00040017u, 0x00000024u,
    0x00000020u, 0x00000004u, 0x00040018u, 0x00000025u, 0x00000024u, 0x00000004u, 0x0005001eu, 0x00000026u,
    0x00000025u, 0x00000024u, 0x00000024u, 0x0003001du, 0x00000027u, 0x00000026u, 0x0003001eu, 0x00000028u,
    0x00000027u, 0x00040020u, 0x00000029u, 0x00000002u, 0x00000028u, 0x0004003bu, 0x00000029u, 0x0000002au,
    0x00000002u, 0x0004002bu, 0x00000015u, 0x0000002cu, 0x00000001u, 0x00040020u, 0x0000002du, 0x00000002u,
    0x00000024u, 0x0004002bu, 0x00000015u, 0x00000033u, 0x00000002u, 0x0004002bu, 0x00000015u, 0x0000003fu,
    0x00000006u, 0x0003001du, 0x00000043u, 0x00000024u, 0x0003001eu, 0x00000044u, 0x00000043u, 0x00040020u,
    0x00000045u, 0x00000002u, 0x00000044u, 0x0004003bu, 0x00000045u, 0x00000046u, 0x00000002u, 0x0004002bu,
    0x00000020u, 0x0000005bu, 0x00000000u, 0x0004002bu, 0x00000006u, 0x00000064u, 0x00000001u, 0x0003001du,
    0x00000066u, 0x00000025u, 0x0003001eu, 0x00000067u, 0x00000066u, 0x00040020u, 0x00000068u, 0x00000002u,
    0x00000067u, 0x0004003bu, 0x00000068u, 0x00000069u, 0x00000002u, 0x00040020u, 0x0000006cu, 0x00000002u,
    0x00000025u, 0x0004002bu, 0x00000006u, 0x00000070u, 0x00000040u, 0x0006002cu, 0x00000009u, 0x00000071u,
    0x00000070u, 0x00000064u, 0x00000064u, 0x0003002au, 0x0000001bu, 0x00000074u, 0x00030029u, 0x0000001bu,
    0x00000077u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u,
    0x000300f7u, 0x00000072u, 0x00000000u, 0x000300fbu, 0x0000000cu, 0x00000073u, 0x000200f8u, 0x00000073u,
    0x00050041u, 0x0000000du, 0x0000000eu, 0x0000000bu, 0x0000000cu, 0x0004003du, 0x00000006u, 0x0000000fu,
    0x0000000eu, 0x00060041u, 0x00000018u, 0x00000019u, 0x00000014u, 0x00000016u, 0x00000017u, 0x0004003du,
    0x00000006u, 0x0000001au, 0x00000019u, 0x000500aeu, 0x0000001bu, 0x0000001cu, 0x0000000fu, 0x0000001au,
    0x000300f7u, 0x0000001eu, 0x00000000u, 0x000400fau, 0x0000001cu, 0x0000001du, 0x0000001eu, 0x000200f8u,
    0x0000001du, 0x000200f9u, 0x00000072u, 0x000200f8u, 0x0000001eu, 0x00070041u, 0x0000002du, 0x0000002eu,
    0x0000002au, 0x00000016u, 0x0000000fu, 0x0000002cu, 0x0004003du, 0x00000024u, 0x0000002fu, 0x0000002eu,
    0x0008004fu, 0x00000021u, 0x00000030u, 0x0000002fu, 0x0000002fu, 0x00000000u, 0x00000001u, 0x00000002u,
    0x00070041u, 0x0000002du, 0x00000034u, 0x0000002au, 0x00000016u, 0x0000000fu, 0x00000033u, 0x0004003du,
    0x00000024u, 0x00000035u, 0x00000034u, 0x0008004fu, 0x00000021u, 0x00000036u, 0x00000035u, 0x00000035u,
    0x00000000u, 0x00000001u, 0x00000002u, 0x000200f9u, 0x00000039u, 0x000200f8u, 0x00000039u, 0x000700f5u,
    0x00000015u, 0x0000007bu, 0x00000016u, 0x0000001eu, 0x00000061u, 0x0000003cu, 0x000500b1u, 0x0000001bu,
    0x00000040u, 0x0000007bu, 0x0000003fu, 0x000400f6u, 0x0000003bu, 0x0000003cu, 0x00000000u, 0x000400fau,
    0x00000040u, 0x0000003au, 0x0000003bu, 0x000200f8u, 0x0000003au, 0x00060041u, 0x0000002du, 0x00000048u,
    0x00000046u, 0x00000016u, 0x0000007bu, 0x0004003du, 0x00000024u, 0x00000049u, 0x00000048u, 0x0008004fu,
    0x00000021u, 0x0000004eu, 0x00000049u, 0x00000049u, 0x00000000u, 0x00000001u, 0x00000002u, 0x0006000cu,
    0x00000021u, 0x0000004fu, 0x00000001u, 0x00000004u, 0x0000004eu, 0x00050094u, 0x00000020u, 0x00000050u,
    0x00000036u, 0x0000004fu, 0x00050094u, 0x00000020u, 0x00000054u, 0x0000004eu, 0x00000030u, 0x00050051u,
    0x00000020u, 0x00000057u, 0x00000049u, 0x00000003u, 0x00050081u, 0x00000020u, 0x00000058u, 0x00000054u,
    0x00000057u, 0x00050083u, 0x00000020u, 0x0000005au, 0x00000058u, 0x00000050u, 0x000500bau, 0x0000001bu,
    0x0000005cu, 0x0000005au, 0x0000005bu, 0x000300f7u, 0x0000005eu, 0x00000000u, 0x000400fau, 0x0000005cu,
    0x0000005du, 0x0000005eu, 0x000200f8u, 0x0000005du, 0x000200f9u, 0x0000003bu, 0x000200f8u, 0x0000005eu,
    0x000200f9u, 0x0000003cu, 0x000200f8u, 0x0000003cu, 0x00050080u, 0x00000015u, 0x00000061u, 0x0000007bu,
    0x0000002cu, 0x000200f9u, 0x00000039u, 0x000200f8u, 0x0000003bu, 0x000700f5u, 0x0000001bu, 0x0000007cu,
    0x00000074u, 0x00000039u, 0x00000077u, 0x0000005du, 0x000300f7u, 0x00000078u, 0x00000000u, 0x000400fau,
    0x0000007cu, 0x00000072u, 0x00000078u, 0x000200f8u, 0x00000078u, 0x00060041u, 0x00000018u, 0x00000063u,
    0x00000014u, 0x00000016u, 0x0000002cu, 0x000700eau, 0x00000006u, 0x00000065u, 0x00000063u, 0x00000064u,
    0x0000000cu, 0x00000064u, 0x00070041u, 0x0000006cu, 0x0000006du, 0x0000002au, 0x00000016u, 0x0000000fu,
    0x00000016u, 0x0004003du, 0x00000025u, 0x0000006eu, 0x0000006du, 0x00060041u, 0x0000006cu, 0x0000006fu,
    0x00000069u, 0x00000016u, 0x00000065u, 0x0003003eu, 0x0000006fu, 0x0000006eu, 0x000200f9u, 0x00000072u,
    0x000200f8u, 0x00000072u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kCullVulkanComputeSpirVByteSize = sizeof(kCullVulkanComputeSpirV);

inline constexpr std::array<PayloadProvenance, 3> kPayloads = {{
    {"kCullEsComputeSource", "cull.es.comp.glsl", "27eb923be7ccbc1539da7743028c3417cc881c4c901eb0f83dc99de96e614bef", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kCullDesktopComputeSource", "cull.desktop.comp.glsl", "ffd4179d0336610db639eadc5bb70aa4ffc7d550a060ffd8e3f54e2ca9ab251c", "glsl", "glsl", "compute", "text", "main"},
    {"kCullVulkanComputeSpirV", "cull.vulkan.comp.glsl", "f914253a3cd47dd2b0ba0ac9059ef0618065c7af55148d8e14ed45ef6a5706e5", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
}};

} // namespace CNA::Graphics::detail::GpuInstanceCullerGenerated

#endif // CNA_CNAEXT
