// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Graphics::detail::AtmosphericSkyGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "atmospheric_sky";
inline constexpr std::string_view kManifestSha256 = "95600cd717b842ab4e2669ee3b70de5e4dfe817b42c960027fe2af0adaed6220";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";

inline constexpr std::string_view kEsVertexSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

layout(location = 0) in vec2 aPos;
layout(location = 1) in vec2 aTexCoord;
layout(location = 2) in vec4 aColor;

out vec2 TexCoord;
out vec4 SpriteColor;

uniform mat4 projection;

void main()
{
    gl_Position = projection * vec4(aPos, 0.0, 1.0);
    TexCoord = aTexCoord;
    SpriteColor = aColor;
}
)CNA_SHADER";

inline constexpr std::string_view kEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

in vec2 TexCoord;
in vec4 SpriteColor;
out vec4 FragColor;

uniform sampler2D texture1;
uniform mat4 uSkyMatrices[1];
uniform vec3 uSkyVectors[1];
uniform float uSkyScalars[2];

const vec3 kRayleigh = vec3(0.0464, 0.1085, 0.2650);
const float kMiePerTurbidity = 0.021;
const float kMieG = 0.76;
const float kSkyScale = 24.0;

float cnaRayleighPhase(float cosAngle)
{
    return 0.05968310365 * (1.0 + cosAngle * cosAngle);
}

float cnaMiePhase(float cosAngle)
{
    float gg = kMieG * kMieG;
    float d = 1.0 + gg - 2.0 * kMieG * cosAngle;
    return 0.07957747155 * (1.0 - gg)
         / max(pow(max(d, 1e-4), 1.5) * (2.0 + gg), 1e-4);
}

float cnaAirMass(float upwards)
{
    float up = clamp(upwards, 0.0, 1.0);
    float zenithDegrees = degrees(acos(up));
    return 1.0
         / max(up + 0.50572 * pow(max(96.07995 - zenithDegrees, 1e-3), -1.6364), 1e-4);
}

vec3 cnaScatteringAlongPath(vec3 viewDirection, vec3 sunDirection, float turbidity,
                            float viewMass)
{
    vec3 view = normalize(viewDirection);
    vec3 toSun = -normalize(sunDirection);
    float cosAngle = dot(view, toSun);
    float sunMass = cnaAirMass(toSun.y);
    float mie = kMiePerTurbidity * max(turbidity - 1.0, 0.0);
    vec3 total = kRayleigh + vec3(mie);
    vec3 scattered = kRayleigh * cnaRayleighPhase(cosAngle)
                   + vec3(mie * cnaMiePhase(cosAngle));
    vec3 alongView = vec3(1.0) - exp(-total * viewMass);
    vec3 sunlight = exp(-total * sunMass);
    return scattered / total * alongView * sunlight * kSkyScale;
}

vec3 cnaSkyRadiance(vec3 viewDirection, vec3 sunDirection, float turbidity)
{
    return cnaScatteringAlongPath(viewDirection, sunDirection, turbidity,
                                  cnaAirMass(normalize(viewDirection).y));
}

void main()
{
    vec2 cameraUv = vec2(TexCoord.x, 1.0 - TexCoord.y);
    vec2 ndc = cameraUv * 2.0 - 1.0;
    vec4 ray = uSkyMatrices[0] * vec4(ndc, 1.0, 1.0);
    vec3 direction = normalize(ray.xyz / ray.w);
    vec3 radiance = cnaSkyRadiance(direction, uSkyVectors[0], uSkyScalars[0])
                  * uSkyScalars[1];
    FragColor = vec4(radiance, 1.0) * SpriteColor;
    FragColor.a += texture(texture1, TexCoord).a * 0.0;
}
)CNA_SHADER";

inline constexpr std::string_view kDesktopVertexSource =
    R"CNA_SHADER(#version 330 core

layout(location = 0) in vec2 aPos;
layout(location = 1) in vec2 aTexCoord;
layout(location = 2) in vec4 aColor;

out vec2 TexCoord;
out vec4 SpriteColor;

uniform mat4 projection;

void main()
{
    gl_Position = projection * vec4(aPos, 0.0, 1.0);
    TexCoord = aTexCoord;
    SpriteColor = aColor;
}
)CNA_SHADER";

inline constexpr std::string_view kDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core

in vec2 TexCoord;
in vec4 SpriteColor;
out vec4 FragColor;

uniform sampler2D texture1;
uniform mat4 uSkyMatrices[1];
uniform vec3 uSkyVectors[1];
uniform float uSkyScalars[2];

const vec3 kRayleigh = vec3(0.0464, 0.1085, 0.2650);
const float kMiePerTurbidity = 0.021;
const float kMieG = 0.76;
const float kSkyScale = 24.0;

float cnaRayleighPhase(float cosAngle)
{
    return 0.05968310365 * (1.0 + cosAngle * cosAngle);
}

float cnaMiePhase(float cosAngle)
{
    float gg = kMieG * kMieG;
    float d = 1.0 + gg - 2.0 * kMieG * cosAngle;
    return 0.07957747155 * (1.0 - gg)
         / max(pow(max(d, 1e-4), 1.5) * (2.0 + gg), 1e-4);
}

float cnaAirMass(float upwards)
{
    float up = clamp(upwards, 0.0, 1.0);
    float zenithDegrees = degrees(acos(up));
    return 1.0
         / max(up + 0.50572 * pow(max(96.07995 - zenithDegrees, 1e-3), -1.6364), 1e-4);
}

vec3 cnaScatteringAlongPath(vec3 viewDirection, vec3 sunDirection, float turbidity,
                            float viewMass)
{
    vec3 view = normalize(viewDirection);
    vec3 toSun = -normalize(sunDirection);
    float cosAngle = dot(view, toSun);
    float sunMass = cnaAirMass(toSun.y);
    float mie = kMiePerTurbidity * max(turbidity - 1.0, 0.0);
    vec3 total = kRayleigh + vec3(mie);
    vec3 scattered = kRayleigh * cnaRayleighPhase(cosAngle)
                   + vec3(mie * cnaMiePhase(cosAngle));
    vec3 alongView = vec3(1.0) - exp(-total * viewMass);
    vec3 sunlight = exp(-total * sunMass);
    return scattered / total * alongView * sunlight * kSkyScale;
}

vec3 cnaSkyRadiance(vec3 viewDirection, vec3 sunDirection, float turbidity)
{
    return cnaScatteringAlongPath(viewDirection, sunDirection, turbidity,
                                  cnaAirMass(normalize(viewDirection).y));
}

void main()
{
    vec2 cameraUv = vec2(TexCoord.x, 1.0 - TexCoord.y);
    vec2 ndc = cameraUv * 2.0 - 1.0;
    vec4 ray = uSkyMatrices[0] * vec4(ndc, 1.0, 1.0);
    vec3 direction = normalize(ray.xyz / ray.w);
    vec3 radiance = cnaSkyRadiance(direction, uSkyVectors[0], uSkyScalars[0])
                  * uSkyScalars[1];
    FragColor = vec4(radiance, 1.0) * SpriteColor;
    FragColor.a += texture(texture1, TexCoord).a * 0.0;
}
)CNA_SHADER";

inline constexpr std::uint32_t kVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000031u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x000b000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00000021u, 0x0000002au,
    0x0000002bu, 0x0000002du, 0x0000002fu, 0x00040047u, 0x0000000bu, 0x0000001eu, 0x00000000u, 0x00030047u,
    0x0000000du, 0x00000002u, 0x00050048u, 0x0000000du, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u,
    0x0000001fu, 0x00000002u, 0x00050048u, 0x0000001fu, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u,
    0x0000001fu, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x0000001fu, 0x00000002u, 0x0000000bu,
    0x00000003u, 0x00050048u, 0x0000001fu, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00040047u, 0x0000002au,
    0x0000001eu, 0x00000000u, 0x00040047u, 0x0000002bu, 0x0000001eu, 0x00000001u, 0x00040047u, 0x0000002du,
    0x0000001eu, 0x00000001u, 0x00040047u, 0x0000002fu, 0x0000001eu, 0x00000002u, 0x00020013u, 0x00000002u,
    0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u,
    0x00000006u, 0x00000002u, 0x00040020u, 0x0000000au, 0x00000001u, 0x00000007u, 0x0004003bu, 0x0000000au,
    0x0000000bu, 0x00000001u, 0x0003001eu, 0x0000000du, 0x00000007u, 0x00040020u, 0x0000000eu, 0x00000009u,
    0x0000000du, 0x0004003bu, 0x0000000eu, 0x0000000fu, 0x00000009u, 0x00040015u, 0x00000010u, 0x00000020u,
    0x00000001u, 0x0004002bu, 0x00000010u, 0x00000011u, 0x00000000u, 0x00040020u, 0x00000012u, 0x00000009u,
    0x00000007u, 0x0004002bu, 0x00000006u, 0x00000016u, 0x40000000u, 0x0004002bu, 0x00000006u, 0x00000018u,
    0x3f800000u, 0x0005002cu, 0x00000007u, 0x00000019u, 0x00000018u, 0x00000018u, 0x00040017u, 0x0000001bu,
    0x00000006u, 0x00000004u, 0x00040015u, 0x0000001cu, 0x00000020u, 0x00000000u, 0x0004002bu, 0x0000001cu,
    0x0000001du, 0x00000001u, 0x0004001cu, 0x0000001eu, 0x00000006u, 0x0000001du, 0x0006001eu, 0x0000001fu,
    0x0000001bu, 0x00000006u, 0x0000001eu, 0x0000001eu, 0x00040020u, 0x00000020u, 0x00000003u, 0x0000001fu,
    0x0004003bu, 0x00000020u, 0x00000021u, 0x00000003u, 0x0004002bu, 0x00000006u, 0x00000023u, 0x00000000u,
    0x00040020u, 0x00000027u, 0x00000003u, 0x0000001bu, 0x00040020u, 0x00000029u, 0x00000003u, 0x00000007u,
    0x0004003bu, 0x00000029u, 0x0000002au, 0x00000003u, 0x0004003bu, 0x0000000au, 0x0000002bu, 0x00000001u,
    0x0004003bu, 0x00000027u, 0x0000002du, 0x00000003u, 0x00040020u, 0x0000002eu, 0x00000001u, 0x0000001bu,
    0x0004003bu, 0x0000002eu, 0x0000002fu, 0x00000001u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u,
    0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du, 0x00000007u, 0x0000000cu, 0x0000000bu, 0x00050041u,
    0x00000012u, 0x00000013u, 0x0000000fu, 0x00000011u, 0x0004003du, 0x00000007u, 0x00000014u, 0x00000013u,
    0x00050088u, 0x00000007u, 0x00000015u, 0x0000000cu, 0x00000014u, 0x0005008eu, 0x00000007u, 0x00000017u,
    0x00000015u, 0x00000016u, 0x00050083u, 0x00000007u, 0x0000001au, 0x00000017u, 0x00000019u, 0x00050051u,
    0x00000006u, 0x00000024u, 0x0000001au, 0x00000000u, 0x00050051u, 0x00000006u, 0x00000025u, 0x0000001au,
    0x00000001u, 0x00070050u, 0x0000001bu, 0x00000026u, 0x00000024u, 0x00000025u, 0x00000023u, 0x00000018u,
    0x00050041u, 0x00000027u, 0x00000028u, 0x00000021u, 0x00000011u, 0x0003003eu, 0x00000028u, 0x00000026u,
    0x0004003du, 0x00000007u, 0x0000002cu, 0x0000002bu, 0x0003003eu, 0x0000002au, 0x0000002cu, 0x0004003du,
    0x0000001bu, 0x00000030u, 0x0000002fu, 0x0003003eu, 0x0000002du, 0x00000030u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kVulkanVertexSpirVByteSize = sizeof(kVulkanVertexSpirV);

inline constexpr std::uint32_t kVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x000001a4u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0008000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x000000b3u, 0x000000f6u, 0x000000fdu,
    0x00030010u, 0x00000004u, 0x00000007u, 0x00040047u, 0x000000b3u, 0x0000001eu, 0x00000000u, 0x00040047u,
    0x000000c6u, 0x00000006u, 0x00000040u, 0x00030047u, 0x000000c7u, 0x00000002u, 0x00040048u, 0x000000c7u,
    0x00000000u, 0x00000005u, 0x00050048u, 0x000000c7u, 0x00000000u, 0x00000007u, 0x00000010u, 0x00050048u,
    0x000000c7u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x000000c9u, 0x00000021u, 0x0000000fu,
    0x00040047u, 0x000000c9u, 0x00000022u, 0x00000001u, 0x00040047u, 0x000000deu, 0x00000006u, 0x00000010u,
    0x00030047u, 0x000000dfu, 0x00000002u, 0x00050048u, 0x000000dfu, 0x00000000u, 0x00000023u, 0x00000000u,
    0x00040047u, 0x000000e1u, 0x00000021u, 0x0000000eu, 0x00040047u, 0x000000e1u, 0x00000022u, 0x00000001u,
    0x00040047u, 0x000000e2u, 0x00000006u, 0x00000010u, 0x00030047u, 0x000000e3u, 0x00000002u, 0x00050048u,
    0x000000e3u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x000000e5u, 0x00000021u, 0x0000000cu,
    0x00040047u, 0x000000e5u, 0x00000022u, 0x00000001u, 0x00040047u, 0x000000f6u, 0x0000001eu, 0x00000000u,
    0x00040047u, 0x000000fdu, 0x0000001eu, 0x00000001u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u,
    0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000012u, 0x00000006u, 0x00000003u,
    0x0004002bu, 0x00000006u, 0x00000021u, 0x3d747645u, 0x0004002bu, 0x00000006u, 0x00000022u, 0x3f800000u,
    0x0004002bu, 0x00000006u, 0x0000002fu, 0x3fc28f5cu, 0x0004002bu, 0x00000006u, 0x00000038u, 0x38d1b717u,
    0x0004002bu, 0x00000006u, 0x0000003au, 0x3fc00000u, 0x0004002bu, 0x00000006u, 0x0000003cu, 0x40000000u,
    0x0004002bu, 0x00000006u, 0x00000046u, 0x00000000u, 0x0004002bu, 0x00000006u, 0x0000004du, 0x3f0176deu,
    0x0004002bu, 0x00000006u, 0x0000004eu, 0x42c028efu, 0x0004002bu, 0x00000006u, 0x00000051u, 0x3a83126fu,
    0x0004002bu, 0x00000006u, 0x00000053u, 0xbfd1758eu, 0x00040015u, 0x00000068u, 0x00000020u, 0x00000000u,
    0x0004002bu, 0x00000068u, 0x00000069u, 0x00000001u, 0x0004002bu, 0x00000006u, 0x0000006eu, 0x3cac0831u,
    0x0004002bu, 0x00000006u, 0x00000074u, 0x3d3e0dedu, 0x0004002bu, 0x00000006u, 0x00000075u, 0x3dde353fu,
    0x0004002bu, 0x00000006u, 0x00000076u, 0x3e87ae14u, 0x0006002cu, 0x00000012u, 0x00000077u, 0x00000074u,
    0x00000075u, 0x00000076u, 0x0006002cu, 0x00000012u, 0x00000088u, 0x00000022u, 0x00000022u, 0x00000022u,
    0x0004002bu, 0x00000006u, 0x0000009cu, 0x41c00000u, 0x00040017u, 0x000000afu, 0x00000006u, 0x00000002u,
    0x00040020u, 0x000000b2u, 0x00000001u, 0x000000afu, 0x0004003bu, 0x000000b2u, 0x000000b3u, 0x00000001u,
    0x0004002bu, 0x00000068u, 0x000000b4u, 0x00000000u, 0x00040020u, 0x000000b5u, 0x00000001u, 0x00000006u,
    0x00040017u, 0x000000c1u, 0x00000006u, 0x00000004u, 0x00040018u, 0x000000c4u, 0x000000c1u, 0x00000004u,
    0x0004002bu, 0x00000068u, 0x000000c5u, 0x00000048u, 0x0004001cu, 0x000000c6u, 0x000000c4u, 0x000000c5u,
    0x0003001eu, 0x000000c7u, 0x000000c6u, 0x00040020u, 0x000000c8u, 0x00000002u, 0x000000c7u, 0x0004003bu,
    0x000000c8u, 0x000000c9u, 0x00000002u, 0x00040015u, 0x000000cau, 0x00000020u, 0x00000001u, 0x0004002bu,
    0x000000cau, 0x000000cbu, 0x00000000u, 0x00040020u, 0x000000ccu, 0x00000002u, 0x000000c4u, 0x0004002bu,
    0x00000068u, 0x000000d7u, 0x00000003u, 0x0004001cu, 0x000000deu, 0x00000012u, 0x000000c5u, 0x0003001eu,
    0x000000dfu, 0x000000deu, 0x00040020u, 0x000000e0u, 0x00000002u, 0x000000dfu, 0x0004003bu, 0x000000e0u,
    0x000000e1u, 0x00000002u, 0x0004001cu, 0x000000e2u, 0x00000006u, 0x000000c5u, 0x0003001eu, 0x000000e3u,
    0x000000e2u, 0x00040020u, 0x000000e4u, 0x00000002u, 0x000000e3u, 0x0004003bu, 0x000000e4u, 0x000000e5u,
    0x00000002u, 0x00040020u, 0x000000e9u, 0x00000002u, 0x00000012u, 0x00040020u, 0x000000edu, 0x00000002u,
    0x00000006u, 0x0004002bu, 0x000000cau, 0x000000f1u, 0x00000001u, 0x00040020u, 0x000000f5u, 0x00000003u,
    0x000000c1u, 0x0004003bu, 0x000000f5u, 0x000000f6u, 0x00000003u, 0x00040020u, 0x000000fcu, 0x00000001u,
    0x000000c1u, 0x0004003bu, 0x000000fcu, 0x000000fdu, 0x00000001u, 0x00040020u, 0x00000109u, 0x00000003u,
    0x00000006u, 0x0005002cu, 0x000000afu, 0x0000019bu, 0x00000022u, 0x00000022u, 0x0004002bu, 0x00000006u,
    0x0000019cu, 0x3fc9eeccu, 0x0004002bu, 0x00000006u, 0x0000019eu, 0x3d09ae55u, 0x0004002bu, 0x00000006u,
    0x0000019fu, 0x4024f766u, 0x0004002bu, 0x00000006u, 0x000001a0u, 0xbd3e0dedu, 0x0004002bu, 0x00000006u,
    0x000001a1u, 0xbdde353fu, 0x0004002bu, 0x00000006u, 0x000001a2u, 0xbe87ae14u, 0x0006002cu, 0x00000012u,
    0x000001a3u, 0x000001a0u, 0x000001a1u, 0x000001a2u, 0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u,
    0x00000003u, 0x000200f8u, 0x00000005u, 0x00050041u, 0x000000b5u, 0x000000b6u, 0x000000b3u, 0x000000b4u,
    0x0004003du, 0x00000006u, 0x000000b7u, 0x000000b6u, 0x00050041u, 0x000000b5u, 0x000000b8u, 0x000000b3u,
    0x00000069u, 0x0004003du, 0x00000006u, 0x000000b9u, 0x000000b8u, 0x00050083u, 0x00000006u, 0x000000bau,
    0x00000022u, 0x000000b9u, 0x00050050u, 0x000000afu, 0x000000bbu, 0x000000b7u, 0x000000bau, 0x0005008eu,
    0x000000afu, 0x000000beu, 0x000000bbu, 0x0000003cu, 0x00050083u, 0x000000afu, 0x000000c0u, 0x000000beu,
    0x0000019bu, 0x00060041u, 0x000000ccu, 0x000000cdu, 0x000000c9u, 0x000000cbu, 0x000000cbu, 0x0004003du,
    0x000000c4u, 0x000000ceu, 0x000000cdu, 0x00050051u, 0x00000006u, 0x000000d0u, 0x000000c0u, 0x00000000u,
    0x00050051u, 0x00000006u, 0x000000d1u, 0x000000c0u, 0x00000001u, 0x00070050u, 0x000000c1u, 0x000000d2u,
    0x000000d0u, 0x000000d1u, 0x00000022u, 0x00000022u, 0x00050091u, 0x000000c1u, 0x000000d3u, 0x000000ceu,
    0x000000d2u, 0x0008004fu, 0x00000012u, 0x000000d6u, 0x000000d3u, 0x000000d3u, 0x00000000u, 0x00000001u,
    0x00000002u, 0x00050051u, 0x00000006u, 0x000000d9u, 0x000000d3u, 0x00000003u, 0x00060050u, 0x00000012u,
    0x000000dau, 0x000000d9u, 0x000000d9u, 0x000000d9u, 0x00050088u, 0x00000012u, 0x000000dbu, 0x000000d6u,
    0x000000dau, 0x0006000cu, 0x00000012u, 0x000000dcu, 0x00000001u, 0x00000045u, 0x000000dbu, 0x00060041u,
    0x000000e9u, 0x000000eau, 0x000000e1u, 0x000000cbu, 0x000000cbu, 0x0004003du, 0x00000012u, 0x000000ebu,
    0x000000eau, 0x00060041u, 0x000000edu, 0x000000eeu, 0x000000e5u, 0x000000cbu, 0x000000cbu, 0x0004003du,
    0x00000006u, 0x000000efu, 0x000000eeu, 0x0006000cu, 0x00000012u, 0x00000117u, 0x00000001u, 0x00000045u,
    0x000000dcu, 0x00050051u, 0x00000006u, 0x00000118u, 0x00000117u, 0x00000001u, 0x0008000cu, 0x00000006u,
    0x00000123u, 0x00000001u, 0x0000002bu, 0x00000118u, 0x00000046u, 0x00000022u, 0x0006000cu, 0x00000006u,
    0x00000125u, 0x00000001u, 0x00000011u, 0x00000123u, 0x0006000cu, 0x00000006u, 0x00000126u, 0x00000001u,
    0x0000000cu, 0x00000125u, 0x00050083u, 0x00000006u, 0x00000129u, 0x0000004eu, 0x00000126u, 0x0007000cu,
    0x00000006u, 0x0000012au, 0x00000001u, 0x00000028u, 0x00000129u, 0x00000051u, 0x0007000cu, 0x00000006u,
    0x0000012bu, 0x00000001u, 0x0000001au, 0x0000012au, 0x00000053u, 0x00050085u, 0x00000006u, 0x0000012cu,
    0x0000004du, 0x0000012bu, 0x00050081u, 0x00000006u, 0x0000012du, 0x00000123u, 0x0000012cu, 0x0007000cu,
    0x00000006u, 0x0000012eu, 0x00000001u, 0x00000028u, 0x0000012du, 0x00000038u, 0x00050088u, 0x00000006u,
    0x0000012fu, 0x00000022u, 0x0000012eu, 0x0006000cu, 0x00000012u, 0x00000141u, 0x00000001u, 0x00000045u,
    0x000000ebu, 0x0004007fu, 0x00000012u, 0x00000142u, 0x00000141u, 0x00050094u, 0x00000006u, 0x00000145u,
    0x00000117u, 0x00000142u, 0x00050051u, 0x00000006u, 0x00000147u, 0x00000142u, 0x00000001u, 0x0008000cu,
    0x00000006u, 0x00000171u, 0x00000001u, 0x0000002bu, 0x00000147u, 0x00000046u, 0x00000022u, 0x0006000cu,
    0x00000006u, 0x00000173u, 0x00000001u, 0x00000011u, 0x00000171u, 0x0006000cu, 0x00000006u, 0x00000174u,
    0x00000001u, 0x0000000cu, 0x00000173u, 0x00050083u, 0x00000006u, 0x00000177u, 0x0000004eu, 0x00000174u,
    0x0007000cu, 0x00000006u, 0x00000178u, 0x00000001u, 0x00000028u, 0x00000177u, 0x00000051u, 0x0007000cu,
    0x00000006u, 0x00000179u, 0x00000001u, 0x0000001au, 0x00000178u, 0x00000053u, 0x00050085u, 0x00000006u,
    0x0000017au, 0x0000004du, 0x00000179u, 0x00050081u, 0x00000006u, 0x0000017bu, 0x00000171u, 0x0000017au,
    0x0007000cu, 0x00000006u, 0x0000017cu, 0x00000001u, 0x00000028u, 0x0000017bu, 0x00000038u, 0x00050088u,
    0x00000006u, 0x0000017du, 0x00000022u, 0x0000017cu, 0x00050083u, 0x00000006u, 0x0000014au, 0x000000efu,
    0x00000022u, 0x0007000cu, 0x00000006u, 0x0000014bu, 0x00000001u, 0x00000028u, 0x0000014au, 0x00000046u,
    0x00050085u, 0x00000006u, 0x0000014cu, 0x0000006eu, 0x0000014bu, 0x00060050u, 0x00000012u, 0x0000014eu,
    0x0000014cu, 0x0000014cu, 0x0000014cu, 0x00050081u, 0x00000012u, 0x0000014fu, 0x00000077u, 0x0000014eu,
    0x00050085u, 0x00000006u, 0x00000182u, 0x00000145u, 0x00000145u, 0x00050081u, 0x00000006u, 0x00000183u,
    0x00000022u, 0x00000182u, 0x00050085u, 0x00000006u, 0x00000184u, 0x00000021u, 0x00000183u, 0x0005008eu,
    0x00000012u, 0x00000152u, 0x00000077u, 0x00000184u, 0x00050085u, 0x00000006u, 0x0000018cu, 0x0000002fu,
    0x00000145u, 0x00050083u, 0x00000006u, 0x0000018du, 0x0000019cu, 0x0000018cu, 0x0007000cu, 0x00000006u,
    0x00000192u, 0x00000001u, 0x00000028u, 0x0000018du, 0x00000038u, 0x0007000cu, 0x00000006u, 0x00000193u,
    0x00000001u, 0x0000001au, 0x00000192u, 0x0000003au, 0x00050085u, 0x00000006u, 0x00000196u, 0x00000193u,
    0x0000019fu, 0x0007000cu, 0x00000006u, 0x00000197u, 0x00000001u, 0x00000028u, 0x00000196u, 0x00000038u,
    0x00050088u, 0x00000006u, 0x00000198u, 0x0000019eu, 0x00000197u, 0x00050085u, 0x00000006u, 0x00000156u,
    0x0000014cu, 0x00000198u, 0x00060050u, 0x00000012u, 0x00000157u, 0x00000156u, 0x00000156u, 0x00000156u,
    0x00050081u, 0x00000012u, 0x00000158u, 0x00000152u, 0x00000157u, 0x00050083u, 0x00000012u, 0x0000015au,
    0x000001a3u, 0x0000014eu, 0x0005008eu, 0x00000012u, 0x0000015cu, 0x0000015au, 0x0000012fu, 0x0006000cu,
    0x00000012u, 0x0000015du, 0x00000001u, 0x0000001bu, 0x0000015cu, 0x00050083u, 0x00000012u, 0x0000015eu,
    0x00000088u, 0x0000015du, 0x0005008eu, 0x00000012u, 0x00000162u, 0x0000015au, 0x0000017du, 0x0006000cu,
    0x00000012u, 0x00000163u, 0x00000001u, 0x0000001bu, 0x00000162u, 0x00050088u, 0x00000012u, 0x00000166u,
    0x00000158u, 0x0000014fu, 0x00050085u, 0x00000012u, 0x00000168u, 0x00000166u, 0x0000015eu, 0x00050085u,
    0x00000012u, 0x0000016au, 0x00000168u, 0x00000163u, 0x0005008eu, 0x00000012u, 0x0000016bu, 0x0000016au,
    0x0000009cu, 0x00060041u, 0x000000edu, 0x000000f2u, 0x000000e5u, 0x000000cbu, 0x000000f1u, 0x0004003du,
    0x00000006u, 0x000000f3u, 0x000000f2u, 0x0005008eu, 0x00000012u, 0x000000f4u, 0x0000016bu, 0x000000f3u,
    0x00050051u, 0x00000006u, 0x000000f8u, 0x000000f4u, 0x00000000u, 0x00050051u, 0x00000006u, 0x000000f9u,
    0x000000f4u, 0x00000001u, 0x00050051u, 0x00000006u, 0x000000fau, 0x000000f4u, 0x00000002u, 0x00070050u,
    0x000000c1u, 0x000000fbu, 0x000000f8u, 0x000000f9u, 0x000000fau, 0x00000022u, 0x0004003du, 0x000000c1u,
    0x000000feu, 0x000000fdu, 0x00050085u, 0x000000c1u, 0x000000ffu, 0x000000fbu, 0x000000feu, 0x0003003eu,
    0x000000f6u, 0x000000ffu, 0x00050041u, 0x00000109u, 0x0000010au, 0x000000f6u, 0x000000d7u, 0x0004003du,
    0x00000006u, 0x0000010bu, 0x0000010au, 0x0003003eu, 0x0000010au, 0x0000010bu, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kVulkanFragmentSpirVByteSize = sizeof(kVulkanFragmentSpirV);

inline constexpr std::array<PayloadProvenance, 6> kPayloads = {{
    {"kEsVertexSource", "sky.es.vert.glsl", "8cdfb0a708dbc0ce8a5f2c4f4123a5c7be01b89c8d0d212d9e6017e0205c2fb1", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kEsFragmentSource", "sky.es.frag.glsl", "ea4004716af3807aaa8c8406358f9346179b4836fcd12bf6bf8a6f609de55c46", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kDesktopVertexSource", "sky.desktop.vert.glsl", "613b520f75f1e4c158a8986abad0f6313266b423cf9954f40e98ab683b90f498", "glsl", "glsl", "vertex", "text", "main"},
    {"kDesktopFragmentSource", "sky.desktop.frag.glsl", "04b44a73d09a9e74f4a10d107e716eb201149ee632e59620e8b6b77691c97dae", "glsl", "glsl", "fragment", "text", "main"},
    {"kVulkanVertexSpirV", "sky.vulkan.vert.glsl", "c347a0738d726e58833e35577e9a5bf70e9a213fc0129af71e57783672f912bd", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kVulkanFragmentSpirV", "sky.vulkan.frag.glsl", "f2f31bf33d1b932787c01c8711d117a41a8b50fbb24f4de04f29e0f9b4f82c3c", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
}};

} // namespace CNA::Graphics::detail::AtmosphericSkyGenerated

#endif // CNA_CNAEXT
