// SPDX-License-Identifier: MS-PL
#pragma once

// plans/plan_gltf.md GLTF-007: the L5 rung of the numerical oracle ladder (plans/plan_gltf.md §7.1) -- a
// byte-exact comparison of the vertex and index buffers CNA generates against spec-derived goldens.
//
// TEST SCOPE ONLY -- see GltfOracleEXT.hpp for the scope rules. Nothing here is CNA public API,
// CNAEXT surface, or part of CNA::Internal::GltfImport.
//
// L5 exists because every layer above it can be right while the bytes are wrong. A field written
// at the wrong offset, a stride selected wrongly, a colour packed in the wrong channel order, an
// index narrowed to the wrong width -- all of them still decode back to plausible values at L3,
// and all of them draw garbage. The comparison point is `MeshOut::vertexBytes`/`indexBytes`,
// which is exactly what the loaders hand to VertexBuffer::SetData/IndexBuffer::SetData, so no GPU
// and no renderer is involved.
//
// A difference report is only useful if it says *what* differs, not just *that* something does.
// These comparisons therefore resolve a byte offset back through the vertex stride ABI to the
// vertex number and the semantic field that owns it, so a failure reads "vertex 1, Normal +4"
// rather than "byte 40".
//
// Buffers are compared as bytes throughout. Nothing here casts a byte pointer to a wider type: a
// golden read from disk carries no alignment guarantee at all (plans/plan_gltf.md §8.4).

#include <cstdint>
#include <string>
#include <vector>

#include "GltfFixtureCorpus.hpp"

namespace CnaTest::GltfOracle
{
    /** @brief Which of a mesh part's two buffers a comparison is about. */
    enum class BufferKind
    {
        /** @brief The generated vertex buffer. */
        Vertex,
        /** @brief The generated index buffer. */
        Index,
    };

    /** @brief The specification name for a buffer kind, for diagnostics ("VB" / "IB"). */
    [[nodiscard]] const char* BufferKindName(BufferKind kind);

    /** @brief One named field within a vertex, as the stride ABI places it. */
    struct VertexField
    {
        /** @brief The field's name in CNA's own vertex-declaration vocabulary, e.g. "Normal". */
        std::string name;
        /** @brief Byte offset of the field within one vertex. */
        std::size_t offset = 0;
        /** @brief Size of the field in bytes. */
        std::size_t size = 0;
    };

    /**
     * @brief The vertex layout a stride implies (plans/plan_gltf.md §2.3, the de-facto CNA/glTF ABI).
     *
     * This is an independent statement of the same table the fixture generator carries, and a test
     * asserts the two agree — a layout table that only exists once cannot catch its own drift.
     */
    struct VertexLayout
    {
        /** @brief The stride this layout describes. */
        int stride = 0;
        /** @brief False when the stride is not one of the layouts in the ABI table. */
        bool known = false;
        /** @brief The fields, in ascending offset order. Empty when @ref known is false. */
        std::vector<VertexField> fields;
    };

    /**
     * @brief Looks up the vertex layout for a stride.
     *
     * @param stride The vertex stride in bytes.
     * @return The layout; `known` is false for a stride outside the ABI table.
     */
    [[nodiscard]] VertexLayout VertexLayoutForStrideEXT(int stride);

    /** @brief The result of comparing one generated buffer against its golden. */
    struct BufferDifference
    {
        /** @brief True when the two buffers are byte-identical. */
        bool equal = true;
        /** @brief The fixture the comparison was about. */
        std::string fixture;
        /** @brief Which buffer was compared. */
        BufferKind kind = BufferKind::Vertex;
        /** @brief Size of the golden buffer in bytes. */
        std::size_t expectedSize = 0;
        /** @brief Size of the generated buffer in bytes. */
        std::size_t actualSize = 0;
        /** @brief True when the two buffers differ in length, whatever their common prefix does. */
        bool sizeDiffers = false;
        /**
         * @brief Byte offset of the first difference.
         *
         * When only the length differs, this is the first offset past the shorter buffer.
         * Meaningless when @ref equal is true.
         */
        std::size_t offset = 0;
        /** @brief The golden byte at @ref offset, or -1 when the golden ends before it. */
        int expectedByte = -1;
        /** @brief The generated byte at @ref offset, or -1 when the generated buffer ends before it. */
        int actualByte = -1;
        /** @brief Vertex number (VB) or index number (IB) containing @ref offset, or -1. */
        long long element = -1;
        /** @brief The semantic field owning @ref offset, empty when it cannot be derived. */
        std::string field;
        /** @brief Offset of @ref offset within @ref field. */
        std::size_t fieldByteOffset = 0;
        /** @brief A complete, human-readable account of the difference. Empty when @ref equal. */
        std::string report;
    };

    /**
     * @brief Compares generated vertex bytes against a golden, byte for byte.
     *
     * @param fixture The fixture id, used only in the report.
     * @param stride The vertex stride, which resolves a byte offset to a vertex and a field.
     * @param expected The golden bytes.
     * @param actual The bytes CNA generated.
     * @return The difference, or an `equal` result.
     */
    [[nodiscard]] BufferDifference CompareVertexBytesEXT(const std::string& fixture, int stride,
                                                          const std::vector<std::uint8_t>& expected,
                                                          const std::vector<std::uint8_t>& actual);

    /**
     * @brief Compares generated index bytes against a golden, byte for byte.
     *
     * @param fixture The fixture id, used only in the report.
     * @param indexElementSize 2 for 16-bit indices, 4 for 32-bit.
     * @param expected The golden bytes.
     * @param actual The bytes CNA generated.
     * @return The difference, or an `equal` result.
     */
    [[nodiscard]] BufferDifference CompareIndexBytesEXT(const std::string& fixture,
                                                         std::size_t indexElementSize,
                                                         const std::vector<std::uint8_t>& expected,
                                                         const std::vector<std::uint8_t>& actual);

    /** @brief One mesh part's golden buffers, as the fixture's manifest declares them. */
    struct GoldenBufferPart
    {
        /** @brief The source mesh's index. */
        int mesh = -1;
        /** @brief The primitive's index within that mesh. */
        int primitive = -1;
        /** @brief The vertex stride the golden was packed at. */
        int stride = 0;
        /** @brief Number of vertices in the golden vertex buffer. */
        std::size_t vertexCount = 0;
        /** @brief Number of indices in the golden index buffer. */
        std::size_t indexCount = 0;
        /** @brief 2 for 16-bit indices, 4 for 32-bit. */
        std::size_t indexElementSize = 0;
        /** @brief The declared topology's specification name. */
        std::string topology;
        /** @brief The draw-call primitive count the index list implies for that topology. */
        std::size_t primitiveCount = 0;
        /** @brief The golden vertex bytes, read from `<id>.vb.bin`. */
        std::vector<std::uint8_t> vertexBytes;
        /** @brief The golden index bytes, read from `<id>.ib.bin`. */
        std::vector<std::uint8_t> indexBytes;
        /** @brief The layout the manifest declares, for cross-checking the C++ ABI table. */
        std::vector<VertexField> declaredFields;
    };

    /** @brief A fixture's whole L5 expectation. */
    struct GoldenBuffers
    {
        /** @brief False when the fixture's manifest has no `l5` block at all. */
        bool declared = false;
        /**
         * @brief False when the fixture deliberately has no golden.
         *
         * A primitive CNA classifies and rejects produces no buffers to compare; the manifest says
         * so, and names the tasks that will change it, rather than leaving the layer silently
         * absent.
         */
        bool supported = false;
        /** @brief Why there is no golden, when @ref supported is false. */
        std::string reason;
        /** @brief The tasks that will produce a golden, when @ref supported is false. */
        std::vector<std::string> blockedBy;
        /** @brief One entry per mesh part, in manifest order. */
        std::vector<GoldenBufferPart> parts;
        /** @brief False when a declared golden file could not be read or was the wrong size. */
        bool ok = true;
        /** @brief Why @ref ok is false. */
        std::string error;
    };

    /**
     * @brief Loads a fixture's declared golden buffers from the corpus directory.
     *
     * @param fixture The opened fixture.
     * @return Its L5 expectation; check @ref GoldenBuffers::ok before using the parts.
     */
    [[nodiscard]] GoldenBuffers LoadGoldenBuffersEXT(const LoadedFixture& fixture);
}
