#include "CNA/Internal/Backends/OpenGL1/OpenGL1GraphicsBackend.hpp"
#include <SDL3/SDL.h>
#if defined(_WIN32)
#include <windows.h>
#endif
#include <SDL3/SDL_opengl.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <stdexcept>

using namespace CNA::Internal::Backends;
namespace CNA::Internal::Backends::OpenGL1 {
namespace {
GLenum Prim(PrimitiveType p){switch(p){case PrimitiveType::TriangleList:return GL_TRIANGLES;case PrimitiveType::TriangleStrip:return GL_TRIANGLE_STRIP;case PrimitiveType::LineList:return GL_LINES;case PrimitiveType::LineStrip:return GL_LINE_STRIP;default:return GL_POINTS;}}
int VertCount(PrimitiveType p,int n){switch(p){case PrimitiveType::TriangleList:return n*3;case PrimitiveType::TriangleStrip:return n+2;case PrimitiveType::LineList:return n*2;case PrimitiveType::LineStrip:return n+1;default:return n;}}
GLenum Cmp(int v){static const GLenum a[]={GL_ALWAYS,GL_NEVER,GL_LESS,GL_LEQUAL,GL_EQUAL,GL_GEQUAL,GL_GREATER,GL_NOTEQUAL};return (v>=0&&v<8)?a[v]:GL_ALWAYS;}
GLenum BlendF(int v){static const GLenum a[]={GL_ONE,GL_ZERO,GL_SRC_COLOR,GL_ONE_MINUS_SRC_COLOR,GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA,GL_DST_COLOR,GL_ONE_MINUS_DST_COLOR,GL_DST_ALPHA,GL_ONE_MINUS_DST_ALPHA,GL_ONE,GL_ZERO,GL_SRC_ALPHA_SATURATE};return(v>=0&&v<13)?a[v]:GL_ONE;}
GLenum StencilOp(int v){static const GLenum a[]={GL_KEEP,GL_ZERO,GL_REPLACE,GL_INCR,GL_DECR,GL_INCR,GL_DECR,GL_INVERT};return(v>=0&&v<8)?a[v]:GL_KEEP;}
void Mat(const Matrix&m,float o[16]){o[0]=m.M11;o[1]=m.M12;o[2]=m.M13;o[3]=m.M14;o[4]=m.M21;o[5]=m.M22;o[6]=m.M23;o[7]=m.M24;o[8]=m.M31;o[9]=m.M32;o[10]=m.M33;o[11]=m.M34;o[12]=m.M41;o[13]=m.M42;o[14]=m.M43;o[15]=m.M44;}
void Color4(const Color&c){glColor4ub((GLubyte)c.getRProperty(),(GLubyte)c.getGProperty(),(GLubyte)c.getBProperty(),(GLubyte)c.getAProperty());}
}
void OpenGL1VertexBufferBackend::SetData(const void*d,int c,std::size_t s){if(c<0||c>capacity_)throw std::runtime_error("OPENGL1 vertex count exceeds capacity");count_=c;stride_=s;data_.resize((size_t)c*s);if(d&&!data_.empty())std::memcpy(data_.data(),d,data_.size());}
void OpenGL1IndexBufferBackend::SetData16(const void*d,int c){i32_=false;count_=c;data_.resize((size_t)c*2);if(d&&c)std::memcpy(data_.data(),d,data_.size());}
void OpenGL1IndexBufferBackend::SetData32(const void*d,int c){i32_=true;count_=c;data_.resize((size_t)c*4);if(d&&c)std::memcpy(data_.data(),d,data_.size());}
OpenGL1TextureBackend::OpenGL1TextureBackend(const ImageData&d):width_(d.width),height_(d.height){glGenTextures(1,&id_);glBindTexture(GL_TEXTURE_2D,id_);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA,width_,height_,0,GL_RGBA,GL_UNSIGNED_BYTE,d.pixels.empty()?nullptr:d.pixels.data());}
OpenGL1TextureBackend::~OpenGL1TextureBackend(){if(id_)glDeleteTextures(1,&id_);}void OpenGL1TextureBackend::BindGL()const{glBindTexture(GL_TEXTURE_2D,id_);}void OpenGL1TextureBackend::UpdatePixels(const uint8_t*p,int stride){if(!p)return;glBindTexture(GL_TEXTURE_2D,id_);glPixelStorei(GL_UNPACK_ALIGNMENT,1);if(stride==width_*4)glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width_,height_,GL_RGBA,GL_UNSIGNED_BYTE,p);else for(int y=0;y<height_;++y)glTexSubImage2D(GL_TEXTURE_2D,0,0,y,width_,1,GL_RGBA,GL_UNSIGNED_BYTE,p+y*stride);}void OpenGL1TextureBackend::UpdatePixelsLevel(int level,const uint8_t*p,int w,int h){glBindTexture(GL_TEXTURE_2D,id_);glTexImage2D(GL_TEXTURE_2D,level,GL_RGBA,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,p);}
OpenGL1GraphicsBackend::OpenGL1GraphicsBackend(const GraphicsBackendCreateArgs&a):window_(a.window),virtualWidth_(a.virtualWidth),virtualHeight_(a.virtualHeight){if(!window_)throw std::runtime_error("OPENGL1 requires SDL window");SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION,1);SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION,1);SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE,24);SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE,8);SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER,1);glContext_=SDL_GL_CreateContext(window_);if(!glContext_)throw std::runtime_error(std::string("OPENGL1 SDL_GL_CreateContext failed: ")+SDL_GetError());SDL_GL_MakeCurrent(window_,glContext_);SDL_GL_SetSwapInterval(a.swapInterval);glEnable(GL_TEXTURE_2D);glEnable(GL_DEPTH_TEST);glDepthFunc(GL_LEQUAL);glShadeModel(GL_SMOOTH);glHint(GL_PERSPECTIVE_CORRECTION_HINT,GL_NICEST);IGraphicsBackend::RegisterForWindow(window_,this);}
OpenGL1GraphicsBackend::~OpenGL1GraphicsBackend(){IGraphicsBackend::UnregisterForWindow(window_);if(glContext_)SDL_GL_DestroyContext(glContext_);}void OpenGL1GraphicsBackend::Clear(float r,float g,float b,float a){glClearColor(r,g,b,a);glClear(GL_COLOR_BUFFER_BIT);}void OpenGL1GraphicsBackend::Present(){SDL_GL_SwapWindow(window_);}void OpenGL1GraphicsBackend::GetViewportSize(int&w,int&h){SDL_GetWindowSizeInPixels(window_,&w,&h);}void OpenGL1GraphicsBackend::SetVirtualResolution(int w,int h){virtualWidth_=w;virtualHeight_=h;}void OpenGL1GraphicsBackend::SetPresentationMode(int){}
void OpenGL1GraphicsBackend::ReadBackbuffer(int x,int y,int w,int h,uint8_t*pixels){int W,H;GetViewportSize(W,H);glReadBuffer(GL_BACK);glPixelStorei(GL_PACK_ALIGNMENT,1);const int glY=H-y-h;glReadPixels(x,glY,w,h,GL_RGBA,GL_UNSIGNED_BYTE,pixels);const int rowBytes=w*4;std::vector<uint8_t>tmp(rowBytes);for(int i=0;i<h/2;++i){uint8_t*top=pixels+i*rowBytes;uint8_t*bot=pixels+(h-1-i)*rowBytes;std::copy(top,top+rowBytes,tmp.data());std::copy(bot,bot+rowBytes,top);std::copy(tmp.begin(),tmp.end(),bot);}}
std::unique_ptr<ITextureBackend>OpenGL1GraphicsBackend::CreateTexture(const ImageData&d){return std::make_unique<OpenGL1TextureBackend>(d);}std::unique_ptr<ISpriteBatchBackend>OpenGL1GraphicsBackend::CreateSpriteBatch(){return std::make_unique<OpenGL1SpriteBatchBackend>(*this);}std::unique_ptr<IVertexBufferBackend>OpenGL1GraphicsBackend::CreateVertexBuffer(int c){return std::make_unique<OpenGL1VertexBufferBackend>(c);}std::unique_ptr<IIndexBufferBackend>OpenGL1GraphicsBackend::CreateIndexBuffer16(int){return std::make_unique<OpenGL1IndexBufferBackend>(false);}std::unique_ptr<IIndexBufferBackend>OpenGL1GraphicsBackend::CreateIndexBuffer32(int){return std::make_unique<OpenGL1IndexBufferBackend>(true);}
void OpenGL1GraphicsBackend::SetDepthTestEnabled(bool e){e?glEnable(GL_DEPTH_TEST):glDisable(GL_DEPTH_TEST);}void OpenGL1GraphicsBackend::SetBlendEnabled(bool e){e?glEnable(GL_BLEND):glDisable(GL_BLEND);}void OpenGL1GraphicsBackend::SetDepthWriteEnabled(bool e){glDepthMask(e?GL_TRUE:GL_FALSE);}void OpenGL1GraphicsBackend::ClearColorAndDepth(float r,float g,float b,float a,float d){glClearColor(r,g,b,a);glClearDepth(d);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);}void OpenGL1GraphicsBackend::ClearDepth(float d){glClearDepth(d);glClear(GL_DEPTH_BUFFER_BIT);}void OpenGL1GraphicsBackend::ClearStencil(int s){glClearStencil(s);glClear(GL_STENCIL_BUFFER_BIT);}void OpenGL1GraphicsBackend::ClearDepthAndStencil(float d,int s){glClearDepth(d);glClearStencil(s);glClear(GL_DEPTH_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);}void OpenGL1GraphicsBackend::ClearColorAndStencil(float r,float g,float b,float a,int s){glClearColor(r,g,b,a);glClearStencil(s);glClear(GL_COLOR_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);}void OpenGL1GraphicsBackend::ClearColorDepthAndStencil(float r,float g,float b,float a,float d,int s){glClearColor(r,g,b,a);glClearDepth(d);glClearStencil(s);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);}
void OpenGL1GraphicsBackend::ApplyBlendState(int cs,int,int cd,int,int,int){glEnable(GL_BLEND);glBlendFunc(BlendF(cs),BlendF(cd));}void OpenGL1GraphicsBackend::ApplyDepthStencilState(bool de,bool dw,int df,bool se,int sf,int sp,int sfa,int sdf,int sm,int sw,int ref,bool,int,int,int,int){de?glEnable(GL_DEPTH_TEST):glDisable(GL_DEPTH_TEST);glDepthMask(dw);glDepthFunc(Cmp(df));se?glEnable(GL_STENCIL_TEST):glDisable(GL_STENCIL_TEST);stencilRef_=ref;glStencilFunc(Cmp(sf),ref,(GLuint)sm);glStencilMask((GLuint)sw);glStencilOp(StencilOp(sfa),StencilOp(sdf),StencilOp(sp));}
void OpenGL1GraphicsBackend::ApplyRasterizerState(int c,int f,bool sc,float db,float slope){if(c==0)glDisable(GL_CULL_FACE);else{glEnable(GL_CULL_FACE);glFrontFace(GL_CCW);glCullFace(c==1?GL_BACK:GL_FRONT);}glPolygonMode(GL_FRONT_AND_BACK,f==1?GL_LINE:GL_FILL);sc?glEnable(GL_SCISSOR_TEST):glDisable(GL_SCISSOR_TEST);if(db!=0||slope!=0){glEnable(GL_POLYGON_OFFSET_FILL);glPolygonOffset(slope,db);}else glDisable(GL_POLYGON_OFFSET_FILL);}void OpenGL1GraphicsBackend::ApplySamplerState(int,int filter,int u,int v,int){glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,filter==1?GL_NEAREST:GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,filter==1?GL_NEAREST:GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,u==0?GL_REPEAT:GL_CLAMP);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,v==0?GL_REPEAT:GL_CLAMP);}void OpenGL1GraphicsBackend::SetBlendFactor(float,float,float,float){}void OpenGL1GraphicsBackend::SetReferenceStencil(int v){stencilRef_=v;}void OpenGL1GraphicsBackend::SetScissorRect(int x,int y,int w,int h){int W,H;GetViewportSize(W,H);glScissor(x,H-y-h,w,h);}void OpenGL1GraphicsBackend::SetViewport(int x,int y,int w,int h,float mn,float mx){int W,H;GetViewportSize(W,H);glViewport(x,H-y-h,w,h);glDepthRange(mn,mx);}
void OpenGL1GraphicsBackend::SetupMatrices(const Matrix&w,const Matrix&v,const Matrix&p){float a[16];glMatrixMode(GL_PROJECTION);Mat(p,a);glLoadMatrixf(a);glMatrixMode(GL_MODELVIEW);Mat(v,a);glLoadMatrixf(a);Mat(w,a);glMultMatrixf(a);}
void OpenGL1GraphicsBackend::DrawInternal(const OpenGL1VertexBufferBackend&vb,const OpenGL1IndexBufferBackend*ib,PrimitiveType prim,int pc,const GpuDrawParams*params){const auto&s=vb.Data();const size_t st=vb.Stride();if(st<12||s.empty())return;bool tex=params&&params->texture0&&(st==20||st==24||st==32);bool normal=(st==32);if(tex){glEnable(GL_TEXTURE_2D);params->texture0->BindGL();}else glDisable(GL_TEXTURE_2D);if(params&&params->lightingEnabled&&normal){glEnable(GL_LIGHTING);glEnable(GL_LIGHT0);float amb[4]={params->ambientColor[0],params->ambientColor[1],params->ambientColor[2],1};float dif[4]={params->light0Diffuse[0],params->light0Diffuse[1],params->light0Diffuse[2],1};float pos[4]={-params->light0Dir[0],-params->light0Dir[1],-params->light0Dir[2],0};glLightModelfv(GL_LIGHT_MODEL_AMBIENT,amb);glLightfv(GL_LIGHT0,GL_DIFFUSE,dif);glLightfv(GL_LIGHT0,GL_POSITION,pos);glEnable(GL_COLOR_MATERIAL);glColorMaterial(GL_FRONT_AND_BACK,GL_AMBIENT_AND_DIFFUSE);}else glDisable(GL_LIGHTING);if(params&&params->fogEnabled){glEnable(GL_FOG);float fc[4]={params->fogColor[0],params->fogColor[1],params->fogColor[2],1};glFogi(GL_FOG_MODE,GL_LINEAR);glFogfv(GL_FOG_COLOR,fc);glFogf(GL_FOG_START,params->fogStart);glFogf(GL_FOG_END,params->fogEnd);}else glDisable(GL_FOG);if(params&&params->alphaTest[3]<0){glEnable(GL_ALPHA_TEST);glAlphaFunc(GL_GEQUAL,params->alphaTest[0]);}else glDisable(GL_ALPHA_TEST);
 auto emit=[&](uint32_t i){if(i>=(uint32_t)vb.GetVertexCount())return;const uint8_t*b=s.data()+i*st;const float*f=(const float*)b;if(st==16){const uint32_t c=*(const uint32_t*)(b+12);glColor4ub(c&255,(c>>8)&255,(c>>16)&255,(c>>24)&255);}else if(st==24){const uint32_t c=*(const uint32_t*)(b+12);glColor4ub(c&255,(c>>8)&255,(c>>16)&255,(c>>24)&255);const float*t=(const float*)(b+16);glTexCoord2f(t[0],t[1]);}else if(st==20){const float*t=(const float*)(b+12);if(params)glColor4fv(params->diffuseColor);else glColor4f(1,1,1,1);glTexCoord2f(t[0],t[1]);}else if(st==32){const float*n=(const float*)(b+12);const float*t=(const float*)(b+24);glNormal3f(n[0],n[1],n[2]);glTexCoord2f(t[0],t[1]);if(params)glColor4fv(params->diffuseColor);}else glColor4f(1,1,1,1);glVertex3f(f[0],f[1],f[2]);};
 int count=VertCount(prim,pc);glBegin(Prim(prim));if(ib){count=std::min(count,ib->GetIndexCount());for(int k=0;k<count;k++){uint32_t i=ib->IsThirtyTwoBit()?((const uint32_t*)ib->Data().data())[k]:((const uint16_t*)ib->Data().data())[k];emit(i);}}else{count=std::min(count,vb.GetVertexCount());for(int i=0;i<count;i++)emit((uint32_t)i);}glEnd();glDisable(GL_ALPHA_TEST);glDisable(GL_LIGHTING);}
void OpenGL1GraphicsBackend::DrawColoredPrimitives(const IVertexBufferBackend&v,const Matrix&w,const Matrix&vi,const Matrix&p,PrimitiveType pr,int c){SetupMatrices(w,vi,p);DrawInternal(dynamic_cast<const OpenGL1VertexBufferBackend&>(v),nullptr,pr,c,nullptr);}void OpenGL1GraphicsBackend::DrawIndexedColoredPrimitives(const IVertexBufferBackend&v,const IIndexBufferBackend&i,const Matrix&w,const Matrix&vi,const Matrix&p,PrimitiveType pr,int c){SetupMatrices(w,vi,p);DrawInternal(dynamic_cast<const OpenGL1VertexBufferBackend&>(v),&dynamic_cast<const OpenGL1IndexBufferBackend&>(i),pr,c,nullptr);}void OpenGL1GraphicsBackend::DrawPrimitivesEx(const IVertexBufferBackend&v,const Matrix&w,const Matrix&vi,const Matrix&p,PrimitiveType pr,int c,const GpuDrawParams&gp){SetupMatrices(w,vi,p);DrawInternal(dynamic_cast<const OpenGL1VertexBufferBackend&>(v),nullptr,pr,c,&gp);}void OpenGL1GraphicsBackend::DrawIndexedPrimitivesEx(const IVertexBufferBackend&v,const IIndexBufferBackend&i,const Matrix&w,const Matrix&vi,const Matrix&p,PrimitiveType pr,int c,const GpuDrawParams&gp){SetupMatrices(w,vi,p);DrawInternal(dynamic_cast<const OpenGL1VertexBufferBackend&>(v),&dynamic_cast<const OpenGL1IndexBufferBackend&>(i),pr,c,&gp);}bool OpenGL1GraphicsBackend::SupportsCapability(CNA::GraphicsCapability capability)const{
 switch(capability){
  case CNA::GraphicsCapability::ThreeD:
  case CNA::GraphicsCapability::DepthStencilBuffer:
  case CNA::GraphicsCapability::WireFrame: return true;
  case CNA::GraphicsCapability::MultiSampleAntiAliasing:
  case CNA::GraphicsCapability::MultipleRenderTargets:
  case CNA::GraphicsCapability::AnisotropicFiltering:
  case CNA::GraphicsCapability::OcclusionQuery:
  case CNA::GraphicsCapability::CustomEffects: return false;
 }
 return false;
}
void OpenGL1SpriteBatchBackend::Begin(){if(begun_)return;begun_=true;glPushAttrib(GL_ENABLE_BIT|GL_COLOR_BUFFER_BIT|GL_TEXTURE_BIT);glDisable(GL_DEPTH_TEST);glEnable(GL_TEXTURE_2D);glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);glMatrixMode(GL_PROJECTION);glPushMatrix();glLoadIdentity();glOrtho(0,owner_.VirtualWidth(),owner_.VirtualHeight(),0,-1,1);glMatrixMode(GL_MODELVIEW);glPushMatrix();float m[16];Mat(transform_,m);glLoadMatrixf(m);}void OpenGL1SpriteBatchBackend::End(){if(!begun_)return;glMatrixMode(GL_MODELVIEW);glPopMatrix();glMatrixMode(GL_PROJECTION);glPopMatrix();glPopAttrib();begun_=false;}void OpenGL1SpriteBatchBackend::Draw(const ITextureBackend&t,float x,float y){Rectangle d((int)x,(int)y,t.GetWidth(),t.GetHeight()),s(0,0,t.GetWidth(),t.GetHeight());Draw(t,d,s,Color::White);}void OpenGL1SpriteBatchBackend::Draw(const ITextureBackend&t,const Rectangle&d,const Rectangle&s,const Color&c){Draw(t,d,s,c,0,Vector2::Zero,SpriteEffects::None,0);}void OpenGL1SpriteBatchBackend::Draw(const ITextureBackend&t,const Rectangle&d,const Rectangle&s,const Color&c,float rot,const Vector2&o,SpriteEffects e,float z){if(!begun_)Begin();t.BindGL();glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,filter_==1?GL_NEAREST:GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,filter_==1?GL_NEAREST:GL_LINEAR);float u0=(float)s.X/t.GetWidth(),v0=(float)s.Y/t.GetHeight(),u1=(float)(s.X+s.Width)/t.GetWidth(),v1=(float)(s.Y+s.Height)/t.GetHeight();if((int)e&1)std::swap(u0,u1);if((int)e&2)std::swap(v0,v1);
glPushMatrix();glTranslatef((float)d.X,(float)d.Y,z);glRotatef(rot*57.2957795f,0,0,1);glTranslatef(-o.X,-o.Y,0);Color4(c);glBegin(GL_QUADS);glTexCoord2f(u0,v0);glVertex2f(0,0);glTexCoord2f(u1,v0);glVertex2f((float)d.Width,0);glTexCoord2f(u1,v1);glVertex2f((float)d.Width,(float)d.Height);glTexCoord2f(u0,v1);glVertex2f(0,(float)d.Height);glEnd();glPopMatrix();}
}
#ifdef CNA_BACKEND_OPENGL1
namespace CNA::Internal::Backends {std::unique_ptr<IGraphicsBackend>CreateGraphicsBackend(const GraphicsBackendCreateArgs&args){return std::make_unique<OpenGL1::OpenGL1GraphicsBackend>(args);}}
#endif
