# SPDX-License-Identifier: MS-PL
"""Texture fixtures -- owning group ``textures`` (plan_gltf.md §24.2).

The corpus had **no textured asset at all** until `GLTF-190`, which is why every texture-shaped
task -- the sampler wiring, the base-colour/occlusion selection, the UV-set choice, the
dual-texture stride's golden bytes -- had a unit test for its arithmetic and no fixture proving a
real file arrives with it applied. These are that fixture set.

The image itself is generated by ``png.py``: an asymmetric reference texture whose four quadrants
carry four different colours *and* four different numerals, so a V flip, a UV-set swap and a 180°
rotation are each individually visible. See that module's own documentation for why a plain
checkerboard cannot serve.

Specification: §3.9 ``materials``, §5.28 ``texture``, §5.29 ``sampler``, §5.16 ``image``.
"""

from __future__ import annotations

import math
import struct

from ..builder import TRIANGLES, UNSIGNED_SHORT, GltfBuilder
from ..manifest import Fixture, l3_primitive, world_positions
from ..png import reference_texture

_SPEC = ["materials", "texture", "sampler", "image"]

#: A quad, so every quadrant of the reference texture is actually sampled by some triangle. Two
#: triangles, four vertices, UVs covering the whole [0,1] square.
_QUAD_POSITIONS = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (1.0, 1.0, 0.0)]
_QUAD_NORMALS = [(0.0, 0.0, 1.0)] * 4
#: V increases downward in both glTF and XNA (`docs/gltf-conventions.md`), so (0,0) is the image's
#: TOP-left -- quadrant 1. A V flip sends it to quadrant 3, which is a different colour AND a
#: different numeral.
_QUAD_TEXCOORDS = [(0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (1.0, 1.0)]
_QUAD_INDICES = [0, 1, 2, 2, 1, 3]
#: An authored tangent basis. The quad is in the XY plane with U along +X, so +X with a +1
#: handedness is the basis its own UVs imply -- authored rather than left to generation, because
#: what these fixtures are about is textures, and a generated basis is CNA's own algorithm rather
#: than anything the specification prescribes (`GLTF-178`).
_QUAD_TANGENTS = [(1.0, 0.0, 0.0, 1.0)] * 4

#: glTF's own enum values, spelled out so a fixture reads as the specification does.
_NEAREST = 9728
_LINEAR = 9729
_CLAMP_TO_EDGE = 33071
_MIRRORED_REPEAT = 33648


def _quad(builder: GltfBuilder, material: int, mesh_name: str) -> int:
    """Adds the shared textured quad as mesh ``mesh_name`` and returns its mesh index."""
    position = builder.add_packed_accessor(usage="POSITION", values=_QUAD_POSITIONS,
                                           accessor_type="VEC3", with_bounds=True)
    normal = builder.add_packed_accessor(usage="NORMAL", values=_QUAD_NORMALS,
                                         accessor_type="VEC3")
    tangent = builder.add_packed_accessor(usage="TANGENT", values=_QUAD_TANGENTS,
                                          accessor_type="VEC4")
    texcoord = builder.add_packed_accessor(usage="TEXCOORD_0", values=_QUAD_TEXCOORDS,
                                           accessor_type="VEC2")
    indices = builder.add_packed_accessor(usage="indices", values=_QUAD_INDICES,
                                          accessor_type="SCALAR", component_type=UNSIGNED_SHORT)
    return builder.add_mesh([{
        "attributes": {"POSITION": position, "NORMAL": normal, "TANGENT": tangent,
                       "TEXCOORD_0": texcoord},
        "indices": indices,
        "material": material,
        "mode": TRIANGLES,
    }], name=mesh_name)


def _expected_material(index: int, name: str, *, base_color: bool = False,
                       occlusion: bool = False, model: str | None = None) -> dict:
    """The L3 material record for the fixtures below, with every field the comparison reads."""
    record = {
        "index": index,
        "name": name,
        "baseColorFactor": [1.0, 1.0, 1.0, 1.0],
        "metallicFactor": 1.0,
        "roughnessFactor": 1.0,
        "emissiveFactor": [0.0, 0.0, 0.0],
        "alphaMode": "OPAQUE",
        "alphaCutoff": 0.5,
        "doubleSided": False,
        "hasBaseColorTexture": base_color,
        "hasNormalTexture": False,
        "hasMetallicRoughnessTexture": False,
        "hasOcclusionTexture": occlusion,
        "hasEmissiveTexture": False,
    }
    if model is not None:
        record["model"] = model
    return record


def tex_reference_checkerboard() -> Fixture:
    """`GLTF-190`'s reference texture, on a quad that samples all four of its quadrants.

    The asset every later UV fixture is meant to build on: a base-colour texture with a declared
    sampler, so the sampler mapping (`GLTF-202`/`GLTF-203`) has a real file behind it rather than
    only a unit test over raw enum values, and so a V flip is detectable at **L3** -- from the
    decoded UVs -- rather than only in a rendered image.
    """
    b = GltfBuilder("tex-reference-checkerboard")
    image = b.add_image(reference_texture(), name="Reference")
    sampler = b.add_sampler({"magFilter": _NEAREST, "minFilter": _NEAREST,
                             "wrapS": _CLAMP_TO_EDGE, "wrapT": _CLAMP_TO_EDGE})
    texture = b.add_texture(source=image, sampler=sampler, name="ReferenceTexture")
    material = b.add_material({
        "name": "Textured",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": texture}},
    })
    mesh = _quad(b, material, "TexturedQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id="tex-reference-checkerboard", audit_fixture=None, owning_group="textures",
        description="A quad carrying the asymmetric reference texture as its base colour, with a "
                    "NEAREST/CLAMP_TO_EDGE sampler. The four quadrants differ in both colour and "
                    "numeral, so a V flip, a UV-set swap and a 180-degree rotation are each "
                    "individually visible rather than producing a plausible image.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["base-colour texture", "image data: URI", "sampler NEAREST", "CLAMP_TO_EDGE"],
        spec_anchors=_SPEC,
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="TexturedQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "Textured", base_color=True))]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


def tex_dual_texture_stride() -> Fixture:
    """The one texture combination that changes the vertex stride -- `GLTF-149`'s last gap.

    Stride 20 is `DualTextureEffect`'s layout (Position + TextureCoordinate, no normal at all), and
    it is selected only by a **non-PBR** material carrying *both* a base-colour and an occlusion
    map. Every other textured material lands on the stride its material model already chose, which
    is why this was the last of the seven strides with no golden bytes: it needs two textures and a
    material model, and the corpus had no texture at all.

    The two images are deliberately different -- the reference texture and a flat mid-grey -- so a
    swap of the two slots is visible in the golden's own bytes rather than only on screen.
    """
    b = GltfBuilder("tex-dual-texture-stride")
    base_image = b.add_image(reference_texture(), name="BaseColor")
    occlusion_image = b.add_image(_flat_png(), name="Occlusion")
    base_texture = b.add_texture(source=base_image, name="BaseColorTexture")
    occlusion_texture = b.add_texture(source=occlusion_image, name="OcclusionTexture")
    material = b.add_material({
        "name": "UnlitDual",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": base_texture}},
        "occlusionTexture": {"index": occlusion_texture},
        "extensions": {"KHR_materials_unlit": {}},
    })
    b.declare_extensions(used=["KHR_materials_unlit"])
    mesh = _quad(b, material, "DualTexturedQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id="tex-dual-texture-stride", audit_fixture=None, owning_group="textures",
        description="A non-PBR material with both a base-colour and an occlusion texture, which "
                    "selects DualTextureEffect's stride-20 layout -- the only stride a texture "
                    "combination decides, and the last of the seven with no golden bytes.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["base-colour texture", "occlusion texture", "KHR_materials_unlit",
                  "vertex stride 20"],
        spec_anchors=_SPEC,
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="DualTexturedQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "UnlitDual", base_color=True, occlusion=True,
                                        model="unlit"),
            dropped_attributes=["normals", "tangents"],
            dropped_reason="DualTextureEffect's stride-20 layout is Position + TextureCoordinate "
                           "and has no normal or tangent slot at all, so both authored streams are "
                           "discarded at import and the primitive cannot be lit "
                           "(GLTF-086/GLTF-241, documented limits reported by both loaders).")]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


def _flat_png() -> bytes:
    """A 4x4 mid-grey image, as the second texture of the dual-texture fixture.

    Flat on purpose: what that fixture is about is which SLOT each image lands in, and a second
    asymmetric image would make a slot swap harder to read rather than easier.
    """
    from ..png import encode_png
    row = [(128, 128, 128, 255)] * 4
    return encode_png(4, 4, [row] * 4)


#: `tex-texture-transform`'s authored transform. Every term is non-neutral and no two are equal, so
#: a swapped offset pair, a swapped scale pair, or a rotation applied in the wrong order each
#: produce different UVs. The rotation is a quarter turn, whose sine and cosine are exact.
_TRANSFORM_OFFSET = (0.125, 0.375)
_TRANSFORM_SCALE = (2.0, 0.5)
_TRANSFORM_ROTATION = math.pi / 2.0


def _f32(value: float) -> float:
    """Rounds ``value`` to IEEE-754 binary32, the precision the importer works in."""
    return struct.unpack("<f", struct.pack("<f", value))[0]


def _baked_uv(u: float, v: float) -> tuple[float, float]:
    """The specification's own KHR_texture_transform composition: scale, then rotate, then offset.

    Stated here from the extension's formula rather than read back from CNA, so a wrong order is a
    mismatch against the specification rather than against a second reading of the same code. Order
    is the whole risk: rotate-then-scale is a different matrix, and with a square scale it would be
    indistinguishable -- which is why the scale here is 2 by 0.5.

    Evaluated in **binary32**, term by term, in the importer's own association order. That is not
    pedantry: the L5 goldens are byte-exact, and no non-zero rotation has an exactly representable
    sine and cosine in single precision -- ``cosf(pi/2)`` is about -4.4e-8, not 0. Computing this
    in Python's doubles and rounding once at the end disagrees with the importer in the last few
    bits, which a byte comparison reports as a failure of the transform rather than of the oracle.
    """
    ox, oy = (_f32(c) for c in _TRANSFORM_OFFSET)
    sx, sy = (_f32(c) for c in _TRANSFORM_SCALE)
    cos_r = _f32(math.cos(_f32(_TRANSFORM_ROTATION)))
    sin_r = _f32(math.sin(_f32(_TRANSFORM_ROTATION)))
    u, v = _f32(u), _f32(v)
    # cosR * u * sx - sinR * v * sy + ox, left-associated exactly as the C++ expression is.
    out_u = _f32(_f32(_f32(_f32(_f32(cos_r * u) * sx) - _f32(_f32(sin_r * v) * sy)) + ox))
    out_v = _f32(_f32(_f32(_f32(_f32(sin_r * u) * sx) + _f32(_f32(cos_r * v) * sy)) + oy))
    return (out_u, out_v)


def tex_texture_transform() -> Fixture:
    """A base-colour texture carrying `KHR_texture_transform`. Owns the extension's corpus witness.

    CNA **claims** this extension -- a file listing it in ``extensionsRequired`` loads -- and until
    this fixture existed every test of it used a scratch document. That is a real gap rather than a
    bookkeeping one: a claim is a promise to accept files that cannot work without the extension,
    and the committed corpus is where such a promise is meant to be kept. `GLTF-335`'s rule now
    fails the build if any claimed extension lacks a fixture, and this is the one that was missing.

    The transform is applied by **baking it into the decoded UVs** at import (`GLTF-336`), because
    `PbrEffect` has a single shared UV channel and no per-map transform matrix. So the expectation
    lives at L2/L3 -- the decoded texture coordinates -- rather than in an effect parameter, and
    the manifest states both the authored UVs and the baked ones so the transform is visible as a
    difference rather than as a single set of numbers that could be either.
    """
    b = GltfBuilder("tex-texture-transform")
    image = b.add_image(reference_texture(), name="Reference")
    texture = b.add_texture(source=image, name="TransformedTexture")
    material = b.add_material({
        "name": "Transformed",
        "pbrMetallicRoughness": {"baseColorTexture": {
            "index": texture,
            "extensions": {"KHR_texture_transform": {
                "offset": list(_TRANSFORM_OFFSET),
                "rotation": _TRANSFORM_ROTATION,
                "scale": list(_TRANSFORM_SCALE),
            }},
        }},
    })
    b.declare_extensions(used=["KHR_texture_transform"])
    mesh = _quad(b, material, "TransformedQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)

    baked = [_baked_uv(u, v) for u, v in _QUAD_TEXCOORDS]
    l4 = world_positions(b, {mesh: list(_QUAD_POSITIONS)})
    l4["textureTransform"] = {
        "offset": list(_TRANSFORM_OFFSET),
        "rotation": _TRANSFORM_ROTATION,
        "scale": list(_TRANSFORM_SCALE),
        "authoredTexcoords": [list(uv) for uv in _QUAD_TEXCOORDS],
        "bakedTexcoords": [list(uv) for uv in baked],
        "compositionRule": "scale, then rotate, then offset -- the extension's own order. "
                           "Rotate-then-scale is a different matrix, and with a square scale the "
                           "two would be indistinguishable, which is why the scale is 2 by 0.5.",
        "bakingRule": "Applied by baking into the decoded UVs at import, because PbrEffect has one "
                      "shared UV channel and no per-map transform matrix (GLTF-336). The "
                      "expectation therefore lives in the texture coordinates, not in an effect "
                      "parameter.",
        "claimRule": "CNA claims this extension, so a file listing it in extensionsRequired loads. "
                     "Until this fixture existed the claim was tested only on scratch documents -- "
                     "GLTF-335's rule now fails if any claimed extension has no corpus witness.",
    }
    return Fixture(
        id="tex-texture-transform", audit_fixture=None, owning_group="textures",
        description="A quad whose base-colour texture declares KHR_texture_transform with a "
                    "non-neutral offset, a quarter-turn rotation and a non-square scale. The "
                    "corpus witness for an extension CNA claims: the transform is baked into the "
                    "decoded UVs, and the manifest states both the authored and the baked ones.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["KHR_texture_transform", "offset", "rotation", "non-square scale",
                  "transform baked into UVs"],
        spec_anchors=_SPEC + ["texture-transform"],
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="TransformedQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=baked, indices=_QUAD_INDICES,
            material=_expected_material(material, "Transformed", base_color=True))]},
        l4=l4,
    )


FIXTURES = [tex_reference_checkerboard, tex_texture_transform, tex_dual_texture_stride]
