# SPDX-License-Identifier: MS-PL
"""Texture fixtures -- owning group ``textures`` (plans/plan_gltf.md §24.2).

The corpus had **no textured asset at all** until `GLTF-190`, which is why every texture-shaped
task -- the sampler wiring, the base-colour/occlusion selection, the UV-set choice, the
dual-texture stride's golden bytes -- had a unit test for its arithmetic and no fixture proving a
real file arrives with it applied. These are that fixture set.

The image itself is generated by ``png.py``: an asymmetric reference texture whose four quadrants
carry four different colours *and* four different numerals, so a V flip, a UV-set swap and a 180°
rotation are each individually visible. See that module's own documentation for why a plain
checkerboard cannot serve.

Specification: §3.9 ``materials``, §5.28 ``texture``, §5.29 ``sampler``, §5.16 ``image``.
"""

from __future__ import annotations

import math

from ..builder import TRIANGLES, UNSIGNED_SHORT, GltfBuilder
from ..manifest import Fixture, l3_primitive, world_positions
from ..png import reference_texture

_SPEC = ["materials", "texture", "sampler", "image"]

#: A quad, so every quadrant of the reference texture is actually sampled by some triangle. Two
#: triangles, four vertices, UVs covering the whole [0,1] square.
_QUAD_POSITIONS = [(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (1.0, 1.0, 0.0)]
_QUAD_NORMALS = [(0.0, 0.0, 1.0)] * 4
#: V increases downward in both glTF and XNA (`docs/gltf-conventions.md`), so (0,0) is the image's
#: TOP-left -- quadrant 1. A V flip sends it to quadrant 3, which is a different colour AND a
#: different numeral.
_QUAD_TEXCOORDS = [(0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (1.0, 1.0)]
#: A second set whose values are disjoint from TEXCOORD_0 at every vertex. A reader hard-wired to
#: set zero therefore produces four wrong pairs rather than accidentally agreeing at a corner.
_QUAD_TEXCOORDS_1 = [(0.125, 0.25), (0.875, 0.125), (0.25, 0.875), (0.75, 0.625)]
#: Coordinates outside [0,1] on both axes. The fractional offsets and unequal upper bounds make
#: CLAMP, REPEAT and MIRRORED_REPEAT three distinct sampling patterns at every edge.
_OUT_OF_RANGE_TEXCOORDS = [(-0.25, -0.5), (1.25, -0.5), (-0.25, 1.75), (1.25, 1.75)]
_QUAD_INDICES = [0, 1, 2, 2, 1, 3]
#: An authored tangent basis. The quad is in the XY plane with U along +X, so +X with a +1
#: handedness is the basis its own UVs imply -- authored rather than left to generation, because
#: what these fixtures are about is textures, and a generated basis is CNA's own algorithm rather
#: than anything the specification prescribes (`GLTF-178`).
_QUAD_TANGENTS = [(1.0, 0.0, 0.0, 1.0)] * 4

#: glTF's own enum values, spelled out so a fixture reads as the specification does.
_NEAREST = 9728
_LINEAR = 9729
_LINEAR_MIPMAP_LINEAR = 9987
_REPEAT = 10497
_CLAMP_TO_EDGE = 33071
_MIRRORED_REPEAT = 33648


def _quad(builder: GltfBuilder, material: int, mesh_name: str, *,
          texcoords: list[tuple[float, float]] = _QUAD_TEXCOORDS,
          texcoords1: list[tuple[float, float]] | None = None) -> int:
    """Adds the shared textured quad as mesh ``mesh_name`` and returns its mesh index."""
    position = builder.add_packed_accessor(usage="POSITION", values=_QUAD_POSITIONS,
                                           accessor_type="VEC3", with_bounds=True)
    normal = builder.add_packed_accessor(usage="NORMAL", values=_QUAD_NORMALS,
                                         accessor_type="VEC3")
    tangent = builder.add_packed_accessor(usage="TANGENT", values=_QUAD_TANGENTS,
                                          accessor_type="VEC4")
    texcoord = builder.add_packed_accessor(usage="TEXCOORD_0", values=texcoords,
                                           accessor_type="VEC2")
    attributes = {"POSITION": position, "NORMAL": normal, "TANGENT": tangent,
                  "TEXCOORD_0": texcoord}
    if texcoords1 is not None:
        attributes["TEXCOORD_1"] = builder.add_packed_accessor(
            usage="TEXCOORD_1", values=texcoords1, accessor_type="VEC2")
    indices = builder.add_packed_accessor(usage="indices", values=_QUAD_INDICES,
                                          accessor_type="SCALAR", component_type=UNSIGNED_SHORT)
    return builder.add_mesh([{
        "attributes": attributes,
        "indices": indices,
        "material": material,
        "mode": TRIANGLES,
    }], name=mesh_name)


def _expected_material(index: int, name: str, *, base_color: bool = False,
                       normal: bool = False, occlusion: bool = False,
                       model: str | None = None) -> dict:
    """The L3 material record for the fixtures below, with every field the comparison reads."""
    record = {
        "index": index,
        "name": name,
        "baseColorFactor": [1.0, 1.0, 1.0, 1.0],
        "metallicFactor": 1.0,
        "roughnessFactor": 1.0,
        "emissiveFactor": [0.0, 0.0, 0.0],
        "alphaMode": "OPAQUE",
        "alphaCutoff": 0.5,
        "doubleSided": False,
        "hasBaseColorTexture": base_color,
        "hasNormalTexture": normal,
        "hasMetallicRoughnessTexture": False,
        "hasOcclusionTexture": occlusion,
        "hasEmissiveTexture": False,
    }
    if model is not None:
        record["model"] = model
    return record


def tex_reference_checkerboard() -> Fixture:
    """`GLTF-190`'s reference texture, on a quad that samples all four of its quadrants.

    The asset every later UV fixture is meant to build on: a base-colour texture with a declared
    sampler, so the sampler mapping (`GLTF-202`/`GLTF-203`) has a real file behind it rather than
    only a unit test over raw enum values, and so a V flip is detectable at **L3** -- from the
    decoded UVs -- rather than only in a rendered image.
    """
    b = GltfBuilder("tex-reference-checkerboard")
    image = b.add_image(reference_texture(), name="Reference")
    sampler = b.add_sampler({"magFilter": _NEAREST, "minFilter": _NEAREST,
                             "wrapS": _CLAMP_TO_EDGE, "wrapT": _CLAMP_TO_EDGE})
    texture = b.add_texture(source=image, sampler=sampler, name="ReferenceTexture")
    material = b.add_material({
        "name": "Textured",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": texture}},
    })
    mesh = _quad(b, material, "TexturedQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id="tex-reference-checkerboard", audit_fixture=None, owning_group="textures",
        description="A quad carrying the asymmetric reference texture as its base colour, with a "
                    "NEAREST/CLAMP_TO_EDGE sampler. The four quadrants differ in both colour and "
                    "numeral, so a V flip, a UV-set swap and a 180-degree rotation are each "
                    "individually visible rather than producing a plausible image.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["base-colour texture", "image data: URI", "sampler NEAREST", "CLAMP_TO_EDGE"],
        spec_anchors=_SPEC,
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="TexturedQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "Textured", base_color=True))]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


def uv1_material() -> Fixture:
    """Two material maps simultaneously selecting disjoint TEXCOORD_0/1 streams."""
    b = GltfBuilder("uv1-material")
    image = b.add_image(reference_texture(), name="Reference")
    texture = b.add_texture(source=image, name="Uv1Texture")
    material = b.add_material({
        "name": "Uv1Material",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": texture, "texCoord": 1}},
        "emissiveTexture": {"index": texture, "texCoord": 0},
        "emissiveFactor": [0.35, 0.2, 0.1],
    })
    mesh = _quad(b, material, "Uv1Quad", texcoords=_QUAD_TEXCOORDS,
                 texcoords1=_QUAD_TEXCOORDS_1)
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id="uv1-material", audit_fixture=None, owning_group="textures",
        description="A textured quad with disjoint TEXCOORD_0 and TEXCOORD_1 streams. Its "
                    "base-colour map selects authored set 1 while its emissive map simultaneously "
                    "selects set 0, requiring both packed GPU UV channels and per-map selectors.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["TEXCOORD_0", "TEXCOORD_1", "baseColorTexture.texCoord 1",
                  "emissiveTexture.texCoord 0", "simultaneous dual UV channels"],
        spec_anchors=_SPEC + ["texture-coordinate"],
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="Uv1Quad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS_1, texcoords1=_QUAD_TEXCOORDS,
            indices=_QUAD_INDICES,
            material={**_expected_material(material, "Uv1Material", base_color=True),
                      "emissiveFactor": [0.35, 0.2, 0.1],
                      "hasEmissiveTexture": True})]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


def _single_sampler_fixture(*, fixture_id: str, description: str,
                            texcoords: list[tuple[float, float]], sampler_fields: dict,
                            sampler_features: list[str]) -> Fixture:
    """Builds one base-colour quad whose sampler is the fixture's distinguishing state."""
    b = GltfBuilder(fixture_id)
    image = b.add_image(reference_texture(), name="Reference")
    sampler = b.add_sampler(sampler_fields)
    texture = b.add_texture(source=image, sampler=sampler, name="SampledTexture")
    material = b.add_material({
        "name": "SampledMaterial",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": texture}},
    })
    mesh = _quad(b, material, "SampledQuad", texcoords=texcoords)
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id=fixture_id, audit_fixture=None, owning_group="textures", description=description,
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["base-colour texture"] + sampler_features,
        spec_anchors=_SPEC,
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="SampledQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=texcoords, indices=_QUAD_INDICES,
            material=_expected_material(material, "SampledMaterial", base_color=True))]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


def uv_out_of_range_clamp() -> Fixture:
    """Out-of-range UVs paired with CLAMP_TO_EDGE on both axes (`GLTF-189`)."""
    return _single_sampler_fixture(
        fixture_id="uv-out-of-range-clamp",
        description="A quad with U and V outside [0,1] and a CLAMP_TO_EDGE sampler. It shares "
                    "geometry and image with the repeat and mirror controls, so only address mode "
                    "can explain a different edge sample.",
        texcoords=_OUT_OF_RANGE_TEXCOORDS,
        sampler_fields={"magFilter": _LINEAR, "minFilter": _LINEAR_MIPMAP_LINEAR,
                        "wrapS": _CLAMP_TO_EDGE, "wrapT": _CLAMP_TO_EDGE},
        sampler_features=["out-of-range UV", "CLAMP_TO_EDGE"],
    )


def uv_out_of_range_wrap() -> Fixture:
    """Out-of-range UVs paired with REPEAT on both axes (`GLTF-189`)."""
    return _single_sampler_fixture(
        fixture_id="uv-out-of-range-wrap",
        description="The clamp fixture's byte-identical geometry and image with REPEAT instead. "
                    "Both axes cross both boundaries, so a mapper that applies wrapS to V as well "
                    "cannot hide behind coordinates that never leave the unit square.",
        texcoords=_OUT_OF_RANGE_TEXCOORDS,
        sampler_fields={"magFilter": _LINEAR, "minFilter": _LINEAR_MIPMAP_LINEAR,
                        "wrapS": _REPEAT, "wrapT": _REPEAT},
        sampler_features=["out-of-range UV", "REPEAT"],
    )


def uv_out_of_range_mirror() -> Fixture:
    """Out-of-range UVs paired with MIRRORED_REPEAT on both axes (`GLTF-189`)."""
    return _single_sampler_fixture(
        fixture_id="uv-out-of-range-mirror",
        description="The clamp/repeat control geometry with MIRRORED_REPEAT. Fractional negative "
                    "coordinates and coordinates beyond one make mirroring differ from both "
                    "ordinary repeat and clamping on each axis.",
        texcoords=_OUT_OF_RANGE_TEXCOORDS,
        sampler_fields={"magFilter": _LINEAR, "minFilter": _LINEAR_MIPMAP_LINEAR,
                        "wrapS": _MIRRORED_REPEAT, "wrapT": _MIRRORED_REPEAT},
        sampler_features=["out-of-range UV", "MIRRORED_REPEAT"],
    )


def sampler_trilinear() -> Fixture:
    """A real-file witness for LINEAR_MIPMAP_LINEAR rather than only the raw-enum unit table."""
    return _single_sampler_fixture(
        fixture_id="sampler-trilinear",
        description="A textured quad declaring LINEAR magnification and LINEAR_MIPMAP_LINEAR "
                    "minification. The sampler must arrive as XNA Linear rather than the point or "
                    "mixed filters used by the neighbouring mapping-table rows.",
        texcoords=_QUAD_TEXCOORDS,
        sampler_fields={"magFilter": _LINEAR, "minFilter": _LINEAR_MIPMAP_LINEAR,
                        "wrapS": _REPEAT, "wrapT": _REPEAT},
        sampler_features=["LINEAR", "LINEAR_MIPMAP_LINEAR", "trilinear filtering"],
    )


def tex_dual_texture_stride() -> Fixture:
    """The one texture combination that changes the vertex stride -- `GLTF-149`'s last gap.

    Stride 20 is `DualTextureEffect`'s layout (Position + TextureCoordinate, no normal at all), and
    it is selected only by a **non-PBR** material carrying *both* a base-colour and an occlusion
    map. Every other textured material lands on the stride its material model already chose, which
    is why this was the last of the seven strides with no golden bytes: it needs two textures and a
    material model, and the corpus had no texture at all.

    The two images are deliberately different -- the reference texture and a flat mid-grey -- so a
    swap of the two slots is visible in the golden's own bytes rather than only on screen.
    """
    b = GltfBuilder("tex-dual-texture-stride")
    base_image = b.add_image(reference_texture(), name="BaseColor")
    occlusion_image = b.add_image(_flat_png(), name="Occlusion")
    base_texture = b.add_texture(source=base_image, name="BaseColorTexture")
    occlusion_texture = b.add_texture(source=occlusion_image, name="OcclusionTexture")
    material = b.add_material({
        "name": "UnlitDual",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": base_texture}},
        "occlusionTexture": {"index": occlusion_texture},
        "extensions": {"KHR_materials_unlit": {}},
    })
    b.declare_extensions(used=["KHR_materials_unlit"])
    mesh = _quad(b, material, "DualTexturedQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id="tex-dual-texture-stride", audit_fixture=None, owning_group="textures",
        description="A non-PBR material with both a base-colour and an occlusion texture, which "
                    "selects DualTextureEffect's stride-20 layout -- the only stride a texture "
                    "combination decides, and the last of the seven with no golden bytes.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["base-colour texture", "occlusion texture", "KHR_materials_unlit",
                  "vertex stride 20"],
        spec_anchors=_SPEC,
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="DualTexturedQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "UnlitDual", base_color=True, occlusion=True,
                                        model="unlit"),
            dropped_attributes=["normals", "tangents"],
            dropped_reason="DualTextureEffect's stride-20 layout is Position + TextureCoordinate "
                           "and has no normal or tangent slot at all, so both authored streams are "
                           "discarded at import and the primitive cannot be lit "
                           "(GLTF-086/GLTF-241, documented limits reported by both loaders).")]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


def _flat_png() -> bytes:
    """A 4x4 mid-grey image, as the second texture of the dual-texture fixture.

    Flat on purpose: what that fixture is about is which SLOT each image lands in, and a second
    asymmetric image would make a slot swap harder to read rather than easier.
    """
    from ..png import encode_png
    row = [(128, 128, 128, 255)] * 4
    return encode_png(4, 4, [row] * 4)


def _normal_quadrant_png() -> bytes:
    """An 8x8 normal map whose quadrants make a transform swap visible at L7.

    The per-map-transform fixture samples its bottom-right quadrant through the normal map's own
    transform, but its bottom-left quadrant if the base-colour transform is incorrectly reused.
    Those encode +Z and +X respectively, which separate a front light into a bright and a nearly
    dark fragment. The remaining directions keep any other rearrangement visibly non-neutral too.
    """
    from ..png import encode_png
    directions = (
        (128, 255, 128, 255),  # top-left: +Y
        (0, 128, 128, 255),    # top-right: -X
        (255, 128, 128, 255),  # bottom-left: +X (wrong shared-transform sample)
        (128, 128, 255, 255),  # bottom-right: +Z (correct normal-transform sample)
    )
    rows = []
    for y in range(8):
        rows.append([directions[(0 if y < 4 else 2) + (0 if x < 4 else 1)]
                     for x in range(8)])
    return encode_png(8, 8, rows)


#: `tex-texture-transform`'s authored transform. Every term is non-neutral and no two are equal, so
#: a swapped offset pair, a swapped scale pair, or a rotation applied in the wrong order each
#: produce different UVs. The rotation is a quarter turn, whose sine and cosine are exact.
_TRANSFORM_OFFSET = (0.125, 0.375)
_TRANSFORM_SCALE = (2.0, 0.5)
_TRANSFORM_ROTATION = math.pi / 2.0


def tex_texture_transform() -> Fixture:
    """A base-colour texture carrying `KHR_texture_transform`. Owns the extension's corpus witness.

    CNA **claims** this extension -- a file listing it in ``extensionsRequired`` loads -- and until
    this fixture existed every test of it used a scratch document. That is a real gap rather than a
    bookkeeping one: a claim is a promise to accept files that cannot work without the extension,
    and the committed corpus is where such a promise is meant to be kept. `GLTF-335`'s rule now
    fails the build if any claimed extension lacks a fixture, and this is the one that was missing.

    `GLTF-184` retains the transform as per-map effect state. L3/L5 therefore keep the authored UVs
    byte-exact, while L4 states the independently transported offset/rotation/scale and L6/L7 own
    the GPU affine conversion and visible sample.
    """
    b = GltfBuilder("tex-texture-transform")
    image = b.add_image(reference_texture(), name="Reference")
    texture = b.add_texture(source=image, name="TransformedTexture")
    material = b.add_material({
        "name": "Transformed",
        "pbrMetallicRoughness": {"baseColorTexture": {
            "index": texture,
            "extensions": {"KHR_texture_transform": {
                "offset": list(_TRANSFORM_OFFSET),
                "rotation": _TRANSFORM_ROTATION,
                "scale": list(_TRANSFORM_SCALE),
            }},
        }},
    })
    b.declare_extensions(used=["KHR_texture_transform"])
    mesh = _quad(b, material, "TransformedQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)

    l4 = world_positions(b, {mesh: list(_QUAD_POSITIONS)})
    l4["textureTransform"] = {
        "offset": list(_TRANSFORM_OFFSET),
        "rotation": _TRANSFORM_ROTATION,
        "scale": list(_TRANSFORM_SCALE),
        "authoredTexcoords": [list(uv) for uv in _QUAD_TEXCOORDS],
        "compositionRule": "scale, then rotate, then offset -- the extension's own order. "
                           "Rotate-then-scale is a different matrix, and with a square scale the "
                           "two would be indistinguishable, which is why the scale is 2 by 0.5.",
        "transportRule": "The decoded vertex UV remains authored. PbrEffect carries this map's "
                         "transform independently and converts it to affine GPU rows, so maps "
                         "sharing a coordinate stream need not share a transform (GLTF-184).",
        "claimRule": "CNA claims this extension, so a file listing it in extensionsRequired loads. "
                     "Until this fixture existed the claim was tested only on scratch documents -- "
                     "GLTF-335's rule now fails if any claimed extension has no corpus witness.",
    }
    return Fixture(
        id="tex-texture-transform", audit_fixture=None, owning_group="textures",
        description="A quad whose base-colour texture declares KHR_texture_transform with a "
                    "non-neutral offset, a quarter-turn rotation and a non-square scale. The "
                    "corpus witness for an extension CNA claims: authored UVs stay byte-exact and "
                    "the transform travels as independent per-map shader state.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["KHR_texture_transform", "offset", "rotation", "non-square scale",
                  "per-map shader transform"],
        spec_anchors=_SPEC + ["texture-transform"],
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="TransformedQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "Transformed", base_color=True))]},
        l4=l4,
    )


def texture_transform_per_map() -> Fixture:
    """Base colour and normal maps with deliberately different texture transforms.

    The two maps share one authored UV stream but cannot share one transformed stream. This is the
    discriminating `GLTF-184` witness for independent effect/GPU/shader state.
    """
    b = GltfBuilder("texture-transform-per-map")
    base_image = b.add_image(reference_texture(), name="BaseColor")
    normal_image = b.add_image(_normal_quadrant_png(), name="Normal")
    base_texture = b.add_texture(source=base_image, name="BaseColorTexture")
    normal_texture = b.add_texture(source=normal_image, name="NormalTexture")
    normal_transform = {
        "offset": [0.625, 0.25],
        "rotation": -math.pi / 4.0,
        "scale": [0.75, 1.5],
    }
    material = b.add_material({
        "name": "PerMapTransforms",
        "pbrMetallicRoughness": {"baseColorTexture": {
            "index": base_texture,
            "extensions": {"KHR_texture_transform": {
                "offset": list(_TRANSFORM_OFFSET),
                "rotation": _TRANSFORM_ROTATION,
                "scale": list(_TRANSFORM_SCALE),
            }},
        }},
        "normalTexture": {
            "index": normal_texture,
            "extensions": {"KHR_texture_transform": normal_transform},
        },
    })
    b.declare_extensions(used=["KHR_texture_transform"])
    mesh = _quad(b, material, "PerMapTransformQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)

    l4 = world_positions(b, {mesh: list(_QUAD_POSITIONS)})
    l4["textureTransforms"] = {
        "transport": "independent shader-side state for each map; authored UVs remain unchanged",
        "baseColor": {
            "offset": list(_TRANSFORM_OFFSET),
            "rotation": _TRANSFORM_ROTATION,
            "scale": list(_TRANSFORM_SCALE),
        },
        "normal": normal_transform,
        "reason": "One shared UV stream cannot contain two transformed values at once. Each map "
                  "therefore applies its own affine transform after selecting that stream.",
    }
    return Fixture(
        id="texture-transform-per-map", audit_fixture=None, owning_group="textures",
        description="A base-colour map and normal map selecting the same UV set but declaring "
                    "different KHR_texture_transform values. Both remain independent shader-side "
                    "state while the shared authored UV bytes remain unchanged.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["KHR_texture_transform", "per-map transforms", "base-colour texture",
                  "normal texture", "shared UV with independent transforms"],
        spec_anchors=_SPEC + ["texture-transform"],
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="PerMapTransformQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "PerMapTransforms", base_color=True,
                                        normal=True))]},
        l4=l4,
    )


def texture_shared_two_samplers() -> Fixture:
    """Two textures share one image but retain independent sampler objects and material slots."""
    b = GltfBuilder("texture-shared-two-samplers")
    image = b.add_image(reference_texture(), name="SharedImage")
    base_sampler = b.add_sampler({
        "magFilter": _NEAREST,
        "minFilter": _NEAREST,
        "wrapS": _CLAMP_TO_EDGE,
        "wrapT": _CLAMP_TO_EDGE,
    })
    normal_sampler = b.add_sampler({
        "magFilter": _LINEAR,
        "minFilter": _LINEAR_MIPMAP_LINEAR,
        "wrapS": _MIRRORED_REPEAT,
        "wrapT": _REPEAT,
    })
    base_texture = b.add_texture(source=image, sampler=base_sampler, name="BaseFromShared")
    normal_texture = b.add_texture(source=image, sampler=normal_sampler, name="NormalFromShared")
    material = b.add_material({
        "name": "SharedImageTwoSamplers",
        "pbrMetallicRoughness": {"baseColorTexture": {"index": base_texture}},
        "normalTexture": {"index": normal_texture},
    })
    mesh = _quad(b, material, "SharedSamplerQuad")
    node = b.add_node(name="MeshNode", mesh=mesh)
    b.add_scene([node], name="Scene")
    b.set_default_scene(0)
    return Fixture(
        id="texture-shared-two-samplers", audit_fixture=None, owning_group="textures",
        description="One image is referenced by two textures: Point/Clamp for base colour and "
                    "Linear/Mirror-U/Wrap-V for the normal map. Caching by image must not collapse "
                    "the texture-owned sampler state into one shared value.",
        builder=b, validated_layers=["L1", "L2", "L3", "L4", "L5"],
        features=["shared image", "two textures", "two samplers", "per-slot sampler state",
                  "independent U/V addressing"],
        spec_anchors=_SPEC,
        l3={"primitives": [l3_primitive(
            mesh=mesh, mesh_name="SharedSamplerQuad", primitive=0, mode=TRIANGLES,
            positions=_QUAD_POSITIONS, normals=_QUAD_NORMALS, tangents=_QUAD_TANGENTS,
            texcoords=_QUAD_TEXCOORDS, indices=_QUAD_INDICES,
            material=_expected_material(material, "SharedImageTwoSamplers", base_color=True,
                                        normal=True))]},
        l4=world_positions(b, {mesh: list(_QUAD_POSITIONS)}),
    )


FIXTURES = [
    tex_reference_checkerboard,
    uv1_material,
    uv_out_of_range_clamp,
    uv_out_of_range_wrap,
    uv_out_of_range_mirror,
    sampler_trilinear,
    tex_texture_transform,
    texture_transform_per_map,
    texture_shared_two_samplers,
    tex_dual_texture_stride,
]
