// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Examples::ComputeParticlesGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "compute_particles_example";
inline constexpr std::string_view kManifestSha256 = "ac6d1cb2430049a8bdd2c1533beffed06c3ec12900f14b26d9272708865565b8";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kIntegratorEsComputeSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

layout(local_size_x = 64) in;
struct Particle { vec4 position; vec4 velocity; };
layout(std430, binding = 0) buffer Particles { Particle particles[]; };
layout(std140, binding = 1) uniform IntegratorParameters { vec4 uIntegrator; };

void main()
{
    uint index = gl_GlobalInvocationID.x;
    uint count = uint(max(uIntegrator.x, 0.0) + 0.5);
    if (index >= count)
        return;
    float step = uIntegrator.y;
    vec3 velocity = particles[index].velocity.xyz + vec3(0.0, -9.81, 0.0) * step;
    vec3 position = particles[index].position.xyz + velocity * step;
    if (position.y < 0.0)
    {
        position.y = -position.y;
        velocity.y = -velocity.y * 0.5;
    }
    particles[index].position = vec4(position, particles[index].position.w);
    particles[index].velocity = vec4(velocity, 0.0);
}
)CNA_SHADER";

inline constexpr std::string_view kIntegratorDesktopComputeSource =
    R"CNA_SHADER(#version 430 core

layout(local_size_x = 64) in;
struct Particle { vec4 position; vec4 velocity; };
layout(std430, binding = 0) buffer Particles { Particle particles[]; };
layout(std140, binding = 1) uniform IntegratorParameters { vec4 uIntegrator; };

void main()
{
    uint index = gl_GlobalInvocationID.x;
    uint count = uint(max(uIntegrator.x, 0.0) + 0.5);
    if (index >= count)
        return;
    float step = uIntegrator.y;
    vec3 velocity = particles[index].velocity.xyz + vec3(0.0, -9.81, 0.0) * step;
    vec3 position = particles[index].position.xyz + velocity * step;
    if (position.y < 0.0)
    {
        position.y = -position.y;
        velocity.y = -velocity.y * 0.5;
    }
    particles[index].position = vec4(position, particles[index].position.w);
    particles[index].velocity = vec4(velocity, 0.0);
}
)CNA_SHADER";

inline constexpr std::uint32_t kIntegratorVulkanComputeSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x0000007au, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000bu, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000040u, 0x00000001u, 0x00000001u, 0x00040047u, 0x0000000bu, 0x0000000bu, 0x0000001cu,
    0x00030047u, 0x00000013u, 0x00000002u, 0x00050048u, 0x00000013u, 0x00000000u, 0x00000023u, 0x00000000u,
    0x00040047u, 0x00000015u, 0x00000021u, 0x00000001u, 0x00040047u, 0x00000015u, 0x00000022u, 0x00000000u,
    0x00050048u, 0x0000002fu, 0x00000000u, 0x00000023u, 0x00000000u, 0x00050048u, 0x0000002fu, 0x00000001u,
    0x00000023u, 0x00000010u, 0x00040047u, 0x00000030u, 0x00000006u, 0x00000020u, 0x00030047u, 0x00000031u,
    0x00000003u, 0x00050048u, 0x00000031u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x00000033u,
    0x00000021u, 0x00000000u, 0x00040047u, 0x00000033u, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000069u,
    0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u,
    0x00000006u, 0x00000020u, 0x00000000u, 0x00040017u, 0x00000009u, 0x00000006u, 0x00000003u, 0x00040020u,
    0x0000000au, 0x00000001u, 0x00000009u, 0x0004003bu, 0x0000000au, 0x0000000bu, 0x00000001u, 0x0004002bu,
    0x00000006u, 0x0000000cu, 0x00000000u, 0x00040020u, 0x0000000du, 0x00000001u, 0x00000006u, 0x00030016u,
    0x00000011u, 0x00000020u, 0x00040017u, 0x00000012u, 0x00000011u, 0x00000004u, 0x0003001eu, 0x00000013u,
    0x00000012u, 0x00040020u, 0x00000014u, 0x00000002u, 0x00000013u, 0x0004003bu, 0x00000014u, 0x00000015u,
    0x00000002u, 0x00040015u, 0x00000016u, 0x00000020u, 0x00000001u, 0x0004002bu, 0x00000016u, 0x00000017u,
    0x00000000u, 0x00040020u, 0x00000018u, 0x00000002u, 0x00000011u, 0x0004002bu, 0x00000011u, 0x0000001bu,
    0x00000000u, 0x0004002bu, 0x00000011u, 0x0000001du, 0x3f000000u, 0x00020014u, 0x00000022u, 0x0004002bu,
    0x00000006u, 0x00000029u, 0x00000001u, 0x00040017u, 0x0000002cu, 0x00000011u, 0x00000003u, 0x0004001eu,
    0x0000002fu, 0x00000012u, 0x00000012u, 0x0003001du, 0x00000030u, 0x0000002fu, 0x0003001eu, 0x00000031u,
    0x00000030u, 0x00040020u, 0x00000032u, 0x00000002u, 0x00000031u, 0x0004003bu, 0x00000032u, 0x00000033u,
    0x00000002u, 0x0004002bu, 0x00000016u, 0x00000035u, 0x00000001u, 0x00040020u, 0x00000036u, 0x00000002u,
    0x00000012u, 0x0004002bu, 0x00000011u, 0x0000003au, 0xc11cf5c3u, 0x0006002cu, 0x0000002cu, 0x0000003bu,
    0x0000001bu, 0x0000003au, 0x0000001bu, 0x0004002bu, 0x00000006u, 0x00000059u, 0x00000003u, 0x0004002bu,
    0x00000006u, 0x00000068u, 0x00000040u, 0x0006002cu, 0x00000009u, 0x00000069u, 0x00000068u, 0x00000029u,
    0x00000029u, 0x0004002bu, 0x00000011u, 0x00000079u, 0xbf000000u, 0x00050036u, 0x00000002u, 0x00000004u,
    0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x000300f7u, 0x0000006au, 0x00000000u, 0x000300fbu,
    0x0000000cu, 0x0000006bu, 0x000200f8u, 0x0000006bu, 0x00050041u, 0x0000000du, 0x0000000eu, 0x0000000bu,
    0x0000000cu, 0x0004003du, 0x00000006u, 0x0000000fu, 0x0000000eu, 0x00060041u, 0x00000018u, 0x00000019u,
    0x00000015u, 0x00000017u, 0x0000000cu, 0x0004003du, 0x00000011u, 0x0000001au, 0x00000019u, 0x0007000cu,
    0x00000011u, 0x0000001cu, 0x00000001u, 0x00000028u, 0x0000001au, 0x0000001bu, 0x00050081u, 0x00000011u,
    0x0000001eu, 0x0000001cu, 0x0000001du, 0x0004006du, 0x00000006u, 0x0000001fu, 0x0000001eu, 0x000500aeu,
    0x00000022u, 0x00000023u, 0x0000000fu, 0x0000001fu, 0x000300f7u, 0x00000025u, 0x00000000u, 0x000400fau,
    0x00000023u, 0x00000024u, 0x00000025u, 0x000200f8u, 0x00000024u, 0x000200f9u, 0x0000006au, 0x000200f8u,
    0x00000025u, 0x00060041u, 0x00000018u, 0x0000002au, 0x00000015u, 0x00000017u, 0x00000029u, 0x0004003du,
    0x00000011u, 0x0000002bu, 0x0000002au, 0x00070041u, 0x00000036u, 0x00000037u, 0x00000033u, 0x00000017u,
    0x0000000fu, 0x00000035u, 0x0004003du, 0x00000012u, 0x00000038u, 0x00000037u, 0x0008004fu, 0x0000002cu,
    0x00000039u, 0x00000038u, 0x00000038u, 0x00000000u, 0x00000001u, 0x00000002u, 0x0005008eu, 0x0000002cu,
    0x0000003du, 0x0000003bu, 0x0000002bu, 0x00050081u, 0x0000002cu, 0x0000003eu, 0x00000039u, 0x0000003du,
    0x00070041u, 0x00000036u, 0x00000041u, 0x00000033u, 0x00000017u, 0x0000000fu, 0x00000017u, 0x0004003du,
    0x00000012u, 0x00000042u, 0x00000041u, 0x0008004fu, 0x0000002cu, 0x00000043u, 0x00000042u, 0x00000042u,
    0x00000000u, 0x00000001u, 0x00000002u, 0x0005008eu, 0x0000002cu, 0x00000046u, 0x0000003eu, 0x0000002bu,
    0x00050081u, 0x0000002cu, 0x00000047u, 0x00000043u, 0x00000046u, 0x00050051u, 0x00000011u, 0x00000049u,
    0x00000047u, 0x00000001u, 0x000500b8u, 0x00000022u, 0x0000004au, 0x00000049u, 0x0000001bu, 0x000300f7u,
    0x0000004cu, 0x00000000u, 0x000400fau, 0x0000004au, 0x0000004bu, 0x0000004cu, 0x000200f8u, 0x0000004bu,
    0x0004007fu, 0x00000011u, 0x0000004fu, 0x00000049u, 0x00060052u, 0x0000002cu, 0x00000073u, 0x0000004fu,
    0x00000047u, 0x00000001u, 0x00050051u, 0x00000011u, 0x00000052u, 0x0000003eu, 0x00000001u, 0x00050085u,
    0x00000011u, 0x00000054u, 0x00000052u, 0x00000079u, 0x00060052u, 0x0000002cu, 0x00000076u, 0x00000054u,
    0x0000003eu, 0x00000001u, 0x000200f9u, 0x0000004cu, 0x000200f8u, 0x0000004cu, 0x000700f5u, 0x0000002cu,
    0x00000078u, 0x0000003eu, 0x00000025u, 0x00000076u, 0x0000004bu, 0x000700f5u, 0x0000002cu, 0x00000077u,
    0x00000047u, 0x00000025u, 0x00000073u, 0x0000004bu, 0x00080041u, 0x00000018u, 0x0000005au, 0x00000033u,
    0x00000017u, 0x0000000fu, 0x00000017u, 0x00000059u, 0x0004003du, 0x00000011u, 0x0000005bu, 0x0000005au,
    0x00050051u, 0x00000011u, 0x0000005cu, 0x00000077u, 0x00000000u, 0x00050051u, 0x00000011u, 0x0000005du,
    0x00000077u, 0x00000001u, 0x00050051u, 0x00000011u, 0x0000005eu, 0x00000077u, 0x00000002u, 0x00070050u,
    0x00000012u, 0x0000005fu, 0x0000005cu, 0x0000005du, 0x0000005eu, 0x0000005bu, 0x0003003eu, 0x00000041u,
    0x0000005fu, 0x00050051u, 0x00000011u, 0x00000063u, 0x00000078u, 0x00000000u, 0x00050051u, 0x00000011u,
    0x00000064u, 0x00000078u, 0x00000001u, 0x00050051u, 0x00000011u, 0x00000065u, 0x00000078u, 0x00000002u,
    0x00070050u, 0x00000012u, 0x00000066u, 0x00000063u, 0x00000064u, 0x00000065u, 0x0000001bu, 0x0003003eu,
    0x00000037u, 0x00000066u, 0x000200f9u, 0x0000006au, 0x000200f8u, 0x0000006au, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kIntegratorVulkanComputeSpirVByteSize = sizeof(kIntegratorVulkanComputeSpirV);

inline constexpr std::string_view kIntegratorVulkanComputeWgsl =
    R"CNA_SHADER(// integrate.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct IntegratorParameters {
    uIntegrator: vec4<f32>,
}

struct Particle {
    position: vec4<f32>,
    velocity: vec4<f32>,
}

struct Particles {
    particles: array<Particle>,
}

var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(0) @binding(1) 
var<uniform> unnamed: IntegratorParameters;
@group(0) @binding(0) 
var<storage, read_write> unnamed_1: Particles;

fn main_1() {
    var index: u32;
    var count: u32;
    var step: f32;
    var velocity: vec3<f32>;
    var position: vec3<f32>;

    let _e20 = gl_GlobalInvocationID_1[0u];
    index = _e20;
    let _e23 = unnamed.uIntegrator[0u];
    count = u32((max(_e23, 0f) + 0.5f));
    let _e27 = index;
    let _e28 = count;
    if (_e27 >= _e28) {
        return;
    }
    let _e32 = unnamed.uIntegrator[1u];
    step = _e32;
    let _e33 = index;
    let _e37 = unnamed_1.particles[_e33].velocity;
    let _e39 = step;
    velocity = (_e37.xyz + (vec3<f32>(0f, -9.81f, 0f) * _e39));
    let _e42 = index;
    let _e46 = unnamed_1.particles[_e42].position;
    let _e48 = velocity;
    let _e49 = step;
    position = (_e46.xyz + (_e48 * _e49));
    let _e53 = position[1u];
    if (_e53 < 0f) {
        let _e56 = position[1u];
        position[1u] = -(_e56);
        let _e60 = velocity[1u];
        velocity[1u] = (-(_e60) * 0.5f);
    }
    let _e64 = index;
    let _e65 = position;
    let _e66 = index;
    let _e71 = unnamed_1.particles[_e66].position[3u];
    unnamed_1.particles[_e64].position = vec4<f32>(_e65.x, _e65.y, _e65.z, _e71);
    let _e79 = index;
    let _e80 = velocity;
    unnamed_1.particles[_e79].velocity = vec4<f32>(_e80.x, _e80.y, _e80.z, 0f);
    return;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 4> kPayloads = {{
    {"kIntegratorEsComputeSource", "integrate.es.comp.glsl", "71fd4fc687bb9846f4c137f6975f0f21a5cbd2689c6dc873bd936c6c7071a3ab", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kIntegratorDesktopComputeSource", "integrate.desktop.comp.glsl", "c7d62e6199bc74fd84facf3d2649b918e13a8e9adb9fb40ee531d18b36d86782", "glsl", "glsl", "compute", "text", "main"},
    {"kIntegratorVulkanComputeSpirV", "integrate.vulkan.comp.glsl", "e5032d13ed366f1e0676e56cdf5b4de9e701601fabc80ad3e086c56ea151676b", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kIntegratorVulkanComputeWgsl", "integrate.vulkan.comp.glsl", "e5032d13ed366f1e0676e56cdf5b4de9e701601fabc80ad3e086c56ea151676b", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
}};

} // namespace CNA::Examples::ComputeParticlesGenerated

#endif // CNA_CNAEXT
