// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Examples::TransparencyGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "transparency_example";
inline constexpr std::string_view kManifestSha256 = "9ab53320a385cd9e8162fc7b5bb5f4d3c1eb7993870778f19ad98d19e4aae3fc";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";

inline constexpr std::string_view kBasicEsVertexSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

layout(location = 0) in vec3 aPos;

void main()
{
    gl_Position = vec4(aPos, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kEmitterEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

layout(location = 0) out vec4 cnaOitAccumulation;
layout(location = 1) out vec4 cnaOitRevealage;
uniform vec4 uEffectParams;
uniform float uScalar;

void main()
{
    float alpha = uEffectParams.a;
    float z = clamp(uScalar, 0.0, 1.0);
    float weight = alpha * clamp(0.03 / (1e-5 + pow(z, 4.0)), 1e-2, 3e3);
    cnaOitAccumulation = vec4(uEffectParams.rgb * alpha * weight, alpha * weight);
    cnaOitRevealage = vec4(log(max(1.0 - alpha, 1e-4)), 0.0, 0.0, 0.0);
}
)CNA_SHADER";

inline constexpr std::string_view kFlatEsFragmentSource =
    R"CNA_SHADER(#version 300 es
precision highp float;

out vec4 FragColor;
uniform vec4 uEffectParams;

void main()
{
    FragColor = uEffectParams;
}
)CNA_SHADER";

inline constexpr std::string_view kBasicDesktopVertexSource =
    R"CNA_SHADER(#version 330 core

layout(location = 0) in vec3 aPos;

void main()
{
    gl_Position = vec4(aPos, 1.0);
}
)CNA_SHADER";

inline constexpr std::string_view kEmitterDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core

layout(location = 0) out vec4 cnaOitAccumulation;
layout(location = 1) out vec4 cnaOitRevealage;
uniform vec4 uEffectParams;
uniform float uScalar;

void main()
{
    float alpha = uEffectParams.a;
    float z = clamp(uScalar, 0.0, 1.0);
    float weight = alpha * clamp(0.03 / (1e-5 + pow(z, 4.0)), 1e-2, 3e3);
    cnaOitAccumulation = vec4(uEffectParams.rgb * alpha * weight, alpha * weight);
    cnaOitRevealage = vec4(log(max(1.0 - alpha, 1e-4)), 0.0, 0.0, 0.0);
}
)CNA_SHADER";

inline constexpr std::string_view kFlatDesktopFragmentSource =
    R"CNA_SHADER(#version 330 core

out vec4 FragColor;
uniform vec4 uEffectParams;

void main()
{
    FragColor = uEffectParams;
}
)CNA_SHADER";

inline constexpr std::uint32_t kBasicVulkanVertexSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000023u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0007000fu, 0x00000000u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000000du, 0x00000012u, 0x00030047u,
    0x0000000bu, 0x00000002u, 0x00050048u, 0x0000000bu, 0x00000000u, 0x0000000bu, 0x00000000u, 0x00050048u,
    0x0000000bu, 0x00000001u, 0x0000000bu, 0x00000001u, 0x00050048u, 0x0000000bu, 0x00000002u, 0x0000000bu,
    0x00000003u, 0x00050048u, 0x0000000bu, 0x00000003u, 0x0000000bu, 0x00000004u, 0x00040047u, 0x00000012u,
    0x0000001eu, 0x00000000u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u,
    0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u, 0x00040015u, 0x00000008u,
    0x00000020u, 0x00000000u, 0x0004002bu, 0x00000008u, 0x00000009u, 0x00000001u, 0x0004001cu, 0x0000000au,
    0x00000006u, 0x00000009u, 0x0006001eu, 0x0000000bu, 0x00000007u, 0x00000006u, 0x0000000au, 0x0000000au,
    0x00040020u, 0x0000000cu, 0x00000003u, 0x0000000bu, 0x0004003bu, 0x0000000cu, 0x0000000du, 0x00000003u,
    0x00040015u, 0x0000000eu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000eu, 0x0000000fu, 0x00000000u,
    0x00040017u, 0x00000010u, 0x00000006u, 0x00000003u, 0x00040020u, 0x00000011u, 0x00000001u, 0x00000010u,
    0x0004003bu, 0x00000011u, 0x00000012u, 0x00000001u, 0x0004002bu, 0x00000008u, 0x00000016u, 0x00000002u,
    0x00040020u, 0x00000017u, 0x00000001u, 0x00000006u, 0x0004002bu, 0x00000006u, 0x0000001au, 0x3f000000u,
    0x0004002bu, 0x00000006u, 0x0000001du, 0x3f800000u, 0x00040020u, 0x00000021u, 0x00000003u, 0x00000007u,
    0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x0004003du,
    0x00000010u, 0x00000014u, 0x00000012u, 0x00050041u, 0x00000017u, 0x00000018u, 0x00000012u, 0x00000016u,
    0x0004003du, 0x00000006u, 0x00000019u, 0x00000018u, 0x00050085u, 0x00000006u, 0x0000001bu, 0x00000019u,
    0x0000001au, 0x00050081u, 0x00000006u, 0x0000001cu, 0x0000001bu, 0x0000001au, 0x00050051u, 0x00000006u,
    0x0000001eu, 0x00000014u, 0x00000000u, 0x00050051u, 0x00000006u, 0x0000001fu, 0x00000014u, 0x00000001u,
    0x00070050u, 0x00000007u, 0x00000020u, 0x0000001eu, 0x0000001fu, 0x0000001cu, 0x0000001du, 0x00050041u,
    0x00000021u, 0x00000022u, 0x0000000du, 0x0000000fu, 0x0003003eu, 0x00000022u, 0x00000020u, 0x000100fdu,
    0x00010038u,
};
inline constexpr std::size_t kBasicVulkanVertexSpirVByteSize = sizeof(kBasicVulkanVertexSpirV);

inline constexpr std::uint32_t kEmitterVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000043u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0007000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000002bu, 0x0000003cu, 0x00030010u,
    0x00000004u, 0x00000007u, 0x00030047u, 0x0000000cu, 0x00000002u, 0x00050048u, 0x0000000cu, 0x00000000u,
    0x00000023u, 0x00000000u, 0x00040048u, 0x0000000cu, 0x00000001u, 0x00000005u, 0x00050048u, 0x0000000cu,
    0x00000001u, 0x00000007u, 0x00000010u, 0x00050048u, 0x0000000cu, 0x00000001u, 0x00000023u, 0x00000010u,
    0x00050048u, 0x0000000cu, 0x00000002u, 0x00000023u, 0x00000050u, 0x00050048u, 0x0000000cu, 0x00000003u,
    0x00000023u, 0x00000060u, 0x00040047u, 0x0000002bu, 0x0000001eu, 0x00000000u, 0x00040047u, 0x0000003cu,
    0x0000001eu, 0x00000001u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u,
    0x00000006u, 0x00000020u, 0x00040017u, 0x00000009u, 0x00000006u, 0x00000002u, 0x00040017u, 0x0000000au,
    0x00000006u, 0x00000004u, 0x00040018u, 0x0000000bu, 0x0000000au, 0x00000004u, 0x0006001eu, 0x0000000cu,
    0x00000009u, 0x0000000bu, 0x0000000au, 0x00000006u, 0x00040020u, 0x0000000du, 0x00000009u, 0x0000000cu,
    0x0004003bu, 0x0000000du, 0x0000000eu, 0x00000009u, 0x00040015u, 0x0000000fu, 0x00000020u, 0x00000001u,
    0x0004002bu, 0x0000000fu, 0x00000010u, 0x00000002u, 0x00040015u, 0x00000011u, 0x00000020u, 0x00000000u,
    0x0004002bu, 0x00000011u, 0x00000012u, 0x00000003u, 0x00040020u, 0x00000013u, 0x00000009u, 0x00000006u,
    0x0004002bu, 0x0000000fu, 0x00000017u, 0x00000003u, 0x0004002bu, 0x00000006u, 0x0000001au, 0x00000000u,
    0x0004002bu, 0x00000006u, 0x0000001bu, 0x3f800000u, 0x0004002bu, 0x00000006u, 0x0000001fu, 0x3cf5c28fu,
    0x0004002bu, 0x00000006u, 0x00000020u, 0x3727c5acu, 0x0004002bu, 0x00000006u, 0x00000022u, 0x40800000u,
    0x0004002bu, 0x00000006u, 0x00000026u, 0x3c23d70au, 0x0004002bu, 0x00000006u, 0x00000027u, 0x453b8000u,
    0x00040020u, 0x0000002au, 0x00000003u, 0x0000000au, 0x0004003bu, 0x0000002au, 0x0000002bu, 0x00000003u,
    0x00040017u, 0x0000002cu, 0x00000006u, 0x00000003u, 0x00040020u, 0x0000002du, 0x00000009u, 0x0000000au,
    0x0004003bu, 0x0000002au, 0x0000003cu, 0x00000003u, 0x0004002bu, 0x00000006u, 0x0000003fu, 0x38d1b717u,
    0x00050036u, 0x00000002u, 0x00000004u, 0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x00060041u,
    0x00000013u, 0x00000014u, 0x0000000eu, 0x00000010u, 0x00000012u, 0x0004003du, 0x00000006u, 0x00000015u,
    0x00000014u, 0x00050041u, 0x00000013u, 0x00000018u, 0x0000000eu, 0x00000017u, 0x0004003du, 0x00000006u,
    0x00000019u, 0x00000018u, 0x0008000cu, 0x00000006u, 0x0000001cu, 0x00000001u, 0x0000002bu, 0x00000019u,
    0x0000001au, 0x0000001bu, 0x0007000cu, 0x00000006u, 0x00000023u, 0x00000001u, 0x0000001au, 0x0000001cu,
    0x00000022u, 0x00050081u, 0x00000006u, 0x00000024u, 0x00000020u, 0x00000023u, 0x00050088u, 0x00000006u,
    0x00000025u, 0x0000001fu, 0x00000024u, 0x0008000cu, 0x00000006u, 0x00000028u, 0x00000001u, 0x0000002bu,
    0x00000025u, 0x00000026u, 0x00000027u, 0x00050085u, 0x00000006u, 0x00000029u, 0x00000015u, 0x00000028u,
    0x00050041u, 0x0000002du, 0x0000002eu, 0x0000000eu, 0x00000010u, 0x0004003du, 0x0000000au, 0x0000002fu,
    0x0000002eu, 0x0008004fu, 0x0000002cu, 0x00000030u, 0x0000002fu, 0x0000002fu, 0x00000000u, 0x00000001u,
    0x00000002u, 0x0005008eu, 0x0000002cu, 0x00000032u, 0x00000030u, 0x00000015u, 0x0005008eu, 0x0000002cu,
    0x00000034u, 0x00000032u, 0x00000029u, 0x00050085u, 0x00000006u, 0x00000037u, 0x00000015u, 0x00000029u,
    0x00050051u, 0x00000006u, 0x00000038u, 0x00000034u, 0x00000000u, 0x00050051u, 0x00000006u, 0x00000039u,
    0x00000034u, 0x00000001u, 0x00050051u, 0x00000006u, 0x0000003au, 0x00000034u, 0x00000002u, 0x00070050u,
    0x0000000au, 0x0000003bu, 0x00000038u, 0x00000039u, 0x0000003au, 0x00000037u, 0x0003003eu, 0x0000002bu,
    0x0000003bu, 0x00050083u, 0x00000006u, 0x0000003eu, 0x0000001bu, 0x00000015u, 0x0007000cu, 0x00000006u,
    0x00000040u, 0x00000001u, 0x00000028u, 0x0000003eu, 0x0000003fu, 0x0006000cu, 0x00000006u, 0x00000041u,
    0x00000001u, 0x0000001cu, 0x00000040u, 0x00070050u, 0x0000000au, 0x00000042u, 0x00000041u, 0x0000001au,
    0x0000001au, 0x0000001au, 0x0003003eu, 0x0000003cu, 0x00000042u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kEmitterVulkanFragmentSpirVByteSize = sizeof(kEmitterVulkanFragmentSpirV);

inline constexpr std::uint32_t kFlatVulkanFragmentSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x00000014u, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000004u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x00000009u, 0x00030010u, 0x00000004u,
    0x00000007u, 0x00040047u, 0x00000009u, 0x0000001eu, 0x00000000u, 0x00030047u, 0x0000000cu, 0x00000002u,
    0x00050048u, 0x0000000cu, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040048u, 0x0000000cu, 0x00000001u,
    0x00000005u, 0x00050048u, 0x0000000cu, 0x00000001u, 0x00000007u, 0x00000010u, 0x00050048u, 0x0000000cu,
    0x00000001u, 0x00000023u, 0x00000010u, 0x00050048u, 0x0000000cu, 0x00000002u, 0x00000023u, 0x00000050u,
    0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u, 0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u,
    0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u, 0x00040020u, 0x00000008u, 0x00000003u, 0x00000007u,
    0x0004003bu, 0x00000008u, 0x00000009u, 0x00000003u, 0x00040017u, 0x0000000au, 0x00000006u, 0x00000002u,
    0x00040018u, 0x0000000bu, 0x00000007u, 0x00000004u, 0x0005001eu, 0x0000000cu, 0x0000000au, 0x0000000bu,
    0x00000007u, 0x00040020u, 0x0000000du, 0x00000009u, 0x0000000cu, 0x0004003bu, 0x0000000du, 0x0000000eu,
    0x00000009u, 0x00040015u, 0x0000000fu, 0x00000020u, 0x00000001u, 0x0004002bu, 0x0000000fu, 0x00000010u,
    0x00000002u, 0x00040020u, 0x00000011u, 0x00000009u, 0x00000007u, 0x00050036u, 0x00000002u, 0x00000004u,
    0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x00050041u, 0x00000011u, 0x00000012u, 0x0000000eu,
    0x00000010u, 0x0004003du, 0x00000007u, 0x00000013u, 0x00000012u, 0x0003003eu, 0x00000009u, 0x00000013u,
    0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kFlatVulkanFragmentSpirVByteSize = sizeof(kFlatVulkanFragmentSpirV);

inline constexpr std::array<PayloadProvenance, 9> kPayloads = {{
    {"kBasicEsVertexSource", "basic.es.vert.glsl", "274ad658c2f3bc56f3586c802ae30779f9df41363afe823405f05586e2fc5d01", "glsl-es", "glsl-es", "vertex", "text", "main"},
    {"kEmitterEsFragmentSource", "emitter.es.frag.glsl", "7d70cebf103026f9e4930dd87f8b44e0f86662a4e38cde1250f72d4ffc407b90", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kFlatEsFragmentSource", "flat.es.frag.glsl", "99f51e2c2de33d44fa8fd85d1f13d91f95a2f32cc0a8de1a0e1646435e4f4932", "glsl-es", "glsl-es", "fragment", "text", "main"},
    {"kBasicDesktopVertexSource", "basic.desktop.vert.glsl", "0008eb043c9fca12d1548c104aec22fead0f0d73f90054885d9dcb54ddcbceb4", "glsl", "glsl", "vertex", "text", "main"},
    {"kEmitterDesktopFragmentSource", "emitter.desktop.frag.glsl", "844617ac9f802f28c8137cf8cdf495efd84e1f8c6053640930578982c10b4a6c", "glsl", "glsl", "fragment", "text", "main"},
    {"kFlatDesktopFragmentSource", "flat.desktop.frag.glsl", "f0e3c81eda3d000bcf5d63230a1e4de5530eca958d59360d9e5f0136608d7efa", "glsl", "glsl", "fragment", "text", "main"},
    {"kBasicVulkanVertexSpirV", "basic.vulkan.vert.glsl", "776d5215c78990640065ef09013a993b20e4805f3071a57e68dcf67d0120d679", "spirv", "vulkan-glsl", "vertex", "spirv", "main"},
    {"kEmitterVulkanFragmentSpirV", "emitter.vulkan.frag.glsl", "4f3a2984288cee6af3da9185499d9fd934830d6f0fdb81e2c24430ee818ab003", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
    {"kFlatVulkanFragmentSpirV", "flat.vulkan.frag.glsl", "331c06008eeb349df23c17e43bad242bf7142a88d2c01f7c515afd4884b387e4", "spirv", "vulkan-glsl", "fragment", "spirv", "main"},
}};

} // namespace CNA::Examples::TransparencyGenerated

#endif // CNA_CNAEXT
