// SPDX-License-Identifier: MS-PL

#include <CNA/C/abi.h>
#include <CNA/C/core.h>
#include <CNA/C/graphics.h>
#include <CNA/C/graphics_resource.h>
#include <CNA/C/cna.h>

#include <cstddef>

static_assert(CNA_ABI_VERSION == CNA_ABI_VERSION_ENCODE(0, 1, 0));
static_assert(sizeof(CNA_Result) == sizeof(uint32_t));
static_assert(sizeof(CNA_Handle) == sizeof(uint64_t));
static_assert(sizeof(CNA_GraphicsResourceTag) == sizeof(uint64_t));
static_assert(sizeof(CNA_GraphicsResourceEventRegistrationHandle) == sizeof(uint64_t));
static_assert(sizeof(CNA_ErrorCategory) == sizeof(uint32_t));
static_assert(sizeof(CNA_GameTime) == 24U);
static_assert(sizeof(CNA_Color) == 4U);
static_assert(CNA_COLOR_TRANSPARENT.a == UINT8_C(0));
static_assert(CNA_COLOR_CORNFLOWER_BLUE.r == UINT8_C(100));
static_assert(CNA_COLOR_YELLOW_GREEN.b == UINT8_C(50));
static_assert(sizeof(CNA_GraphicsCapability) == sizeof(uint32_t));
static_assert(sizeof(CNA_GraphicsRendererType) == sizeof(uint32_t));
static_assert(sizeof(CNA_GraphicsCapabilityFlags) == sizeof(uint64_t));
static_assert(sizeof(CNA_EffectParameterClass) == sizeof(uint32_t));
static_assert(CNA_EFFECT_PARAMETER_CLASS_SCALAR == UINT32_C(0));
static_assert(CNA_EFFECT_PARAMETER_CLASS_VECTOR == UINT32_C(1));
static_assert(CNA_EFFECT_PARAMETER_CLASS_MATRIX == UINT32_C(2));
static_assert(CNA_EFFECT_PARAMETER_CLASS_OBJECT == UINT32_C(3));
static_assert(CNA_EFFECT_PARAMETER_CLASS_STRUCT == UINT32_C(4));
static_assert(sizeof(CNA_EffectParameterType) == sizeof(uint32_t));
static_assert(CNA_EFFECT_PARAMETER_TYPE_VOID == UINT32_C(0));
static_assert(CNA_EFFECT_PARAMETER_TYPE_BOOL == UINT32_C(1));
static_assert(CNA_EFFECT_PARAMETER_TYPE_INT32 == UINT32_C(2));
static_assert(CNA_EFFECT_PARAMETER_TYPE_SINGLE == UINT32_C(3));
static_assert(CNA_EFFECT_PARAMETER_TYPE_STRING == UINT32_C(4));
static_assert(CNA_EFFECT_PARAMETER_TYPE_TEXTURE == UINT32_C(5));
static_assert(CNA_EFFECT_PARAMETER_TYPE_TEXTURE1D == UINT32_C(6));
static_assert(CNA_EFFECT_PARAMETER_TYPE_TEXTURE2D == UINT32_C(7));
static_assert(CNA_EFFECT_PARAMETER_TYPE_TEXTURE3D == UINT32_C(8));
static_assert(CNA_EFFECT_PARAMETER_TYPE_TEXTURE_CUBE == UINT32_C(9));
static_assert(sizeof(CNA_EffectAnnotationHandle) == 8U);
static_assert(sizeof(CNA_EffectAnnotationCollectionHandle) == 8U);
static_assert(sizeof(CNA_EffectAnnotationCreateInfo) == 88U);
static_assert(alignof(CNA_EffectAnnotationCreateInfo) == 8U);
static_assert(offsetof(CNA_EffectAnnotationCreateInfo, name) == 8U);
static_assert(offsetof(CNA_EffectAnnotationCreateInfo, semantic) == 24U);
static_assert(offsetof(CNA_EffectAnnotationCreateInfo, row_count) == 40U);
static_assert(offsetof(CNA_EffectAnnotationCreateInfo, data) == 56U);
static_assert(offsetof(CNA_EffectAnnotationCreateInfo, cached_string) == 72U);
static_assert(sizeof(CNA_EffectAnnotationInfo) == 24U);
static_assert(alignof(CNA_EffectAnnotationInfo) == 4U);
static_assert(sizeof(CNA_EffectValueType) == sizeof(uint32_t));
static_assert(CNA_EFFECT_VALUE_BOOLEAN == UINT32_C(0));
static_assert(CNA_EFFECT_VALUE_INT32 == UINT32_C(1));
static_assert(CNA_EFFECT_VALUE_SINGLE == UINT32_C(2));
static_assert(CNA_EFFECT_VALUE_MATRIX == UINT32_C(3));
static_assert(CNA_EFFECT_VALUE_MATRIX_TRANSPOSE == UINT32_C(4));
static_assert(CNA_EFFECT_VALUE_QUATERNION == UINT32_C(5));
static_assert(CNA_EFFECT_VALUE_VECTOR2 == UINT32_C(6));
static_assert(CNA_EFFECT_VALUE_VECTOR3 == UINT32_C(7));
static_assert(CNA_EFFECT_VALUE_VECTOR4 == UINT32_C(8));
static_assert(sizeof(CNA_EffectTextureType) == sizeof(uint32_t));
static_assert(CNA_EFFECT_TEXTURE_BASE == UINT32_C(0));
static_assert(CNA_EFFECT_TEXTURE_2D == UINT32_C(1));
static_assert(CNA_EFFECT_TEXTURE_3D == UINT32_C(2));
static_assert(CNA_EFFECT_TEXTURE_CUBE == UINT32_C(3));
static_assert(sizeof(CNA_EffectParameterHandle) == 8U);
static_assert(sizeof(CNA_EffectParameterCollectionHandle) == 8U);
static_assert(sizeof(CNA_EffectParameterCreateInfo) == 56U);
static_assert(alignof(CNA_EffectParameterCreateInfo) == 8U);
static_assert(offsetof(CNA_EffectParameterCreateInfo, name) == 8U);
static_assert(offsetof(CNA_EffectParameterCreateInfo, semantic) == 24U);
static_assert(offsetof(CNA_EffectParameterCreateInfo, row_count) == 40U);
static_assert(offsetof(CNA_EffectParameterCreateInfo, parameter_type) == 52U);
static_assert(sizeof(CNA_EffectParameterInfo) == 24U);
static_assert(alignof(CNA_EffectParameterInfo) == 4U);
static_assert(sizeof(CNA_EffectPassHandle) == 8U);
static_assert(sizeof(CNA_EffectPassCollectionHandle) == 8U);
static_assert(sizeof(CNA_EffectTechniqueHandle) == 8U);
static_assert(sizeof(CNA_EffectTechniqueCollectionHandle) == 8U);
static_assert(sizeof(CNA_EffectHandle) == 8U);
static_assert(sizeof(CNA_DirectionalLightHandle) == 8U);
static_assert(CNA_SKINNED_EFFECT_MAX_BONES == UINT32_C(72));
static_assert(sizeof(CNA_ColorMatrix4x4) == 64U);
static_assert(alignof(CNA_ColorMatrix4x4) == 4U);
static_assert(sizeof(CNA_PbrTextureSlot) == sizeof(uint32_t));
static_assert(CNA_PBR_TEXTURE_BASE_COLOR == UINT32_C(0));
static_assert(CNA_PBR_TEXTURE_NORMAL == UINT32_C(1));
static_assert(CNA_PBR_TEXTURE_METALLIC_ROUGHNESS == UINT32_C(2));
static_assert(CNA_PBR_TEXTURE_EMISSIVE == UINT32_C(3));
static_assert(CNA_PBR_TEXTURE_OCCLUSION == UINT32_C(4));
static_assert(CNA_SKINNED_PBR_EFFECT_MAX_BONES == UINT32_C(72));
static_assert(sizeof(CNA_ModelBoneHandle) == 8U);
static_assert(sizeof(CNA_ModelBoneCollectionHandle) == 8U);
static_assert(sizeof(CNA_ModelMeshPartHandle) == 8U);
static_assert(sizeof(CNA_ModelMeshPartCollectionHandle) == 8U);
static_assert(sizeof(CNA_ModelMeshPartTag) == 8U);
static_assert(sizeof(CNA_ModelMeshHandle) == 8U);
static_assert(sizeof(CNA_ModelMeshCollectionHandle) == 8U);
static_assert(sizeof(CNA_ModelEffectCollectionHandle) == 8U);
static_assert(sizeof(CNA_ModelMeshTag) == 8U);
static_assert(sizeof(CNA_ModelHandle) == 8U);
static_assert(sizeof(CNA_ModelTag) == 8U);
static_assert(sizeof(CNA_MorphTargetDataEXTHandle) == 8U);
static_assert(sizeof(CNA_MorphWeightKeyframeEXTDescriptor) == 56U);
static_assert(sizeof(CNA_MorphWeightTrackEXTDescriptor) == 24U);
static_assert(sizeof(CNA_MorphTargetDeltaEXTDescriptor) == 32U);
static_assert(sizeof(CNA_MorphTargetDataEXTDescriptor) == 80U);
static_assert(sizeof(CNA_SkinnedModelEXTHandle) == 8U);
static_assert(sizeof(CNA_KeyframeEXT) == 48U);
static_assert(sizeof(CNA_BoneTrackEXTDescriptor) == 24U);
static_assert(sizeof(CNA_AnimationClipEXTDescriptor) == 24U);
static_assert(sizeof(CNA_NamedAnimationClipEXTDescriptor) == 40U);
static_assert(sizeof(CNA_SkinnedModelEXTDescriptor) == 48U);
static_assert(sizeof(CNA_SkinningDataHandle) == 8U);
static_assert(sizeof(CNA_AnimationPlayerHandle) == 8U);
static_assert(sizeof(CNA_SkinningDataDescriptor) == 64U);
static_assert(sizeof(CNA_RendererInfo) == 32U);
static_assert(CNA_GRAPHICS_RENDERER_SDL_RENDERER == UINT32_C(1));
static_assert(CNA_GRAPHICS_RENDERER_PORTABLEGL == UINT32_C(46));
static_assert(CNA_GRAPHICS_CAPABILITY_THREE_D == UINT32_C(0));
static_assert(CNA_GRAPHICS_CAPABILITY_ADDITIVE_BLENDING == UINT32_C(12));
static_assert(sizeof(CNA_SurfaceFormat) == sizeof(uint32_t));
static_assert(CNA_SURFACE_FORMAT_COLOR == UINT32_C(0));
static_assert(CNA_SURFACE_FORMAT_USHORT_EXT == UINT32_C(26));
static_assert(sizeof(CNA_Texture2DCreateInfo) == 24U);
static_assert(sizeof(CNA_Texture2DInfo) == 24U);
static_assert(sizeof(CNA_TextureDataType) == sizeof(uint32_t));
static_assert(CNA_TEXTURE_DATA_COLOR == UINT32_C(0));
static_assert(CNA_TEXTURE_DATA_USHORT == UINT32_C(17));
static_assert(sizeof(CNA_TextureImageFormat) == sizeof(uint32_t));
static_assert(CNA_TEXTURE_IMAGE_FORMAT_PNG == UINT32_C(0));
static_assert(CNA_TEXTURE_IMAGE_FORMAT_JPEG == UINT32_C(1));
static_assert(sizeof(CNA_TextureInfo) == 16U);
static_assert(sizeof(CNA_Texture2DTransfer) == 48U);
static_assert(alignof(CNA_Texture2DTransfer) == 8U);
static_assert(offsetof(CNA_Texture2DTransfer, level) == 8U);
static_assert(offsetof(CNA_Texture2DTransfer, has_rectangle) == 12U);
static_assert(offsetof(CNA_Texture2DTransfer, rectangle) == 16U);
static_assert(offsetof(CNA_Texture2DTransfer, start_index) == 32U);
static_assert(offsetof(CNA_Texture2DTransfer, element_count) == 40U);
static_assert(sizeof(CNA_Texture2DDecodeInfo) == 24U);
static_assert(sizeof(CNA_Texture2DStorageInfo) == 16U);
static_assert(sizeof(CNA_BackBufferInfo) == 24U);
static_assert(sizeof(CNA_Vector2) == 8U);
static_assert(sizeof(CNA_Rectangle) == 16U);
static_assert(sizeof(CNA_SpriteSortMode) == sizeof(uint32_t));
static_assert(CNA_SPRITE_SORT_MODE_DEFERRED == UINT32_C(0));
static_assert(CNA_SPRITE_SORT_MODE_IMMEDIATE == UINT32_C(1));
static_assert(CNA_SPRITE_SORT_MODE_TEXTURE == UINT32_C(2));
static_assert(CNA_SPRITE_SORT_MODE_BACK_TO_FRONT == UINT32_C(3));
static_assert(CNA_SPRITE_SORT_MODE_FRONT_TO_BACK == UINT32_C(4));
static_assert(sizeof(CNA_SpriteEffects) == sizeof(uint32_t));
static_assert(CNA_SPRITE_EFFECT_NONE == UINT32_C(0));
static_assert(CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY == UINT32_C(1));
static_assert(CNA_SPRITE_EFFECT_FLIP_VERTICALLY == UINT32_C(2));
static_assert(sizeof(CNA_SpriteBatchBeginInfo) == 16U);
static_assert(sizeof(CNA_SpriteCommand) == 72U);
static_assert(sizeof(CNA_Key) == sizeof(uint32_t));
static_assert(CNA_KEY_NONE == UINT32_C(0));
static_assert(CNA_KEY_A == UINT32_C(65));
static_assert(CNA_KEY_F24 == UINT32_C(135));
static_assert(CNA_KEY_OEM_CLEAR == UINT32_C(254));
static_assert(sizeof(CNA_KeyboardState) == 40U);
static_assert(sizeof(CNA_MouseState) == 32U);
static_assert(CNA_MOUSE_BUTTON_LEFT == UINT32_C(1));
static_assert(CNA_MOUSE_BUTTON_X2 == UINT32_C(16));
static_assert(sizeof(CNA_PlayerIndex) == sizeof(uint32_t));
static_assert(CNA_PLAYER_INDEX_ONE == UINT32_C(0));
static_assert(CNA_PLAYER_INDEX_FOUR == UINT32_C(3));
static_assert(sizeof(CNA_GamePadDeadZone) == sizeof(uint32_t));
static_assert(CNA_GAMEPAD_DEAD_ZONE_NONE == UINT32_C(0));
static_assert(CNA_GAMEPAD_DEAD_ZONE_CIRCULAR == UINT32_C(2));
static_assert(CNA_GAMEPAD_BUTTON_DPAD_UP == UINT32_C(1));
static_assert(CNA_GAMEPAD_BUTTON_A == UINT32_C(0x00001000));
static_assert(CNA_GAMEPAD_BUTTON_ALL == UINT32_C(0x7fffffff));
static_assert(sizeof(CNA_GamePadAnalogState) == 24U);
static_assert(sizeof(CNA_GamePadState) == 48U);
static_assert(sizeof(CNA_TouchLocationState) == sizeof(uint32_t));
static_assert(CNA_TOUCH_LOCATION_INVALID == UINT32_C(0));
static_assert(CNA_TOUCH_LOCATION_MOVED == UINT32_C(3));
static_assert(CNA_TOUCH_MAX_TOUCHES == UINT32_C(8));
static_assert(sizeof(CNA_TouchLocation) == 32U);
static_assert(sizeof(CNA_TouchCapabilities) == 16U);
static_assert(sizeof(CNA_TouchState) == 272U);
static_assert(sizeof(CNA_AudioChannels) == sizeof(uint32_t));
static_assert(CNA_AUDIO_CHANNELS_MONO == UINT32_C(1));
static_assert(CNA_AUDIO_CHANNELS_STEREO == UINT32_C(2));
static_assert(sizeof(CNA_SoundState) == sizeof(uint32_t));
static_assert(CNA_SOUND_STATE_PLAYING == UINT32_C(0));
static_assert(CNA_SOUND_STATE_PAUSED == UINT32_C(1));
static_assert(CNA_SOUND_STATE_STOPPED == UINT32_C(2));
static_assert(sizeof(CNA_AudioCapabilities) == 16U);
static_assert(sizeof(CNA_SoundEffectCreateInfo) == 24U);
static_assert(sizeof(CNA_SoundEffectInstanceInfo) == 32U);
static_assert(sizeof(CNA_Vector3) == 12U);
static_assert(sizeof(CNA_Blend) == sizeof(uint32_t));
static_assert(CNA_BLEND_ONE == UINT32_C(0));
static_assert(CNA_BLEND_SOURCE_ALPHA_SATURATION == UINT32_C(12));
static_assert(sizeof(CNA_BlendFunction) == sizeof(uint32_t));
static_assert(CNA_BLEND_FUNCTION_ADD == UINT32_C(0));
static_assert(CNA_BLEND_FUNCTION_MIN == UINT32_C(4));
static_assert(sizeof(CNA_ColorWriteChannels) == sizeof(uint32_t));
static_assert(CNA_COLOR_WRITE_NONE == UINT32_C(0));
static_assert(CNA_COLOR_WRITE_ALL == UINT32_C(15));
static_assert(sizeof(CNA_CompareFunction) == sizeof(uint32_t));
static_assert(CNA_COMPARE_ALWAYS == UINT32_C(0));
static_assert(CNA_COMPARE_NOT_EQUAL == UINT32_C(7));
static_assert(sizeof(CNA_StencilOperation) == sizeof(uint32_t));
static_assert(CNA_STENCIL_KEEP == UINT32_C(0));
static_assert(CNA_STENCIL_INVERT == UINT32_C(7));
static_assert(sizeof(CNA_CullMode) == sizeof(uint32_t));
static_assert(CNA_CULL_NONE == UINT32_C(0));
static_assert(CNA_CULL_COUNTER_CLOCKWISE_FACE == UINT32_C(2));
static_assert(sizeof(CNA_FillMode) == sizeof(uint32_t));
static_assert(CNA_FILL_SOLID == UINT32_C(0));
static_assert(CNA_FILL_WIREFRAME == UINT32_C(1));
static_assert(sizeof(CNA_TextureAddressMode) == sizeof(uint32_t));
static_assert(CNA_TEXTURE_ADDRESS_WRAP == UINT32_C(0));
static_assert(CNA_TEXTURE_ADDRESS_MIRROR == UINT32_C(2));
static_assert(sizeof(CNA_TextureFilter) == sizeof(uint32_t));
static_assert(CNA_TEXTURE_FILTER_LINEAR == UINT32_C(0));
static_assert(CNA_TEXTURE_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT == UINT32_C(8));
static_assert(sizeof(CNA_BlendState) == 56U);
static_assert(sizeof(CNA_DepthStencilState) == 64U);
static_assert(sizeof(CNA_RasterizerState) == 28U);
static_assert(sizeof(CNA_SamplerState) == 40U);
static_assert(sizeof(CNA_DepthFormat) == sizeof(uint32_t));
static_assert(CNA_DEPTH_FORMAT_NONE == UINT32_C(0));
static_assert(CNA_DEPTH_FORMAT_DEPTH24_STENCIL8 == UINT32_C(3));
static_assert(sizeof(CNA_RenderTargetUsage) == sizeof(uint32_t));
static_assert(CNA_RENDER_TARGET_USAGE_DISCARD_CONTENTS == UINT32_C(0));
static_assert(CNA_RENDER_TARGET_USAGE_PLATFORM_CONTENTS == UINT32_C(2));
static_assert(sizeof(CNA_CubeMapFace) == sizeof(uint32_t));
static_assert(CNA_CUBE_MAP_FACE_POSITIVE_X == UINT32_C(0));
static_assert(CNA_CUBE_MAP_FACE_NEGATIVE_Z == UINT32_C(5));
static_assert(sizeof(CNA_RenderTarget2DCreateInfo) == 40U);
static_assert(sizeof(CNA_RenderTargetCubeCreateInfo) == 32U);
static_assert(sizeof(CNA_RenderTargetInfo) == 44U);
static_assert(sizeof(CNA_RenderTargetBinding) == 24U);
static_assert(sizeof(CNA_Texture3DCreateInfo) == 32U);
static_assert(sizeof(CNA_Texture3DInfo) == 32U);
static_assert(sizeof(CNA_Texture3DTransfer) == 56U);
static_assert(offsetof(CNA_Texture3DTransfer, start_index) == 40U);
static_assert(offsetof(CNA_Texture3DTransfer, element_count) == 48U);
static_assert(sizeof(CNA_TextureCubeCreateInfo) == 24U);
static_assert(sizeof(CNA_TextureCubeInfo) == 24U);
static_assert(sizeof(CNA_TextureCubeTransfer) == 56U);
static_assert(offsetof(CNA_TextureCubeTransfer, rectangle) == 20U);
static_assert(offsetof(CNA_TextureCubeTransfer, start_index) == 40U);
static_assert(sizeof(CNA_Char16) == sizeof(uint16_t));
static_assert(sizeof(CNA_SpriteFontGlyph) == 56U);
static_assert(sizeof(((CNA_SpriteFontCreateInfo*)nullptr)->glyphs) == sizeof(void*));
static_assert(sizeof(CNA_SpriteFontInfo) == 32U);
static_assert(sizeof(CNA_GraphicsProfile) == sizeof(uint32_t));
static_assert(CNA_GRAPHICS_PROFILE_REACH == UINT32_C(0));
static_assert(CNA_GRAPHICS_PROFILE_HI_DEF == UINT32_C(1));
static_assert(sizeof(CNA_PresentInterval) == sizeof(uint32_t));
static_assert(CNA_PRESENT_INTERVAL_DEFAULT == UINT32_C(0));
static_assert(CNA_PRESENT_INTERVAL_IMMEDIATE == UINT32_C(3));
static_assert(sizeof(CNA_DisplayOrientation) == sizeof(uint32_t));
static_assert(CNA_DISPLAY_ORIENTATION_DEFAULT == UINT32_C(0));
static_assert(CNA_DISPLAY_ORIENTATION_PORTRAIT == UINT32_C(4));
static_assert(sizeof(CNA_NativeHandleValue) == sizeof(uint64_t));
static_assert(sizeof(CNA_DisplayMode) == 24U);
static_assert(sizeof(CNA_GraphicsAdapterInfo) == 48U);
static_assert(sizeof(CNA_GraphicsFormatSelection) == 24U);
static_assert(sizeof(CNA_PresentationParameters) == 44U);
static_assert(sizeof(CNA_ContainmentType) == sizeof(uint32_t));
static_assert(CNA_CONTAINMENT_DISJOINT == UINT32_C(0));
static_assert(CNA_CONTAINMENT_CONTAINS == UINT32_C(1));
static_assert(CNA_CONTAINMENT_INTERSECTS == UINT32_C(2));
static_assert(sizeof(CNA_PlaneIntersectionType) == sizeof(uint32_t));
static_assert(CNA_PLANE_INTERSECTION_FRONT == UINT32_C(0));
static_assert(CNA_PLANE_INTERSECTION_BACK == UINT32_C(1));
static_assert(CNA_PLANE_INTERSECTION_INTERSECTING == UINT32_C(2));
static_assert(CNA_CURVE_CONTINUITY_SMOOTH == UINT32_C(0));
static_assert(CNA_CURVE_CONTINUITY_STEP == UINT32_C(1));
static_assert(CNA_CURVE_LOOP_CONSTANT == UINT32_C(0));
static_assert(CNA_CURVE_LOOP_CYCLE == UINT32_C(1));
static_assert(CNA_CURVE_LOOP_CYCLE_OFFSET == UINT32_C(2));
static_assert(CNA_CURVE_LOOP_OSCILLATE == UINT32_C(3));
static_assert(CNA_CURVE_LOOP_LINEAR == UINT32_C(4));
static_assert(CNA_CURVE_TANGENT_FLAT == UINT32_C(0));
static_assert(CNA_CURVE_TANGENT_LINEAR == UINT32_C(1));
static_assert(CNA_CURVE_TANGENT_SMOOTH == UINT32_C(2));
static_assert(sizeof(CNA_PackedVectorFormat) == sizeof(uint32_t));
static_assert(CNA_PACKED_VECTOR_FORMAT_ALPHA8 == UINT32_C(0));
static_assert(CNA_PACKED_VECTOR_FORMAT_BGR565 == UINT32_C(1));
static_assert(CNA_PACKED_VECTOR_FORMAT_BGRA4444 == UINT32_C(2));
static_assert(CNA_PACKED_VECTOR_FORMAT_BGRA5551 == UINT32_C(3));
static_assert(CNA_PACKED_VECTOR_FORMAT_BYTE4 == UINT32_C(4));
static_assert(CNA_PACKED_VECTOR_FORMAT_HALF_SINGLE == UINT32_C(5));
static_assert(CNA_PACKED_VECTOR_FORMAT_HALF_VECTOR2 == UINT32_C(6));
static_assert(CNA_PACKED_VECTOR_FORMAT_HALF_VECTOR4 == UINT32_C(7));
static_assert(CNA_PACKED_VECTOR_FORMAT_NORMALIZED_BYTE2 == UINT32_C(8));
static_assert(CNA_PACKED_VECTOR_FORMAT_NORMALIZED_BYTE4 == UINT32_C(9));
static_assert(CNA_PACKED_VECTOR_FORMAT_NORMALIZED_SHORT2 == UINT32_C(10));
static_assert(CNA_PACKED_VECTOR_FORMAT_NORMALIZED_SHORT4 == UINT32_C(11));
static_assert(CNA_PACKED_VECTOR_FORMAT_RG32 == UINT32_C(12));
static_assert(CNA_PACKED_VECTOR_FORMAT_RGBA1010102 == UINT32_C(13));
static_assert(CNA_PACKED_VECTOR_FORMAT_RGBA64 == UINT32_C(14));
static_assert(CNA_PACKED_VECTOR_FORMAT_SHORT2 == UINT32_C(15));
static_assert(CNA_PACKED_VECTOR_FORMAT_SHORT4 == UINT32_C(16));
static_assert(sizeof(CNA_Point) == 8U);
static_assert(sizeof(CNA_Vector4) == 16U);
static_assert(sizeof(CNA_Quaternion) == 16U);
static_assert(alignof(CNA_Point) == 4U);
static_assert(alignof(CNA_Vector4) == 4U);
static_assert(alignof(CNA_Quaternion) == 4U);
static_assert(offsetof(CNA_Point, x) == 0U);
static_assert(offsetof(CNA_Point, y) == 4U);
static_assert(offsetof(CNA_Vector4, x) == 0U);
static_assert(offsetof(CNA_Vector4, y) == 4U);
static_assert(offsetof(CNA_Vector4, z) == 8U);
static_assert(offsetof(CNA_Vector4, w) == 12U);
static_assert(offsetof(CNA_Quaternion, x) == 0U);
static_assert(offsetof(CNA_Quaternion, y) == 4U);
static_assert(offsetof(CNA_Quaternion, z) == 8U);
static_assert(offsetof(CNA_Quaternion, w) == 12U);
static_assert(sizeof(CNA_Matrix) == 64U);
static_assert(sizeof(CNA_Plane) == 16U);
static_assert(sizeof(CNA_Ray) == 24U);
static_assert(offsetof(CNA_Matrix, m11) == 0U);
static_assert(offsetof(CNA_Matrix, m12) == 4U);
static_assert(offsetof(CNA_Matrix, m13) == 8U);
static_assert(offsetof(CNA_Matrix, m14) == 12U);
static_assert(offsetof(CNA_Matrix, m21) == 16U);
static_assert(offsetof(CNA_Matrix, m22) == 20U);
static_assert(offsetof(CNA_Matrix, m23) == 24U);
static_assert(offsetof(CNA_Matrix, m24) == 28U);
static_assert(offsetof(CNA_Matrix, m31) == 32U);
static_assert(offsetof(CNA_Matrix, m32) == 36U);
static_assert(offsetof(CNA_Matrix, m33) == 40U);
static_assert(offsetof(CNA_Matrix, m34) == 44U);
static_assert(offsetof(CNA_Matrix, m41) == 48U);
static_assert(offsetof(CNA_Matrix, m42) == 52U);
static_assert(offsetof(CNA_Matrix, m43) == 56U);
static_assert(offsetof(CNA_Matrix, m44) == 60U);
static_assert(offsetof(CNA_Plane, normal) == 0U);
static_assert(offsetof(CNA_Plane, d) == 12U);
static_assert(offsetof(CNA_Ray, position) == 0U);
static_assert(offsetof(CNA_Ray, direction) == 12U);
static_assert(sizeof(CNA_BoundingBox) == 24U);
static_assert(sizeof(CNA_BoundingSphere) == 16U);
static_assert(sizeof(CNA_BoundingFrustum) == 64U);
static_assert(offsetof(CNA_BoundingBox, min) == 0U);
static_assert(offsetof(CNA_BoundingBox, max) == 12U);
static_assert(offsetof(CNA_BoundingSphere, center) == 0U);
static_assert(offsetof(CNA_BoundingSphere, radius) == 12U);
static_assert(offsetof(CNA_BoundingFrustum, matrix) == 0U);
static_assert(sizeof(CNA_CurveKey) == 20U);
static_assert(sizeof(CNA_CurveKeyCollectionHandle) == 8U);
static_assert(sizeof(CNA_CurveHandle) == 8U);
static_assert(alignof(CNA_CurveKey) == 4U);
static_assert(offsetof(CNA_CurveKey, position) == 0U);
static_assert(offsetof(CNA_CurveKey, value) == 4U);
static_assert(offsetof(CNA_CurveKey, tangent_in) == 8U);
static_assert(offsetof(CNA_CurveKey, tangent_out) == 12U);
static_assert(offsetof(CNA_CurveKey, continuity) == 16U);
static_assert(sizeof(CNA_PackedAlpha8) == 1U);
static_assert(sizeof(CNA_PackedBgr565) == 2U);
static_assert(sizeof(CNA_PackedBgra4444) == 2U);
static_assert(sizeof(CNA_PackedBgra5551) == 2U);
static_assert(sizeof(CNA_PackedByte4) == 4U);
static_assert(sizeof(CNA_PackedHalfSingle) == 2U);
static_assert(sizeof(CNA_PackedHalfVector2) == 4U);
static_assert(sizeof(CNA_PackedHalfVector4) == 8U);
static_assert(sizeof(CNA_PackedNormalizedByte2) == 2U);
static_assert(sizeof(CNA_PackedNormalizedByte4) == 4U);
static_assert(sizeof(CNA_PackedNormalizedShort2) == 4U);
static_assert(sizeof(CNA_PackedNormalizedShort4) == 8U);
static_assert(sizeof(CNA_PackedRg32) == 4U);
static_assert(sizeof(CNA_PackedRgba1010102) == 4U);
static_assert(sizeof(CNA_PackedRgba64) == 8U);
static_assert(sizeof(CNA_PackedShort2) == 4U);
static_assert(sizeof(CNA_PackedShort4) == 8U);
static_assert(sizeof(CNA_BufferUsage) == sizeof(uint32_t));
static_assert(CNA_BUFFER_USAGE_NONE == UINT32_C(0));
static_assert(CNA_BUFFER_USAGE_WRITE_ONLY == UINT32_C(1));
static_assert(sizeof(CNA_IndexElementSize) == sizeof(uint32_t));
static_assert(CNA_INDEX_ELEMENT_SIZE_SIXTEEN_BITS == UINT32_C(0));
static_assert(CNA_INDEX_ELEMENT_SIZE_THIRTY_TWO_BITS == UINT32_C(1));
static_assert(sizeof(CNA_PrimitiveType) == sizeof(uint32_t));
static_assert(CNA_PRIMITIVE_TRIANGLE_LIST == UINT32_C(0));
static_assert(CNA_PRIMITIVE_TRIANGLE_STRIP == UINT32_C(1));
static_assert(CNA_PRIMITIVE_LINE_LIST == UINT32_C(2));
static_assert(CNA_PRIMITIVE_LINE_STRIP == UINT32_C(3));
static_assert(CNA_PRIMITIVE_POINT_LIST_EXT == UINT32_C(4));
static_assert(sizeof(CNA_SetDataOptions) == sizeof(uint32_t));
static_assert(CNA_SET_DATA_NONE == UINT32_C(0));
static_assert(CNA_SET_DATA_DISCARD == UINT32_C(1));
static_assert(CNA_SET_DATA_NO_OVERWRITE == UINT32_C(2));
static_assert(sizeof(CNA_VertexElementFormat) == sizeof(uint32_t));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_SINGLE == UINT32_C(0));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_VECTOR2 == UINT32_C(1));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_VECTOR3 == UINT32_C(2));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_VECTOR4 == UINT32_C(3));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_COLOR == UINT32_C(4));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_BYTE4 == UINT32_C(5));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_SHORT2 == UINT32_C(6));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_SHORT4 == UINT32_C(7));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_NORMALIZED_SHORT2 == UINT32_C(8));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_NORMALIZED_SHORT4 == UINT32_C(9));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_HALF_VECTOR2 == UINT32_C(10));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_HALF_VECTOR4 == UINT32_C(11));
static_assert(sizeof(CNA_VertexElementUsage) == sizeof(uint32_t));
static_assert(CNA_VERTEX_ELEMENT_USAGE_POSITION == UINT32_C(0));
static_assert(CNA_VERTEX_ELEMENT_USAGE_COLOR == UINT32_C(1));
static_assert(CNA_VERTEX_ELEMENT_USAGE_TEXTURE_COORDINATE == UINT32_C(2));
static_assert(CNA_VERTEX_ELEMENT_USAGE_NORMAL == UINT32_C(3));
static_assert(CNA_VERTEX_ELEMENT_USAGE_BINORMAL == UINT32_C(4));
static_assert(CNA_VERTEX_ELEMENT_USAGE_TANGENT == UINT32_C(5));
static_assert(CNA_VERTEX_ELEMENT_USAGE_BLEND_INDICES == UINT32_C(6));
static_assert(CNA_VERTEX_ELEMENT_USAGE_BLEND_WEIGHT == UINT32_C(7));
static_assert(CNA_VERTEX_ELEMENT_USAGE_DEPTH == UINT32_C(8));
static_assert(CNA_VERTEX_ELEMENT_USAGE_FOG == UINT32_C(9));
static_assert(CNA_VERTEX_ELEMENT_USAGE_POINT_SIZE == UINT32_C(10));
static_assert(CNA_VERTEX_ELEMENT_USAGE_SAMPLE == UINT32_C(11));
static_assert(CNA_VERTEX_ELEMENT_USAGE_TESSELLATE_FACTOR == UINT32_C(12));
static_assert(sizeof(CNA_VertexElement) == 16U);
static_assert(alignof(CNA_VertexElement) == 4U);
static_assert(offsetof(CNA_VertexElement, offset) == 0U);
static_assert(offsetof(CNA_VertexElement, format) == 4U);
static_assert(offsetof(CNA_VertexElement, usage) == 8U);
static_assert(offsetof(CNA_VertexElement, usage_index) == 12U);
static_assert(sizeof(CNA_VertexType) == sizeof(uint32_t));
static_assert(CNA_VERTEX_TYPE_POSITION_COLOR == UINT32_C(0));
static_assert(CNA_VERTEX_TYPE_POSITION_COLOR_TEXTURE == UINT32_C(1));
static_assert(CNA_VERTEX_TYPE_POSITION_NORMAL_TANGENT_TEXTURE == UINT32_C(2));
static_assert(CNA_VERTEX_TYPE_POSITION_NORMAL_TANGENT_TEXTURE_SKINNED == UINT32_C(3));
static_assert(CNA_VERTEX_TYPE_POSITION_NORMAL_TEXTURE == UINT32_C(4));
static_assert(CNA_VERTEX_TYPE_POSITION_NORMAL_TEXTURE_SKINNED == UINT32_C(5));
static_assert(CNA_VERTEX_TYPE_POSITION_TEXTURE == UINT32_C(6));
static_assert(sizeof(CNA_VertexPositionColor) == 16U);
static_assert(sizeof(CNA_VertexPositionColorTexture) == 24U);
static_assert(sizeof(CNA_VertexPositionNormalTangentTexture) == 48U);
static_assert(sizeof(CNA_VertexPositionNormalTangentTextureSkinned) == 68U);
static_assert(sizeof(CNA_VertexPositionNormalTexture) == 32U);
static_assert(sizeof(CNA_VertexPositionNormalTextureSkinned) == 52U);
static_assert(sizeof(CNA_VertexPositionTexture) == 20U);
static_assert(sizeof(CNA_VertexValue) == 68U);
static_assert(alignof(CNA_VertexValue) == 4U);
static_assert(offsetof(CNA_VertexPositionColor, color) == 12U);
static_assert(offsetof(CNA_VertexPositionColorTexture, texture_coordinate) == 16U);
static_assert(offsetof(CNA_VertexPositionNormalTangentTexture, tangent) == 24U);
static_assert(offsetof(CNA_VertexPositionNormalTangentTexture, texture_coordinate) == 40U);
static_assert(offsetof(CNA_VertexPositionNormalTangentTextureSkinned, blend_weight) == 48U);
static_assert(offsetof(CNA_VertexPositionNormalTangentTextureSkinned, blend_indices) == 64U);
static_assert(offsetof(CNA_VertexPositionNormalTexture, texture_coordinate) == 24U);
static_assert(offsetof(CNA_VertexPositionNormalTextureSkinned, blend_weight) == 32U);
static_assert(offsetof(CNA_VertexPositionNormalTextureSkinned, blend_indices) == 48U);
static_assert(offsetof(CNA_VertexPositionTexture, texture_coordinate) == 12U);
static_assert(sizeof(CNA_VertexDeclarationHandle) == 8U);
static_assert(sizeof(CNA_VertexBufferHandle) == 8U);
static_assert(sizeof(CNA_VertexBufferEventRegistrationHandle) == 8U);
static_assert(sizeof(CNA_VertexBufferCreateInfo) == 32U);
static_assert(alignof(CNA_VertexBufferCreateInfo) == 8U);
static_assert(offsetof(CNA_VertexBufferCreateInfo, vertex_declaration) == 8U);
static_assert(offsetof(CNA_VertexBufferCreateInfo, vertex_count) == 16U);
static_assert(offsetof(CNA_VertexBufferCreateInfo, dynamic) == 24U);
static_assert(sizeof(CNA_VertexBufferInfo) == 32U);
static_assert(alignof(CNA_VertexBufferInfo) == 8U);
static_assert(offsetof(CNA_VertexBufferInfo, vertex_stride) == 20U);
static_assert(offsetof(CNA_VertexBufferInfo, vertex_element_count) == 24U);
static_assert(sizeof(CNA_VertexBufferTransfer) == 32U);
static_assert(alignof(CNA_VertexBufferTransfer) == 8U);
static_assert(offsetof(CNA_VertexBufferTransfer, start_index) == 16U);
static_assert(offsetof(CNA_VertexBufferTransfer, element_count) == 24U);
static_assert(sizeof(CNA_IndexBufferHandle) == 8U);
static_assert(sizeof(CNA_IndexBufferEventRegistrationHandle) == 8U);
static_assert(sizeof(CNA_IndexBufferCreateInfo) == 24U);
static_assert(alignof(CNA_IndexBufferCreateInfo) == 4U);
static_assert(offsetof(CNA_IndexBufferCreateInfo, index_count) == 8U);
static_assert(offsetof(CNA_IndexBufferCreateInfo, index_element_size) == 12U);
static_assert(offsetof(CNA_IndexBufferCreateInfo, dynamic) == 20U);
static_assert(sizeof(CNA_IndexBufferInfo) == 24U);
static_assert(alignof(CNA_IndexBufferInfo) == 4U);
static_assert(offsetof(CNA_IndexBufferInfo, index_count) == 8U);
static_assert(offsetof(CNA_IndexBufferInfo, dynamic) == 20U);
static_assert(sizeof(CNA_IndexBufferTransfer) == 32U);
static_assert(alignof(CNA_IndexBufferTransfer) == 8U);
static_assert(offsetof(CNA_IndexBufferTransfer, start_index) == 16U);
static_assert(offsetof(CNA_IndexBufferTransfer, element_count) == 24U);
static_assert(sizeof(CNA_VertexBufferBinding) == 16U);
static_assert(alignof(CNA_VertexBufferBinding) == 8U);
static_assert(offsetof(CNA_VertexBufferBinding, vertex_buffer) == 0U);
static_assert(offsetof(CNA_VertexBufferBinding, vertex_offset) == 8U);
static_assert(offsetof(CNA_VertexBufferBinding, instance_frequency) == 12U);
static_assert(CNA_MATH_E == 2.71828175F);
static_assert(CNA_MATH_LOG10_E == 0.4342945F);
static_assert(CNA_MATH_LOG2_E == 1.442695F);
static_assert(CNA_MATH_PI == 3.14159274F);
static_assert(CNA_MATH_PI_OVER_2 == 1.57079637F);
static_assert(CNA_MATH_PI_OVER_4 == 0.7853982F);
static_assert(CNA_MATH_TWO_PI == 6.28318548F);
static_assert(CNA_MATH_MACHINE_EPSILON_FLOAT == 5.96046448E-8F);
static_assert(sizeof(CNA_Viewport) == 24U);
static_assert(alignof(CNA_Viewport) == 4U);
static_assert(offsetof(CNA_Viewport, x) == 0U);
static_assert(offsetof(CNA_Viewport, y) == 4U);
static_assert(offsetof(CNA_Viewport, width) == 8U);
static_assert(offsetof(CNA_Viewport, height) == 12U);
static_assert(offsetof(CNA_Viewport, min_depth) == 16U);
static_assert(offsetof(CNA_Viewport, max_depth) == 20U);
static_assert(sizeof(CNA_ClearOptions) == sizeof(uint32_t));
static_assert(CNA_CLEAR_OPTION_TARGET == UINT32_C(1));
static_assert(CNA_CLEAR_OPTION_DEPTH_BUFFER == UINT32_C(2));
static_assert(CNA_CLEAR_OPTION_STENCIL == UINT32_C(4));
static_assert(sizeof(CNA_GraphicsDeviceStatus) == sizeof(uint32_t));
static_assert(CNA_GRAPHICS_DEVICE_STATUS_NORMAL == UINT32_C(0));
static_assert(CNA_GRAPHICS_DEVICE_STATUS_LOST == UINT32_C(1));
static_assert(CNA_GRAPHICS_DEVICE_STATUS_NOT_RESET == UINT32_C(2));
static_assert(sizeof(CNA_Unsupported3DGraphicsCallBehavior) == sizeof(uint32_t));
static_assert(CNA_UNSUPPORTED_3D_GRAPHICS_CALL_BEHAVIOR_THROW == UINT32_C(0));
static_assert(CNA_UNSUPPORTED_3D_GRAPHICS_CALL_BEHAVIOR_WARN_AND_STUB == UINT32_C(1));
static_assert(sizeof(CNA_SpriteEffects) == sizeof(uint32_t));
static_assert((CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY | CNA_SPRITE_EFFECT_FLIP_VERTICALLY) == UINT32_C(3));
static_assert(((CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY | CNA_SPRITE_EFFECT_FLIP_VERTICALLY) &
               CNA_SPRITE_EFFECT_FLIP_VERTICALLY) == CNA_SPRITE_EFFECT_FLIP_VERTICALLY);
static_assert(sizeof(CNA_GraphicsDeviceEventRegistrationHandle) == 8U);
static_assert(sizeof(CNA_GraphicsDeviceEvent) == sizeof(uint32_t));
static_assert(CNA_GRAPHICS_DEVICE_EVENT_DISPOSING == UINT32_C(0));
static_assert(CNA_GRAPHICS_DEVICE_EVENT_DEVICE_LOST == UINT32_C(1));
static_assert(CNA_GRAPHICS_DEVICE_EVENT_DEVICE_RESET == UINT32_C(2));
static_assert(CNA_GRAPHICS_DEVICE_EVENT_DEVICE_RESETTING == UINT32_C(3));
static_assert(sizeof(CNA_ResourceCreatedEventInfo) == 16U);
static_assert(alignof(CNA_ResourceCreatedEventInfo) == 4U);
static_assert(offsetof(CNA_ResourceCreatedEventInfo, has_resource) == 8U);
static_assert(offsetof(CNA_ResourceCreatedEventInfo, reserved) == 9U);
static_assert(sizeof(CNA_ResourceDestroyedEventInfo) == 32U);
static_assert(alignof(CNA_ResourceDestroyedEventInfo) == 8U);
static_assert(offsetof(CNA_ResourceDestroyedEventInfo, has_tag) == 8U);
static_assert(offsetof(CNA_ResourceDestroyedEventInfo, name) == 16U);
static_assert(CNA_TEXTURE_COLLECTION_MAX_TEXTURES == UINT32_C(16));
static_assert(sizeof(CNA_TextureSlotInfo) == 24U);
static_assert(alignof(CNA_TextureSlotInfo) == 8U);
static_assert(offsetof(CNA_TextureSlotInfo, bound) == 8U);
static_assert(offsetof(CNA_TextureSlotInfo, reserved) == 9U);
static_assert(offsetof(CNA_TextureSlotInfo, texture) == 16U);
static_assert(sizeof(CNA_BackBufferReadback) == 48U);
static_assert(alignof(CNA_BackBufferReadback) == 8U);
static_assert(offsetof(CNA_BackBufferReadback, has_source_rectangle) == 8U);
static_assert(offsetof(CNA_BackBufferReadback, source_rectangle) == 12U);
static_assert(offsetof(CNA_BackBufferReadback, start_index) == 32U);
static_assert(offsetof(CNA_BackBufferReadback, element_count) == 40U);
static_assert(sizeof(CNA_UserVertexSource) == sizeof(uint32_t));
static_assert(CNA_USER_VERTEX_SOURCE_RAW_STREAM == UINT32_C(0));
static_assert(CNA_USER_VERTEX_SOURCE_POSITION_NORMAL_TEXTURE == UINT32_C(4));
static_assert(sizeof(CNA_UserPrimitives) == 48U);
static_assert(alignof(CNA_UserPrimitives) == 8U);
static_assert(offsetof(CNA_UserPrimitives, vertex_data) == 16U);
static_assert(offsetof(CNA_UserPrimitives, vertex_declaration) == 24U);
static_assert(offsetof(CNA_UserPrimitives, vertex_offset) == 32U);
static_assert(sizeof(CNA_UserIndices) == 24U);
static_assert(alignof(CNA_UserIndices) == 8U);
static_assert(offsetof(CNA_UserIndices, index_element_size) == 8U);
static_assert(offsetof(CNA_UserIndices, index_data) == 16U);
static_assert(sizeof(CNA_OcclusionQueryHandle) == 8U);
static_assert(sizeof(CNA_SpriteTextCommand) == 72U);
static_assert(alignof(CNA_SpriteTextCommand) == 8U);
static_assert(offsetof(CNA_SpriteTextCommand, sprite_font) == 8U);
static_assert(offsetof(CNA_SpriteTextCommand, text) == 16U);
static_assert(offsetof(CNA_SpriteTextCommand, position) == 32U);
static_assert(sizeof(CNA_SpriteMeshEXT) == 64U);
static_assert(alignof(CNA_SpriteMeshEXT) == 8U);
static_assert(offsetof(CNA_SpriteMeshEXT, effect) == 8U);
static_assert(offsetof(CNA_SpriteMeshEXT, positions) == 16U);
static_assert(offsetof(CNA_SpriteMeshEXT, vertex_count) == 48U);
static_assert(sizeof(CNA_AsciiPostProcessEffectHandle) == 8U);
static_assert(sizeof(CNA_AsciiQuantizeMode) == sizeof(uint32_t));
static_assert(sizeof(CNA_CRTMaskType) == sizeof(uint32_t));
static_assert(sizeof(CNA_DitherMode) == sizeof(uint32_t));
static_assert(sizeof(CNA_RenderQuality) == sizeof(uint32_t));
static_assert(sizeof(CNA_ShadowQuality) == sizeof(uint32_t));
static_assert(sizeof(CNA_TonemappingMode) == sizeof(uint32_t));
static_assert(sizeof(CNA_DepthEffectMode) == sizeof(uint32_t));
static_assert(CNA_CRT_MASK_TYPE_SHADOW_MASK == UINT32_C(2));
static_assert(CNA_DEPTH_EFFECT_MODE_PALETTE_16 == UINT32_C(6));
static_assert(CNA_SHADOW_QUALITY_ULTRA == UINT32_C(4));
static_assert(sizeof(CNA_PbrMaterial) == 72U);
static_assert(alignof(CNA_PbrMaterial) == 8U);
static_assert(offsetof(CNA_PbrMaterial, albedo_color) == 40U);
static_assert(offsetof(CNA_PbrMaterial, emissive_color) == 44U);
static_assert(offsetof(CNA_PbrMaterial, metallic_factor) == 48U);
static_assert(offsetof(CNA_PbrMaterial, alpha_blend_enabled) == 68U);
static_assert(offsetof(CNA_PbrMaterial, reserved) == 69U);
static_assert(sizeof(CNA_RenderPipelineSettings) == 28U);
static_assert(alignof(CNA_RenderPipelineSettings) == 4U);
static_assert(offsetof(CNA_RenderPipelineSettings, tonemapping_mode) == 12U);
static_assert(offsetof(CNA_RenderPipelineSettings, render_quality) == 16U);
static_assert(offsetof(CNA_RenderPipelineSettings, hdr_enabled) == 24U);
static_assert(offsetof(CNA_RenderPipelineSettings, shadows_enabled) == 27U);
static_assert(sizeof(CNA_StorageDeviceHandle) == 8U);
static_assert(sizeof(CNA_StorageContainerHandle) == 8U);
static_assert(sizeof(CNA_StorageStreamHandle) == 8U);
static_assert(sizeof(CNA_FileMode) == sizeof(uint32_t));
static_assert(sizeof(CNA_FileAccess) == sizeof(uint32_t));
static_assert(sizeof(CNA_FileShare) == sizeof(uint32_t));
static_assert(sizeof(CNA_SeekOrigin) == sizeof(uint32_t));
static_assert(CNA_FILE_MODE_CREATE_NEW == UINT32_C(1));
static_assert(CNA_FILE_MODE_APPEND == UINT32_C(6));
static_assert(CNA_FILE_ACCESS_READ_WRITE == UINT32_C(3));
static_assert(CNA_FILE_SHARE_NONE == UINT32_C(0));
static_assert(CNA_FILE_SHARE_INHERITABLE == UINT32_C(16));
static_assert(CNA_SEEK_ORIGIN_END == UINT32_C(2));
