// SPDX-License-Identifier: MS-PL

#include <CNA/C/abi.h>
#include <CNA/C/core.h>
#include <CNA/C/graphics.h>
#include <CNA/C/cna.h>

#include <cstddef>

static_assert(CNA_ABI_VERSION == CNA_ABI_VERSION_ENCODE(0, 1, 0));
static_assert(sizeof(CNA_Result) == sizeof(uint32_t));
static_assert(sizeof(CNA_Handle) == sizeof(uint64_t));
static_assert(sizeof(CNA_ErrorCategory) == sizeof(uint32_t));
static_assert(sizeof(CNA_GameTime) == 24U);
static_assert(sizeof(CNA_Color) == 4U);
static_assert(sizeof(CNA_GraphicsCapability) == sizeof(uint32_t));
static_assert(sizeof(CNA_GraphicsRendererType) == sizeof(uint32_t));
static_assert(sizeof(CNA_GraphicsCapabilityFlags) == sizeof(uint64_t));
static_assert(sizeof(CNA_RendererInfo) == 32U);
static_assert(CNA_GRAPHICS_RENDERER_SDL_RENDERER == UINT32_C(1));
static_assert(CNA_GRAPHICS_RENDERER_PORTABLEGL == UINT32_C(46));
static_assert(CNA_GRAPHICS_CAPABILITY_THREE_D == UINT32_C(0));
static_assert(CNA_GRAPHICS_CAPABILITY_ADDITIVE_BLENDING == UINT32_C(12));
static_assert(sizeof(CNA_SurfaceFormat) == sizeof(uint32_t));
static_assert(CNA_SURFACE_FORMAT_COLOR == UINT32_C(0));
static_assert(CNA_SURFACE_FORMAT_USHORT_EXT == UINT32_C(26));
static_assert(sizeof(CNA_Texture2DCreateInfo) == 24U);
static_assert(sizeof(CNA_Texture2DInfo) == 24U);
static_assert(sizeof(CNA_BackBufferInfo) == 24U);
static_assert(sizeof(CNA_Vector2) == 8U);
static_assert(sizeof(CNA_Rectangle) == 16U);
static_assert(sizeof(CNA_SpriteSortMode) == sizeof(uint32_t));
static_assert(CNA_SPRITE_SORT_MODE_DEFERRED == UINT32_C(0));
static_assert(CNA_SPRITE_SORT_MODE_IMMEDIATE == UINT32_C(1));
static_assert(CNA_SPRITE_SORT_MODE_TEXTURE == UINT32_C(2));
static_assert(CNA_SPRITE_SORT_MODE_BACK_TO_FRONT == UINT32_C(3));
static_assert(CNA_SPRITE_SORT_MODE_FRONT_TO_BACK == UINT32_C(4));
static_assert(sizeof(CNA_SpriteEffects) == sizeof(uint32_t));
static_assert(CNA_SPRITE_EFFECT_NONE == UINT32_C(0));
static_assert(CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY == UINT32_C(1));
static_assert(CNA_SPRITE_EFFECT_FLIP_VERTICALLY == UINT32_C(2));
static_assert(sizeof(CNA_SpriteBatchBeginInfo) == 16U);
static_assert(sizeof(CNA_SpriteCommand) == 72U);
static_assert(sizeof(CNA_Key) == sizeof(uint32_t));
static_assert(CNA_KEY_NONE == UINT32_C(0));
static_assert(CNA_KEY_A == UINT32_C(65));
static_assert(CNA_KEY_F24 == UINT32_C(135));
static_assert(CNA_KEY_OEM_CLEAR == UINT32_C(254));
static_assert(sizeof(CNA_KeyboardState) == 40U);
static_assert(sizeof(CNA_MouseState) == 32U);
static_assert(CNA_MOUSE_BUTTON_LEFT == UINT32_C(1));
static_assert(CNA_MOUSE_BUTTON_X2 == UINT32_C(16));
static_assert(sizeof(CNA_PlayerIndex) == sizeof(uint32_t));
static_assert(CNA_PLAYER_INDEX_ONE == UINT32_C(0));
static_assert(CNA_PLAYER_INDEX_FOUR == UINT32_C(3));
static_assert(sizeof(CNA_GamePadDeadZone) == sizeof(uint32_t));
static_assert(CNA_GAMEPAD_DEAD_ZONE_NONE == UINT32_C(0));
static_assert(CNA_GAMEPAD_DEAD_ZONE_CIRCULAR == UINT32_C(2));
static_assert(CNA_GAMEPAD_BUTTON_DPAD_UP == UINT32_C(1));
static_assert(CNA_GAMEPAD_BUTTON_A == UINT32_C(0x00001000));
static_assert(CNA_GAMEPAD_BUTTON_ALL == UINT32_C(0x7fffffff));
static_assert(sizeof(CNA_GamePadAnalogState) == 24U);
static_assert(sizeof(CNA_GamePadState) == 48U);
static_assert(sizeof(CNA_TouchLocationState) == sizeof(uint32_t));
static_assert(CNA_TOUCH_LOCATION_INVALID == UINT32_C(0));
static_assert(CNA_TOUCH_LOCATION_MOVED == UINT32_C(3));
static_assert(CNA_TOUCH_MAX_TOUCHES == UINT32_C(8));
static_assert(sizeof(CNA_TouchLocation) == 32U);
static_assert(sizeof(CNA_TouchCapabilities) == 16U);
static_assert(sizeof(CNA_TouchState) == 272U);
static_assert(sizeof(CNA_AudioChannels) == sizeof(uint32_t));
static_assert(CNA_AUDIO_CHANNELS_MONO == UINT32_C(1));
static_assert(CNA_AUDIO_CHANNELS_STEREO == UINT32_C(2));
static_assert(sizeof(CNA_SoundState) == sizeof(uint32_t));
static_assert(CNA_SOUND_STATE_PLAYING == UINT32_C(0));
static_assert(CNA_SOUND_STATE_PAUSED == UINT32_C(1));
static_assert(CNA_SOUND_STATE_STOPPED == UINT32_C(2));
static_assert(sizeof(CNA_AudioCapabilities) == 16U);
static_assert(sizeof(CNA_SoundEffectCreateInfo) == 24U);
static_assert(sizeof(CNA_SoundEffectInstanceInfo) == 32U);
static_assert(sizeof(CNA_Vector3) == 12U);
static_assert(sizeof(CNA_Blend) == sizeof(uint32_t));
static_assert(CNA_BLEND_ONE == UINT32_C(0));
static_assert(CNA_BLEND_SOURCE_ALPHA_SATURATION == UINT32_C(12));
static_assert(sizeof(CNA_BlendFunction) == sizeof(uint32_t));
static_assert(CNA_BLEND_FUNCTION_ADD == UINT32_C(0));
static_assert(CNA_BLEND_FUNCTION_MIN == UINT32_C(4));
static_assert(sizeof(CNA_ColorWriteChannels) == sizeof(uint32_t));
static_assert(CNA_COLOR_WRITE_NONE == UINT32_C(0));
static_assert(CNA_COLOR_WRITE_ALL == UINT32_C(15));
static_assert(sizeof(CNA_CompareFunction) == sizeof(uint32_t));
static_assert(CNA_COMPARE_ALWAYS == UINT32_C(0));
static_assert(CNA_COMPARE_NOT_EQUAL == UINT32_C(7));
static_assert(sizeof(CNA_StencilOperation) == sizeof(uint32_t));
static_assert(CNA_STENCIL_KEEP == UINT32_C(0));
static_assert(CNA_STENCIL_INVERT == UINT32_C(7));
static_assert(sizeof(CNA_CullMode) == sizeof(uint32_t));
static_assert(CNA_CULL_NONE == UINT32_C(0));
static_assert(CNA_CULL_COUNTER_CLOCKWISE_FACE == UINT32_C(2));
static_assert(sizeof(CNA_FillMode) == sizeof(uint32_t));
static_assert(CNA_FILL_SOLID == UINT32_C(0));
static_assert(CNA_FILL_WIREFRAME == UINT32_C(1));
static_assert(sizeof(CNA_TextureAddressMode) == sizeof(uint32_t));
static_assert(CNA_TEXTURE_ADDRESS_WRAP == UINT32_C(0));
static_assert(CNA_TEXTURE_ADDRESS_MIRROR == UINT32_C(2));
static_assert(sizeof(CNA_TextureFilter) == sizeof(uint32_t));
static_assert(CNA_TEXTURE_FILTER_LINEAR == UINT32_C(0));
static_assert(CNA_TEXTURE_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT == UINT32_C(8));
static_assert(sizeof(CNA_BlendState) == 56U);
static_assert(sizeof(CNA_DepthStencilState) == 64U);
static_assert(sizeof(CNA_RasterizerState) == 28U);
static_assert(sizeof(CNA_SamplerState) == 40U);
static_assert(sizeof(CNA_DepthFormat) == sizeof(uint32_t));
static_assert(CNA_DEPTH_FORMAT_NONE == UINT32_C(0));
static_assert(CNA_DEPTH_FORMAT_DEPTH24_STENCIL8 == UINT32_C(3));
static_assert(sizeof(CNA_RenderTargetUsage) == sizeof(uint32_t));
static_assert(CNA_RENDER_TARGET_USAGE_DISCARD_CONTENTS == UINT32_C(0));
static_assert(CNA_RENDER_TARGET_USAGE_PLATFORM_CONTENTS == UINT32_C(2));
static_assert(sizeof(CNA_CubeMapFace) == sizeof(uint32_t));
static_assert(CNA_CUBE_MAP_FACE_POSITIVE_X == UINT32_C(0));
static_assert(CNA_CUBE_MAP_FACE_NEGATIVE_Z == UINT32_C(5));
static_assert(sizeof(CNA_RenderTarget2DCreateInfo) == 40U);
static_assert(sizeof(CNA_RenderTargetCubeCreateInfo) == 32U);
static_assert(sizeof(CNA_RenderTargetInfo) == 44U);
static_assert(sizeof(CNA_RenderTargetBinding) == 24U);
static_assert(sizeof(CNA_Char16) == sizeof(uint16_t));
static_assert(sizeof(CNA_SpriteFontGlyph) == 56U);
static_assert(sizeof(((CNA_SpriteFontCreateInfo*)nullptr)->glyphs) == sizeof(void*));
static_assert(sizeof(CNA_SpriteFontInfo) == 32U);
static_assert(sizeof(CNA_GraphicsProfile) == sizeof(uint32_t));
static_assert(CNA_GRAPHICS_PROFILE_REACH == UINT32_C(0));
static_assert(CNA_GRAPHICS_PROFILE_HI_DEF == UINT32_C(1));
static_assert(sizeof(CNA_PresentInterval) == sizeof(uint32_t));
static_assert(CNA_PRESENT_INTERVAL_DEFAULT == UINT32_C(0));
static_assert(CNA_PRESENT_INTERVAL_IMMEDIATE == UINT32_C(3));
static_assert(sizeof(CNA_DisplayOrientation) == sizeof(uint32_t));
static_assert(CNA_DISPLAY_ORIENTATION_DEFAULT == UINT32_C(0));
static_assert(CNA_DISPLAY_ORIENTATION_PORTRAIT == UINT32_C(4));
static_assert(sizeof(CNA_NativeHandleValue) == sizeof(uint64_t));
static_assert(sizeof(CNA_DisplayMode) == 24U);
static_assert(sizeof(CNA_GraphicsAdapterInfo) == 48U);
static_assert(sizeof(CNA_GraphicsFormatSelection) == 24U);
static_assert(sizeof(CNA_PresentationParameters) == 44U);
static_assert(sizeof(CNA_ContainmentType) == sizeof(uint32_t));
static_assert(CNA_CONTAINMENT_DISJOINT == UINT32_C(0));
static_assert(CNA_CONTAINMENT_CONTAINS == UINT32_C(1));
static_assert(CNA_CONTAINMENT_INTERSECTS == UINT32_C(2));
static_assert(sizeof(CNA_PlaneIntersectionType) == sizeof(uint32_t));
static_assert(CNA_PLANE_INTERSECTION_FRONT == UINT32_C(0));
static_assert(CNA_PLANE_INTERSECTION_BACK == UINT32_C(1));
static_assert(CNA_PLANE_INTERSECTION_INTERSECTING == UINT32_C(2));
static_assert(CNA_CURVE_CONTINUITY_SMOOTH == UINT32_C(0));
static_assert(CNA_CURVE_CONTINUITY_STEP == UINT32_C(1));
static_assert(CNA_CURVE_LOOP_CONSTANT == UINT32_C(0));
static_assert(CNA_CURVE_LOOP_CYCLE == UINT32_C(1));
static_assert(CNA_CURVE_LOOP_CYCLE_OFFSET == UINT32_C(2));
static_assert(CNA_CURVE_LOOP_OSCILLATE == UINT32_C(3));
static_assert(CNA_CURVE_LOOP_LINEAR == UINT32_C(4));
static_assert(CNA_CURVE_TANGENT_FLAT == UINT32_C(0));
static_assert(CNA_CURVE_TANGENT_LINEAR == UINT32_C(1));
static_assert(CNA_CURVE_TANGENT_SMOOTH == UINT32_C(2));
static_assert(sizeof(CNA_Point) == 8U);
static_assert(sizeof(CNA_Vector4) == 16U);
static_assert(sizeof(CNA_Quaternion) == 16U);
static_assert(alignof(CNA_Point) == 4U);
static_assert(alignof(CNA_Vector4) == 4U);
static_assert(alignof(CNA_Quaternion) == 4U);
static_assert(offsetof(CNA_Point, x) == 0U);
static_assert(offsetof(CNA_Point, y) == 4U);
static_assert(offsetof(CNA_Vector4, x) == 0U);
static_assert(offsetof(CNA_Vector4, y) == 4U);
static_assert(offsetof(CNA_Vector4, z) == 8U);
static_assert(offsetof(CNA_Vector4, w) == 12U);
static_assert(offsetof(CNA_Quaternion, x) == 0U);
static_assert(offsetof(CNA_Quaternion, y) == 4U);
static_assert(offsetof(CNA_Quaternion, z) == 8U);
static_assert(offsetof(CNA_Quaternion, w) == 12U);
static_assert(sizeof(CNA_Matrix) == 64U);
static_assert(sizeof(CNA_Plane) == 16U);
static_assert(sizeof(CNA_Ray) == 24U);
static_assert(offsetof(CNA_Matrix, m11) == 0U);
static_assert(offsetof(CNA_Matrix, m12) == 4U);
static_assert(offsetof(CNA_Matrix, m13) == 8U);
static_assert(offsetof(CNA_Matrix, m14) == 12U);
static_assert(offsetof(CNA_Matrix, m21) == 16U);
static_assert(offsetof(CNA_Matrix, m22) == 20U);
static_assert(offsetof(CNA_Matrix, m23) == 24U);
static_assert(offsetof(CNA_Matrix, m24) == 28U);
static_assert(offsetof(CNA_Matrix, m31) == 32U);
static_assert(offsetof(CNA_Matrix, m32) == 36U);
static_assert(offsetof(CNA_Matrix, m33) == 40U);
static_assert(offsetof(CNA_Matrix, m34) == 44U);
static_assert(offsetof(CNA_Matrix, m41) == 48U);
static_assert(offsetof(CNA_Matrix, m42) == 52U);
static_assert(offsetof(CNA_Matrix, m43) == 56U);
static_assert(offsetof(CNA_Matrix, m44) == 60U);
static_assert(offsetof(CNA_Plane, normal) == 0U);
static_assert(offsetof(CNA_Plane, d) == 12U);
static_assert(offsetof(CNA_Ray, position) == 0U);
static_assert(offsetof(CNA_Ray, direction) == 12U);
static_assert(sizeof(CNA_BoundingBox) == 24U);
static_assert(sizeof(CNA_BoundingSphere) == 16U);
static_assert(sizeof(CNA_BoundingFrustum) == 64U);
static_assert(offsetof(CNA_BoundingBox, min) == 0U);
static_assert(offsetof(CNA_BoundingBox, max) == 12U);
static_assert(offsetof(CNA_BoundingSphere, center) == 0U);
static_assert(offsetof(CNA_BoundingSphere, radius) == 12U);
static_assert(offsetof(CNA_BoundingFrustum, matrix) == 0U);
static_assert(sizeof(CNA_CurveKey) == 20U);
static_assert(sizeof(CNA_CurveKeyCollectionHandle) == 8U);
static_assert(alignof(CNA_CurveKey) == 4U);
static_assert(offsetof(CNA_CurveKey, position) == 0U);
static_assert(offsetof(CNA_CurveKey, value) == 4U);
static_assert(offsetof(CNA_CurveKey, tangent_in) == 8U);
static_assert(offsetof(CNA_CurveKey, tangent_out) == 12U);
static_assert(offsetof(CNA_CurveKey, continuity) == 16U);
static_assert(sizeof(CNA_PackedAlpha8) == 1U);
static_assert(sizeof(CNA_PackedBgr565) == 2U);
static_assert(sizeof(CNA_PackedBgra4444) == 2U);
static_assert(sizeof(CNA_PackedBgra5551) == 2U);
static_assert(sizeof(CNA_PackedByte4) == 4U);
static_assert(sizeof(CNA_PackedHalfSingle) == 2U);
static_assert(sizeof(CNA_PackedHalfVector2) == 4U);
static_assert(sizeof(CNA_PackedHalfVector4) == 8U);
static_assert(sizeof(CNA_PackedNormalizedByte2) == 2U);
static_assert(sizeof(CNA_PackedNormalizedByte4) == 4U);
static_assert(sizeof(CNA_PackedNormalizedShort2) == 4U);
static_assert(sizeof(CNA_PackedNormalizedShort4) == 8U);
static_assert(sizeof(CNA_PackedRg32) == 4U);
static_assert(sizeof(CNA_PackedRgba1010102) == 4U);
static_assert(sizeof(CNA_PackedRgba64) == 8U);
static_assert(sizeof(CNA_PackedShort2) == 4U);
static_assert(sizeof(CNA_PackedShort4) == 8U);
static_assert(sizeof(CNA_BufferUsage) == sizeof(uint32_t));
static_assert(CNA_BUFFER_USAGE_NONE == UINT32_C(0));
static_assert(CNA_BUFFER_USAGE_WRITE_ONLY == UINT32_C(1));
static_assert(sizeof(CNA_IndexElementSize) == sizeof(uint32_t));
static_assert(CNA_INDEX_ELEMENT_SIZE_SIXTEEN_BITS == UINT32_C(0));
static_assert(CNA_INDEX_ELEMENT_SIZE_THIRTY_TWO_BITS == UINT32_C(1));
static_assert(sizeof(CNA_PrimitiveType) == sizeof(uint32_t));
static_assert(CNA_PRIMITIVE_TRIANGLE_LIST == UINT32_C(0));
static_assert(CNA_PRIMITIVE_TRIANGLE_STRIP == UINT32_C(1));
static_assert(CNA_PRIMITIVE_LINE_LIST == UINT32_C(2));
static_assert(CNA_PRIMITIVE_LINE_STRIP == UINT32_C(3));
static_assert(CNA_PRIMITIVE_POINT_LIST_EXT == UINT32_C(4));
static_assert(sizeof(CNA_SetDataOptions) == sizeof(uint32_t));
static_assert(CNA_SET_DATA_NONE == UINT32_C(0));
static_assert(CNA_SET_DATA_DISCARD == UINT32_C(1));
static_assert(CNA_SET_DATA_NO_OVERWRITE == UINT32_C(2));
static_assert(sizeof(CNA_VertexElementFormat) == sizeof(uint32_t));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_SINGLE == UINT32_C(0));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_VECTOR2 == UINT32_C(1));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_VECTOR3 == UINT32_C(2));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_VECTOR4 == UINT32_C(3));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_COLOR == UINT32_C(4));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_BYTE4 == UINT32_C(5));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_SHORT2 == UINT32_C(6));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_SHORT4 == UINT32_C(7));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_NORMALIZED_SHORT2 == UINT32_C(8));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_NORMALIZED_SHORT4 == UINT32_C(9));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_HALF_VECTOR2 == UINT32_C(10));
static_assert(CNA_VERTEX_ELEMENT_FORMAT_HALF_VECTOR4 == UINT32_C(11));
static_assert(sizeof(CNA_VertexElementUsage) == sizeof(uint32_t));
static_assert(CNA_VERTEX_ELEMENT_USAGE_POSITION == UINT32_C(0));
static_assert(CNA_VERTEX_ELEMENT_USAGE_COLOR == UINT32_C(1));
static_assert(CNA_VERTEX_ELEMENT_USAGE_TEXTURE_COORDINATE == UINT32_C(2));
static_assert(CNA_VERTEX_ELEMENT_USAGE_NORMAL == UINT32_C(3));
static_assert(CNA_VERTEX_ELEMENT_USAGE_BINORMAL == UINT32_C(4));
static_assert(CNA_VERTEX_ELEMENT_USAGE_TANGENT == UINT32_C(5));
static_assert(CNA_VERTEX_ELEMENT_USAGE_BLEND_INDICES == UINT32_C(6));
static_assert(CNA_VERTEX_ELEMENT_USAGE_BLEND_WEIGHT == UINT32_C(7));
static_assert(CNA_VERTEX_ELEMENT_USAGE_DEPTH == UINT32_C(8));
static_assert(CNA_VERTEX_ELEMENT_USAGE_FOG == UINT32_C(9));
static_assert(CNA_VERTEX_ELEMENT_USAGE_POINT_SIZE == UINT32_C(10));
static_assert(CNA_VERTEX_ELEMENT_USAGE_SAMPLE == UINT32_C(11));
static_assert(CNA_VERTEX_ELEMENT_USAGE_TESSELLATE_FACTOR == UINT32_C(12));
static_assert(sizeof(CNA_VertexElement) == 16U);
static_assert(alignof(CNA_VertexElement) == 4U);
static_assert(offsetof(CNA_VertexElement, offset) == 0U);
static_assert(offsetof(CNA_VertexElement, format) == 4U);
static_assert(offsetof(CNA_VertexElement, usage) == 8U);
static_assert(offsetof(CNA_VertexElement, usage_index) == 12U);
static_assert(CNA_MATH_E == 2.71828175F);
static_assert(CNA_MATH_LOG10_E == 0.4342945F);
static_assert(CNA_MATH_LOG2_E == 1.442695F);
static_assert(CNA_MATH_PI == 3.14159274F);
static_assert(CNA_MATH_PI_OVER_2 == 1.57079637F);
static_assert(CNA_MATH_PI_OVER_4 == 0.7853982F);
static_assert(CNA_MATH_TWO_PI == 6.28318548F);
static_assert(CNA_MATH_MACHINE_EPSILON_FLOAT == 5.96046448E-8F);
