// SPDX-License-Identifier: MS-PL
// Generated by tools/shader_package/generate_shader_package.py. Do not edit.
#pragma once

#ifdef CNA_CNAEXT

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace CNA::Graphics::detail::ClusteredLightComputeGenerated {

struct PayloadProvenance
{
    std::string_view symbol;
    std::string_view source;
    std::string_view sourceSha256;
    std::string_view language;
    std::string_view sourceLanguage;
    std::string_view stage;
    std::string_view format;
    std::string_view entryPoint;
};

inline constexpr std::string_view kPackageName = "clustered_light_compute";
inline constexpr std::string_view kManifestSha256 = "6861952d8010b118d540b86cf30fb448473581e64a790e35117dd1cb1dfc4434";
inline constexpr std::string_view kCompiler = "shaderc shared library";
inline constexpr std::string_view kCompilerSoname = "libshaderc.so.1";
inline constexpr std::string_view kCompilerSha256 = "31400b359d2f4b4a43168978412a72913474725befb87966068cfac1922ac6c9";
inline constexpr std::uint32_t kCompilerSpirVVersion = 0x00010600u;
inline constexpr std::uint32_t kCompilerSpirVRevision = 1u;
inline constexpr std::string_view kCompilerTarget = "Vulkan 1.0 / SPIR-V 1.0";
inline constexpr std::string_view kCompilerOptimization = "performance";
inline constexpr std::string_view kWgslTranslator = "naga-cli";
inline constexpr std::string_view kWgslTranslatorVersion = "28.0.0";
inline constexpr std::string_view kWgslTranslatorSha256 = "6721540d62bd3f618ca4c19ab1b70033a5a286a69e34e1eeca38079bdf392481";
inline constexpr std::string_view kWgslSourceTransform = "cna-webgpu-glsl/1";

inline constexpr std::string_view kAssignEsComputeSource =
    R"CNA_SHADER(#version 310 es
precision highp float;
precision highp int;

layout(local_size_x = 64) in;
layout(std430, binding = 0) readonly buffer CnaLights { vec4 uLights[]; };
layout(std430, binding = 1) readonly buffer CnaMatrix { float uInverseProjection[]; };
layout(std430, binding = 2) buffer CnaCounts { int uCounts[]; };
layout(std430, binding = 3) buffer CnaIndices { int uIndices[]; };
layout(std140, binding = 4) uniform ClusteredLightParameters
{
    ivec4 uGrid;
    ivec4 uOutput;
    vec4 uDepth;
};

vec3 cnaUnproject(mat4 inverseProjection, float x, float y, float z)
{
    vec4 p = inverseProjection * vec4(x, y, z, 1.0);
    if (abs(p.w) <= 1e-9)
        return p.xyz;
    return p.xyz / p.w;
}

vec3 cnaAtDistance(vec3 atNear, vec3 atFar, float distance)
{
    float span = atNear.z - atFar.z;
    if (abs(span) <= 1e-9)
        return atNear;
    float t = (atNear.z + distance) / span;
    return vec3(atNear.x + (atFar.x - atNear.x) * t,
                atNear.y + (atFar.y - atNear.y) * t,
                -distance);
}

float cnaSliceDistance(int slice)
{
    if (slice == 0)
        return uDepth.x;
    if (slice == uGrid.z)
        return uDepth.y;
    return uDepth.x * pow(uDepth.y / uDepth.x, float(slice) / float(uGrid.z));
}

void main()
{
    int cluster = int(gl_GlobalInvocationID.x);
    if (cluster >= uOutput.y)
        return;

    int x = cluster % uGrid.x;
    int y = (cluster / uGrid.x) % uGrid.y;
    int slice = cluster / (uGrid.x * uGrid.y);

    mat4 inverseProjection = mat4(
        uInverseProjection[0],  uInverseProjection[1],  uInverseProjection[2],  uInverseProjection[3],
        uInverseProjection[4],  uInverseProjection[5],  uInverseProjection[6],  uInverseProjection[7],
        uInverseProjection[8],  uInverseProjection[9],  uInverseProjection[10], uInverseProjection[11],
        uInverseProjection[12], uInverseProjection[13], uInverseProjection[14], uInverseProjection[15]);

    float u0 = 2.0 * float(x) / float(uGrid.x) - 1.0;
    float u1 = 2.0 * float(x + 1) / float(uGrid.x) - 1.0;
    float v0 = 2.0 * float(y) / float(uGrid.y) - 1.0;
    float v1 = 2.0 * float(y + 1) / float(uGrid.y) - 1.0;
    float d0 = cnaSliceDistance(slice);
    float d1 = cnaSliceDistance(slice + 1);

    vec3 minimum = vec3(3.4028235e38);
    vec3 maximum = vec3(-3.4028235e38);
    for (int i = 0; i < 2; ++i)
    {
        float u = i == 0 ? u0 : u1;
        for (int j = 0; j < 2; ++j)
        {
            float v = j == 0 ? v0 : v1;
            vec3 atNear = cnaUnproject(inverseProjection, u, v, 0.0);
            vec3 atFar = cnaUnproject(inverseProjection, u, v, 1.0);
            for (int k = 0; k < 2; ++k)
            {
                vec3 p = cnaAtDistance(atNear, atFar, k == 0 ? d0 : d1);
                minimum = min(minimum, p);
                maximum = max(maximum, p);
            }
        }
    }

    int found = 0;
    for (int light = 0; light < uGrid.w; ++light)
    {
        vec4 sphere = uLights[light];
        if (sphere.w <= 0.0)
            continue;
        vec3 nearest = clamp(sphere.xyz, minimum, maximum);
        vec3 delta = sphere.xyz - nearest;
        if (dot(delta, delta) > sphere.w * sphere.w)
            continue;
        if (found < uOutput.x)
            uIndices[cluster * uOutput.x + found] = light;
        ++found;
    }

    uCounts[cluster] = min(found, uOutput.x);
    if (found > uOutput.x)
        uCounts[uOutput.y] = 1;
}
)CNA_SHADER";

inline constexpr std::string_view kAssignDesktopComputeSource =
    R"CNA_SHADER(#version 430 core

layout(local_size_x = 64) in;
layout(std430, binding = 0) readonly buffer CnaLights { vec4 uLights[]; };
layout(std430, binding = 1) readonly buffer CnaMatrix { float uInverseProjection[]; };
layout(std430, binding = 2) buffer CnaCounts { int uCounts[]; };
layout(std430, binding = 3) buffer CnaIndices { int uIndices[]; };
layout(std140, binding = 4) uniform ClusteredLightParameters
{
    ivec4 uGrid;
    ivec4 uOutput;
    vec4 uDepth;
};

vec3 cnaUnproject(mat4 inverseProjection, float x, float y, float z)
{
    vec4 p = inverseProjection * vec4(x, y, z, 1.0);
    if (abs(p.w) <= 1e-9)
        return p.xyz;
    return p.xyz / p.w;
}

vec3 cnaAtDistance(vec3 atNear, vec3 atFar, float distance)
{
    float span = atNear.z - atFar.z;
    if (abs(span) <= 1e-9)
        return atNear;
    float t = (atNear.z + distance) / span;
    return vec3(atNear.x + (atFar.x - atNear.x) * t,
                atNear.y + (atFar.y - atNear.y) * t,
                -distance);
}

float cnaSliceDistance(int slice)
{
    if (slice == 0)
        return uDepth.x;
    if (slice == uGrid.z)
        return uDepth.y;
    return uDepth.x * pow(uDepth.y / uDepth.x, float(slice) / float(uGrid.z));
}

void main()
{
    int cluster = int(gl_GlobalInvocationID.x);
    if (cluster >= uOutput.y)
        return;

    int x = cluster % uGrid.x;
    int y = (cluster / uGrid.x) % uGrid.y;
    int slice = cluster / (uGrid.x * uGrid.y);

    mat4 inverseProjection = mat4(
        uInverseProjection[0],  uInverseProjection[1],  uInverseProjection[2],  uInverseProjection[3],
        uInverseProjection[4],  uInverseProjection[5],  uInverseProjection[6],  uInverseProjection[7],
        uInverseProjection[8],  uInverseProjection[9],  uInverseProjection[10], uInverseProjection[11],
        uInverseProjection[12], uInverseProjection[13], uInverseProjection[14], uInverseProjection[15]);

    float u0 = 2.0 * float(x) / float(uGrid.x) - 1.0;
    float u1 = 2.0 * float(x + 1) / float(uGrid.x) - 1.0;
    float v0 = 2.0 * float(y) / float(uGrid.y) - 1.0;
    float v1 = 2.0 * float(y + 1) / float(uGrid.y) - 1.0;
    float d0 = cnaSliceDistance(slice);
    float d1 = cnaSliceDistance(slice + 1);

    vec3 minimum = vec3(3.4028235e38);
    vec3 maximum = vec3(-3.4028235e38);
    for (int i = 0; i < 2; ++i)
    {
        float u = i == 0 ? u0 : u1;
        for (int j = 0; j < 2; ++j)
        {
            float v = j == 0 ? v0 : v1;
            vec3 atNear = cnaUnproject(inverseProjection, u, v, 0.0);
            vec3 atFar = cnaUnproject(inverseProjection, u, v, 1.0);
            for (int k = 0; k < 2; ++k)
            {
                vec3 p = cnaAtDistance(atNear, atFar, k == 0 ? d0 : d1);
                minimum = min(minimum, p);
                maximum = max(maximum, p);
            }
        }
    }

    int found = 0;
    for (int light = 0; light < uGrid.w; ++light)
    {
        vec4 sphere = uLights[light];
        if (sphere.w <= 0.0)
            continue;
        vec3 nearest = clamp(sphere.xyz, minimum, maximum);
        vec3 delta = sphere.xyz - nearest;
        if (dot(delta, delta) > sphere.w * sphere.w)
            continue;
        if (found < uOutput.x)
            uIndices[cluster * uOutput.x + found] = light;
        ++found;
    }

    uCounts[cluster] = min(found, uOutput.x);
    if (found > uOutput.x)
        uCounts[uOutput.y] = 1;
}
)CNA_SHADER";

inline constexpr std::uint32_t kAssignVulkanComputeSpirV[] = {
    0x07230203u, 0x00010000u, 0x000d000bu, 0x000002cbu, 0x00000000u, 0x00020011u, 0x00000001u, 0x0006000bu,
    0x00000001u, 0x4c534c47u, 0x6474732eu, 0x3035342eu, 0x00000000u, 0x0003000eu, 0x00000000u, 0x00000001u,
    0x0006000fu, 0x00000005u, 0x00000004u, 0x6e69616du, 0x00000000u, 0x0000009au, 0x00060010u, 0x00000004u,
    0x00000011u, 0x00000040u, 0x00000001u, 0x00000001u, 0x00030047u, 0x00000074u, 0x00000002u, 0x00050048u,
    0x00000074u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00050048u, 0x00000074u, 0x00000001u, 0x00000023u,
    0x00000010u, 0x00050048u, 0x00000074u, 0x00000002u, 0x00000023u, 0x00000020u, 0x00040047u, 0x00000076u,
    0x00000021u, 0x00000004u, 0x00040047u, 0x00000076u, 0x00000022u, 0x00000000u, 0x00040047u, 0x0000009au,
    0x0000000bu, 0x0000001cu, 0x00040047u, 0x000000bdu, 0x00000006u, 0x00000004u, 0x00030047u, 0x000000beu,
    0x00000003u, 0x00040048u, 0x000000beu, 0x00000000u, 0x00000018u, 0x00050048u, 0x000000beu, 0x00000000u,
    0x00000023u, 0x00000000u, 0x00030047u, 0x000000c0u, 0x00000018u, 0x00040047u, 0x000000c0u, 0x00000021u,
    0x00000001u, 0x00040047u, 0x000000c0u, 0x00000022u, 0x00000000u, 0x00040047u, 0x00000184u, 0x00000006u,
    0x00000010u, 0x00030047u, 0x00000185u, 0x00000003u, 0x00040048u, 0x00000185u, 0x00000000u, 0x00000018u,
    0x00050048u, 0x00000185u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00030047u, 0x00000187u, 0x00000018u,
    0x00040047u, 0x00000187u, 0x00000021u, 0x00000000u, 0x00040047u, 0x00000187u, 0x00000022u, 0x00000000u,
    0x00040047u, 0x000001afu, 0x00000006u, 0x00000004u, 0x00030047u, 0x000001b0u, 0x00000003u, 0x00050048u,
    0x000001b0u, 0x00000000u, 0x00000023u, 0x00000000u, 0x00040047u, 0x000001b2u, 0x00000021u, 0x00000003u,
    0x00040047u, 0x000001b2u, 0x00000022u, 0x00000000u, 0x00040047u, 0x000001bfu, 0x00000006u, 0x00000004u,
    0x00030047u, 0x000001c0u, 0x00000003u, 0x00050048u, 0x000001c0u, 0x00000000u, 0x00000023u, 0x00000000u,
    0x00040047u, 0x000001c2u, 0x00000021u, 0x00000002u, 0x00040047u, 0x000001c2u, 0x00000022u, 0x00000000u,
    0x00040047u, 0x000001d3u, 0x0000000bu, 0x00000019u, 0x00020013u, 0x00000002u, 0x00030021u, 0x00000003u,
    0x00000002u, 0x00030016u, 0x00000006u, 0x00000020u, 0x00040017u, 0x00000007u, 0x00000006u, 0x00000004u,
    0x00040018u, 0x00000008u, 0x00000007u, 0x00000004u, 0x00040017u, 0x0000000bu, 0x00000006u, 0x00000003u,
    0x00040015u, 0x0000001au, 0x00000020u, 0x00000001u, 0x0004002bu, 0x00000006u, 0x00000026u, 0x3f800000u,
    0x00040015u, 0x00000029u, 0x00000020u, 0x00000000u, 0x0004002bu, 0x00000029u, 0x0000002au, 0x00000003u,
    0x0004002bu, 0x00000006u, 0x0000002eu, 0x3089705fu, 0x00020014u, 0x0000002fu, 0x0004002bu, 0x00000029u,
    0x0000003fu, 0x00000002u, 0x0004002bu, 0x00000029u, 0x00000053u, 0x00000000u, 0x0004002bu, 0x00000029u,
    0x0000005eu, 0x00000001u, 0x0004002bu, 0x0000001au, 0x0000006fu, 0x00000000u, 0x00040017u, 0x00000073u,
    0x0000001au, 0x00000004u, 0x0005001eu, 0x00000074u, 0x00000073u, 0x00000073u, 0x00000007u, 0x00040020u,
    0x00000075u, 0x00000002u, 0x00000074u, 0x0004003bu, 0x00000075u, 0x00000076u, 0x00000002u, 0x0004002bu,
    0x0000001au, 0x00000077u, 0x00000002u, 0x00040020u, 0x00000078u, 0x00000002u, 0x00000006u, 0x00040020u,
    0x0000007du, 0x00000002u, 0x0000001au, 0x00040017u, 0x00000098u, 0x00000029u, 0x00000003u, 0x00040020u,
    0x00000099u, 0x00000001u, 0x00000098u, 0x0004003bu, 0x00000099u, 0x0000009au, 0x00000001u, 0x00040020u,
    0x0000009bu, 0x00000001u, 0x00000029u, 0x0004002bu, 0x0000001au, 0x000000a0u, 0x00000001u, 0x0003001du,
    0x000000bdu, 0x00000006u, 0x0003001eu, 0x000000beu, 0x000000bdu, 0x00040020u, 0x000000bfu, 0x00000002u,
    0x000000beu, 0x0004003bu, 0x000000bfu, 0x000000c0u, 0x00000002u, 0x0004002bu, 0x0000001au, 0x000000c7u,
    0x00000003u, 0x0004002bu, 0x0000001au, 0x000000cau, 0x00000004u, 0x0004002bu, 0x0000001au, 0x000000cdu,
    0x00000005u, 0x0004002bu, 0x0000001au, 0x000000d0u, 0x00000006u, 0x0004002bu, 0x0000001au, 0x000000d3u,
    0x00000007u, 0x0004002bu, 0x0000001au, 0x000000d6u, 0x00000008u, 0x0004002bu, 0x0000001au, 0x000000d9u,
    0x00000009u, 0x0004002bu, 0x0000001au, 0x000000dcu, 0x0000000au, 0x0004002bu, 0x0000001au, 0x000000dfu,
    0x0000000bu, 0x0004002bu, 0x0000001au, 0x000000e2u, 0x0000000cu, 0x0004002bu, 0x0000001au, 0x000000e5u,
    0x0000000du, 0x0004002bu, 0x0000001au, 0x000000e8u, 0x0000000eu, 0x0004002bu, 0x0000001au, 0x000000ebu,
    0x0000000fu, 0x0004002bu, 0x00000006u, 0x000000eeu, 0x00000000u, 0x0004002bu, 0x00000006u, 0x000000f5u,
    0x40000000u, 0x0004002bu, 0x00000006u, 0x00000125u, 0x7f7fffffu, 0x0006002cu, 0x0000000bu, 0x00000126u,
    0x00000125u, 0x00000125u, 0x00000125u, 0x0004002bu, 0x00000006u, 0x00000128u, 0xff7fffffu, 0x0006002cu,
    0x0000000bu, 0x00000129u, 0x00000128u, 0x00000128u, 0x00000128u, 0x0003001du, 0x00000184u, 0x00000007u,
    0x0003001eu, 0x00000185u, 0x00000184u, 0x00040020u, 0x00000186u, 0x00000002u, 0x00000185u, 0x0004003bu,
    0x00000186u, 0x00000187u, 0x00000002u, 0x00040020u, 0x00000189u, 0x00000002u, 0x00000007u, 0x0003001du,
    0x000001afu, 0x0000001au, 0x0003001eu, 0x000001b0u, 0x000001afu, 0x00040020u, 0x000001b1u, 0x00000002u,
    0x000001b0u, 0x0004003bu, 0x000001b1u, 0x000001b2u, 0x00000002u, 0x0003001du, 0x000001bfu, 0x0000001au,
    0x0003001eu, 0x000001c0u, 0x000001bfu, 0x00040020u, 0x000001c1u, 0x00000002u, 0x000001c0u, 0x0004003bu,
    0x000001c1u, 0x000001c2u, 0x00000002u, 0x0004002bu, 0x00000029u, 0x000001d2u, 0x00000040u, 0x0006002cu,
    0x00000098u, 0x000001d3u, 0x000001d2u, 0x0000005eu, 0x0000005eu, 0x00050036u, 0x00000002u, 0x00000004u,
    0x00000000u, 0x00000003u, 0x000200f8u, 0x00000005u, 0x000300f7u, 0x000001d4u, 0x00000000u, 0x000300fbu,
    0x00000053u, 0x000001d5u, 0x000200f8u, 0x000001d5u, 0x00050041u, 0x0000009bu, 0x0000009cu, 0x0000009au,
    0x00000053u, 0x0004003du, 0x00000029u, 0x0000009du, 0x0000009cu, 0x0004007cu, 0x0000001au, 0x0000009eu,
    0x0000009du, 0x00060041u, 0x0000007du, 0x000000a1u, 0x00000076u, 0x000000a0u, 0x0000005eu, 0x0004003du,
    0x0000001au, 0x000000a2u, 0x000000a1u, 0x000500afu, 0x0000002fu, 0x000000a3u, 0x0000009eu, 0x000000a2u,
    0x000300f7u, 0x000000a5u, 0x00000000u, 0x000400fau, 0x000000a3u, 0x000000a4u, 0x000000a5u, 0x000200f8u,
    0x000000a4u, 0x000200f9u, 0x000001d4u, 0x000200f8u, 0x000000a5u, 0x00060041u, 0x0000007du, 0x000000a9u,
    0x00000076u, 0x0000006fu, 0x00000053u, 0x0004003du, 0x0000001au, 0x000000aau, 0x000000a9u, 0x0005008bu,
    0x0000001au, 0x000000abu, 0x0000009eu, 0x000000aau, 0x00050087u, 0x0000001au, 0x000000b0u, 0x0000009eu,
    0x000000aau, 0x00060041u, 0x0000007du, 0x000000b1u, 0x00000076u, 0x0000006fu, 0x0000005eu, 0x0004003du,
    0x0000001au, 0x000000b2u, 0x000000b1u, 0x0005008bu, 0x0000001au, 0x000000b3u, 0x000000b0u, 0x000000b2u,
    0x00050084u, 0x0000001au, 0x000000bau, 0x000000aau, 0x000000b2u, 0x00050087u, 0x0000001au, 0x000000bbu,
    0x0000009eu, 0x000000bau, 0x00060041u, 0x00000078u, 0x000000c1u, 0x000000c0u, 0x0000006fu, 0x0000006fu,
    0x0004003du, 0x00000006u, 0x000000c2u, 0x000000c1u, 0x00060041u, 0x00000078u, 0x000000c3u, 0x000000c0u,
    0x0000006fu, 0x000000a0u, 0x0004003du, 0x00000006u, 0x000000c4u, 0x000000c3u, 0x00060041u, 0x00000078u,
    0x000000c5u, 0x000000c0u, 0x0000006fu, 0x00000077u, 0x0004003du, 0x00000006u, 0x000000c6u, 0x000000c5u,
    0x00060041u, 0x00000078u, 0x000000c8u, 0x000000c0u, 0x0000006fu, 0x000000c7u, 0x0004003du, 0x00000006u,
    0x000000c9u, 0x000000c8u, 0x00060041u, 0x00000078u, 0x000000cbu, 0x000000c0u, 0x0000006fu, 0x000000cau,
    0x0004003du, 0x00000006u, 0x000000ccu, 0x000000cbu, 0x00060041u, 0x00000078u, 0x000000ceu, 0x000000c0u,
    0x0000006fu, 0x000000cdu, 0x0004003du, 0x00000006u, 0x000000cfu, 0x000000ceu, 0x00060041u, 0x00000078u,
    0x000000d1u, 0x000000c0u, 0x0000006fu, 0x000000d0u, 0x0004003du, 0x00000006u, 0x000000d2u, 0x000000d1u,
    0x00060041u, 0x00000078u, 0x000000d4u, 0x000000c0u, 0x0000006fu, 0x000000d3u, 0x0004003du, 0x00000006u,
    0x000000d5u, 0x000000d4u, 0x00060041u, 0x00000078u, 0x000000d7u, 0x000000c0u, 0x0000006fu, 0x000000d6u,
    0x0004003du, 0x00000006u, 0x000000d8u, 0x000000d7u, 0x00060041u, 0x00000078u, 0x000000dau, 0x000000c0u,
    0x0000006fu, 0x000000d9u, 0x0004003du, 0x00000006u, 0x000000dbu, 0x000000dau, 0x00060041u, 0x00000078u,
    0x000000ddu, 0x000000c0u, 0x0000006fu, 0x000000dcu, 0x0004003du, 0x00000006u, 0x000000deu, 0x000000ddu,
    0x00060041u, 0x00000078u, 0x000000e0u, 0x000000c0u, 0x0000006fu, 0x000000dfu, 0x0004003du, 0x00000006u,
    0x000000e1u, 0x000000e0u, 0x00060041u, 0x00000078u, 0x000000e3u, 0x000000c0u, 0x0000006fu, 0x000000e2u,
    0x0004003du, 0x00000006u, 0x000000e4u, 0x000000e3u, 0x00060041u, 0x00000078u, 0x000000e6u, 0x000000c0u,
    0x0000006fu, 0x000000e5u, 0x0004003du, 0x00000006u, 0x000000e7u, 0x000000e6u, 0x00060041u, 0x00000078u,
    0x000000e9u, 0x000000c0u, 0x0000006fu, 0x000000e8u, 0x0004003du, 0x00000006u, 0x000000eau, 0x000000e9u,
    0x00060041u, 0x00000078u, 0x000000ecu, 0x000000c0u, 0x0000006fu, 0x000000ebu, 0x0004003du, 0x00000006u,
    0x000000edu, 0x000000ecu, 0x00070050u, 0x00000007u, 0x000000efu, 0x000000c2u, 0x000000c4u, 0x000000c6u,
    0x000000c9u, 0x00070050u, 0x00000007u, 0x000000f0u, 0x000000ccu, 0x000000cfu, 0x000000d2u, 0x000000d5u,
    0x00070050u, 0x00000007u, 0x000000f1u, 0x000000d8u, 0x000000dbu, 0x000000deu, 0x000000e1u, 0x00070050u,
    0x00000007u, 0x000000f2u, 0x000000e4u, 0x000000e7u, 0x000000eau, 0x000000edu, 0x00070050u, 0x00000008u,
    0x000000f3u, 0x000000efu, 0x000000f0u, 0x000000f1u, 0x000000f2u, 0x0004006fu, 0x00000006u, 0x000000f7u,
    0x000000abu, 0x00050085u, 0x00000006u, 0x000000f8u, 0x000000f5u, 0x000000f7u, 0x0004006fu, 0x00000006u,
    0x000000fbu, 0x000000aau, 0x00050088u, 0x00000006u, 0x000000fcu, 0x000000f8u, 0x000000fbu, 0x00050083u,
    0x00000006u, 0x000000fdu, 0x000000fcu, 0x00000026u, 0x00050080u, 0x0000001au, 0x00000100u, 0x000000abu,
    0x000000a0u, 0x0004006fu, 0x00000006u, 0x00000101u, 0x00000100u, 0x00050085u, 0x00000006u, 0x00000102u,
    0x000000f5u, 0x00000101u, 0x00050088u, 0x00000006u, 0x00000106u, 0x00000102u, 0x000000fbu, 0x00050083u,
    0x00000006u, 0x00000107u, 0x00000106u, 0x00000026u, 0x0004006fu, 0x00000006u, 0x0000010au, 0x000000b3u,
    0x00050085u, 0x00000006u, 0x0000010bu, 0x000000f5u, 0x0000010au, 0x0004006fu, 0x00000006u, 0x0000010eu,
    0x000000b2u, 0x00050088u, 0x00000006u, 0x0000010fu, 0x0000010bu, 0x0000010eu, 0x00050083u, 0x00000006u,
    0x00000110u, 0x0000010fu, 0x00000026u, 0x00050080u, 0x0000001au, 0x00000113u, 0x000000b3u, 0x000000a0u,
    0x0004006fu, 0x00000006u, 0x00000114u, 0x00000113u, 0x00050085u, 0x00000006u, 0x00000115u, 0x000000f5u,
    0x00000114u, 0x00050088u, 0x00000006u, 0x00000119u, 0x00000115u, 0x0000010eu, 0x00050083u, 0x00000006u,
    0x0000011au, 0x00000119u, 0x00000026u, 0x000300f7u, 0x0000020bu, 0x00000000u, 0x000300fbu, 0x00000053u,
    0x000001edu, 0x000200f8u, 0x000001edu, 0x000500aau, 0x0000002fu, 0x000001efu, 0x000000bbu, 0x0000006fu,
    0x000300f7u, 0x000001f3u, 0x00000000u, 0x000400fau, 0x000001efu, 0x000001f0u, 0x000001f3u, 0x000200f8u,
    0x000001f0u, 0x00060041u, 0x00000078u, 0x000001f1u, 0x00000076u, 0x00000077u, 0x00000053u, 0x0004003du,
    0x00000006u, 0x000001f2u, 0x000001f1u, 0x000200f9u, 0x0000020bu, 0x000200f8u, 0x000001f3u, 0x00060041u,
    0x0000007du, 0x000001f5u, 0x00000076u, 0x0000006fu, 0x0000003fu, 0x0004003du, 0x0000001au, 0x000001f6u,
    0x000001f5u, 0x000500aau, 0x0000002fu, 0x000001f7u, 0x000000bbu, 0x000001f6u, 0x000300f7u, 0x000001fbu,
    0x00000000u, 0x000400fau, 0x000001f7u, 0x000001f8u, 0x000001fbu, 0x000200f8u, 0x000001f8u, 0x00060041u,
    0x00000078u, 0x000001f9u, 0x00000076u, 0x00000077u, 0x0000005eu, 0x0004003du, 0x00000006u, 0x000001fau,
    0x000001f9u, 0x000200f9u, 0x0000020bu, 0x000200f8u, 0x000001fbu, 0x00060041u, 0x00000078u, 0x000001fcu,
    0x00000076u, 0x00000077u, 0x00000053u, 0x0004003du, 0x00000006u, 0x000001fdu, 0x000001fcu, 0x00060041u,
    0x00000078u, 0x000001feu, 0x00000076u, 0x00000077u, 0x0000005eu, 0x0004003du, 0x00000006u, 0x000001ffu,
    0x000001feu, 0x00050088u, 0x00000006u, 0x00000202u, 0x000001ffu, 0x000001fdu, 0x0004006fu, 0x00000006u,
    0x00000204u, 0x000000bbu, 0x0004006fu, 0x00000006u, 0x00000207u, 0x000001f6u, 0x00050088u, 0x00000006u,
    0x00000208u, 0x00000204u, 0x00000207u, 0x0007000cu, 0x00000006u, 0x00000209u, 0x00000001u, 0x0000001au,
    0x00000202u, 0x00000208u, 0x00050085u, 0x00000006u, 0x0000020au, 0x000001fdu, 0x00000209u, 0x000200f9u,
    0x0000020bu, 0x000200f8u, 0x0000020bu, 0x000900f5u, 0x00000006u, 0x000002aau, 0x000001f2u, 0x000001f0u,
    0x000001fau, 0x000001f8u, 0x0000020au, 0x000001fbu, 0x00050080u, 0x0000001au, 0x00000121u, 0x000000bbu,
    0x000000a0u, 0x000300f7u, 0x0000022fu, 0x00000000u, 0x000300fbu, 0x00000053u, 0x00000211u, 0x000200f8u,
    0x00000211u, 0x000500aau, 0x0000002fu, 0x00000213u, 0x00000121u, 0x0000006fu, 0x000300f7u, 0x00000217u,
    0x00000000u, 0x000400fau, 0x00000213u, 0x00000214u, 0x00000217u, 0x000200f8u, 0x00000214u, 0x00060041u,
    0x00000078u, 0x00000215u, 0x00000076u, 0x00000077u, 0x00000053u, 0x0004003du, 0x00000006u, 0x00000216u,
    0x00000215u, 0x000200f9u, 0x0000022fu, 0x000200f8u, 0x00000217u, 0x00060041u, 0x0000007du, 0x00000219u,
    0x00000076u, 0x0000006fu, 0x0000003fu, 0x0004003du, 0x0000001au, 0x0000021au, 0x00000219u, 0x000500aau,
    0x0000002fu, 0x0000021bu, 0x00000121u, 0x0000021au, 0x000300f7u, 0x0000021fu, 0x00000000u, 0x000400fau,
    0x0000021bu, 0x0000021cu, 0x0000021fu, 0x000200f8u, 0x0000021cu, 0x00060041u, 0x00000078u, 0x0000021du,
    0x00000076u, 0x00000077u, 0x0000005eu, 0x0004003du, 0x00000006u, 0x0000021eu, 0x0000021du, 0x000200f9u,
    0x0000022fu, 0x000200f8u, 0x0000021fu, 0x00060041u, 0x00000078u, 0x00000220u, 0x00000076u, 0x00000077u,
    0x00000053u, 0x0004003du, 0x00000006u, 0x00000221u, 0x00000220u, 0x00060041u, 0x00000078u, 0x00000222u,
    0x00000076u, 0x00000077u, 0x0000005eu, 0x0004003du, 0x00000006u, 0x00000223u, 0x00000222u, 0x00050088u,
    0x00000006u, 0x00000226u, 0x00000223u, 0x00000221u, 0x0004006fu, 0x00000006u, 0x00000228u, 0x00000121u,
    0x0004006fu, 0x00000006u, 0x0000022bu, 0x0000021au, 0x00050088u, 0x00000006u, 0x0000022cu, 0x00000228u,
    0x0000022bu, 0x0007000cu, 0x00000006u, 0x0000022du, 0x00000001u, 0x0000001au, 0x00000226u, 0x0000022cu,
    0x00050085u, 0x00000006u, 0x0000022eu, 0x00000221u, 0x0000022du, 0x000200f9u, 0x0000022fu, 0x000200f8u,
    0x0000022fu, 0x000900f5u, 0x00000006u, 0x000002abu, 0x00000216u, 0x00000214u, 0x0000021eu, 0x0000021cu,
    0x0000022eu, 0x0000021fu, 0x000200f9u, 0x0000012bu, 0x000200f8u, 0x0000012bu, 0x000700f5u, 0x0000000bu,
    0x000002b2u, 0x00000129u, 0x0000022fu, 0x000002c8u, 0x0000012eu, 0x000700f5u, 0x0000000bu, 0x000002b0u,
    0x00000126u, 0x0000022fu, 0x000002c3u, 0x0000012eu, 0x000700f5u, 0x0000001au, 0x000002acu, 0x0000006fu,
    0x0000022fu, 0x00000177u, 0x0000012eu, 0x000500b1u, 0x0000002fu, 0x00000131u, 0x000002acu, 0x00000077u,
    0x000400f6u, 0x0000012du, 0x0000012eu, 0x00000000u, 0x000400fau, 0x00000131u, 0x0000012cu, 0x0000012du,
    0x000200f8u, 0x0000012cu, 0x000500aau, 0x0000002fu, 0x00000134u, 0x000002acu, 0x0000006fu, 0x000600a9u,
    0x00000006u, 0x00000137u, 0x00000134u, 0x000000fdu, 0x00000107u, 0x000200f9u, 0x00000139u, 0x000200f8u,
    0x00000139u, 0x000700f5u, 0x0000001au, 0x000002b6u, 0x0000006fu, 0x0000012cu, 0x00000175u, 0x0000013cu,
    0x000700f5u, 0x0000000bu, 0x000002c8u, 0x000002b2u, 0x0000012cu, 0x000002c5u, 0x0000013cu, 0x000700f5u,
    0x0000000bu, 0x000002c3u, 0x000002b0u, 0x0000012cu, 0x000002c0u, 0x0000013cu, 0x000500b1u, 0x0000002fu,
    0x0000013fu, 0x000002b6u, 0x00000077u, 0x000400f6u, 0x0000013bu, 0x0000013cu, 0x00000000u, 0x000400fau,
    0x0000013fu, 0x0000013au, 0x0000013bu, 0x000200f8u, 0x0000013au, 0x000500aau, 0x0000002fu, 0x00000142u,
    0x000002b6u, 0x0000006fu, 0x000600a9u, 0x00000006u, 0x00000145u, 0x00000142u, 0x00000110u, 0x0000011au,
    0x000300f7u, 0x0000024bu, 0x00000000u, 0x000300fbu, 0x00000053u, 0x00000236u, 0x000200f8u, 0x00000236u,
    0x00070050u, 0x00000007u, 0x0000023bu, 0x00000137u, 0x00000145u, 0x000000eeu, 0x00000026u, 0x00050091u,
    0x00000007u, 0x0000023cu, 0x000000f3u, 0x0000023bu, 0x00050051u, 0x00000006u, 0x0000023eu, 0x0000023cu,
    0x00000003u, 0x0006000cu, 0x00000006u, 0x0000023fu, 0x00000001u, 0x00000004u, 0x0000023eu, 0x000500bcu,
    0x0000002fu, 0x00000240u, 0x0000023fu, 0x0000002eu, 0x000300f7u, 0x00000244u, 0x00000000u, 0x000400fau,
    0x00000240u, 0x00000241u, 0x00000244u, 0x000200f8u, 0x00000241u, 0x0008004fu, 0x0000000bu, 0x00000243u,
    0x0000023cu, 0x0000023cu, 0x00000000u, 0x00000001u, 0x00000002u, 0x000200f9u, 0x0000024bu, 0x000200f8u,
    0x00000244u, 0x0008004fu, 0x0000000bu, 0x00000246u, 0x0000023cu, 0x0000023cu, 0x00000000u, 0x00000001u,
    0x00000002u, 0x00060050u, 0x0000000bu, 0x00000249u, 0x0000023eu, 0x0000023eu, 0x0000023eu, 0x00050088u,
    0x0000000bu, 0x0000024au, 0x00000246u, 0x00000249u, 0x000200f9u, 0x0000024bu, 0x000200f8u, 0x0000024bu,
    0x000700f5u, 0x0000000bu, 0x000002b8u, 0x00000243u, 0x00000241u, 0x0000024au, 0x00000244u, 0x000300f7u,
    0x00000267u, 0x00000000u, 0x000300fbu, 0x00000053u, 0x00000252u, 0x000200f8u, 0x00000252u, 0x00070050u,
    0x00000007u, 0x00000257u, 0x00000137u, 0x00000145u, 0x00000026u, 0x00000026u, 0x00050091u, 0x00000007u,
    0x00000258u, 0x000000f3u, 0x00000257u, 0x00050051u, 0x00000006u, 0x0000025au, 0x00000258u, 0x00000003u,
    0x0006000cu, 0x00000006u, 0x0000025bu, 0x00000001u, 0x00000004u, 0x0000025au, 0x000500bcu, 0x0000002fu,
    0x0000025cu, 0x0000025bu, 0x0000002eu, 0x000300f7u, 0x00000260u, 0x00000000u, 0x000400fau, 0x0000025cu,
    0x0000025du, 0x00000260u, 0x000200f8u, 0x0000025du, 0x0008004fu, 0x0000000bu, 0x0000025fu, 0x00000258u,
    0x00000258u, 0x00000000u, 0x00000001u, 0x00000002u, 0x000200f9u, 0x00000267u, 0x000200f8u, 0x00000260u,
    0x0008004fu, 0x0000000bu, 0x00000262u, 0x00000258u, 0x00000258u, 0x00000000u, 0x00000001u, 0x00000002u,
    0x00060050u, 0x0000000bu, 0x00000265u, 0x0000025au, 0x0000025au, 0x0000025au, 0x00050088u, 0x0000000bu,
    0x00000266u, 0x00000262u, 0x00000265u, 0x000200f9u, 0x00000267u, 0x000200f8u, 0x00000267u, 0x000700f5u,
    0x0000000bu, 0x000002b9u, 0x0000025fu, 0x0000025du, 0x00000266u, 0x00000260u, 0x000200f9u, 0x00000159u,
    0x000200f8u, 0x00000159u, 0x000700f5u, 0x0000000bu, 0x000002c5u, 0x000002c8u, 0x00000267u, 0x00000171u,
    0x0000015cu, 0x000700f5u, 0x0000000bu, 0x000002c0u, 0x000002c3u, 0x00000267u, 0x0000016eu, 0x0000015cu,
    0x000700f5u, 0x0000001au, 0x000002bau, 0x0000006fu, 0x00000267u, 0x00000173u, 0x0000015cu, 0x000500b1u,
    0x0000002fu, 0x0000015fu, 0x000002bau, 0x00000077u, 0x000400f6u, 0x0000015bu, 0x0000015cu, 0x00000000u,
    0x000400fau, 0x0000015fu, 0x0000015au, 0x0000015bu, 0x000200f8u, 0x0000015au, 0x000500aau, 0x0000002fu,
    0x00000162u, 0x000002bau, 0x0000006fu, 0x000600a9u, 0x00000006u, 0x00000165u, 0x00000162u, 0x000002aau,
    0x000002abu, 0x000300f7u, 0x00000298u, 0x00000000u, 0x000300fbu, 0x00000053u, 0x0000026fu, 0x000200f8u,
    0x0000026fu, 0x00050051u, 0x00000006u, 0x00000271u, 0x000002b8u, 0x00000002u, 0x00050051u, 0x00000006u,
    0x00000273u, 0x000002b9u, 0x00000002u, 0x00050083u, 0x00000006u, 0x00000274u, 0x00000271u, 0x00000273u,
    0x0006000cu, 0x00000006u, 0x00000276u, 0x00000001u, 0x00000004u, 0x00000274u, 0x000500bcu, 0x0000002fu,
    0x00000277u, 0x00000276u, 0x0000002eu, 0x000300f7u, 0x0000027au, 0x00000000u, 0x000400fau, 0x00000277u,
    0x00000278u, 0x0000027au, 0x000200f8u, 0x00000278u, 0x000200f9u, 0x00000298u, 0x000200f8u, 0x0000027au,
    0x00050081u, 0x00000006u, 0x0000027eu, 0x00000271u, 0x00000165u, 0x00050088u, 0x00000006u, 0x00000280u,
    0x0000027eu, 0x00000274u, 0x00050051u, 0x00000006u, 0x00000282u, 0x000002b8u, 0x00000000u, 0x00050051u,
    0x00000006u, 0x00000284u, 0x000002b9u, 0x00000000u, 0x00050083u, 0x00000006u, 0x00000287u, 0x00000284u,
    0x00000282u, 0x00050085u, 0x00000006u, 0x00000289u, 0x00000287u, 0x00000280u, 0x00050081u, 0x00000006u,
    0x0000028au, 0x00000282u, 0x00000289u, 0x00050051u, 0x00000006u, 0x0000028cu, 0x000002b8u, 0x00000001u,
    0x00050051u, 0x00000006u, 0x0000028eu, 0x000002b9u, 0x00000001u, 0x00050083u, 0x00000006u, 0x00000291u,
    0x0000028eu, 0x0000028cu, 0x00050085u, 0x00000006u, 0x00000293u, 0x00000291u, 0x00000280u, 0x00050081u,
    0x00000006u, 0x00000294u, 0x0000028cu, 0x00000293u, 0x0004007fu, 0x00000006u, 0x00000296u, 0x00000165u,
    0x00060050u, 0x0000000bu, 0x00000297u, 0x0000028au, 0x00000294u, 0x00000296u, 0x000200f9u, 0x00000298u,
    0x000200f8u, 0x00000298u, 0x000700f5u, 0x0000000bu, 0x000002beu, 0x000002b8u, 0x00000278u, 0x00000297u,
    0x0000027au, 0x0007000cu, 0x0000000bu, 0x0000016eu, 0x00000001u, 0x00000025u, 0x000002c0u, 0x000002beu,
    0x0007000cu, 0x0000000bu, 0x00000171u, 0x00000001u, 0x00000028u, 0x000002c5u, 0x000002beu, 0x000200f9u,
    0x0000015cu, 0x000200f8u, 0x0000015cu, 0x00050080u, 0x0000001au, 0x00000173u, 0x000002bau, 0x000000a0u,
    0x000200f9u, 0x00000159u, 0x000200f8u, 0x0000015bu, 0x000200f9u, 0x0000013cu, 0x000200f8u, 0x0000013cu,
    0x00050080u, 0x0000001au, 0x00000175u, 0x000002b6u, 0x000000a0u, 0x000200f9u, 0x00000139u, 0x000200f8u,
    0x0000013bu, 0x000200f9u, 0x0000012eu, 0x000200f8u, 0x0000012eu, 0x00050080u, 0x0000001au, 0x00000177u,
    0x000002acu, 0x000000a0u, 0x000200f9u, 0x0000012bu, 0x000200f8u, 0x0000012du, 0x000200f9u, 0x0000017au,
    0x000200f8u, 0x0000017au, 0x000700f5u, 0x0000001au, 0x000002aeu, 0x0000006fu, 0x0000012du, 0x000002cau,
    0x0000017du, 0x000700f5u, 0x0000001au, 0x000002adu, 0x0000006fu, 0x0000012du, 0x000001beu, 0x0000017du,
    0x00060041u, 0x0000007du, 0x00000180u, 0x00000076u, 0x0000006fu, 0x0000002au, 0x0004003du, 0x0000001au,
    0x00000181u, 0x00000180u, 0x000500b1u, 0x0000002fu, 0x00000182u, 0x000002adu, 0x00000181u, 0x000400f6u,
    0x0000017cu, 0x0000017du, 0x00000000u, 0x000400fau, 0x00000182u, 0x0000017bu, 0x0000017cu, 0x000200f8u,
    0x0000017bu, 0x00060041u, 0x00000189u, 0x0000018au, 0x00000187u, 0x0000006fu, 0x000002adu, 0x0004003du,
    0x00000007u, 0x0000018bu, 0x0000018au, 0x00050051u, 0x00000006u, 0x0000018du, 0x0000018bu, 0x00000003u,
    0x000500bcu, 0x0000002fu, 0x0000018eu, 0x0000018du, 0x000000eeu, 0x000300f7u, 0x00000190u, 0x00000000u,
    0x000400fau, 0x0000018eu, 0x0000018fu, 0x00000190u, 0x000200f8u, 0x0000018fu, 0x000200f9u, 0x0000017du,
    0x000200f8u, 0x00000190u, 0x0008004fu, 0x0000000bu, 0x00000194u, 0x0000018bu, 0x0000018bu, 0x00000000u,
    0x00000001u, 0x00000002u, 0x0008000cu, 0x0000000bu, 0x00000197u, 0x00000001u, 0x0000002bu, 0x00000194u,
    0x000002b0u, 0x000002b2u, 0x00050083u, 0x0000000bu, 0x0000019cu, 0x00000194u, 0x00000197u, 0x00050094u,
    0x00000006u, 0x0000019fu, 0x0000019cu, 0x0000019cu, 0x00050085u, 0x00000006u, 0x000001a4u, 0x0000018du,
    0x0000018du, 0x000500bau, 0x0000002fu, 0x000001a5u, 0x0000019fu, 0x000001a4u, 0x000300f7u, 0x000001a7u,
    0x00000000u, 0x000400fau, 0x000001a5u, 0x000001a6u, 0x000001a7u, 0x000200f8u, 0x000001a6u, 0x000200f9u,
    0x0000017du, 0x000200f8u, 0x000001a7u, 0x00060041u, 0x0000007du, 0x000001aau, 0x00000076u, 0x000000a0u,
    0x00000053u, 0x0004003du, 0x0000001au, 0x000001abu, 0x000001aau, 0x000500b1u, 0x0000002fu, 0x000001acu,
    0x000002aeu, 0x000001abu, 0x000300f7u, 0x000001aeu, 0x00000000u, 0x000400fau, 0x000001acu, 0x000001adu,
    0x000001aeu, 0x000200f8u, 0x000001adu, 0x00050084u, 0x0000001au, 0x000001b6u, 0x0000009eu, 0x000001abu,
    0x00050080u, 0x0000001au, 0x000001b8u, 0x000001b6u, 0x000002aeu, 0x00060041u, 0x0000007du, 0x000001bau,
    0x000001b2u, 0x0000006fu, 0x000001b8u, 0x0003003eu, 0x000001bau, 0x000002adu, 0x000200f9u, 0x000001aeu,
    0x000200f8u, 0x000001aeu, 0x00050080u, 0x0000001au, 0x000001bcu, 0x000002aeu, 0x000000a0u, 0x000200f9u,
    0x0000017du, 0x000200f8u, 0x0000017du, 0x000900f5u, 0x0000001au, 0x000002cau, 0x000002aeu, 0x0000018fu,
    0x000002aeu, 0x000001a6u, 0x000001bcu, 0x000001aeu, 0x00050080u, 0x0000001au, 0x000001beu, 0x000002adu,
    0x000000a0u, 0x000200f9u, 0x0000017au, 0x000200f8u, 0x0000017cu, 0x00060041u, 0x0000007du, 0x000001c5u,
    0x00000076u, 0x000000a0u, 0x00000053u, 0x0004003du, 0x0000001au, 0x000001c6u, 0x000001c5u, 0x0007000cu,
    0x0000001au, 0x000001c7u, 0x00000001u, 0x00000027u, 0x000002aeu, 0x000001c6u, 0x00060041u, 0x0000007du,
    0x000001c8u, 0x000001c2u, 0x0000006fu, 0x0000009eu, 0x0003003eu, 0x000001c8u, 0x000001c7u, 0x000500adu,
    0x0000002fu, 0x000001ccu, 0x000002aeu, 0x000001c6u, 0x000300f7u, 0x000001ceu, 0x00000000u, 0x000400fau,
    0x000001ccu, 0x000001cdu, 0x000001ceu, 0x000200f8u, 0x000001cdu, 0x00060041u, 0x0000007du, 0x000001d1u,
    0x000001c2u, 0x0000006fu, 0x000000a2u, 0x0003003eu, 0x000001d1u, 0x000000a0u, 0x000200f9u, 0x000001ceu,
    0x000200f8u, 0x000001ceu, 0x000200f9u, 0x000001d4u, 0x000200f8u, 0x000001d4u, 0x000100fdu, 0x00010038u,
};
inline constexpr std::size_t kAssignVulkanComputeSpirVByteSize = sizeof(kAssignVulkanComputeSpirV);

inline constexpr std::string_view kAssignVulkanComputeWgsl =
    R"CNA_SHADER(// assign.vulkan.comp.glsl -> cna-webgpu-glsl/1 -> shaderc -> naga. Generated; edit the Vulkan GLSL source.
struct ClusteredLightParameters {
    uGrid: vec4<i32>,
    uOutput: vec4<i32>,
    uDepth: vec4<f32>,
}

struct CnaMatrix {
    uInverseProjection: array<f32>,
}

struct CnaLights {
    uLights: array<vec4<f32>>,
}

struct CnaIndices {
    uIndices: array<i32>,
}

struct CnaCounts {
    uCounts: array<i32>,
}

@group(0) @binding(4) 
var<uniform> unnamed: ClusteredLightParameters;
var<private> gl_GlobalInvocationID_1: vec3<u32>;
@group(0) @binding(1) 
var<storage> unnamed_1: CnaMatrix;
@group(0) @binding(0) 
var<storage> unnamed_2: CnaLights;
@group(0) @binding(3) 
var<storage, read_write> unnamed_3: CnaIndices;
@group(0) @binding(2) 
var<storage, read_write> unnamed_4: CnaCounts;

fn cnaAtDistance_u0028_vf3_u003b_vf3_u003b_f1_u003b(atNear: ptr<function, vec3<f32>>, atFar: ptr<function, vec3<f32>>, distance: ptr<function, f32>) -> vec3<f32> {
    var span: f32;
    var t: f32;

    let _e42 = (*atNear)[2u];
    let _e44 = (*atFar)[2u];
    span = (_e42 - _e44);
    let _e46 = span;
    if (abs(_e46) <= 0.000000001f) {
        let _e49 = (*atNear);
        return _e49;
    }
    let _e51 = (*atNear)[2u];
    let _e52 = (*distance);
    let _e54 = span;
    t = ((_e51 + _e52) / _e54);
    let _e57 = (*atNear)[0u];
    let _e59 = (*atFar)[0u];
    let _e61 = (*atNear)[0u];
    let _e63 = t;
    let _e67 = (*atNear)[1u];
    let _e69 = (*atFar)[1u];
    let _e71 = (*atNear)[1u];
    let _e73 = t;
    let _e76 = (*distance);
    return vec3<f32>((_e57 + ((_e59 - _e61) * _e63)), (_e67 + ((_e69 - _e71) * _e73)), -(_e76));
}

fn cnaUnproject_u0028_mf44_u003b_f1_u003b_f1_u003b_f1_u003b(inverseProjection: ptr<function, mat4x4<f32>>, x: ptr<function, f32>, y: ptr<function, f32>, z: ptr<function, f32>) -> vec3<f32> {
    var p: vec4<f32>;

    let _e41 = (*inverseProjection);
    let _e42 = (*x);
    let _e43 = (*y);
    let _e44 = (*z);
    p = (_e41 * vec4<f32>(_e42, _e43, _e44, 1f));
    let _e48 = p[3u];
    if (abs(_e48) <= 0.000000001f) {
        let _e51 = p;
        return _e51.xyz;
    }
    let _e53 = p;
    let _e56 = p[3u];
    return (_e53.xyz / vec3(_e56));
}

fn cnaSliceDistance_u0028_i1_u003b(slice: ptr<function, i32>) -> f32 {
    let _e37 = (*slice);
    if (_e37 == 0i) {
        let _e41 = unnamed.uDepth[0u];
        return _e41;
    }
    let _e42 = (*slice);
    let _e45 = unnamed.uGrid[2u];
    if (_e42 == _e45) {
        let _e49 = unnamed.uDepth[1u];
        return _e49;
    }
    let _e52 = unnamed.uDepth[0u];
    let _e55 = unnamed.uDepth[1u];
    let _e58 = unnamed.uDepth[0u];
    let _e60 = (*slice);
    let _e64 = unnamed.uGrid[2u];
    return (_e52 * pow((_e55 / _e58), (f32(_e60) / f32(_e64))));
}

fn main_1() {
    var cluster: i32;
    var x_1: i32;
    var y_1: i32;
    var slice_1: i32;
    var inverseProjection_1: mat4x4<f32>;
    var u0_: f32;
    var u1_: f32;
    var v0_: f32;
    var v1_: f32;
    var d0_: f32;
    var param: i32;
    var d1_: f32;
    var param_1: i32;
    var minimum: vec3<f32>;
    var maximum: vec3<f32>;
    var i: i32;
    var u: f32;
    var j: i32;
    var v: f32;
    var atNear_1: vec3<f32>;
    var param_2: mat4x4<f32>;
    var param_3: f32;
    var param_4: f32;
    var param_5: f32;
    var atFar_1: vec3<f32>;
    var param_6: mat4x4<f32>;
    var param_7: f32;
    var param_8: f32;
    var param_9: f32;
    var k: i32;
    var p_1: vec3<f32>;
    var param_10: vec3<f32>;
    var param_11: vec3<f32>;
    var param_12: f32;
    var found: i32;
    var light: i32;
    var sphere: vec4<f32>;
    var nearest: vec3<f32>;
    var delta: vec3<f32>;

    let _e76 = gl_GlobalInvocationID_1[0u];
    cluster = bitcast<i32>(_e76);
    let _e78 = cluster;
    let _e81 = unnamed.uOutput[1u];
    if (_e78 >= _e81) {
        return;
    }
    let _e83 = cluster;
    let _e86 = unnamed.uGrid[0u];
    x_1 = (_e83 - (i32(floor((f32(_e83) / f32(_e86)))) * _e86));
    let _e94 = cluster;
    let _e97 = unnamed.uGrid[0u];
    let _e98 = (_e94 / _e97);
    let _e101 = unnamed.uGrid[1u];
    y_1 = (_e98 - (i32(floor((f32(_e98) / f32(_e101)))) * _e101));
    let _e109 = cluster;
    let _e112 = unnamed.uGrid[0u];
    let _e115 = unnamed.uGrid[1u];
    slice_1 = (_e109 / (_e112 * _e115));
    let _e120 = unnamed_1.uInverseProjection[0i];
    let _e123 = unnamed_1.uInverseProjection[1i];
    let _e126 = unnamed_1.uInverseProjection[2i];
    let _e129 = unnamed_1.uInverseProjection[3i];
    let _e132 = unnamed_1.uInverseProjection[4i];
    let _e135 = unnamed_1.uInverseProjection[5i];
    let _e138 = unnamed_1.uInverseProjection[6i];
    let _e141 = unnamed_1.uInverseProjection[7i];
    let _e144 = unnamed_1.uInverseProjection[8i];
    let _e147 = unnamed_1.uInverseProjection[9i];
    let _e150 = unnamed_1.uInverseProjection[10i];
    let _e153 = unnamed_1.uInverseProjection[11i];
    let _e156 = unnamed_1.uInverseProjection[12i];
    let _e159 = unnamed_1.uInverseProjection[13i];
    let _e162 = unnamed_1.uInverseProjection[14i];
    let _e165 = unnamed_1.uInverseProjection[15i];
    inverseProjection_1 = mat4x4<f32>(vec4<f32>(_e120, _e123, _e126, _e129), vec4<f32>(_e132, _e135, _e138, _e141), vec4<f32>(_e144, _e147, _e150, _e153), vec4<f32>(_e156, _e159, _e162, _e165));
    let _e171 = x_1;
    let _e176 = unnamed.uGrid[0u];
    u0_ = (((2f * f32(_e171)) / f32(_e176)) - 1f);
    let _e180 = x_1;
    let _e186 = unnamed.uGrid[0u];
    u1_ = (((2f * f32((_e180 + 1i))) / f32(_e186)) - 1f);
    let _e190 = y_1;
    let _e195 = unnamed.uGrid[1u];
    v0_ = (((2f * f32(_e190)) / f32(_e195)) - 1f);
    let _e199 = y_1;
    let _e205 = unnamed.uGrid[1u];
    v1_ = (((2f * f32((_e199 + 1i))) / f32(_e205)) - 1f);
    let _e209 = slice_1;
    param = _e209;
    let _e210 = cnaSliceDistance_u0028_i1_u003b((&param));
    d0_ = _e210;
    let _e211 = slice_1;
    param_1 = (_e211 + 1i);
    let _e213 = cnaSliceDistance_u0028_i1_u003b((&param_1));
    d1_ = _e213;
    minimum = vec3<f32>(340282350000000000000000000000000000000f, 340282350000000000000000000000000000000f, 340282350000000000000000000000000000000f);
    maximum = vec3<f32>(-340282350000000000000000000000000000000f, -340282350000000000000000000000000000000f, -340282350000000000000000000000000000000f);
    i = 0i;
    loop {
        let _e214 = i;
        if (_e214 < 2i) {
            let _e216 = i;
            let _e218 = u0_;
            let _e219 = u1_;
            u = select(_e219, _e218, (_e216 == 0i));
            j = 0i;
            loop {
                let _e221 = j;
                if (_e221 < 2i) {
                    let _e223 = j;
                    let _e225 = v0_;
                    let _e226 = v1_;
                    v = select(_e226, _e225, (_e223 == 0i));
                    let _e228 = inverseProjection_1;
                    param_2 = _e228;
                    let _e229 = u;
                    param_3 = _e229;
                    let _e230 = v;
                    param_4 = _e230;
                    param_5 = 0f;
                    let _e231 = cnaUnproject_u0028_mf44_u003b_f1_u003b_f1_u003b_f1_u003b((&param_2), (&param_3), (&param_4), (&param_5));
                    atNear_1 = _e231;
                    let _e232 = inverseProjection_1;
                    param_6 = _e232;
                    let _e233 = u;
                    param_7 = _e233;
                    let _e234 = v;
                    param_8 = _e234;
                    param_9 = 1f;
                    let _e235 = cnaUnproject_u0028_mf44_u003b_f1_u003b_f1_u003b_f1_u003b((&param_6), (&param_7), (&param_8), (&param_9));
                    atFar_1 = _e235;
                    k = 0i;
                    loop {
                        let _e236 = k;
                        if (_e236 < 2i) {
                            let _e238 = k;
                            let _e240 = d0_;
                            let _e241 = d1_;
                            let _e243 = atNear_1;
                            param_10 = _e243;
                            let _e244 = atFar_1;
                            param_11 = _e244;
                            param_12 = select(_e241, _e240, (_e238 == 0i));
                            let _e245 = cnaAtDistance_u0028_vf3_u003b_vf3_u003b_f1_u003b((&param_10), (&param_11), (&param_12));
                            p_1 = _e245;
                            let _e246 = minimum;
                            let _e247 = p_1;
                            minimum = min(_e246, _e247);
                            let _e249 = maximum;
                            let _e250 = p_1;
                            maximum = max(_e249, _e250);
                            continue;
                        } else {
                            break;
                        }
                        continuing {
                            let _e252 = k;
                            k = (_e252 + 1i);
                        }
                    }
                    continue;
                } else {
                    break;
                }
                continuing {
                    let _e254 = j;
                    j = (_e254 + 1i);
                }
            }
            continue;
        } else {
            break;
        }
        continuing {
            let _e256 = i;
            i = (_e256 + 1i);
        }
    }
    found = 0i;
    light = 0i;
    loop {
        let _e258 = light;
        let _e261 = unnamed.uGrid[3u];
        if (_e258 < _e261) {
            let _e263 = light;
            let _e266 = unnamed_2.uLights[_e263];
            sphere = _e266;
            let _e268 = sphere[3u];
            if (_e268 <= 0f) {
                continue;
            }
            let _e270 = sphere;
            let _e272 = minimum;
            let _e273 = maximum;
            nearest = clamp(_e270.xyz, _e272, _e273);
            let _e275 = sphere;
            let _e277 = nearest;
            delta = (_e275.xyz - _e277);
            let _e279 = delta;
            let _e280 = delta;
            let _e283 = sphere[3u];
            let _e285 = sphere[3u];
            if (dot(_e279, _e280) > (_e283 * _e285)) {
                continue;
            }
            let _e288 = found;
            let _e291 = unnamed.uOutput[0u];
            if (_e288 < _e291) {
                let _e293 = cluster;
                let _e296 = unnamed.uOutput[0u];
                let _e298 = found;
                let _e300 = light;
                unnamed_3.uIndices[((_e293 * _e296) + _e298)] = _e300;
            }
            let _e303 = found;
            found = (_e303 + 1i);
            continue;
        } else {
            break;
        }
        continuing {
            let _e305 = light;
            light = (_e305 + 1i);
        }
    }
    let _e307 = cluster;
    let _e308 = found;
    let _e311 = unnamed.uOutput[0u];
    unnamed_4.uCounts[_e307] = min(_e308, _e311);
    let _e315 = found;
    let _e318 = unnamed.uOutput[0u];
    if (_e315 > _e318) {
        let _e322 = unnamed.uOutput[1u];
        unnamed_4.uCounts[_e322] = 1i;
    }
    return;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) gl_GlobalInvocationID: vec3<u32>) {
    gl_GlobalInvocationID_1 = gl_GlobalInvocationID;
    main_1();
}
)CNA_SHADER";

inline constexpr std::array<PayloadProvenance, 4> kPayloads = {{
    {"kAssignEsComputeSource", "assign.es.comp.glsl", "f1f8298b7f1beaaa75d600e6949c8b6ec44e47ececd263d912d5db12e4c932f9", "glsl-es", "glsl-es", "compute", "text", "main"},
    {"kAssignDesktopComputeSource", "assign.desktop.comp.glsl", "c9dd515eb0556afe2675fea8e1484a16c593fd0779637f1008db7a1c870343f9", "glsl", "glsl", "compute", "text", "main"},
    {"kAssignVulkanComputeSpirV", "assign.vulkan.comp.glsl", "b17aded514c16202149b935850a94e94bf69d5f394b7d41ccba9176851943147", "spirv", "vulkan-glsl", "compute", "spirv", "main"},
    {"kAssignVulkanComputeWgsl", "assign.vulkan.comp.glsl", "b17aded514c16202149b935850a94e94bf69d5f394b7d41ccba9176851943147", "wgsl", "vulkan-glsl", "compute", "wgsl", "main"},
}};

} // namespace CNA::Graphics::detail::ClusteredLightComputeGenerated

#endif // CNA_CNAEXT
