// SPDX-License-Identifier: MS-PL
#pragma once

#include "CNA/Platform/Input/IPlatformMouse.hpp"
#include "X11Headers.hpp"

#include <map>

namespace CNA::Platform::X11 {

    class X11Connection;
    class X11Window;

    /**
     * @brief Reads and controls the X11 pointer.
     *
     * ### Wheels are not buttons here
     *
     * The X core protocol has no scroll axis: a traditional mouse reports a wheel notch as a
     * press and release of button 4 (up), 5 (down), 6 (left) or 7 (right). CNA models scrolling
     * separately, so the event mapper turns those four buttons into `MouseWheelEvent` and never
     * emits a `MouseButtonEvent` for them. A game that watches for button presses must not see a
     * phantom click every time the user scrolls.
     *
     * Buttons 8 and above are the real extra buttons (back, forward, thumb), and they are
     * renumbered down so CNA sees a dense 4, 5, 6… after the three standard ones.
     *
     * ### Relative mode
     *
     * When XInput2 is available, relative mode selects `XI_RawMotion` on the root window. Raw
     * events carry the device's own deltas *before* the server applies pointer acceleration,
     * screen clipping or any warp — which removes at a stroke the two classic problems of the
     * warp-based approach: motion lost at the screen edge, and the synthetic motion generated by
     * the recentring warp being read as real input. The pointer is additionally grabbed and
     * confined so it cannot leave the window or click through to another application.
     *
     * Without XInput2 the capability is reported false and `SetRelativeMode` refuses. A
     * warp-based imitation would satisfy the signature and not the contract.
     */
    class X11Mouse final : public IPlatformMouse
    {
    public:
        /**
         * @brief Builds the mouse for one connection.
         *
         * @param connection The connection to query the pointer on.
         */
        explicit X11Mouse(X11Connection& connection);

        /** @brief Releases the grab, the confinement and every cursor this object created. */
        ~X11Mouse() override;

        X11Mouse(const X11Mouse&) = delete;
        X11Mouse& operator=(const X11Mouse&) = delete;

        /** @brief Re-reads the pointer position and button state from the server. */
        void Update() override;

        /** @brief Gets the most recent snapshot. @return The snapshot. */
        [[nodiscard]] const MouseSnapshot& GetSnapshot() const override { return snapshot_; }

        /**
         * @brief Takes the accumulated relative motion and resets it.
         * @return The delta since the last call.
         */
        [[nodiscard]] MouseDelta ConsumeRelativeDelta() override;

        /**
         * @brief Warps the pointer within a window.
         * @param window The window whose client area the coordinates are in.
         * @param x Target x.
         * @param y Target y.
         */
        void SetPosition(WindowId window, int x, int y) override;

        /** @brief Shows or hides the cursor. @param visible True to show. */
        void SetCursorVisible(bool visible) override;

        /** @brief Sets a standard cursor shape. @param cursor The shape. */
        void SetCursor(SystemCursor cursor) override;

        /**
         * @brief Sets a custom cursor image.
         * @param cursor The ARGB image and hot spot.
         * @throws PlatformNotSupportedException When libXcursor was not available at build time.
         */
        void SetCursor(const CursorImage& cursor) override;

        /**
         * @brief Enters or leaves relative (pointer-locked) mode.
         * @param window The window to lock the pointer to.
         * @param enabled True to enter relative mode.
         * @throws PlatformNotSupportedException When XInput2 is unavailable.
         */
        void SetRelativeMode(WindowId window, bool enabled) override;

        /** @brief Gets whether relative mode is active. @return True when active. */
        [[nodiscard]] bool IsRelativeMode() const override { return relativeWindow_ != 0; }

        /**
         * @brief Grabs or releases the pointer so motion continues outside the window.
         * @param enabled True to capture.
         * @return True when the grab state changed as requested.
         */
        bool SetCapture(bool enabled) override;

        /**
         * @brief Gets the pointer position in desktop coordinates.
         * @param x Receives the x position.
         * @param y Receives the y position.
         * @return True; the X root window always has a pointer position.
         */
        [[nodiscard]] bool TryGetGlobalPosition(float& x, float& y) const override;

        /**
         * @brief Moves the pointer in desktop coordinates.
         * @param x Target x.
         * @param y Target y.
         * @return True when the warp was sent.
         */
        bool SetGlobalPosition(float x, float y) override;

        // --- used by the platform and the event mapper -----------------------------------------

        /**
         * @brief Registers a window so pointer calls can resolve a `WindowId`.
         *
         * @param id The CNA window id.
         * @param window The window, or null to unregister.
         */
        void RegisterWindow(WindowId id, X11Window* window);

        /**
         * @brief Accumulates raw relative motion reported by XInput2.
         *
         * @param deltaX Horizontal movement.
         * @param deltaY Vertical movement.
         */
        void AccumulateRawMotion(double deltaX, double deltaY);

        /** @brief Records the last pointer position seen in an event. */
        void SetLastPosition(WindowId window, int x, int y);

        /** @brief Records a button press or release seen in an event. */
        void SetButtonState(unsigned int button, bool pressed);

        /**
         * @brief Accumulates wheel motion for the snapshot's cumulative scroll fields.
         *
         * @param x Horizontal notches.
         * @param y Vertical notches.
         */
        void AccumulateScroll(int x, int y);

        /** @brief Gets whether XInput2 raw motion is usable on this connection. */
        [[nodiscard]] bool HasRawMotion() const;

    private:
        [[nodiscard]] X11Window* FindWindow(WindowId id) const;
        void ApplyCursor(::Cursor cursor);
        [[nodiscard]] ::Cursor GetHiddenCursor();
        void ReleaseRelativeMode();

        X11Connection& connection_;
        std::map<WindowId, X11Window*> windows_;
        MouseSnapshot snapshot_;
        int relativeX_ = 0;
        int relativeY_ = 0;
        WindowId relativeWindow_ = 0;
        bool cursorVisible_ = true;
        bool captured_ = false;
        ::Cursor activeCursor_ = 0;
        ::Cursor hiddenCursor_ = 0;
        ::Cursor customCursor_ = 0;
        std::map<int, ::Cursor> fontCursors_;
    };

} // namespace CNA::Platform::X11
