// SPDX-License-Identifier: MS-PL
//
// GENERATED by tools/c-api/generate_bool_contract_test.py -- do not edit by hand.
// Regenerate with --write; CApiBoolContractCurrent fails when this file is stale.
//
// plan_binding.md CBIND-067: every route taking a CNA_Bool refuses a byte outside
// {CNA_FALSE, CNA_TRUE}, which docs/c-api/ABI_VERSIONING.md has always declared the only
// valid values and which 66 of 94 routes used to accept -- then read as true in some
// places and false in others. Generated rather than hand-written so a new flag parameter
// is covered the moment it is declared.

#include <CNA/C/cna.h>

#include <stdint.h>
#include <stdio.h>
#include <string.h>

int main(void)
{
    CNA_StringView empty_view;
    CNA_BoundingBox zero_bbox;
    CNA_BoundingFrustum zero_bfrustum;
    CNA_BoundingSphere zero_bsphere;
    CNA_Color zero_color;
    CNA_ColorMatrix4x4 zero_colormatrix;
    CNA_CurveKey zero_curvekey;
    CNA_DateTimeOffset zero_dto;
    CNA_Matrix zero_matrix;
    CNA_OptionalInt32 zero_optional_int32;
    CNA_Plane zero_plane;
    CNA_Point zero_point;
    CNA_Quaternion zero_quat;
    CNA_Ray zero_ray;
    CNA_Rectangle zero_rect;
    CNA_Vector2 zero_v2;
    CNA_Vector3 zero_v3;
    CNA_Vector4 zero_v4;
    CNA_VertexElement zero_velem;
    CNA_Viewport zero_viewport;
    CNA_Result result = CNA_RESULT_SUCCESS;
    int accepted = 0;

    memset(&empty_view, 0, sizeof(empty_view));
    memset(&zero_bbox, 0, sizeof(zero_bbox));
    memset(&zero_bfrustum, 0, sizeof(zero_bfrustum));
    memset(&zero_bsphere, 0, sizeof(zero_bsphere));
    memset(&zero_color, 0, sizeof(zero_color));
    memset(&zero_colormatrix, 0, sizeof(zero_colormatrix));
    memset(&zero_curvekey, 0, sizeof(zero_curvekey));
    memset(&zero_dto, 0, sizeof(zero_dto));
    memset(&zero_matrix, 0, sizeof(zero_matrix));
    memset(&zero_optional_int32, 0, sizeof(zero_optional_int32));
    memset(&zero_plane, 0, sizeof(zero_plane));
    memset(&zero_point, 0, sizeof(zero_point));
    memset(&zero_quat, 0, sizeof(zero_quat));
    memset(&zero_ray, 0, sizeof(zero_ray));
    memset(&zero_rect, 0, sizeof(zero_rect));
    memset(&zero_v2, 0, sizeof(zero_v2));
    memset(&zero_v3, 0, sizeof(zero_v3));
    memset(&zero_v4, 0, sizeof(zero_v4));
    memset(&zero_velem, 0, sizeof(zero_velem));
    memset(&zero_viewport, 0, sizeof(zero_viewport));

    /* A surface this build compiled out answers NOT_SUPPORTED for any input, and refusing
       an argument to a route that does not exist here would be the wrong answer. */
    result = cna_accelerometer_set_event_watch_registration_failure_for_tests_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_accelerometer_set_event_watch_registration_failure_for_tests_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_accelerometer_set_started_for_tests_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_accelerometer_set_started_for_tests_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_accelerometer_set_supported_for_tests_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_accelerometer_set_supported_for_tests_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_achievement_create_ext(empty_view, empty_view, empty_view, UINT8_C(9), UINT8_C(9), 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_achievement_create_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_alpha_test_effect_set_vertex_color_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_alpha_test_effect_set_vertex_color_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_animation_player_update(0, 0, UINT8_C(9), UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_animation_player_update\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_avatar_animation_update(0, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_avatar_animation_update\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_avatar_renderer_create(0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_avatar_renderer_create\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_avatar_renderer_draw_real_ext(0, empty_view, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_avatar_renderer_draw_real_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_basic_effect_set_prefer_per_pixel_lighting(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_basic_effect_set_prefer_per_pixel_lighting\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_basic_effect_set_texture_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_basic_effect_set_texture_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_basic_effect_set_vertex_color_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_basic_effect_set_vertex_color_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_compass_set_test_backend_ext(0, UINT8_C(9), UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_compass_set_test_backend_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_directional_light_set_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_directional_light_set_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_drawable_game_component_set_visible(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_drawable_game_component_set_visible\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_dual_texture_effect_set_vertex_color_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_dual_texture_effect_set_vertex_color_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_effect_fog_set_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_effect_fog_set_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_effect_lights_set_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_effect_lights_set_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_effect_technique_create_reflected_ext(empty_view, 0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_effect_technique_create_reflected_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_file_dialog_set_test_backend_ext(0, UINT8_C(9), 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_file_dialog_set_test_backend_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_file_dialog_show_open_file_ext(0, 0, 0, 0, 0, empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_file_dialog_show_open_file_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_file_dialog_show_open_folder_ext(0, 0, 0, empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_file_dialog_show_open_folder_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_friend_gamer_create_ext(empty_view, empty_view, UINT8_C(9), UINT8_C(9), UINT8_C(9), UINT8_C(9), UINT8_C(9), UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_friend_gamer_create_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_component_set_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_component_set_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_set_is_fixed_time_step(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_set_is_fixed_time_step\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_set_is_mouse_visible(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_set_is_mouse_visible\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_set_run_application_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_set_run_application_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_window_begin_screen_device_change(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_window_begin_screen_device_change\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_window_set_allow_user_resizing(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_window_set_allow_user_resizing\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_game_window_set_is_borderless_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_game_window_set_is_borderless_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_gamepad_dpad_init_from_states(UINT8_C(9), UINT8_C(9), UINT8_C(9), UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_gamepad_dpad_init_from_states\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_adapter_copy_display_modes(0, 0, UINT8_C(9), 0, 0, 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_adapter_copy_display_modes\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_adapter_get_display_mode_count(0, 0, UINT8_C(9), 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_adapter_get_display_mode_count\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_adapter_set_device_preferences(0, 0, UINT8_C(9), UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_adapter_set_device_preferences\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_manager_set_is_full_screen(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_manager_set_is_full_screen\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_manager_set_prefer_multi_sampling(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_manager_set_prefer_multi_sampling\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_manager_set_synchronize_with_vertical_retrace(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_manager_set_synchronize_with_vertical_retrace\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_set_blend_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_set_blend_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_set_context_recovery_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_set_context_recovery_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_set_depth_test_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_set_depth_test_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_device_set_depth_write_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_device_set_depth_write_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_graphics_renderer_set_automatic_fallback_ext(UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_graphics_renderer_set_automatic_fallback_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_guide_begin_show_keyboard_input(0, empty_view, empty_view, empty_view, UINT8_C(9), 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_guide_begin_show_keyboard_input\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_guide_set_is_screen_saver_enabled(UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_guide_set_is_screen_saver_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_guide_set_is_trial_mode(UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_guide_set_is_trial_mode\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_guide_set_is_visible(UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_guide_set_is_visible\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_guide_set_simulate_trial_mode(UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_guide_set_simulate_trial_mode\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_guide_show_sign_in(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_guide_show_sign_in\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_gyroscope_set_event_watch_registration_failure_for_tests_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_gyroscope_set_event_watch_registration_failure_for_tests_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_gyroscope_set_started_for_tests_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_gyroscope_set_started_for_tests_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_gyroscope_set_supported_for_tests_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_gyroscope_set_supported_for_tests_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_invite_accepted_event_info_init(0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_invite_accepted_event_info_init\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_local_network_gamer_enable_send_voice(0, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_local_network_gamer_enable_send_voice\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_debug_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_debug_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_error_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_error_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_experiment_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_experiment_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_fatal_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_fatal_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_info_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_info_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_log(0, empty_view, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_log\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_trace_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_trace_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_logger_warn_if(empty_view, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_logger_warn_if\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_media_player_set_is_muted(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_media_player_set_is_muted\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_media_player_set_is_repeating(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_media_player_set_is_repeating\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_media_player_set_is_shuffled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_media_player_set_is_shuffled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_media_player_set_is_visualization_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_media_player_set_is_visualization_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_message_box_set_test_backend_ext(0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_message_box_set_test_backend_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_morph_target_data_ext_set_recompute_flat_normals_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_morph_target_data_ext_set_recompute_flat_normals_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_motion_set_test_backend_ext(0, UINT8_C(9), UINT8_C(9), UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_motion_set_test_backend_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_mouse_set_capture_ext(0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_mouse_set_capture_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_mouse_set_is_relative_mouse_mode_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_mouse_set_is_relative_mouse_mode_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_network_gamer_set_has_left_session_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_network_gamer_set_has_left_session_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_network_gamer_set_is_host_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_network_gamer_set_is_host_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_network_gamer_set_is_ready(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_network_gamer_set_is_ready\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_network_session_set_allow_host_migration(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_network_session_set_allow_host_migration\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_network_session_set_allow_join_in_progress(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_network_session_set_allow_join_in_progress\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_pbr_effect_set_double_sided_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_pbr_effect_set_double_sided_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_pbr_effect_set_encode_output_to_srgb_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_pbr_effect_set_encode_output_to_srgb_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_pbr_effect_set_texture_is_srgb_ext(0, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_pbr_effect_set_texture_is_srgb_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_pbr_effect_set_vertex_color_enabled_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_pbr_effect_set_vertex_color_enabled_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_signed_in_gamer_create_ext(empty_view, UINT8_C(9), UINT8_C(9), 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_signed_in_gamer_create_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_skinned_effect_set_prefer_per_pixel_lighting(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_skinned_effect_set_prefer_per_pixel_lighting\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_skinned_effect_set_vertex_color_enabled(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_skinned_effect_set_vertex_color_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_skinned_model_ext_compute_bone_transforms(0, empty_view, 0, UINT8_C(9), 0, 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_skinned_model_ext_compute_bone_transforms\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_sound_effect_instance_set_is_looped(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_sound_effect_instance_set_is_looped\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_sound_effect_instance_stop(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_sound_effect_instance_stop\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_sprite_font_set_default_character(0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_sprite_font_set_default_character\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_system_tray_add_entry(0, empty_view, UINT8_C(9), UINT8_C(9), UINT8_C(9), 0, 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_system_tray_add_entry\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_system_tray_set_entry_checked(0, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_system_tray_set_entry_checked\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_system_tray_set_entry_enabled(0, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_system_tray_set_entry_enabled\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_text_input_raise_text_editing_candidates_ext(0, 0, 0, 0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_text_input_raise_text_editing_candidates_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_touch_capabilities_init_from_values_ext(UINT8_C(9), 0, 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_touch_capabilities_init_from_values_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_touch_panel_set_touch_device_exists_ext(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_touch_panel_set_touch_device_exists_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_vibrate_controller_set_test_backend_ext(0, UINT8_C(9), UINT8_C(9), empty_view);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_vibrate_controller_set_test_backend_ext\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_video_player_set_is_looped(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_video_player_set_is_looped\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_video_player_set_is_muted(0, UINT8_C(9));
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_video_player_set_is_muted\n",
               (unsigned)result);
        ++accepted;
    }
    result = cna_write_leaderboards_event_info_init(0, UINT8_C(9), 0);
    if (result != CNA_RESULT_INVALID_ARGUMENT &&
        result != CNA_RESULT_NOT_SUPPORTED) {
        printf("accepted a non-canonical CNA_Bool (%u): cna_write_leaderboards_event_info_init\n",
               (unsigned)result);
        ++accepted;
    }

    printf("%d of 96 routes accepted a CNA_Bool of 9\n", accepted);
    return accepted == 0 ? 0 : 1;
}
