#!/usr/bin/env bash
# SPDX-License-Identifier: MS-PL
#
# plans/plan_gltf.md GLTF-406: CNA's chosen licence policy is that every committed glTF/GLB container is
# CNA-generated corpus output. Real-world third-party models are fetched on demand by
# fetch-gltf-sample-assets.sh and never copied into the repository.

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
readonly REPO_ROOT
cd "$REPO_ROOT"

if ! command -v git >/dev/null 2>&1 || ! git rev-parse --git-dir >/dev/null 2>&1; then
    printf '%s\n' "check-gltf-asset-provenance: a Git checkout is required" >&2
    exit 2
fi

# `--check` compares the directory in both directions: every generated byte must match, and no
# extra file may hide among the corpus outputs. This is what makes the allowed prefix meaningful.
scripts/regenerate-gltf-goldens.sh --check >/dev/null
# The gamer-services avatar catalogs are CNA-generated too (docs/avatars.md: "original CNA work
# generated by tools/avatar_builder/", nothing third-party). The current catalog is proven the
# same way, by regenerating it byte for byte; the released catalogs beside it are that tool's frozen
# earlier outputs. The catalogs (GSX-B, 2026-09-29) landed without this gate learning of them, and
# it rejected all of them on every run (plans/plan_apple_m4.md AM4-259).
python3 tools/avatar_builder/generate_avatar_catalog.py --check >/dev/null

tracked_count=0
unexpected_assets=()
while IFS= read -r -d '' tracked_path; do
    ((tracked_count += 1))
    case "$tracked_path" in
        tests/assets/gltf/*.gltf|tests/assets/gltf/*.glb) ;;
        modules/gamer-services/assets/avatars/v[0-9]*/*.glb) ;;
        *) unexpected_assets+=("$tracked_path") ;;
    esac
done < <(git ls-files -z -- ':(icase)*.gltf' ':(icase)*.glb')

if (( tracked_count == 0 )); then
    printf '%s\n' "check-gltf-asset-provenance: no tracked glTF containers found" >&2
    exit 1
fi

if (( ${#unexpected_assets[@]} != 0 )); then
    printf '%s\n' \
        "check-gltf-asset-provenance: tracked containers outside the CNA-generated corpus:" >&2
    printf '  %s\n' "${unexpected_assets[@]}" >&2
    printf '%s\n' \
        "Third-party models must remain fetch-on-demand. Do not add an exception without the GLTF-018 per-asset licence and attribution review." >&2
    exit 1
fi

printf 'check-gltf-asset-provenance: %d tracked containers are CNA-generated; no third-party glTF asset is committed.\n' \
    "$tracked_count"
