#!/usr/bin/env python3
"""
Compile bgfx .sc shaders to embedded C arrays and write bgfx_shaders.hpp.

Usage:
    python3 compile_shaders.py <shaderc> <bgfx-include-dir>

  shaderc          Path to bgfx shaderc binary
  bgfx-include-dir Path to bgfx/src (contains bgfx_shader.sh)

Typical invocation from the repo root:
    python3 src/CNA/Internal/Backends/Bgfx/shaders/compile_shaders.py \\
        cmake-build-bgfx/_deps/bgfx_cmake-build/cmake/bgfx/shaderc \\
        cmake-build-bgfx/_deps/bgfx_cmake-src/bgfx/src
"""

import os
import subprocess
import sys
import re
import tempfile

SHADER_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_HPP = os.path.join(SHADER_DIR, "bgfx_shaders.hpp")
VARYING_DEF = os.path.join(SHADER_DIR, "varying.def.sc")

# (logical-name, type, source-file)
SHADERS = [
    ("vs_colored3d", "vertex",   "vs_colored3d.sc"),
    ("fs_colored3d", "fragment", "fs_colored3d.sc"),
]

# (type, profile, platform, array-suffix, bgfx RendererType)
# Compile only what shaderc can produce on Linux.
# Do NOT use BGFX_EMBEDDED_SHADER macro — it activates DXBC on Linux too
# (BGFX_PLATFORM_SUPPORTS_DXBC includes BX_PLATFORM_LINUX), which can't be
# compiled without D3D4Linux. We build the EmbeddedShader struct manually.
TARGETS = [
    ("vertex",   "140",    "linux", "glsl", "bgfx::RendererType::OpenGL"),
    ("vertex",   "300_es", "linux", "essl", "bgfx::RendererType::OpenGLES"),
    ("vertex",   "spirv",  "linux", "spv",  "bgfx::RendererType::Vulkan"),
    ("vertex",   "wgsl",   "linux", "wgsl", "bgfx::RendererType::WebGPU"),
    ("fragment", "140",    "linux", "glsl", "bgfx::RendererType::OpenGL"),
    ("fragment", "300_es", "linux", "essl", "bgfx::RendererType::OpenGLES"),
    ("fragment", "spirv",  "linux", "spv",  "bgfx::RendererType::Vulkan"),
    ("fragment", "wgsl",   "linux", "wgsl", "bgfx::RendererType::WebGPU"),
]

# Minimal no-op shader payloads required by createEmbeddedShader for Noop renderer.
NOOP_VSH = r'(const uint8_t*)"VSH\x5\x0\x0\x0\x0\x0\x0"'
NOOP_FSH = r'(const uint8_t*)"FSH\x5\x0\x0\x0\x0\x0\x0"'


def compile_one(shaderc, bgfx_include, sc_path, shader_type, profile, platform, c_name):
    with tempfile.NamedTemporaryFile(suffix=".bin.h", delete=False) as tmp:
        out_path = tmp.name
    try:
        cmd = [
            shaderc,
            "-f", sc_path,
            "-o", out_path,
            "--type", shader_type,
            "--platform", platform,
            "-p", profile,
            "-i", bgfx_include,
            "--varyingdef", VARYING_DEF,
            "--bin2c", c_name,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"  FAILED {shader_type}/{profile}: {result.stdout.strip()} {result.stderr.strip()}")
            return None, None
        with open(out_path, "r") as f:
            text = f.read()
        m = re.search(rf"uint8_t {re.escape(c_name)}\[(\d+)\]", text)
        size = m.group(1) if m else "?"
        return text, size
    finally:
        if os.path.exists(out_path):
            os.remove(out_path)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    shaderc = sys.argv[1]
    bgfx_include = sys.argv[2]

    if not os.path.isfile(shaderc):
        print(f"ERROR: shaderc not found: {shaderc}")
        sys.exit(1)

    # Compile all shader variants
    array_texts = []          # C array text fragments
    present = {}              # name → { suffix: renderer_type }

    for (name, stype, sc_file) in SHADERS:
        sc_path = os.path.join(SHADER_DIR, sc_file)
        present[name] = {}
        print(f"  {name} ({stype}):")
        for (ttype, profile, platform, suffix, renderer) in TARGETS:
            if ttype != stype:
                continue
            c_name = f"{name}_{suffix}"
            print(f"    {profile:10s} → {c_name} ... ", end="", flush=True)
            text, size = compile_one(shaderc, bgfx_include, sc_path, stype,
                                     profile, platform, c_name)
            if text:
                array_texts.append(text)
                present[name][suffix] = renderer
                print(f"OK ({size} bytes)")
            else:
                print("FAILED")

    # --- Generate bgfx_shaders.hpp ---
    lines = [
        "// Auto-generated by compile_shaders.py — do not edit manually.",
        "#pragma once",
        "#include <bgfx/bgfx.h>",
        "#include <bgfx/embedded_shader.h>",
        "",
    ]
    for text in array_texts:
        lines.append(text)

    # Build EmbeddedShader array manually to avoid BGFX_EMBEDDED_SHADER, which
    # on Linux also activates DXBC (BX_PLATFORM_LINUX is in BGFX_PLATFORM_SUPPORTS_DXBC)
    # but shaderc cannot produce DXBC without D3D4Linux.
    lines.append("static const bgfx::EmbeddedShader kColored3dShaders[] =")
    lines.append("{")
    for (name, stype, _) in SHADERS:
        lines.append(f"    // {name}")
        lines.append(f"    {{")
        lines.append(f'        "{name}",')
        lines.append(f"        {{")
        # Emit only the suffixes we actually compiled
        for suffix, renderer in present.get(name, {}).items():
            c_name = f"{name}_{suffix}"
            lines.append(f"            {{ {renderer}, {c_name}, sizeof({c_name}) }},")
        # Noop minimal shader (required so createEmbeddedShader finds something
        # when the active renderer type is Noop in test/headless contexts)
        noop_data = NOOP_VSH if stype == "vertex" else NOOP_FSH
        lines.append(f"            {{ bgfx::RendererType::Noop, {noop_data}, 10 }},")
        # Sentinel
        lines.append(f"            {{ bgfx::RendererType::Count, nullptr, 0 }},")
        lines.append(f"        }}")
        lines.append(f"    }},")
    lines.append("    BGFX_EMBEDDED_SHADER_END()")
    lines.append("};")
    lines.append("")

    with open(OUTPUT_HPP, "w") as f:
        f.write("\n".join(lines))

    print(f"\nWrote {OUTPUT_HPP}")
    print("Done.")


if __name__ == "__main__":
    main()
