#!/usr/bin/env python3
"""Compile the D3D stock-shadow pixel variants with the native Windows FXC."""

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path


SHADERS = (
    ("lit_textured3d.frag.hlsl", "kLitTextured3dShadowFragDxbc", ()),
    ("lit_textured3d.frag.hlsl", "kLitTextured3dColoredShadowFragDxbc",
     ("CNA_LIT_VERTEX_COLOR_INPUT",)),
    ("skinned3d.frag.hlsl", "kSkinned3dShadowFragDxbc", ()),
    ("skinned_colored3d.frag.hlsl", "kSkinned3dColoredShadowFragDxbc", ()),
    ("pbr3d.frag.hlsl", "kPbr3dShadowFragDxbc", ()),
    ("pbr3d.frag.hlsl", "kPbr3dDualUvShadowFragDxbc",
     ("CNA_PBR_DUAL_UV", "CNA_PBR_VERTEX_COLOR")),
    ("pbr_skinned3d.frag.hlsl", "kPbrSkinned3dShadowFragDxbc", ()),
    ("pbr_skinned3d.frag.hlsl", "kPbrSkinned3dDualUvShadowFragDxbc",
     ("CNA_PBR_DUAL_UV",)),
    ("pbr_skinned3d.frag.hlsl", "kPbrSkinned3dDualUvColorShadowFragDxbc",
     ("CNA_PBR_DUAL_UV", "CNA_PBR_VERTEX_COLOR")),
)


def cpp_array(name: str, data: bytes) -> str:
    rows = [", ".join(f"0x{byte:02x}u" for byte in data[i:i + 12])
            for i in range(0, len(data), 12)]
    body = ",\n    ".join(rows)
    return (f"static constexpr uint8_t {name}[] = {{\n"
            f"    {body}\n"
            f"}};\nstatic constexpr size_t {name}_size = sizeof({name});\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fxc", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    shader_dir = Path(__file__).resolve().parents[2] / "modules/renderers/common/d3d/src/shaders"
    output = args.output or shader_dir / "hlsl_modern_stock_shaders.hpp"
    parts = [
        "// AUTO-GENERATED by tools/shader_package/generate_d3d_modern_stock_hlsl.py.\n",
        "#pragma once\n#include <cstddef>\n#include <cstdint>\n\n",
        "namespace CNA::Internal::Renderers::D3DCommon::Shaders {\n\n",
    ]
    with tempfile.TemporaryDirectory() as temporary:
        for filename, name, defines in SHADERS:
            compiled = Path(temporary) / f"{name}.dxbc"
            command = [str(args.fxc), "/nologo", "/Ges", "/O3",
                       "/T", "ps_5_0", "/E", "main", "/I", str(shader_dir),
                       "/D", "CNA_MODERN_SHADOWS=1"]
            for define in defines:
                command.extend(("/D", f"{define}=1"))
            command.extend(("/Fo", str(compiled), str(shader_dir / filename)))
            result = subprocess.run(command, capture_output=True, text=True)
            if result.returncode != 0:
                raise RuntimeError(
                    f"FXC failed for {name}:\n{result.stdout}{result.stderr}")
            if result.stdout.strip() or result.stderr.strip():
                print(f"{name}: {result.stdout.strip()} {result.stderr.strip()}")
            parts.append(cpp_array(name, compiled.read_bytes()) + "\n")
    parts.append("} // namespace CNA::Internal::Renderers::D3DCommon::Shaders\n")
    output.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
