#!/usr/bin/env python3
"""Compile the depth-bias probe's two tiny shaders to SPIR-V and emit probe_spirv.hpp.

Same libshaderc-via-ctypes route the renderer's own
modules/renderers/vulkan/src/shaders/compile_shaders.py uses -- glslc and glslangValidator are
not installed on this machine, libshaderc.so.1 is.
"""

import ctypes
import struct
from pathlib import Path

_lib = None
for candidate in ("libshaderc.so.1",
                  "/usr/lib/x86_64-linux-gnu/libshaderc.so.1",
                  "/usr/lib/x86_64-linux-gnu/libshaderc_shared.so.1"):
    try:
        _lib = ctypes.CDLL(candidate)
        break
    except OSError:
        pass
if _lib is None:
    raise SystemExit("libshaderc.so.1 not found -- install libshaderc1")

_lib.shaderc_compiler_initialize.restype = ctypes.c_void_p
_lib.shaderc_compile_into_spv.restype = ctypes.c_void_p
_lib.shaderc_compile_into_spv.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t,
                                          ctypes.c_int, ctypes.c_char_p, ctypes.c_char_p,
                                          ctypes.c_void_p]
_lib.shaderc_result_get_compilation_status.restype = ctypes.c_int
_lib.shaderc_result_get_compilation_status.argtypes = [ctypes.c_void_p]
_lib.shaderc_result_get_error_message.restype = ctypes.c_char_p
_lib.shaderc_result_get_error_message.argtypes = [ctypes.c_void_p]
_lib.shaderc_result_get_length.restype = ctypes.c_size_t
_lib.shaderc_result_get_length.argtypes = [ctypes.c_void_p]
_lib.shaderc_result_get_bytes.restype = ctypes.POINTER(ctypes.c_char)
_lib.shaderc_result_get_bytes.argtypes = [ctypes.c_void_p]

VERTEX, FRAGMENT = 0, 1

VERT = """#version 450
layout(push_constant) uniform PC {
    vec4  color;
    vec4  z;      // z.x/z.y/z.z = per-vertex depth, z.w unused
} pc;
void main() {
    const vec2 xy[3] = vec2[](vec2(-0.9, -0.9), vec2(0.9, -0.9), vec2(0.0, 0.9));
    const float zs[3] = float[](pc.z.x, pc.z.y, pc.z.z);
    gl_Position = vec4(xy[gl_VertexIndex], zs[gl_VertexIndex], 1.0);
}
"""

FRAG = """#version 450
layout(push_constant) uniform PC {
    vec4  color;
    vec4  z;
} pc;
layout(location = 0) out vec4 outColor;
void main() { outColor = pc.color; }
"""


def compile_glsl(source: str, kind: int, name: str) -> bytes:
    compiler = _lib.shaderc_compiler_initialize()
    src = source.encode()
    result = _lib.shaderc_compile_into_spv(compiler, src, len(src), kind,
                                           name.encode(), b"main", None)
    if _lib.shaderc_result_get_compilation_status(result) != 0:
        raise SystemExit(_lib.shaderc_result_get_error_message(result).decode())
    length = _lib.shaderc_result_get_length(result)
    return bytes(_lib.shaderc_result_get_bytes(result)[:length])


def emit(name: str, spv: bytes) -> str:
    words = struct.unpack(f"<{len(spv)//4}I", spv)
    rows = [", ".join(f"0x{w:08x}u" for w in words[i:i + 8]) for i in range(0, len(words), 8)]
    return (f"static const uint32_t {name}[] = {{\n    " + ",\n    ".join(rows) +
            f"\n}};\nstatic const size_t {name}_size = sizeof({name});\n\n")


def main() -> None:
    out = Path(__file__).parent / "probe_spirv.hpp"
    text = ("// Generated by make_spirv.py -- do not edit.\n#pragma once\n"
            "#include <cstddef>\n#include <cstdint>\n\n")
    text += emit("kProbeVertSpv", compile_glsl(VERT, VERTEX, "probe.vert"))
    text += emit("kProbeFragSpv", compile_glsl(FRAG, FRAGMENT, "probe.frag"))
    out.write_text(text)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
